### ISSUE TITLE
Unable to set framerate.

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1011]
-r 24000/1001 does not work when set.

```
jacob@Workstation:~/Desktop/Convert$ sudo python manual.py -i '/home/jacob/Desktop/HTPC/test/test.vob'
Manual processor started.
/usr/bin/python
64bit Python.
Reading video stream.
Video codec detected: mpeg2video.
Pix Fmt: yuv420p.
Profile: Main.
Reading audio streams.
Audio detected for stream #2: ac3 [und].
Creating audio stream 0 from source stream 2.
Audio Track is number 2 setting disposition to default
Reading subtitle streams.
{
    "preopts": [], 
    "subtitle": {}, 
    "format": "mp4", 
    "postopts": [
        "-threads", 
        "16", 
        "-r 24000/1001"
    ], 
    "video": {
        "profile": null, 
        "map": 1, 
        "level": 5.1, 
        "codec": "h264", 
        "crf": 17, 
        "pix_fmt": null
    }, 
    "audio": {
        "0": {
            "map": 2, 
            "language": "eng", 
            "channels": 6, 
            "codec": "copy", 
            "disposition": "default", 
            "bitrate": 1536, 
            "filter": null
        }
    }
}
Starting conversion.
[          ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/home/jacob/Desktop/Convert/mkvtomp4.py", line 753, in convert
    for timecode in conv:
  File "/home/jacob/Desktop/Convert/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/home/jacob/Desktop/Convert/converter/ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=16758, cmd="/usr/bin/ffmpeg -i /home/jacob/Desktop/HTPC/test/test.vob -vcodec libx264 -map 0:1 -crf 17 -c:a:0 copy -map 0:2 -metadata:s:a:0 language=eng -disposition:a:0 default -f mp4 -threads 16 -r 24000/1001 -y /home/jacob/Desktop/HTPC/test/test.mp4">
/usr/bin/ffmpeg -i /home/jacob/Desktop/HTPC/test/test.vob -vcodec libx264 -map 0:1 -crf 17 -c:a:0 copy -map 0:2 -metadata:s:a:0 language=eng -disposition:a:0 default -f mp4 -threads 16 -r 24000/1001 -y /home/jacob/Desktop/HTPC/test/test.mp4
ffmpeg version 4.0.4-0ubuntu1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Ubuntu 8.2.0-7ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Unrecognized option 'r 24000/1001'.
```

**Comment by mdhiggins** [comment]
Looks like you forgot a comma
