### ISSUE TITLE
Files with E-AC3 Audio Failing

### ISSUE THREAD

**Issue by sowie2016** [mdhiggins/sickbeard_mp4_automator#1093]
Files with E-AC3 Audio seem to be failing when run via the script with error 

  Metadata:
    encoder         : libebml v1.3.9 + libmatroska v1.5.2
  Duration: 00:53:26.37, start: 0.000000, bitrate: 3605 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1, fltp (default)
    Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Too many packets buffered for output stream 0:1.
[libfdk_aac @ 0x56281c8244c0] 2 frames left in the queue on closing
Conversion failed!

Any help appreciated

Thanks

**Comment by mdhiggins** [comment]
This is an FFMPEG error not directly related to this script and appears to be due to newer builds of FFMPEG

Here is something I found on google in 10 seconds
https://stackoverflow.com/questions/49686244/ffmpeg-too-many-packets-buffered-for-output-stream-01#50262835

Looks like you need to specify a  `-max_muxing_queue_size` which you can add to the post-opts section of autoProcess.ini

**Comment by sowie2016** [comment]
Its a stange one. I added that as you said and it still failed with same error. I coped the ffmpeg command the script used and failed with and ran manually and it converted............

**Comment by mdhiggins** [comment]
Could you post the logs and the command

**Comment by sowie2016** [comment]
2019-12-01 10:39:31 - MANUAL - INFO - Manual processor started.
2019-12-01 10:39:31 - MANUAL - INFO - /usr/bin/python
2019-12-01 10:39:41 - MANUAL - INFO - Reading video stream.
2019-12-01 10:39:41 - MANUAL - INFO - Video codec detected: h264.
2019-12-01 10:39:41 - MANUAL - INFO - Pix Fmt: yuv420p.
2019-12-01 10:39:41 - MANUAL - INFO - Profile: High.
2019-12-01 10:39:41 - MANUAL - INFO - Reading audio streams.
2019-12-01 10:39:41 - MANUAL - INFO - Audio detected for stream #1: eac3 [eng].
2019-12-01 10:39:41 - MANUAL - INFO - Creating audio stream 0 from source stream 1.
2019-12-01 10:39:41 - MANUAL - INFO - Audio Track is number 1 setting disposition to default
2019-12-01 10:39:41 - MANUAL - INFO - Reading subtitle streams.
2019-12-01 10:39:41 - MANUAL - INFO - Subtitle detected for stream #2: subrip [eng].
2019-12-01 10:39:41 - MANUAL - INFO - Ripping eng subtitle from source stream 2 into external file.
2019-12-01 10:39:42 - MANUAL - INFO - /home/ldstv/plex/tvshows/tvshows/E-H/Godfather of Harlem/Season 01/Godfather of Harlem - S01E10 - Chickens Come Home to Roost.eng.3.srt created.
2019-12-01 10:39:42 - MANUAL - INFO - {
    "preopts": [], 
    "subtitle": {}, 
    "format": "mp4", 
    "postopts": [
        "-threads", 
        "auto", 
        "-max_muxing_queue_size 9999"
    ], 
    "video": {
        "profile": "main", 
        "map": 0, 
        "level": 4.0, 
        "codec": "h264", 
        "bitrate": 3000, 
        "pix_fmt": null
    }, 
    "audio": {
        "0": {
            "map": 1, 
            "language": "eng", 
            "channels": 2, 
            "codec": "libfdk_aac", 
            "disposition": "default", 
            "bitrate": 256, 
            "filter": null
        }
    }
}
2019-12-01 10:39:42 - MANUAL - INFO - Starting conversion.
2019-12-01 10:39:42 - MANUAL - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/home/ldstv/sickbeard_mp4_automator/mkvtomp4.py", line 732, in convert
    for timecode in conv:
  File "/home/ldstv/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/home/ldstv/sickbeard_mp4_automator/converter/ffmpeg.py", line 551, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=14199, cmd="/root/ffmpeg_sources/ffmpeg/ffmpeg -i /home/ldstv/plex/tvshows/tvshows/E-H/Godfather of Harlem/Season 01/Godfather of Harlem - S01E10 - Chickens Come Home to Roost.mkv -vcodec libx264 -map 0:0 -vb 3000k -profile:v main -level 4.0 -c:a:0 libfdk_aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -f mp4 -threads auto -max_muxing_queue_size 9999 -y /home/ldstv/plex/tvshows/tvshows/E-H/Godfather of Harlem/Season 01/Godfather of Harlem - S01E10 - Chickens Come Home to Roost.mp4">
2019-12-01 10:39:42 - MANUAL - ERROR - /root/ffmpeg_sources/ffmpeg/ffmpeg -i /home/ldstv/plex/tvshows/tvshows/E-H/Godfather of Harlem/Season 01/Godfather of Harlem - S01E10 - Chickens Come Home to Roost.mkv -vcodec libx264 -map 0:0 -vb 3000k -profile:v main -level 4.0 -c:a:0 libfdk_aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -f mp4 -threads auto -max_muxing_queue_size 9999 -y /home/ldstv/plex/tvshows/tvshows/E-H/Godfather of Harlem/Season 01/Godfather of Harlem - S01E10 - Chickens Come Home to Roost.mp4
2019-12-01 10:39:42 - MANUAL - ERROR - ffmpeg version N-95567-ge1d993d Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/root/bin --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 59.102 / 58. 59.102
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 65.100 /  7. 65.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Unrecognized option 'max_muxing_queue_size 9999'.
Error splitting the argument list: Option not found

2019-12-01 10:39:42 - MANUAL - ERROR - /home/ldstv/plex/tvshows/tvshows/E-H/Godfather of Harlem/Season 01/Godfather of Harlem - S01E10 - Chickens Come Home to Roost.mp4 deleted.

The strange thing is it I run the command 

/root/ffmpeg_sources/ffmpeg/ffmpeg -i "/home/ldstv/plex/tvshows/tvshows/E-H/Godfather of Harlem/Season 01/Godfather of Harlem - S01E10 - Chickens Come Home to Roost.mkv" -vcodec libx264 -map 0:0 -vb 3000k -profile:v main -level 4.0 -c:a:0 libfdk_aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -f mp4 -threads auto -max_muxing_queue_size 9999 -y "/home/ldstv/plex/tvshows/tvshows/E-H/Godfather of Harlem/Season 01/Godfather of Harlem - S01E10 - Chickens Come Home to Roost.mp4"


Runs fine....

Sorry for the delay in replying

**Comment by mdhiggins** [comment]
I think I know what's wrong, can you post your preopts/postopts from autoProcess.ini

**Comment by mdhiggins** [comment]
Nevermind I can assume it from the json

You need to include a comma in those options because of how python handles commands
`postopts = -max_muxing_queue_size, 9999`

**Comment by thenezzah** [comment]
I'm having a similar issue, should I add that max_muxing_queue_size to both per and post?  I'm especially noticing issues with extremely large videos (4k):

here is my [MP4] section:
```
[MP4]
ffmpeg = C:\apps\ffmpeg-20190715-af5f770-win64-static\bin\ffmpeg.exe
ffprobe = C:\apps\ffmpeg-20190715-af5f770-win64-static\bin\ffprobe.exe
threads = 0
output_directory = C:\down\converted
copy_to = 
move_to = 
output_extension = m4v
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3
ignore-trudhd = true
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
preopts = -max_muxing_queue_size, 9999
postopts = -max_muxing_queue_size, 9999
force-convert = False

```

**Comment by sowie2016** [comment]
> Nevermind I can assume it from the json
> 
> You need to include a comma in those options because of how python handles commands
> `postopts = -max_muxing_queue_size, 9999`

Works fine for me fixes the issue

Thanks
