### ISSUE TITLE
ffmpeg suddenly having issues, whereas it was fine before

### ISSUE THREAD

**Issue by thenezzah** [mdhiggins/sickbeard_mp4_automator#1097]
I'm not sure if there's a flag or something I need to put in the autoprocess.ini, but I haven't updated ffmpeg and for the past week or so it's developed an issue with medium sized to large sized videos, where handbrake (which also hasn't been updated) works fine on the same vids.  per a comment you made a couple of issues before this one, I edited my autoprocess.ini and altered the [MP4] postopts;

postopts = -max_muxing_queue_size, 9999

------
here's the latest wall of text from the index.log:

```
2019-12-03 05:18:16 - MANUAL - INFO - Manual processor started.
2019-12-03 05:18:16 - MANUAL - INFO - C:\apps\Python37\python.exe
2019-12-03 05:18:16 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2019-12-03 05:18:18 - MANUAL - INFO - Reading video stream.
2019-12-03 05:18:18 - MANUAL - INFO - Video codec detected: h264.
2019-12-03 05:18:18 - MANUAL - INFO - Pix Fmt: yuv420p.
2019-12-03 05:18:18 - MANUAL - INFO - Profile: High.
2019-12-03 05:18:18 - MANUAL - INFO - Reading audio streams.
2019-12-03 05:18:18 - MANUAL - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2019-12-03 05:18:18 - MANUAL - INFO - Audio detected for stream #1: ac3 [eng].
2019-12-03 05:18:18 - MANUAL - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2019-12-03 05:18:18 - MANUAL - INFO - Creating audio stream 1 from source stream 1.
2019-12-03 05:18:18 - MANUAL - ERROR - Audio language array is empty.
2019-12-03 05:18:18 - MANUAL - INFO - Reading subtitle streams.
2019-12-03 05:18:18 - MANUAL - INFO - Attempting to download subtitles.
2019-12-03 05:18:21 - MANUAL - INFO - External eng subtitle file detected.
2019-12-03 05:18:21 - MANUAL - INFO - Creating subtitle stream 0 by importing Ad.Astra.2019.HDRip.XviD.AC3-EVO.en.srt.
2019-12-03 05:18:21 - MANUAL - WARNING - Subtitle language array is empty.
2019-12-03 05:18:21 - MANUAL - INFO - {
    "format": "mp4",
    "video": {
        "codec": "copy",
        "map": 0,
        "bitrate": 1140.6345999999999,
        "level": null,
        "profile": null,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "language": "eng",
            "disposition": "none"
        },
        "1": {
            "map": 1,
            "codec": "copy",
            "channels": 6,
            "bitrate": 1536,
            "filter": null,
            "language": "eng",
            "disposition": "none"
        }
    },
    "subtitle": {
        "0": {
            "path": "C:\\down\\preconvert\\Ad.Astra.2019.HDRip.XviD.AC3-EVO[TGx]\\Ad.Astra.2019.HDRip.XviD.AC3-EVO.en.srt",
            "source": 1,
            "map": 0,
            "codec": "mov_text",
            "disposition": "none",
            "language": "eng"
        }
    },
    "preopts": [
        "-fix_sub_duration"
    ],
    "postopts": [
        "-threads",
        "0"
    ]
}
2019-12-03 05:18:21 - MANUAL - INFO - Starting conversion.
2019-12-03 05:18:22 - MANUAL - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\apps\sickbeard_mp4_automator-notvdb\mkvtomp4.py", line 782, in convert
    for timecode in conv:
  File "C:\apps\sickbeard_mp4_automator-notvdb\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\apps\sickbeard_mp4_automator-notvdb\converter\ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
2019-12-03 05:18:22 - MANUAL - ERROR - C:\apps\ffmpeg-20190715-af5f770-win64-static\bin\ffmpeg.exe -fix_sub_duration -i C:\down\preconvert\Ad.Astra.2019.HDRip.XviD.AC3-EVO[TGx]\Ad.Astra.2019.HDRip.XviD.AC3-EVO.avi -i C:\down\preconvert\Ad.Astra.2019.HDRip.XviD.AC3-EVO[TGx]\Ad.Astra.2019.HDRip.XviD.AC3-EVO.en.srt -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 none -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -c:s:0 mov_text -map 1:0 -disposition:s:0 none -metadata:s:s:0 language=eng -f mp4 -threads 0 -y C:\down\converted\Ad.Astra.2019.HDRip.XviD.AC3-EVO.m4v
2019-12-03 05:18:22 - MANUAL - ERROR - ffmpeg version N-94300-gaf5f770113 Copyright (c) 2000-2019 the FFmpeg developers

  built with gcc 9.1.1 (GCC) 20190621

  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt

  libavutil      56. 30.100 / 56. 30.100

  libavcodec     58. 53.101 / 58. 53.101

  libavformat    58. 28.102 / 58. 28.102

  libavdevice    58.  7.100 / 58.  7.100

  libavfilter     7. 56.101 /  7. 56.101

  libswscale      5.  4.101 /  5.  4.101

  libswresample   3.  4.100 /  3.  4.100

  libpostproc    55.  4.100 / 55.  4.100

Input #0, matroska,webm, from 'C:\down\preconvert\Ad.Astra.2019.HDRip.XviD.AC3-EVO[TGx]\Ad.Astra.2019.HDRip.XviD.AC3-EVO.avi':

  Metadata:

    title           : Ad Astra

    CREATION_TIME   : 2019-12-03T05:08:28Z

    ARTIST          : James Gray

    DATE_RELEASED   : 2019

    GENRE           : Action & Adventure

    DESCRIPTION     : Astronaut Roy McBride (Brad Pitt) travels to the outer edges of the solar system to find his missing

    ENCODER         : Lavf55.12.0

  Duration: 02:03:41.25, start: 0.078000, bitrate: 1584 kb/s

    Chapter #0:0: start 0.000000, end 263.722000

    Metadata:

      title           : Chapter 1

    Chapter #0:1: start 263.805000, end 529.738000

    Metadata:

      title           : Chapter 2

    Chapter #0:2: start 529.821000, end 986.819000

    Metadata:

      title           : Chapter 3

    Chapter #0:3: start 986.902000, end 1354.854000

    Metadata:

      title           : Chapter 4

    Chapter #0:4: start 1354.937000, end 1809.558000

    Metadata:

      title           : Chapter 5

    Chapter #0:5: start 1809.641000, end 2109.316000

    Metadata:

      title           : Chapter 6

    Chapter #0:6: start 2109.399000, end 2434.390000

    Metadata:

      title           : Chapter 7

    Chapter #0:7: start 2434.473000, end 2686.434000

    Metadata:

      title           : Chapter 8

    Chapter #0:8: start 2686.517000, end 2937.852000

    Metadata:

      title           : Chapter 9

    Chapter #0:9: start 2937.935000, end 3232.855000

    Metadata:

      title           : Chapter 10

    Chapter #0:10: start 3232.938000, end 3404.818000

    Metadata:

      title           : Chapter 11

    Chapter #0:11: start 3404.901000, end 3692.939000

    Metadata:

      title           : Chapter 12

    Chapter #0:12: start 3693.022000, end 4044.916000

    Metadata:

      title           : Chapter 13

    Chapter #0:13: start 4044.999000, end 4333.454000

    Metadata:

      title           : Chapter 14

    Chapter #0:14: start 4333.537000, end 4620.157000

    Metadata:

      title           : Chapter 15

    Chapter #0:15: start 4620.240000, end 4896.225000

    Metadata:

      title           : Chapter 16

    Chapter #0:16: start 4896.308000, end 5083.704000

    Metadata:

      title           : Chapter 17

    Chapter #0:17: start 5083.787000, end 5477.597000

    Metadata:

      title           : Chapter 18

    Chapter #0:18: start 5477.680000, end 5788.074000

    Metadata:

      title           : Chapter 19

    Chapter #0:19: start 5788.157000, end 6060.638000

    Metadata:

      title           : Chapter 20

    Chapter #0:20: start 6060.721000, end 6387.631000

    Metadata:

      title           : Chapter 21

    Chapter #0:21: start 6387.714000, end 6601.095000

    Metadata:

      title           : Chapter 22

    Chapter #0:22: start 6601.178000, end 6798.834000

    Metadata:

      title           : Chapter 23

    Chapter #0:23: start 6798.917000, end 7421.164000

    Metadata:

      title           : Chapter 24

    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 720x302, SAR 1:1 DAR 360:151, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)

    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)

    Metadata:

      title           : Surround

Input #1, srt, from 'C:\down\preconvert\Ad.Astra.2019.HDRip.XviD.AC3-EVO[TGx]\Ad.Astra.2019.HDRip.XviD.AC3-EVO.en.srt':

  Duration: N/A, bitrate: N/A

    Stream #1:0: Subtitle: subrip

Stream mapping:

  Stream #0:0 -> #0:0 (copy)

  Stream #0:1 -> #0:1 (ac3 (native) -> aac (native))

  Stream #0:1 -> #0:2 (copy)

  Stream #1:0 -> #0:3 (subrip (srt) -> mov_text (native))

Press [q] to stop, [?] for help

[mp4 @ 0000028509fdd500] track 2: codec frame size is not set

Output #0, mp4, to 'C:\down\converted\Ad.Astra.2019.HDRip.XviD.AC3-EVO.m4v':

  Metadata:

    title           : Ad Astra

    DESCRIPTION     : Astronaut Roy McBride (Brad Pitt) travels to the outer edges of the solar system to find his missing

    ARTIST          : James Gray

    DATE_RELEASED   : 2019

    GENRE           : Action & Adventure

    encoder         : Lavf58.28.102

    Chapter #0:0: start 0.000000, end 263.644000

    Metadata:

      title           : Chapter 1

    Chapter #0:1: start 263.727000, end 529.660000

    Metadata:

      title           : Chapter 2

    Chapter #0:2: start 529.743000, end 986.741000

    Metadata:

      title           : Chapter 3

    Chapter #0:3: start 986.824000, end 1354.776000

    Metadata:

      title           : Chapter 4

    Chapter #0:4: start 1354.859000, end 1809.480000

    Metadata:

      title           : Chapter 5

    Chapter #0:5: start 1809.563000, end 2109.238000

    Metadata:

      title           : Chapter 6

    Chapter #0:6: start 2109.321000, end 2434.312000

    Metadata:

      title           : Chapter 7

    Chapter #0:7: start 2434.395000, end 2686.356000

    Metadata:

      title           : Chapter 8

    Chapter #0:8: start 2686.439000, end 2937.774000

    Metadata:

      title           : Chapter 9

    Chapter #0:9: start 2937.857000, end 3232.777000

    Metadata:

      title           : Chapter 10

    Chapter #0:10: start 3232.860000, end 3404.740000

    Metadata:

      title           : Chapter 11

    Chapter #0:11: start 3404.823000, end 3692.861000

    Metadata:

      title           : Chapter 12

    Chapter #0:12: start 3692.944000, end 4044.838000

    Metadata:

      title           : Chapter 13

    Chapter #0:13: start 4044.921000, end 4333.376000

    Metadata:

      title           : Chapter 14

    Chapter #0:14: start 4333.459000, end 4620.079000

    Metadata:

      title           : Chapter 15

    Chapter #0:15: start 4620.162000, end 4896.147000

    Metadata:

      title           : Chapter 16

    Chapter #0:16: start 4896.230000, end 5083.626000

    Metadata:

      title           : Chapter 17

    Chapter #0:17: start 5083.709000, end 5477.519000

    Metadata:

      title           : Chapter 18

    Chapter #0:18: start 5477.602000, end 5787.996000

    Metadata:

      title           : Chapter 19

    Chapter #0:19: start 5788.079000, end 6060.560000

    Metadata:

      title           : Chapter 20

    Chapter #0:20: start 6060.643000, end 6387.553000

    Metadata:

      title           : Chapter 21

    Chapter #0:21: start 6387.636000, end 6601.017000

    Metadata:

      title           : Chapter 22

    Chapter #0:22: start 6601.100000, end 6798.756000

    Metadata:

      title           : Chapter 23

    Chapter #0:23: start 6798.839000, end 7421.086000

    Metadata:

      title           : Chapter 24

    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 720x302 [SAR 1:1 DAR 360:151], q=2-31, 23.98 fps, 23.98 tbr, 16k tbn, 1k tbc (default)

    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s

    Metadata:

      title           : Surround

      encoder         : Lavc58.53.101 aac

    Stream #0:2(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 384 kb/s

    Metadata:

      title           : Surround

    Stream #0:3(eng): Subtitle: mov_text (tx3g / 0x67337874)

    Metadata:

      encoder         : Lavc58.53.101 mov_text

[mp4 @ 0000028509fdd500] Application provided duration: 14399999000 is invalid

av_interleaved_write_frame(): Invalid argument

frame=    5 fps=0.0 q=-1.0 Lsize=      10kB time=00:00:00.08 bitrate= 956.8kbits/s speed=8.21x    

video:1kB audio:5kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 76.444969%

[aac @ 0000028509ba5140] Qavg: 56254.211

Conversion failed!


2019-12-03 05:18:22 - MANUAL - ERROR - C:\down\converted\Ad.Astra.2019.HDRip.XviD.AC3-EVO.m4v deleted.
```

**Comment by mdhiggins** [comment]
Not sure why you would be getting this error
The command you're generating looks fine
`C:\apps\ffmpeg-20190715-af5f770-win64-static\bin\ffmpeg.exe -fix_sub_duration -i C:\down\preconvert\Ad.Astra.2019.HDRip.XviD.AC3-EVO[TGx]\Ad.Astra.2019.HDRip.XviD.AC3-EVO.avi -i C:\down\preconvert\Ad.Astra.2019.HDRip.XviD.AC3-EVO[TGx]\Ad.Astra.2019.HDRip.XviD.AC3-EVO.en.srt -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 none -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -c:s:0 mov_text -map 1:0 -disposition:s:0 none -metadata:s:s:0 language=eng -f mp4 -threads 0 -y C:\down\converted\Ad.Astra.2019.HDRip.XviD.AC3-EVO.m4v`

Your attempt to add max_muxing_queue_size isn't getting included in the command though (at least not the one you posted). That queue size fix however was for eAC3 so shouldn't have much impact here though you can try to add it and see if it helps

Is it doing this for every file or just this one? Can you send me a small sample file that's failing

**Comment by thenezzah** [comment]
its definitely not every file, and it's normally when attempting to process large files.  I don't currently have any small files to send, but will chime in whenever I do.  is there any more information I could provide.

**Comment by mdhiggins** [comment]
Closing due to inactivity but reopen if this is still ongoing and provide sample files that fail

**Comment by space-pope** [comment]
I know this is old/closed, but in case anyone ends up here from Google like I did trying to hunt down an error message...

I was getting an error in the same format:
```
Application provided duration: <number> is invalid
av_interleaved_write_frame(): Invalid argument
```

I narrowed it down to my subtitle file—it contained a timestamp or two beyond the end of the video stream. This causes the problem consistently, but using the same video with in-bounds subtitles works fine.
