### ISSUE TITLE
Issue with converting files with FLAC audio track

### ISSUE THREAD

**Issue by abhishekjain14** [mdhiggins/sickbeard_mp4_automator#1114]
I'm running into an issue with multiple episodes of a show, which seems to be related to having a FLAC audio track, but ffmpeg looks like it's been installed with FLAC support when I check `ffmpeg -formats`.

Below are the logs. Any ideas?

```
2020-01-14 23:44:55 - MANUAL - INFO - Reading video stream.
2020-01-14 23:44:55 - MANUAL - INFO - Video codec detected: h264.
2020-01-14 23:44:55 - MANUAL - INFO - Pix Fmt: yuv420p.
2020-01-14 23:44:55 - MANUAL - INFO - Profile: High.
2020-01-14 23:44:55 - MANUAL - INFO - Reading audio streams.
2020-01-14 23:44:55 - MANUAL - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2020-01-14 23:44:55 - MANUAL - INFO - Audio detected for stream #1: flac [eng].
2020-01-14 23:44:55 - MANUAL - INFO - Creating audio stream 0 from source stream 1.
2020-01-14 23:44:55 - MANUAL - INFO - Adding copy of original audio track in format flac
2020-01-14 23:44:55 - MANUAL - ERROR - Audio language array is empty.
2020-01-14 23:44:55 - MANUAL - INFO - Reading subtitle streams.
2020-01-14 23:44:55 - MANUAL - WARNING - Subtitle stream array is empty.
2020-01-14 23:44:55 - MANUAL - INFO - {
    "preopts": [],
    "subtitle": {},
    "format": "mp4",
    "postopts": [
        "-threads",
        "0"
    ],
    "video": {
        "profile": null,
        "map": 0,
        "level": null,
        "codec": "copy",
        "bitrate": 9553.974,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "aac",
            "disposition": "none",
            "bitrate": 256,
            "filter": null
        },
        "1": {
            "map": 1,
            "codec": "copy",
            "disposition": "none",
            "language": "eng"
        }
    }
}
2020-01-14 23:44:55 - MANUAL - INFO - Starting conversion.
2020-01-14 23:44:55 - MANUAL - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/srv/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 805, in convert
    for timecode in conv:
  File "/srv/scripts/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/srv/scripts/sickbeard_mp4_automator/converter/ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=12489, cmd="/usr/bin/ffmpeg -i /srv/downloads/completed/Agatha Christies Poirot Season 1-13 S01-S13 1080p BluRay x264-MIXED [RiCK]/Agatha Christies Poirot Season 10 S10 1080p BluRay x264-YELLOWBiRD/Agatha.Christies.Poirot.S10E01.1080p.BluRay.x264-YELLOWBiRD.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 none -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -f mp4 -threads 0 -y /srv/downloads/completed/Agatha Christies Poirot Season 1-13 S01-S13 1080p BluRay x264-MIXED [RiCK]/Agatha Christies Poirot Season 10 S10 1080p BluRay x264-YELLOWBiRD/Agatha.Christies.Poirot.S10E01.1080p.BluRay.x264-YELLOWBiRD.mp4">
2020-01-14 23:44:55 - MANUAL - ERROR - /usr/bin/ffmpeg -i /srv/downloads/completed/Agatha Christies Poirot Season 1-13 S01-S13 1080p BluRay x264-MIXED [RiCK]/Agatha Christies Poirot Season 10 S10 1080p BluRay x264-YELLOWBiRD/Agatha.Christies.Poirot.S10E01.1080p.BluRay.x264-YELLOWBiRD.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 none -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -f mp4 -threads 0 -y /srv/downloads/completed/Agatha Christies Poirot Season 1-13 S01-S13 1080p BluRay x264-MIXED [RiCK]/Agatha Christies Poirot Season 10 S10 1080p BluRay x264-YELLOWBiRD/Agatha.Christies.Poirot.S10E01.1080p.BluRay.x264-YELLOWBiRD.mp4
2020-01-14 23:44:55 - MANUAL - ERROR - ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from '/srv/downloads/completed/Agatha Christies Poirot Season 1-13 S01-S13 1080p BluRay x264-MIXED [RiCK]/Agatha Christies Poirot Season 10 S10 1080p BluRay x264-YELLOWBiRD/Agatha.Christies.Poirot.S10E01.1080p.BluRay.x264-YELLOWBiRD.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-05-19 00:49:36
  Duration: 01:38:10.55, start: 0.000000, bitrate: 9553 kb/s
    Chapter #0:0: start 0.000000, end 527.235000
    Metadata:
      title           : 00:00:00.000
    Chapter #0:1: start 527.235000, end 1095.553000
    Metadata:
      title           : 00:08:47.235
    Chapter #0:2: start 1095.553000, end 1816.815000
    Metadata:
      title           : 00:18:15.553
    Chapter #0:3: start 1816.815000, end 2289.788000
    Metadata:
      title           : 00:30:16.815
    Chapter #0:4: start 2289.788000, end 2986.609000
    Metadata:
      title           : 00:38:09.788
    Chapter #0:5: start 2986.609000, end 3714.794000
    Metadata:
      title           : 00:49:46.609
    Chapter #0:6: start 3714.794000, end 4321.859000
    Metadata:
      title           : 01:01:54.794
    Chapter #0:7: start 4321.859000, end 4857.227000
    Metadata:
      title           : 01:12:01.859
    Chapter #0:8: start 4857.227000, end 5296.917000
    Metadata:
      title           : 01:20:57.227
    Chapter #0:9: start 5296.917000, end 5890.552000
    Metadata:
      title           : 01:28:16.917
    Stream #0:0: Video: h264 (High), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 9151852
      BPS-eng         : 9151852
      DURATION        : 01:38:10.552000000
      DURATION-eng    : 01:38:10.552000000
      NUMBER_OF_FRAMES: 141232
      NUMBER_OF_FRAMES-eng: 141232
      NUMBER_OF_BYTES : 6738682546
      NUMBER_OF_BYTES-eng: 6738682546
      _STATISTICS_WRITING_APP: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-05-19 00:49:36
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-05-19 00:49:36
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: flac, 48000 Hz, stereo, s16 (default)
    Metadata:
      BPS             : 401036
      BPS-eng         : 401036
      DURATION        : 01:37:58.461000000
      DURATION-eng    : 01:37:58.461000000
      NUMBER_OF_FRAMES: 68889
      NUMBER_OF_FRAMES-eng: 68889
      NUMBER_OF_BYTES : 294684907
      NUMBER_OF_BYTES-eng: 294684907
      _STATISTICS_WRITING_APP: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-05-19 00:49:36
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-05-19 00:49:36
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[mp4 @ 0xcb0a40] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0xcb0a40] Codec for stream 2 does not use global headers but container format requires global headers
[mp4 @ 0xcb0a40] Could not find tag for codec flac in stream #2, codec not currently supported in container
Output #0, mp4, to '/srv/downloads/completed/Agatha Christies Poirot Season 1-13 S01-S13 1080p BluRay x264-MIXED [RiCK]/Agatha Christies Poirot Season 10 S10 1080p BluRay x264-YELLOWBiRD/Agatha.Christies.Poirot.S10E01.1080p.BluRay.x264-YELLOWBiRD.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Chapter #0:0: start 0.000000, end 527.235000
    Metadata:
      title           : 00:00:00.000
    Chapter #0:1: start 527.235000, end 1095.553000
    Metadata:
      title           : 00:08:47.235
    Chapter #0:2: start 1095.553000, end 1816.815000
    Metadata:
      title           : 00:18:15.553
    Chapter #0:3: start 1816.815000, end 2289.788000
    Metadata:
      title           : 00:30:16.815
    Chapter #0:4: start 2289.788000, end 2986.609000
    Metadata:
      title           : 00:38:09.788
    Chapter #0:5: start 2986.609000, end 3714.794000
    Metadata:
      title           : 00:49:46.609
    Chapter #0:6: start 3714.794000, end 4321.859000
    Metadata:
      title           : 01:01:54.794
    Chapter #0:7: start 4321.859000, end 4857.227000
    Metadata:
      title           : 01:12:01.859
    Chapter #0:8: start 4857.227000, end 5296.917000
    Metadata:
      title           : 01:20:57.227
    Chapter #0:9: start 5296.917000, end 5890.552000
    Metadata:
      title           : 01:28:16.917
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 16k tbn, 1k tbc (default)
    Metadata:
      BPS             : 9151852
      BPS-eng         : 9151852
      DURATION        : 01:38:10.552000000
      DURATION-eng    : 01:38:10.552000000
      NUMBER_OF_FRAMES: 141232
      NUMBER_OF_FRAMES-eng: 141232
      NUMBER_OF_BYTES : 6738682546
      NUMBER_OF_BYTES-eng: 6738682546
      _STATISTICS_WRITING_APP: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-05-19 00:49:36
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-05-19 00:49:36
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp (16 bit), 256 kb/s
    Metadata:
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS             : 401036
      BPS-eng         : 401036
      DURATION        : 01:37:58.461000000
      DURATION-eng    : 01:37:58.461000000
      NUMBER_OF_FRAMES: 68889
      NUMBER_OF_FRAMES-eng: 68889
      NUMBER_OF_BYTES : 294684907
      NUMBER_OF_BYTES-eng: 294684907
      _STATISTICS_WRITING_APP: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-05-19 00:49:36
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-05-19 00:49:36
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc56.60.100 aac
    Stream #0:2(eng): Audio: flac, 48000 Hz, stereo (16 bit)
    Metadata:
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Metadata:
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS             : 401036
      BPS-eng         : 401036
      DURATION        : 01:37:58.461000000
      DURATION-eng    : 01:37:58.461000000
      NUMBER_OF_FRAMES: 68889
      NUMBER_OF_FRAMES-eng: 68889
      NUMBER_OF_BYTES : 294684907
      NUMBER_OF_BYTES-eng: 294684907
      _STATISTICS_WRITING_APP: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-05-19 00:49:36
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-05-19 00:49:36
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (flac (native) -> aac (native))
  Stream #0:1 -> #0:2 (copy)
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

2020-01-14 23:44:55 - MANUAL - ERROR - /srv/downloads/completed/Agatha Christies Poirot Season 1-13 S01-S13 1080p BluRay x264-MIXED [RiCK]/Agatha Christies Poirot Season 10 S10 1080p BluRay x264-YELLOWBiRD/Agatha.Christies.Poirot.S10E01.1080p.BluRay.x264-YELLOWBiRD.mp4 deleted.
```

**Comment by mdhiggins** [comment]
More of an FFMPEG problem but could it be that the mp4 container doesn't support FLAC? I'm not super familiar and a quick google does look like it might not

**Comment by abhishekjain14** [comment]
Yep, that seemed to do it. I disabled copying the original audio, and it's now working. Thanks!
