### ISSUE TITLE
New mkvtomp4.py Update Gives Errors!

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1123]
Hi, mkvtomp4.py that was updated 4 hours ago gave me this error;

```
2020-02-05 13:26:12 - mkvtomp4 - INFO - Starting conversion.
2020-02-05 13:26:12 - SABPostProcess - ERROR - Error converting file /mnt/downloads/nzb/Farscape.S03E22.1080p.BluRay.x264-TENEIGHTY/teneighty-farscape.s03e22.mkv.
Traceback (most recent call last):
  File "/mp4automator/SABPostProcess.py", line 72, in <module>
    output = converter.process(inputfile)
  File "/mp4automator/mkvtomp4.py", line 217, in process
    outputfile, inputfile = self.convert(inputfile, options, preopts, postopts, reportProgress)
  File "/mp4automator/mkvtomp4.py", line 819, in convert
    if not self.forceConvert and self.output_extension == input_extension and len([x for x in [options['video']] + [x for x in options['audio'].values()] + [x for x in options['subtitle'].values()] if x['codec'] != 'copy']) == 0:
NameError: global name 'input_extension' is not defined
```

I had a backup of that file so I replaced the new one with the one you updated for my issue: https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1111

And that worked! Thought you should know.

**Comment by mdhiggins** [comment]
This should be resolved now, please give it a try

**Comment by morganzero** [comment]
That worked! I just want to say thank you so much for keeping this automator alive and functional. Salute!

**Comment by mdhiggins** [comment]
Thanks for catching that; its what I get for staying up til 5 am and trying to code
