### ISSUE TITLE
New conversion error

### ISSUE THREAD

**Issue by Zachar2** [mdhiggins/sickbeard_mp4_automator#1132]
Long time happy user here. The problem shown below started occurring very recently for me. When I remove value from `video-max-width`, everything converts smoothly. Do you have any idea what might be the problem? Thank you in advance for any help.

```
root@radarrsmadocker:/# /usr/local/bin/sma/env/bin/python3 /usr/local/bin/sma/sickbeard_mp4_automator/manual.py -i /downloads/Complete/Movie.\[1990\].DVDRip.Xvid.Group.avi -a
Manual processor started.
/usr/local/bin/sma/env/bin/python3
Force-convert is true, so convert-mp4 is being overridden to true as well
Python 64-bit 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0].
Guessit version: 3.1.0.
Matched movie title as: Movie 1990-01-01 (TMDB ID: 123456)
Processing Movie Landscapes
Input Data
{
    "format": "avi",
    "format-fullname": "AVI (Audio Video Interleaved)",
    "video": {
        "index": 0,
        "codec": "mpeg4",
        "type": "video",
        "pix_fmt": "yuv420p",
        "profile": "Advanced Simple Profile"
    },
    "audio": [
        {
            "index": 1,
            "codec": "mp3",
            "type": "audio",
            "channels": 2,
            "language": "eng",
            "default": false
        }
    ],
    "subtitle": []
}
Reading video stream.
Video codec detected: mpeg4.
Pix Fmt: yuv420p.
Profile: Advanced Simple Profile.
Reading audio streams.
Audio detected for stream 1 - mp3 eng 2 channel.
Creating aac audio stream from source stream 1.
Unable to set the default audio track.
Traceback (most recent call last):
  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 486, in generateOptions
    self.setDefaultAudioStream(audio_settings)
  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 642, in setDefaultAudioStream
    default_streams = [x for x in audio_streams if 'default' in x['disposition']]
  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 642, in <listcomp>
    default_streams = [x for x in audio_streams if 'default' in x['disposition']]
TypeError: argument of type 'NoneType' is not iterable
Reading subtitle streams.
Output Data
{
    "source": [
        "/downloads/Complete/Movie.[1990].DVDRip.Xvid.Group.avi"
    ],
    "format": "mp4",
    "video": {
        "codec": "h264",
        "map": 0,
        "bitrate": null,
        "level": null,
        "profile": null,
        "pix_fmt": null,
        "field_order": "unknown",
        "width": 1280,
        "debug": "base"
    },
    "audio": [
        {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 128.0,
            "filter": null,
            "language": "eng",
            "disposition": null,
            "bsf": null,
            "debug": "base"
        }
    ],
    "subtitle": []
}
Preopts
[]
Postopts
[
    "-threads",
    "0"
]
Starting conversion.
Traceback (most recent call last):
  File "/usr/local/bin/sma/sickbeard_mp4_automator/manual.py", line 395, in <module>
    main()
  File "/usr/local/bin/sma/sickbeard_mp4_automator/manual.py", line 387, in main
    processFile(path, tagdata, converter, info=info)
  File "/usr/local/bin/sma/sickbeard_mp4_automator/manual.py", line 213, in processFile
    output = converter.process(inputfile, True)
  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 64, in process
    outputfile, inputfile = self.convert(options, preopts, postopts, reportProgress)
  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 1017, in convert
    for timecode in conv:
  File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/__init__.py", line 235, in convert
    optlist = self.parse_options(options, twopass)
  File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/__init__.py", line 140, in parse_options
    video_options = self.video_codecs[c]().parse_options(x)
  File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/avcodecs.py", line 366, in parse_options
    w = safe['width']
KeyError: 'width'
```

Here's my `autoProcess.ini`:
```
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Sonarr]
host = sonarr
port = 8989
web_root = /sonarr
ssl = False
apikey = xxxxxx

[Radarr]
host = radarr
port = 7878
web_root = /radarr
ssl = False
apikey = xxxxxx

[MP4]
ffmpeg = /usr/local/bin/ffmpeg/ffmpeg
ffprobe = /usr/local/bin/ffmpeg/ffprobe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 1280
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = False
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 2
audio-codec = aac
ignore-truehd = true
audio-language = 
audio-default-language = eng
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
allow-audio-language-relax = True
subtitle-codec = mov_text
subtitle-codec-image-based = 
subtitle-language = 
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = True
process-same-extensions = True
force-convert = True
tagfile = True
tag-language = 
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles,tvsubtitles
post-process = False
pix-fmt = 
aac_adtstoasc = False
sort-streams = False
prefer-more-channels = True
temp_extension = 
burn-subtitles = False
download-hearing-impaired-subs = False
preopts = 
postopts = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = False
apikey = 
delay = 65
method = renamer
delete_failed = False

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 
output_directory = 
radarr-label = radarr

[qBittorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
action_before = pause
action_after = resume
host = http://localhost:8080/
username = 
password = 
output_directory = 
radarr-label = radarr

[Deluge]
host = xxxxxx
username = xxxxxx
convert = False
password = xxxxxx
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory = 
remove = false
radarr-label = radarr

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Plex]
host = plex
port = 32400
refresh = True
token = xxxxxx

[Permissions]
chmod = 0755
uid = -1
gid = -1
```

**Comment by mdhiggins** [comment]
Just pushed an update that should address both of those errors you were seeing, please give it a try

**Comment by Zachar2** [comment]
Looks like you fixed it. Thanks again.
