### ISSUE TITLE
manual IMDB/TVDB tagging is failing

### ISSUE THREAD

**Issue by pensphreak** [mdhiggins/sickbeard_mp4_automator#1133]
manual.py -i Star.Wars.Episode.I.mp4 -tmdb 1893
Manual processor started.
/usr/bin/python3
Python 64-bit 3.6.8 (default, Apr  9 2019, 04:59:38) 
[GCC 8.3.0].
Guessit version: 3.1.0.
Traceback (most recent call last):
  File "/home/pens/sickbeard_mp4_automator/manual.py", line 395, in <module>
    main()
  File "/home/pens/sickbeard_mp4_automator/manual.py", line 378, in main
    elif ((args['imdbid'] or args['tmdbid']) and not args['tvdbid']):
KeyError: 'tvdbid'

Or
manual.py -i Star.Wars.Episode.I.mp4 -imdb tt0120915
Manual processor started.
/usr/bin/python3
Python 64-bit 3.6.8 (default, Apr  9 2019, 04:59:38) 
[GCC 8.3.0].
Guessit version: 3.1.0.
Traceback (most recent call last):
  File "/home/pens/sickbeard_mp4_automator/manual.py", line 395, in <module>
    main()
  File "/home/pens/sickbeard_mp4_automator/manual.py", line 378, in main
    elif ((args['imdbid'] or args['tmdbid']) and not args['tvdbid']):
KeyError: 'tvdbid'

**Comment by mdhiggins** [comment]
Just pushed an update, should be fixed
