### ISSUE TITLE
Sonarr manual import not converting

### ISSUE THREAD

**Issue by jeller316** [mdhiggins/sickbeard_mp4_automator#1136]
Hello, first love the program been using it for a long time. if this is the wrong place to ask help please tell me I'll look around elsewhere. I recently migrated to Sonarr v3 and my automatic downloads are working fine but when I try to manually import a file the script doesn't seem to work it just moves the mkv file and doesn't encode it to mp4. Any ideas what this would be? I am not an expert by any means but I did see that arguments are no longer supported error. Could this be it? I tried point the path to postsonarr.py but then I get error script exited with code 1.

**Comment by mdhiggins** [comment]
In V3 you have to combine your path to python and the argument into one line

So if in V2 your setup was
`Path = /usr/local/bin/sma/env/bin/python3`
`Args = /usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py`

Now it just needs to be
`/usr/local/bin/sma/env/bin/python3 /usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py`

**Comment by jeller316** [comment]
Thanks I should have said it's a windows 10 machine. basically the same thing though. i'm not sure of the syntax though. Right now I have 
Path = C:\Python27\python.exe
Args = C:\sickbeard_mp4_automator-master\sickbeard_mp4_automator-master\postSonarr.py

but need something like 

C:\Python27\python.exe  C:\sickbeard_mp4_automator-master\sickbeard_mp4_automator-master\postSonarr.py

**Comment by mdhiggins** [comment]
Yeah no difference for Windows, just like you posted should be fine

`C:\Python27\python.exe C:\sickbeard_mp4_automator-master\sickbeard_mp4_automator-master\postSonarr.py`

**Comment by jeller316** [comment]
That's what I thought and tried but doesn't seem to work. When I use the syntax above and hit test there's a red exclamation mark on the test button , same if I try to save. If I go out of the setting screen and back in the old path and arguments are there. No errors on showing or anything on the screen though. Here's the log if it helps. No rush, I have to leave for bit to visit someone in the hospital. Appreciate the help.

20-2-17 11:37:54.6|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/notification/test

[v3.0.3.698] System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at System.IO.DirectoryInfo..ctor(String path)
   at NzbDrone.Common.Extensions.PathExtensions.IsParentPath(String parentPath, String childPath) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 105
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.Test() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 151
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Test(TProviderDefinition definition) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 81
   at Sonarr.Api.V3.ProviderModuleBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\ProviderModuleBase.cs:line 188
   at Sonarr.Api.V3.ProviderModuleBase`3.Test(TProviderResource providerResource) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\ProviderModuleBase.cs:line 141
   at Sonarr.Api.V3.ProviderModuleBase`3.<.ctor>b__2_1(Object x) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\ProviderModuleBase.cs:line 28
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()

**Comment by mdhiggins** [comment]
You could try just wrapping the command in a batch file
Make a new text document, put your path in there, save it as postSonarr.bat, and point to that file instead

**Comment by mdhiggins** [comment]
The other option for windows might be to add double backslashes instead of single backslashes to your path
`C:\\Python27\\python.exe C:\\sickbeard_mp4_automator-master\\sickbeard_mp4_automator-master\\postSonarr.py`

**Comment by jeller316** [comment]
Tried the bat file with and without double slashes script exited with code 1 error. Will not save also.
Tried using the path directly with double slashes and I get the weird red exclamation mark on the test button. I bet it's something simple just can't quite get it. If I run the manual.py and point it to the file it does encode to mp4, but doesn't move it, not sure if it supposed to at that point.

**Comment by mdhiggins** [comment]
Does anything show up in the Sonarr logs when the patch file fails?

**Comment by jeller316** [comment]
From the logs? I have this, I noticed at the end it says script exited with code 1 but I have no idea what any of it means.

20-2-17 12:03:06.4|Fatal|SonarrErrorPipeline|Request Failed. GET /api/v3/filesystem

[v3.0.3.698] System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at System.IO.DirectoryInfo..ctor(String path)
   at NzbDrone.Common.Disk.FileSystemLookupService.GetParent(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\FileSystemLookupService.cs:line 204
   at NzbDrone.Common.Disk.FileSystemLookupService.GetResult(String path, Boolean includeFiles) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\FileSystemLookupService.cs:line 115
   at NzbDrone.Common.Disk.FileSystemLookupService.LookupContents(String query, Boolean includeFiles, Boolean allowFoldersWithoutTrailingSlashes) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\FileSystemLookupService.cs:line 84
   at Sonarr.Api.V3.FileSystem.FileSystemModule.GetContents() in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\FileSystem\FileSystemModule.cs:line 37
   at Sonarr.Api.V3.FileSystem.FileSystemModule.<.ctor>b__3_0(Object x) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\FileSystem\FileSystemModule.cs:line 26
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()

20-2-17 12:03:15.3|Error|cmd.exe|Traceback (most recent call last):
20-2-17 12:03:15.3|Error|cmd.exe|  File "C:\\sickbeard_mp4_automator-master\\sickbeard_mp4_automator-master\\postSonarr.py", line 21, in <module>
20-2-17 12:03:15.3|Error|cmd.exe|    tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
20-2-17 12:03:15.3|Error|cmd.exe|TypeError: int() argument must be a string or a number, not 'NoneType'
20-2-17 12:03:15.3|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Script exited with code: 1

**Comment by jeller316** [comment]
Actually here is the log from running the bat file with double slashes. 

20-2-17 17:06:28.0|Error|cmd.exe|  File "C:\\sickbeard_mp4_automator-master\\sickbeard_mp4_automator-master\\postSonarr.py", line 21, in <module>
20-2-17 17:06:28.0|Error|cmd.exe|    tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
20-2-17 17:06:28.0|Error|cmd.exe|TypeError: int() argument must be a string or a number, not 'NoneType'
20-2-17 17:06:28.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Script exited with code: 1

**Comment by mdhiggins** [comment]
Hm seems you're losing the environment variables that Sonarr is supposed to set for its post processing scripts

Not sure why that would be though

**Comment by mdhiggins** [comment]
Make sure you have ongrab and onrename turned off in the Sonarr settings

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1086#issuecomment-562913913

**Comment by jeller316** [comment]
I double checked and my setting are already that way. I needed to get it working so I went back to Sonarr v2 and and using the same mp4 automotor folder and it is running perfectly, actually importing files right now. I'll come back to this eventually, maybe it's something in Sonarr broken but I do appreciate the help.

**Comment by mdhiggins** [comment]
Found a bug where the test scenario was accidentally deleted
Made some updates to docker and sonarr and it should be fixed now
If you're using my docker containers postSonarr.sh is included now but for windows the batch file should work
