### ISSUE TITLE
FFMpegConvertError only on one file? 

### ISSUE THREAD

**Issue by evanwins** [mdhiggins/sickbeard_mp4_automator#1153]
I was attempting to manually convert a file and I got this "FFMpegConvertError".  I'm using the latest version of ffmpeg, 4.2.2.2, so I'm not sure what's causing this. It's on a 2018 Mac mini so the hardware his good and I have the havoc codec in my auto process.ini file so I'm a bit lost. Also, I don't know a whole lot about this to begin with so there's that.

Any help is greatly appreciated.

Here's the terminal print:

```
Processing file /Users/atomicenter/Downloads/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD.mkv
Matched movie title as: Joker 2019-10-02 (TMDB ID: 475557)
Processing Joker
Input Data
{
    "subtitle": [
        {
            "index": 3, 
            "language": "eng", 
            "forced": false, 
            "default": false, 
            "codec": "subrip", 
            "type": "subtitle"
        }, 
        {
            "index": 4, 
            "language": "eng", 
            "forced": false, 
            "default": false, 
            "codec": "hdmv_pgs_subtitle", 
            "type": "subtitle"
        }
    ], 
    "format-fullname": "Matroska / WebM", 
    "format": "matroska,webm", 
    "video": {
        "pix_fmt": "yuv420p10le", 
        "index": 0, 
        "codec": "hevc", 
        "type": "video", 
        "profile": "Main 10"
    }, 
    "attachment": [], 
    "audio": [
        {
            "index": 1, 
            "language": "eng", 
            "default": true, 
            "channels": 8, 
            "codec": "truehd", 
            "type": "audio"
        }, 
        {
            "index": 2, 
            "language": "eng", 
            "default": false, 
            "channels": 6, 
            "codec": "ac3", 
            "type": "audio"
        }
    ]
}
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p10le.
Profile: Main 10.
Reading audio streams.
Audio detected for stream 1 - truehd eng 8 channel.
Skipping trueHD stream 1 as typically the 2nd audio stream is the AC3 core of the truehd stream [ignore-truehd].
Audio detected for stream 2 - ac3 eng 6 channel.
Creating aac audio stream source audio stream 2 [iOS-audio].
Creating copy audio stream from source stream 2.
Default audio stream set to eng aac 2 channel stream [prefer-more-channels: False].
Reading subtitle streams.
Text-based subtitle detected for stream 3 - subrip eng.
Creating srt subtitle stream from source stream 3.
Image-based subtitle detected for stream 4 - hdmv_pgs_subtitle eng.
Attempting to download subtitles.
Tagging copied video stream as hvc1
Output Data
{
    "subtitle": [
        {
            "map": 3, 
            "language": "eng", 
            "encoding": null, 
            "codec": "srt", 
            "disposition": "+default", 
            "debug": "base.embed-subs"
        }
    ], 
    "format": "mp4", 
    "source": [
        "/Users/atomicenter/Downloads/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD.mkv"
    ], 
    "video": {
        "profile": null, 
        "map": 0, 
        "field_order": "unknown", 
        "codec": "copy", 
        "crf": null, 
        "level": null, 
        "debug": "base", 
        "width": null, 
        "bitrate": null, 
        "pix_fmt": null
    }, 
    "attachment": [], 
    "audio": [
        {
            "channels": 2, 
            "map": 2, 
            "codec": "aac", 
            "disposition": "+default", 
            "language": "eng", 
            "debug": "ios-audio", 
            "bitrate": 212, 
            "filter": null
        }, 
        {
            "channels": 6, 
            "map": 2, 
            "codec": "copy", 
            "disposition": "", 
            "language": "eng", 
            "debug": "base", 
            "bsf": null, 
            "bitrate": 636, 
            "filter": null
        }
    ]
}
Preopts
[
    "-fix_sub_duration"
]
Postopts
[
    "-threads", 
    "0", 
    "-tag:v", 
    "hvc1"
]
Starting conversion.
[          ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/Applications/sickbeard_mp4_automator-master/mkvtomp4.py", line 1060, in convert
    for timecode in conv:
  File "/Applications/sickbeard_mp4_automator-master/converter/__init__.py", line 274, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/Applications/sickbeard_mp4_automator-master/converter/ffmpeg.py", line 660, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=4901, cmd="/usr/local/cellar/ffmpeg/4.2.2_2/bin/ffmpeg -fix_sub_duration -i /Users/atomicenter/Downloads/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:2 -disposition:a:0 +default -ac:a:0 2 -b:a:0 212k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:2 -metadata:s:a:1 language=eng -c:s:0 srt -map 0:3 -disposition:s:0 +default -metadata:s:s:0 language=eng -f mp4 -threads 0 -tag:v hvc1 -y /Users/atomicenter/Downloads/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD.mp4">
/usr/local/cellar/ffmpeg/4.2.2_2/bin/ffmpeg -fix_sub_duration -i /Users/atomicenter/Downloads/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:2 -disposition:a:0 +default -ac:a:0 2 -b:a:0 212k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:2 -metadata:s:a:1 language=eng -c:s:0 srt -map 0:3 -disposition:s:0 +default -metadata:s:s:0 language=eng -f mp4 -threads 0 -tag:v hvc1 -y /Users/atomicenter/Downloads/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD.mp4
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[matroska,webm @ 0x7ff6d500be00] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, matroska,webm, from '/Users/atomicenter/Downloads/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD.mkv':
  Metadata:
    encoder         : libebml v1.3.9 + libmatroska v1.5.2
    creation_time   : 2019-12-20T00:41:28.000000Z
  Duration: 02:01:49.12, start: 0.000000, bitrate: 19057 kb/s
    Chapter #0:0: start 0.000000, end 628.795000
    Metadata:
      title           : Chapter 01
    Chapter #0:1: start 628.795000, end 1261.302000
    Metadata:
      title           : Chapter 02
    Chapter #0:2: start 1261.302000, end 1724.973000
    Metadata:
      title           : Chapter 03
    Chapter #0:3: start 1724.973000, end 2294.501000
    Metadata:
      title           : Chapter 04
    Chapter #0:4: start 2294.501000, end 2781.570000
    Metadata:
      title           : Chapter 05
    Chapter #0:5: start 2781.570000, end 3379.293000
    Metadata:
      title           : Chapter 06
    Chapter #0:6: start 3379.293000, end 3881.169000
    Metadata:
      title           : Chapter 07
    Chapter #0:7: start 3881.169000, end 4541.746000
    Metadata:
      title           : Chapter 08
    Chapter #0:8: start 4541.746000, end 5176.046000
    Metadata:
      title           : Chapter 09
    Chapter #0:9: start 5176.046000, end 5822.608000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 5822.608000, end 6350.386000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 6350.386000, end 6944.646000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 6944.646000, end 7309.120000
    Metadata:
      title           : Chapter 13
    Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2080 [SAR 1:1 DAR 24:13], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      title           : Joker.2019.2160p.UHD.BluRay.x265-AAAUHD
      BPS-eng         : 14495468
      DURATION-eng    : 02:01:49.094000000
      NUMBER_OF_FRAMES-eng: 175243
      NUMBER_OF_BYTES-eng: 13243592829
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-12-20 00:41:28
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: truehd, 48000 Hz, 7.1, s32 (24 bit) (default)
    Metadata:
      title           : English Dolby TrueHD with Dolby Atmos (TrueHD)
      BPS-eng         : 3819392
      DURATION-eng    : 02:01:49.094000000
      NUMBER_OF_FRAMES-eng: 8770913
      NUMBER_OF_BYTES-eng: 3489537684
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-12-20 00:41:28
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      title           : English Dolby Digital (AC3)
      BPS-eng         : 640000
      DURATION-eng    : 02:01:49.120000000
      NUMBER_OF_FRAMES-eng: 228410
      NUMBER_OF_BYTES-eng: 584729600
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-12-20 00:41:28
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(eng): Subtitle: subrip
    Metadata:
      title           : English SDH
      BPS-eng         : 55
      DURATION-eng    : 01:58:14.086000000
      NUMBER_OF_FRAMES-eng: 1735
      NUMBER_OF_BYTES-eng: 49022
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-12-20 00:41:28
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(eng): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : English PGS
      BPS-eng         : 33769
      DURATION-eng    : 01:58:14.087000000
      NUMBER_OF_FRAMES-eng: 3480
      NUMBER_OF_BYTES-eng: 29945618
      _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-12-20 00:41:28
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (ac3 (native) -> aac (native))
  Stream #0:2 -> #0:2 (copy)
  Stream #0:3 -> #0:3 (subrip (srt) -> subrip (srt))
Press [q] to stop, [?] for help
[mp4 @ 0x7ff6d5001000] track 2: codec frame size is not set
[mp4 @ 0x7ff6d5001000] Could not find tag for codec subrip in stream #3, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 -- 
[aac @ 0x7ff6d5012400] Qavg: nan
Conversion failed!
/Users/atomicenter/Downloads/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD/Joker.2019.2160p.UHD.BluRay.x265-AAAUHD.mp4 deleted.
Traceback (most recent call last):
  File "manual.py", line 393, in <module>
    main()
  File "manual.py", line 359, in main
    walkDir(path, silent, tvdbid=tvdbid, preserveRelative=args['preserveRelative'], tag=settings.tagfile, optionsOnly=args['optionsonly'])
  File "manual.py", line 258, in walkDir
    processFile(filepath, tagdata, converter, info=info, relativePath=relative)
  File "manual.py", line 213, in processFile
    output = converter.process(inputfile, True)
  File "/Applications/sickbeard_mp4_automator-master/mkvtomp4.py", line 64, in process
    outputfile, inputfile = self.convert(options, preopts, postopts, reportProgress)
  File "/Applications/sickbeard_mp4_automator-master/mkvtomp4.py", line 1081, in convert
    raise Exception("FFMpegConvertError")
Exception: FFMpegConvertError
```

**Comment by mdhiggins** [comment]
[mp4 @ 0x7ff6d5001000] Could not find tag for codec subrip in stream #3, codec not currently supported in container

`subrip` isn't supported in MP4 containers

Use `mov_text` by updating autoProcess.ini subtitle-codec

`subtitle-codec = mov_text`
