### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'mediatype'

### ISSUE THREAD

**Issue by JySzE** [mdhiggins/sickbeard_mp4_automator#1154]
```
C:\Users\Jacob\Desktop\sickbeard_mp4_automator-master>python manual.py -i "C:\Users\Jacob\Desktop\Fairy Tail - S01E01 - The Fairy Tail Bluray-1080p.mkv"
Manual processor started.
Python 64-bit 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)].
Guessit version: 3.1.0.
C:\Program Files\Python37\python.exe
Loading config file C:\Users\Jacob\Desktop\sickbeard_mp4_automator-master\autoProcess.ini.
Traceback (most recent call last):
  File "manual.py", line 368, in <module>
    main()
  File "manual.py", line 353, in main
    processFile(path, None, converter, info=info)
  File "manual.py", line 207, in processFile
    if tagdata.mediatype == MediaType.Movie:
AttributeError: 'NoneType' object has no attribute 'mediatype'

C:\Users\Jacob\Desktop\sickbeard_mp4_automator-master>
```

Video Stream Media Info:
```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 24 min 27 s
Bit rate mode                            : Variable
Bit rate                                 : 22.2 Mb/s
Maximum bit rate                         : 39.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.447
Stream size                              : 3.80 GiB (95%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
```

**Comment by JySzE** [comment]
If i enable tagging this error goes away but i do not wish to tag files.

**Comment by mdhiggins** [comment]
Just a small bug introduced in the manual.py rewrite where I had assumed tagdata would be present for logging purposes
Should be fixed now

baeac910e832b41d90abc1c4d195882ab4ca05af

**Comment by JySzE** [comment]
Thank you!
