### ISSUE TITLE
NZBGetPostProcess error

### ISSUE THREAD

**Issue by pensphreak** [mdhiggins/sickbeard_mp4_automator#1156]
Tue Mar  3 21:23:49 2020        INFO    NZBGetPostProcess: Script triggered from NZBGet (11.0 or later).
Tue Mar  3 21:23:49 2020        INFO    NZBGetPostProcess: Traceback (most recent call last):
Tue Mar  3 21:23:49 2020        INFO    NZBGetPostProcess:   File "/home/pens/downloads/scripts/NZBGetPostProcess.py", line 179, in <module>
Tue Mar  3 21:23:49 2020        INFO    NZBGetPostProcess:     settings = ReadSettings(MP4folder, "autoProcess.ini")
Tue Mar  3 21:23:49 2020        INFO    NZBGetPostProcess:   File "/home/pens/sickbeard_mp4_automator/readSettings.py", line 25, in __init__
Tue Mar  3 21:23:49 2020        INFO    NZBGetPostProcess:     self.log.info(sys.executable)
Tue Mar  3 21:23:49 2020        INFO    NZBGetPostProcess: AttributeError: 'str' object has no attribute 'info'
Tue Mar  3 21:23:49 2020        ERROR   Post-process-script NZBGetPostProcess.py for Better.Call.Saul.S05E03.WEBRip.x264-ION10 failed (terminated with unknown status)

**Comment by pensphreak** [comment]
Nevermind.  My NZBget was pointing to an old file
