### ISSUE TITLE
Latest code is missing files?

### ISSUE THREAD

**Issue by ravensorb** [mdhiggins/sickbeard_mp4_automator#1165]
I did a git pull and noticed a bunch of changes -- one of which is the autoProcess.ini.sample file seems to be missing.  Did something change?

[UPDATE] Ok, it looks like there was a pretty major upgrade.  Any chance you can share steps to upgrade (like changes to the ini file and dependencies)?

**Comment by ravensorb** [comment]
I am seeing this in the output of SABNZBD now -- does seem correct?

```
2020-03-09 21:28:03 - SABPostProcess - INFO - Passing None directory to Sonarr.
2020-03-09 21:28:03 - autoprocess.sonarr - INFO - Sonarr notifier started.
2020-03-09 21:28:03 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'None'.
2020-03-09 21:28:03 - autoprocess.sonarr - INFO - Sonarr response: queued.
```

**Comment by mdhiggins** [comment]
I actually just reverted a lot of the changes as they were causing more problems then they were fixing
I did move the default location of autoProcess.ini into a /config folder (though it should pick up the old location still)
Reason for the move was for docker config mounting

**Comment by mdhiggins** [comment]
Depending on when you last updated it will also migrate your configuration file to a new format too

Not sure why it would be sending 'None' as the scan directory though, I don't believe that was changed at all. Is your output-directory set to 'None'?

**Comment by ravensorb** [comment]
I like the cleanup and love the support for docker :) Just trying to get it working again.

For the log above -- I just moved my autoProcess.ini file into the config folder and got that from the next file that was processed. If I revert back to an older commit everything works (and has been working for well over a year)

**Comment by mdhiggins** [comment]
Can you post your autoProcess.ini file? and if it did the migration can you post the .backup file that was created as well?

**Comment by ravensorb** [comment]
Sure, here are both of them

[autoProcess.ini.backup.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4311716/autoProcess.ini.backup.txt)
[autoProcess.ini.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4311717/autoProcess.ini.txt)

**Comment by mdhiggins** [comment]
Hm that all looks ok, any chance you could post some debug logs? Also what issue are you having exactly? Hard to tell from the logs what's going wrong. It looks like SAB is passing 'None' as the directory which I don't have a good way to explain why it would do that

How does that log look on the old commit that does work for you?

Does manual.py process ok?

**Comment by ravensorb** [comment]
Here is an example of one that works with the commit id of e25c4314aa5471fc06477172a7bd03a007ef89c9

Its a fair amount different

The two cahnges are
* The working one used the commit id above
* The latest I had to change the ```#!/usr/bin/env python``` to ```#!/usr/bin/env python3``` as sabnzbd is still using python 2.7 and it looks like your script needs python 3

```
2020-02-15 20:12:47 - SABPostProcess - INFO - SAB post processing started.
2020-02-15 20:12:47 - readSettings - INFO - /usr/local/bin/python
2020-02-15 20:12:47 - SABPostProcess - INFO - Performing conversion
2020-02-15 20:12:47 - SABPostProcess - INFO - Processing file /mnt/Downloads/Complete/tv/MythBusters S05E06 More Myths Reopened READNFO 720p HDTV x264-MiNDTHEGAP.1/mythbusters.s05e06.720p.hdtv.x264-mtg.mkv.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Input Data
2020-02-15 20:12:47 - mkvtomp4 - INFO - {
"audio": [
{
"index": 1,
"language": "eng",
"default": true,
"channels": 6,
"codec": "ac3",
"type": "audio"
}
],
"subtitle": [],
"format-fullname": "Matroska / WebM",
"video": {
"pix_fmt": "yuv420p",
"index": 0,
"codec": "h264",
"type": "video",
"profile": "High"
},
"format": "matroska,webm"
}
2020-02-15 20:12:47 - mkvtomp4 - INFO - Reading video stream.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Video codec detected: h264.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Profile: High.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Reading audio streams.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Audio detected for stream #1 - ac3 eng 6 channel.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Creating copy audio stream 0 from source stream 1.
2020-02-15 20:12:47 - mkvtomp4 - INFO - 1 total audio streams with 1 set to default disposition. 1 defaults in your preferred language (None), 0 in other languages.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Reading subtitle streams.
2020-02-15 20:12:47 - mkvtomp4 - ERROR - Unable to add language for download with subliminal.
Traceback (most recent call last):
File "/mnt/Downloads/Scripts/sickbeard_mp4_automator/mkvtomp4.py", line 878, in downloadSubtitles
languages.add(Language(self.sdl))
File "/usr/local/lib/python2.7/site-packages/babelfish/language.py", line 82, in __init__
raise ValueError('%r is not a valid language' % language)
ValueError: 'en' is not a valid language
2020-02-15 20:12:47 - mkvtomp4 - ERROR - No valid subtitle download languages detected, subtitles will not be downloaded.
2020-02-15 20:12:47 - mkvtomp4 - INFO - Output Data
2020-02-15 20:12:47 - mkvtomp4 - INFO - {
"subtitle": {},
"audio": {
"0": {
"channels": 6,
"map": 1,
"codec": "copy",
"disposition": "+default",
"language": "eng",
"debug": "base",
"bitrate": 384,
"filter": null
}
},
"video": {
"profile": null,
"map": 0,
"field_order": "progressive",
"codec": "copy",
"level": null,
"debug": "base",
"bitrate": 2359.0950999999995,
"pix_fmt": null
},
"format": "mp4"
}
2020-02-15 20:12:47 - mkvtomp4 - INFO - Preopts
2020-02-15 20:12:47 - mkvtomp4 - INFO - []
2020-02-15 20:12:47 - mkvtomp4 - INFO - Postopts
2020-02-15 20:12:47 - mkvtomp4 - INFO - [
"-threads",
"0"
]
2020-02-15 20:12:47 - mkvtomp4 - INFO - Subtitle Extracts
2020-02-15 20:12:47 - mkvtomp4 - INFO - []
2020-02-15 20:12:47 - mkvtomp4 - INFO - Starting conversion.
2020-02-15 20:12:50 - mkvtomp4 - INFO - /mnt/Downloads/Complete/tv/MythBusters S05E06 More Myths Reopened READNFO 720p HDTV x264-MiNDTHEGAP.1/mythbusters.s05e06.720p.hdtv.x264-mtg.m4v created.
2020-02-15 20:12:50 - SABPostProcess - INFO - Passing /mnt/Downloads/Complete/tv/MythBusters S05E06 More Myths Reopened READNFO 720p HDTV x264-MiNDTHEGAP.1 directory to Sonarr.
2020-02-15 20:12:50 - autoprocess.sonarr - INFO - Sonarr notifier started.
2020-02-15 20:12:50 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/mnt/Downloads/Complete/tv/MythBusters S05E06 More Myths Reopened READNFO 720p HDTV x264-MiNDTHEGAP.1'.
2020-02-15 20:12:50 - autoprocess.sonarr - INFO - Sonarr response: queued.
```

**Comment by mdhiggins** [comment]
I found a small bug that was breaking python 2 that has since been fixed if you wanted to update and try again

**Comment by mdhiggins** [comment]
Additionally, it looks like they do have python3 version of SAB out there now
The correct solution if you're still on python2 would be to make a .sh file and include something like this

```
#!/bin/bash
/path/to/python3 /path/to/script/SABPostProcess.py "$@"
```

**Comment by ravensorb** [comment]
Thats pretty much the exact script I ended up writing :)

Question - for debug logs, are you looking for debug logs from sabnzbd or from your script?  If it's your script, is there something I need to do to enable debug logging?

**Comment by mdhiggins** [comment]
Hm so apparently SAB just doesn't like exit codes, even though its the success exit code. Just pushed an update to take that out. I will say that it appears otherwise that should have all worked perfectly. Its passing the correct download directory (assuming that `/mnt/Downloads/Complete/tv/Magnum P I S01E19 Blood in the Water 1080p AMZN WEB-DL DDP5 1 H 264-NTb.1` is the corrrect directory and the request was queued. I suppose its possible that last exception was creating some trouble but that was really a fake exception just due to the exit code

Pushed an update to remove the exit code unless there's an error
88e02866db181b643df323aca8a85f7b8ac0da4c

**Comment by ravensorb** [comment]
Bingo, that fixed the issue with sabnzbd -- next question is, is there anything that changed in how plex is notified? In the latest version new shows are not showing up until after a full library scan.

**Comment by mdhiggins** [comment]
The biggest change with plex was that previously all the media manager scripts had the same code which was consolidated down into a single method handled by the mediaprocessor
In doing so I tweaked the function slightly but nothing major

Are you getting any exceptions in the logs related to plex refresh?

That would happen from postSonarr.py you can check in /var/log/sickbeard_mp4_automator/index.log and see if there's any errors in there related to plex

**Comment by mdhiggins** [comment]
Plex refresh working on my end
Added some additional debugging and cleaned up a logging bug to help if you wanna update before you do further testing to the Plex side of things
I did have to refresh my token in autoProcess.ini

**Comment by ravensorb** [comment]
Ok, let me grab the latest and give it a try.  Thanks!

**Comment by mdhiggins** [comment]
Gonna close this for now since I think I got all these resolved, reopen if any issues

**Comment by ravensorb** [comment]
Agreed -- I think everything is looking ok in regards to this issue.  Thanks!
