### ISSUE TITLE
PostSonarr.py Error when converting with Vaapi...

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1177]
Receive the following error when attempting to auto convert using Sonarr... However, using manual.py to run the same config, works without issue...

Log:
```
2020-03-13 13:45:48 - resources.mediaprocessor - INFO - Starting conversion.
2020-03-13 13:45:48 - resources.mediaprocessor - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1151, in convert
    for timecode in conv:
  File "/usr/local/sma/converter/__init__.py", line 274, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/usr/local/sma/converter/ffmpeg.py", line 671, in convert
    total_output, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
2020-03-13 13:45:48 - resources.mediaprocessor - ERROR - /usr/local/bin/ffmpeg -fix_sub_duration -i /storage/media/tv/show/Season/show  (year) - S01E01.mkv -vcodec h264_vaapi -map 0:0 -field_order progressive -vb 8000k -level 4.0 -vaapi_device /dev/dri/renderD128 -vf format=nv12,hwupload -c:a:0 copy -map 0:1 -metadata:s:a:0 language=eng -disposition:a:0 +default -c:s:0 mov_text -map 0:2 -disposition:s:0 +default -metadata:s:s:0 language=eng -c:s:1 mov_text -map 0:3 -metadata:s:s:1 language=eng -f mp4 -threads 0 -level 40 -maxrate 8000k -y /storage/media/tv/show/Season/show  (year) - S01E01.mp4
2020-03-13 13:45:48 - resources.mediaprocessor - ERROR - ffmpeg version N-96918-gd99f3dc Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 42.100 / 56. 42.100
  libavcodec     58. 74.100 / 58. 74.100
  libavformat    58. 40.100 / 58. 40.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[AVHWDeviceContext @ 0x560a0f21e8c0] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument

2020-03-13 13:45:48 - SonarrPostProcess - INFO - Processing returned False.
2020-03-13 13:45:48 - SonarrPostProcess - ERROR - Error processing file
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 122, in <module>
    sys.exit(1)
SystemExit: 1
```

**Comment by mdhiggins** [comment]
I'm guessing its a permissions issue accessing your rendering device
Assume you're probably running manual as root inside your container but sonarr isn't running as root

I solved this in my `build` containers using this https://github.com/mdhiggins/sonarr-sma/blob/build/root/etc/cont-init.d/50-gid-video
If you're extending the preview container but intend to use hardware acceleration I would include that in your container

**Comment by mdhiggins** [comment]
Or extend the build container

**Comment by RandomNinjaAtk** [comment]
Thx, I'll give that a try and that makes sense

**Comment by RandomNinjaAtk** [comment]
Solved! Thx
