### ISSUE TITLE
Errrors in latest code changes... :(

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1190]
Using manual.py for encoding...

Was working, now it is not...
```
Traceback (most recent call last):
  File "/usr/local/sma/manual.py", line 23, in <module>
    log = getLogger("MANUAL")
  File "/usr/local/sma/resources/log.py", line 123, in getLogger
    fileConfig(configfile, defaults={'logfilename': logfile})
  File "/usr/lib/python3.6/logging/config.py", line 84, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.6/logging/config.py", line 146, in _install_handlers
    args = section["args"]
  File "/usr/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'args'
```

**Comment by mdhiggins** [comment]
597b8f35d54e1a76d77b421c2fcf70f77e259494
Should be fixed, args was missing
