### ISSUE TITLE
Image based subtitle rip failed, ffmpeg timeout or wrong codec maybe?

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1208]
Looks like ffmpeg timed out while trying to determine if the subtitle was image based in this source mkv file. Is my codec for image based subtitles in my config file correct?

Subtitle section of autoProcess.ini

>
    [Subtitle]
    codec = srt
    codec-image-based = pgs
    languages = eng, kor
    default-language =
    encoding =
    burn-subtitles = False
    download-subs = False
    download-hearing-impaired-subs = False
    download-providers =
    embed-subs = False
    embed-image-subs = False
    embed-only-internal-subs = False
    attachment-codec =
    first-stream-of-language = False
    ignore-embedded-subs = False
    burn-dispositions =
    filename-dispositions = forced

Log file of file being processed.

>
    2020-04-01 09:20:44 - DelugePostProcess - INFO - Deluge post processing started.
    2020-04-01 09:20:44 - resources.readsettings - INFO - /usr/bin/python3
    2020-04-01 09:20:44 - resources.readsettings - DEBUG - Loading default config file.
    2020-04-01 09:20:44 - resources.readsettings - INFO - Loading config file /opt/mp4automator/config/autoProcess.ini.
    2020-04-01 09:20:44 - resources.readsettings - WARNING - Force-convert is true, so convert-mp4 is being overridden to true as well
    2020-04-01 09:20:44 - DelugePostProcess - DEBUG - Path: /dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES.
    2020-04-01 09:20:44 - DelugePostProcess - DEBUG - Torrent: Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES.
    2020-04-01 09:20:44 - DelugePostProcess - DEBUG - Hash: 7627ed7ef5e65d8f02e043f2c3ca1efdd6d30bde.
    2020-04-01 09:20:44 - DelugePostProcess - INFO - Successfully connected to Deluge
    2020-04-01 09:20:44 - DelugePostProcess - DEBUG - List of files in path override:
    2020-04-01 09:20:44 - DelugePostProcess - DEBUG - /dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mkv
    2020-04-01 09:20:44 - DelugePostProcess - DEBUG - Overriding output_dir to /dwnldr/tor/converted.
    2020-04-01 09:20:44 - DelugePostProcess - INFO - Processing file /dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mkv.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Process started.
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Input Data
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - {
        "format": "matroska,webm",
        "format-fullname": "Matroska / WebM",
        "video": {
            "index": 0,
            "codec": "h264",
            "pix_fmt": "yuv420p",
            "profile": "high",
            "fps": 23.976023976023978,
            "level": 4.1,
            "field_order": null
        },
        "audio": [
            {
                "index": 1,
                "codec": "dca",
                "bitrate": 1536000,
                "channels": 6,
                "samplerate": 48000,
                "language": "eng",
                "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
            }
        ],
        "subtitle": [
            {
                "index": 2,
                "codec": "srt",
                "disposition": "-default-dub-original-comment-lyrics-karaoke+forced-hearing_impaired-visual_impaired",
                "language": "eng"
            }
        ],
        "attachment": []
    }
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Reading video stream.
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Video codec detected: h264.
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p.
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Profile: high.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Total bitrate is 11812577.0.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Total audio bitrate is 1536000.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Estimated video bitrate is 10276577.0.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video codec: copy.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video bitrate: 9762.74815.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video CRF: -1.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video maxrate: None.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video bufsize: None.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video level: 5.1.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video profile: None.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video pix format: None.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video field order: None.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video width: None.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Video debug video.
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Reading audio streams.
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Audio detected for stream 1 - dca eng 6 channel.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Audio codec: aac.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Channels: 2.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Filter: .
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Bitrate: 256.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Language: eng.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Disposition: +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired.
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Creating aac audio stream source audio stream 1 [universal-audio].
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Audio codec: ac3.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Channels: 6.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Bitrate: 1536.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Language: eng
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Filter: None
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Disposition: +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - Debug: audio
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Creating ac3 audio stream from source stream 1.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - 2 total audio streams with 2 set to default disposition. 2 defaults in your preferred language (), 0 in other languages.
    2020-04-01 09:20:44 - resources.mediaprocessor - DEBUG - 1 streams in preferred language cleared of default disposition flag from preferred language.
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Default audio stream set to eng ac3 6 channel stream [default-more-channels: True].
    2020-04-01 09:20:44 - resources.mediaprocessor - INFO - Reading subtitle streams.
    2020-04-01 09:21:44 - resources.mediaprocessor - ERROR - Unknown error when trying to determine if subtitle is image based.
    Traceback (most recent call last):
      File "/opt/mp4automator/resources/mediaprocessor.py", line 1140, in isImageBasedSubtitle
        for timecode in conv:
      File "/opt/mp4automator/converter/__init__.py", line 274, in convert
        timeout=timeout, preopts=preopts, postopts=postopts):
      File "/opt/mp4automator/converter/ffmpeg.py", line 618, in convert
        ret = p.stderr.read(10)
      File "/opt/mp4automator/converter/ffmpeg.py", line 601, in on_sigalrm
        raise Exception('timed out while waiting for ffmpeg')
    Exception: timed out while waiting for ffmpeg
    2020-04-01 09:21:44 - resources.mediaprocessor - INFO - Image-based subtitle detected for stream 2 - srt eng.
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 0 results in your approved languages.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Subtitle output is empty or no default subtitle language is set, will not pass over subtitle output to set a default stream.
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - Output Data
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - {
        "source": [
            "/dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mkv"
        ],
        "format": "mp4",
        "video": {
            "codec": "copy",
            "map": 0,
            "bitrate": 9762.74815,
            "crf": -1,
            "maxrate": null,
            "bufsize": null,
            "level": 5.1,
            "profile": null,
            "pix_fmt": null,
            "field_order": null,
            "width": null,
            "debug": "video"
        },
        "audio": [
            {
                "map": 1,
                "codec": "aac",
                "channels": 2,
                "bitrate": 256,
                "samplerate": null,
                "filter": "",
                "language": "eng",
                "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
                "title": "Stereo",
                "debug": "universal-audio"
            },
            {
                "map": 1,
                "codec": "ac3",
                "channels": 6,
                "bitrate": 1536,
                "filter": null,
                "samplerate": null,
                "language": "eng",
                "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
                "bsf": null,
                "title": "5.1 Channel",
                "debug": "audio"
            }
        ],
        "subtitle": [],
        "attachment": []
    }
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - Preopts
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - []
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - Postopts
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - [
        "-threads",
        "0",
        "-metadata:g",
        "encoding_tool=SMA"
    ]
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - Subtitle Extracts
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - [
        {
            "source": [
                "/dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mkv"
            ],
            "format": "pgs",
            "subtitle": [
                {
                    "map": 2,
                    "codec": "pgs",
                    "language": "eng",
                    "debug": "subtitle"
                }
            ],
            "disposition": "-default-dub-original-comment-lyrics-karaoke+forced-hearing_impaired-visual_impaired",
            "language": "eng",
            "index": 2
        }
    ]
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - Ripping eng subtitle from source stream 2 into external file.
    2020-04-01 09:21:45 - resources.mediaprocessor - ERROR - Unable to create external sup subtitle file for stream 2, may be an incompatible format.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Unable to set file permissions before deletion. This is not always required.
    2020-04-01 09:21:45 - resources.mediaprocessor - INFO - Starting conversion.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Input directory: /dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - File name: escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Input extension: mkv.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Output directory: /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Output extension: /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Output file: /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mp4.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Input directory: /dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - File name: escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Input extension: mkv.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Output directory: /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Output extension: /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Output file: /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mp4.
    2020-04-01 09:21:45 - resources.mediaprocessor - DEBUG - Final output file: /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mp4.
    2020-04-01 09:28:39 - resources.mediaprocessor - INFO - /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mp4 created.
    2020-04-01 09:28:39 - resources.mediaprocessor - DEBUG - /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mp4 created from /dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mkv successfully.
    2020-04-01 09:28:40 - resources.mediaprocessor - DEBUG - Height: 808
    2020-04-01 09:28:40 - resources.mediaprocessor - DEBUG - Width: 1920
    2020-04-01 09:28:40 - DelugePostProcess - INFO - Successfully processed /dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mkv.
    2020-04-01 09:28:40 - DelugePostProcess - INFO - Passing /dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES directory to Radarr.
    2020-04-01 09:28:40 - autoprocess.radarr - INFO - Radarr notifier started.
    2020-04-01 09:28:40 - autoprocess.radarr - DEBUG - Radarr host: 192.168.0.21.
    2020-04-01 09:28:40 - autoprocess.radarr - DEBUG - Radarr port: 7878.
    2020-04-01 09:28:40 - autoprocess.radarr - DEBUG - Radarr webroot: .
    2020-04-01 09:28:40 - autoprocess.radarr - DEBUG - Radarr apikey: 60c905f957d44413b90e50303744aad2.
    2020-04-01 09:28:40 - autoprocess.radarr - DEBUG - Radarr protocol: http://.
    2020-04-01 09:28:40 - autoprocess.radarr - DEBUG - URL 'http://192.168.0.21:7878/api/command' with payload '{'name': 'DownloadedMoviesScan', 'path': '/dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES'}.'
    2020-04-01 09:28:40 - autoprocess.radarr - INFO - Requesting Radarr to scan directory '/dwnldr/tor/converted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES'.
    2020-04-01 09:28:40 - autoprocess.radarr - INFO - Radarr response: queued.

**Comment by mdhiggins** [comment]
No problem with your codec. 

The way it detects if a subtitle is image based or not is kind of tricky. FFprobe doesn't have a nice way to do it so I actually run a quick subtitle encode to a text based format and output to null. If it fails, then I assume its image based. The exception generated is usually the same but I was allowing any exception to count which probably wasn't ideal.

If you ever encountered a corrupt subtitle stream that times out I guess that would give a false positive for being image based which is what is happening here

c1d6f8dd98f0a1bedd32e646ef77bb6205f5d58c

That should handle that scenario a little more gracefully by just skipping/filtering out that subtitle stream

**Comment by johnwchambers** [comment]
Noice, no exceptions this time around. Thanks!

>
    2020-04-01 10:36:55 - resources.mediaprocessor - DEBUG - 2 total audio streams with 2 set to default disposition. 2 defaults in your preferred language (), 0 in other languages.
    2020-04-01 10:36:55 - resources.mediaprocessor - DEBUG - 1 streams in preferred language cleared of default disposition flag from preferred language.
    2020-04-01 10:36:55 - resources.mediaprocessor - INFO - Default audio stream set to eng ac3 6 channel stream [default-more-channels: True].
    2020-04-01 10:36:55 - resources.mediaprocessor - INFO - Reading subtitle streams.
    2020-04-01 10:37:55 - resources.mediaprocessor - ERROR - Unknown error occurred while trying to determine if subtitle is text or image based. Probably corrupt, skipping.
    2020-04-01 10:37:55 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 0 results in your approved languages.
    2020-04-01 10:37:55 - resources.mediaprocessor - DEBUG - Subtitle output is empty or no default subtitle language is set, will not pass over subtitle output to set a default stream.
    2020-04-01 10:37:55 - resources.mediaprocessor - INFO - Output Data
    2020-04-01 10:37:55 - resources.mediaprocessor - INFO - {
        "source": [
            "/dwnldr/tor/extracted/Escape.from.Pretoria.2020.LIMITED.1080p.BluRay.x264-DRONES/escape.from.pretoria.2020.limited.1080p.bluray.x264-drones.mkv"
        ],
        "format": "mp4",
