### ISSUE TITLE
OverflowError manual.py on Rpi

### ISSUE THREAD

**Issue by ko3n** [mdhiggins/sickbeard_mp4_automator#1210]
When trying to run manual.py on a video larger then 2GB I get the following error:
`OverflowError: Python int too large to convert to C ssize_t`
This does not occur when a file has a different extension like .mkv or .avi.

Trackback:
```bash
root@rpi:/mp4automator# python3 manual.py -i /downloads/Jupiters_moon/
Manual processor started.
Python 32-bit 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0].
Guessit version: 3.1.0.
/usr/bin/python3
Loading config file /mp4automator/config/autoProcess.ini.
Processing file /downloads/Jupiters_moon/Jupites_moon.mp4
Unable to retrieve rating.
Matched movie title as: Jupiter's Moon 2017-11-01 (TMDB ID: 444395)
Proceed using guessed identification from filename?
# [y/n]: y
Processing Jupiter's Moon
Input and output extensions are the same so passing back the original file [process-same-extensions: False].
Bypassing conversion and setting outputfile to inputfile.
Tagging file: /downloads/Jupiters_moon/Jupites_moon.mp4.
Trying to write tags.
There was an error writing the tags.
Traceback (most recent call last):
  File "/mp4automator/resources/metadata.py", line 205, in writeTags
    video.save()
  File "/usr/local/lib/python3.6/dist-packages/mutagen/mp4/__init__.py", line 1099, in save
    super(MP4, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/_file.py", line 133, in save
    return self.tags.save(filething, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/mp4/__init__.py", line 425, in save
    self.__save(filething.fileobj, atoms, data, padding)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/mp4/__init__.py", line 433, in __save
    self.__save_existing(fileobj, atoms, path, data, padding)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/mp4/__init__.py", line 493, in __save_existing
    resize_bytes(fileobj, length, len(ilst_data), offset)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/_util.py", line 916, in resize_bytes
    insert_bytes(fobj, insert_size, insert_at)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/_util.py", line 853, in insert_bytes
    mmap_move(fobj, offset + size, offset, movesize)
  File "/usr/local/lib/python3.6/dist-packages/mutagen/_util.py", line 737, in mmap_move
    file_map = mmap.mmap(fileno, length - offset, offset=offset)
OverflowError: Python int too large to convert to C ssize_t
Relocating MOOV atom to start of file.
QT FastStart did not run - perhaps moov atom was at the start already or file is in the wrong format.
```

**Comment by mdhiggins** [comment]
This is a mutagen error due to your sys.maxsize being too low, I would post this over here
https://github.com/quodlibet/mutagen

Not something I have the power to fix
