### ISSUE TITLE
manual.py breaks when trying to convert...

### ISSUE THREAD

**Issue by Fleshwounded** [mdhiggins/sickbeard_mp4_automator#1221]
Hey so I installed the requirements.txt, used python3 what does this error mean, from what I can see its quessit? Any help would be great I kind like this project from what I can see.

```
Manual processor started.
Python 64-bit 3.8.2 (default, Feb 26 2020, 22:21:03)
[GCC 9.2.1 20200130].
Guessit version: 3.1.0.
/usr/bin/python3
Loading config file /home/hyperion/sickbeard_mp4_automator/config/autoProcess.ini.
Traceback (most recent call last):
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/home/hyperion/.local/lib/python3.8/site-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/home/hyperion/.local/lib/python3.8/site-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/home/hyperion/.local/lib/python3.8/site-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/home/hyperion/.local/lib/python3.8/site-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'conflict_solver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manual.py", line 382, in <module>
    main()
  File "manual.py", line 370, in main
    tagdata = getInfo(path, silent=silent, tmdbid=args.get('tmdbid'), tvdbid=args.get('tvdbid'), imdbid=args.get('imdbid'), season=args.get('season'), episode=args.get('episode'))
  File "manual.py", line 110, in getInfo
    tagdata = guessInfo(fileName, tvdbid=tvdbid, tmdbid=tmdbid, imdbid=imdbid, season=season, episode=episode)
  File "manual.py", line 155, in guessInfo
    guess = guessit.guessit(fileName)
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=Rick and Morty - S04E05 - Rattlestar Ricklactica.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/home/hyperion/.local/lib/python3.8/site-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/home/hyperion/.local/lib/python3.8/site-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/home/hyperion/.local/lib/python3.8/site-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/home/hyperion/.local/lib/python3.8/site-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/home/hyperion/.local/lib/python3.8/site-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'conflict_solver'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================

```

**Comment by Fleshwounded** [comment]
Solved it... 

`diff --git a/rebulk/loose.py b/rebulk/loose.py
index 5e747a8..e92d594 100644
--- a/rebulk/loose.py
+++ b/rebulk/loose.py
@@ -56,7 +56,7 @@ def call(function, *args, **kwargs):
     :rtype: object
     """
     func = constructor_args if isclass(function) else function_args
-    call_args, call_kwargs = func(function, *args, **kwargs)
+    call_args, call_kwargs = func(function, *args, ignore_unused=True, **kwargs)
     return function(*call_args, **call_kwargs)`

Save that to a patch file, and patch rebulks loose.py

Hope that helps some

**Comment by mdhiggins** [comment]
This looks like a guessit bug, does it do this for every file or just certain ones?
I would open a ticket on their github about this patch; not really an SMA issue though

**Comment by mdhiggins** [comment]
Looks like this might be the underlying issue
https://github.com/guessit-io/guessit/issues/633
Does adding that environment variable change to the top of manual.py fix this?

`os.environ["REGEX_DISABLED"] = "1"`

**Comment by mdhiggins** [comment]
Further digging looks like they know about the issue, hopefully the environment variable fixes things
https://github.com/Toilal/rebulk/issues/20

**Comment by Fleshwounded** [comment]
It was pretty easy to fix but I can see some people not having a clue, I dont like waiting on other developers so I figured Id mention it, just in case anyone else had the same problem. Thanks for getting back to me so soon.

**Comment by mdhiggins** [comment]
If you revert your fix does using the environment variable change I posted above fix things? That would be something I could include.

**Comment by mdhiggins** [comment]
28b2191354ba423261efc352b1bbdbf8d720cfcf
