### ISSUE TITLE
sbanzbd fails to find the file

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1225]
hello mate. for the past few days after sabs has downloaded/unpacked and moved the files. then i get script error code 1. it is saying that it cannot see or find the file. or location. but yet. manual.py find it and converts it. and today. there is a lot of movies that hasn't been done. and they have failed. but yet i can see the mkv files. etc. i have posted a link to a screen shot i have taken of sabnzbd saying the script failed due to no file there. and there is also a screen shot on there. showing the file in the location. https://imgur.com/cBAX1NM
i have tried permission on sabs for the folders. but that still don't work mate.

**Comment by pazport** [comment]
just an update. i have tried another movie. and this is the full log file i managed to get mate. hope this helps.

2020-04-18 18:24:15 - SABPostProcess - INFO - SAB post processing started.
2020-04-18 18:24:15 - resources.readsettings - INFO - /usr/bin/python3
2020-04-18 18:24:15 - resources.readsettings - INFO - Loading config file /opt/appdata/sickbeard_mp4_automator-movie/sickbeard_mp4_automator-master/config/autoProcess.ini.
2020-04-18 18:24:15 - SABPostProcess - INFO - Performing conversion
2020-04-18 18:24:15 - SABPostProcess - INFO - Processing file /mnt/downloads/nzb/DC.Showcase.The.Spectre.2010.1080p.BluRay.x264-aAF/aaf-dcsts.1080p.mkv.
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Input Data
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - {
"audio": [
{
"disposition": "-karaoke-visual_impaired-lyrics-comment+default-forced-dub-hearing_impaired-original",
"index": 1,
"bitrate": 640000,
"samplerate": 48000,
"channels": 6,
"codec": "ac3",
"language": "und"
}
],
"format-fullname": "Matroska / WebM",
"attachment": [],
"subtitle": [],
"format": "matroska,webm",
"video": {
"index": 0,
"field_order": null,
"fps": 23.976023976023978,
"pix_fmt": "yuv420p",
"codec": "h264",
"level": 4.1,
"profile": "high"
}
}
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Reading video stream.
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Video codec detected: h264.
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p.
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Profile: high.
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Reading audio streams.
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Audio detected for stream 1 - ac3 und 6 channel.
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Creating aac audio stream source audio stream 1 [universal-audio].
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Creating acc audio stream from source stream 1.
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Copying audio stream from source stream 1 format ac3 [audio-copy-original].
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Default audio stream set to und acc 6 channel stream [default-more-channels: True].
2020-04-18 18:24:15 - resources.mediaprocessor - INFO - Reading subtitle streams.
2020-04-18 18:24:16 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 0 results in your approved languages.
2020-04-18 18:24:16 - resources.mediaprocessor - INFO - Output Data
2020-04-18 18:24:16 - resources.mediaprocessor - INFO - {
"audio": [
{
"disposition": "-karaoke-visual_impaired-lyrics-comment-default-forced-dub-hearing_impaired-original",
"title": "Stereo",
"bitrate": 256,
"samplerate": null,
"channels": 2,
"debug": "universal-audio",
"map": 1,
"filter": null,
"codec": "aac",
"language": "und"
},
{
"disposition": "-karaoke-visual_impaired-lyrics-comment+default-forced-dub-hearing_impaired-original",
"title": "5.1 Channel",
"bitrate": 768,
"samplerate": null,
"debug": "audio",
"channels": 6,
"bsf": null,
"map": 1,
"filter": null,
"codec": "acc",
"language": "und"
},
{
"disposition": "-karaoke-visual_impaired-lyrics-comment-default-forced-dub-hearing_impaired-original",
"title": "5.1 Channel",
"channels": 6,
"debug": "audio-copy-original",
"map": 1,
"codec": "copy",
"language": "und"
}
],
"video": {
"bitrate": 6554.786249999999,
"debug": "video",
"map": 0,
"pix_fmt": null,
"crf": -1,
"maxrate": null,
"field_order": null,
"width": null,
"bufsize": null,
"codec": "copy",
"level": 0.0,
"profile": null
},
"attachment": [],
"subtitle": [],
"format": "mp4",
"source": [
"/mnt/downloads/nzb/DC.Showcase.The.Spectre.2010.1080p.BluRay.x264-aAF/aaf-dcsts.1080p.mkv"
]
}
2020-04-18 18:24:16 - resources.mediaprocessor - INFO - Preopts
2020-04-18 18:24:16 - resources.mediaprocessor - INFO - []
2020-04-18 18:24:16 - resources.mediaprocessor - INFO - Postopts
2020-04-18 18:24:16 - resources.mediaprocessor - INFO - [
"-threads",
"3",
"-metadata:g",
"encoding_tool=SMA"
]
2020-04-18 18:24:16 - resources.mediaprocessor - INFO - Starting conversion.
2020-04-18 18:24:16 - resources.mediaprocessor - ERROR - Unexpected exception during conversion.
Traceback (most recent call last):
File "/opt/appdata/sickbeard_mp4_automator-movie/sickbeard_mp4_automator-master/resources/mediaprocessor.py", line 1268, in convert
for timecode in conv:
File "/opt/appdata/sickbeard_mp4_automator-movie/sickbeard_mp4_automator-master/converter/__init__.py", line 272, in convert
optlist = self.parse_options(options, twopass)
File "/opt/appdata/sickbeard_mp4_automator-movie/sickbeard_mp4_automator-master/converter/__init__.py", line 122, in parse_options
raise ConverterError('Requested unknown audio codec ' + str(c))
converter.ConverterError: Requested unknown audio codec acc
2020-04-18 18:24:16 - SABPostProcess - ERROR - Converting file failed /mnt/downloads/nzb/DC.Showcase.The.Spectre.2010.1080p.BluRay.x264-aAF/aaf-dcsts.1080p.mkv.
2020-04-18 18:24:16 - SABPostProcess - ERROR - No valid files found for conversion in download, aborting.
2020-04-18 18:24:16 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "/opt/appdata/sickbeard_mp4_automator-movie/sickbeard_mp4_automator-master/SABPostProcess.py", line 75, in <module>
sys.exit(1)
SystemExit: 1

**Comment by mdhiggins** [comment]
Looks like you set your codec to acc instead of aac
