### ISSUE TITLE
Requested output format 'mp4' is not a suitable output format

### ISSUE THREAD

**Issue by Jay2645** [mdhiggins/sickbeard_mp4_automator#1228]
Mentioned in the title -- for some reason, FFMPEG isn't running for any of my files, and I'm not sure what I'm doing wrong or how to force it to run.

Input:

`python3 manual.py -i /data/Videos --notag`

Output:
```
Processing file /data/Videos/Movies/Saludos Amigos (1942)/Saludos Amigos (1942).m4v
Processing file /data/Videos/Movies/Saludos Amigos (1942)/Saludos Amigos (1942).m4v
Input Data
{
    "format": "mov,mp4,m4a,3gp,3g2,mj2",
    "format-fullname": "unknown",
    "video": {
        "index": 0,
        "codec": "h264",
        "bitrate": 3625936,
        "pix_fmt": "yuv420p",
        "profile": "100",
        "fps": 23.976023976023978,
        "level": 3.1,
        "field_order": "unknown"
    },
    "audio": [
        {
            "index": 1,
            "codec": "aac",
            "bitrate": 159938,
            "channels": 2,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
        },
        {
            "index": 2,
            "codec": "ac3",
            "bitrate": 384000,
            "channels": 6,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
        }
    ],
    "subtitle": [],
    "attachment": []
}
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Profile: 100.
Reading audio streams.
Audio detected for stream 2 - ac3 eng 6 channel.
Creating aac audio stream source audio stream 2 [universal-audio].
Creating copy audio stream from source stream 2.
Audio detected for stream 1 - aac eng 2 channel.
Creating copy audio stream from source stream 1.
Default audio stream set to eng copy 2 channel stream [default-more-channels: True].
Reading subtitle streams.
Scanned for external subtitles and found 0 results in your approved languages.
Output Data
{
    "source": [
        "/data/Videos/Movies/Saludos Amigos (1942)/Saludos Amigos (1942).m4v"
    ],
    "format": "mp4",
    "video": {
        "codec": "copy",
        "map": 0,
        "bitrate": 3449.944,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "pix_fmt": null,
        "field_order": "unknown",
        "width": null,
        "debug": "video"
    },
    "audio": [
        {
            "map": 2,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "samplerate": null,
            "filter": null,
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "title": "Stereo",
            "debug": "universal-audio"
        },
        {
            "map": 2,
            "codec": "copy",
            "channels": 6,
            "bitrate": 768,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "5.1 Channel",
            "debug": "audio"
        },
        {
            "map": 1,
            "codec": "copy",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "samplerate": null,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "Stereo",
            "debug": "universal-audio"
        }
    ],
    "subtitle": [],
    "attachment": []
}
Preopts
[]
Postopts
[
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
Starting conversion.
[                    ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/data/Github/sickbeard_mp4_automator/resources/mediaprocessor.py", line 1268, in convert
    for timecode in conv:
  File "/data/Github/sickbeard_mp4_automator/converter/__init__.py", line 273, in convert
    for timecode in self.ffmpeg.convert(outfile, optlist,
  File "/data/Github/sickbeard_mp4_automator/converter/ffmpeg.py", line 681, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
/usr/bin/ffmpeg -i /data/Videos/Movies/Saludos Amigos (1942)/Saludos Amigos (1942).m4v -vcodec copy -map 0:0 -c:a:0 aac -map 0:2 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 copy -map 0:2 -metadata:s:a:1 title=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:a:2 copy -map 0:1 -metadata:s:a:2 title=Stereo -metadata:s:a:2 language=eng -disposition:a:2 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /data/Videos/Movies/Saludos Amigos (1942)/Saludos Amigos (1942).mp4
ffmpeg version 3.4.4 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10+deb8u1)
  configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --cc=cc --libdir=/usr/lib/x86_64-linux-gnu --shlibdir=/usr/lib/x86_64-linux-gnu --enable-shared --disable-stripping --enable-small --disable-amd3dnow --disable-cuvid --disable-cuda --disable-bsfs --disable-ffserver --enable-avresample --disable-devices --disable-protocols --enable-protocol=file --enable-protocol=pipe --disable-parsers --enable-parser=aac --enable-parser=ac3 --enable-parser=dvbsub --enable-parser=dvdsub --enable-parser=flac --enable-parser=h261 --enable-parser=h263 --enable-parser=h264 --enable-parser=mjpeg --enable-parser=mlp --enable-parser=mpeg4video --enable-parser=mpegaudio --enable-parser=mpegvideo --enable-parser=vc1 --enable-parser=vorbis --enable-parser=vp3 --enable-parser=vp8 --disable-demuxers --enable-demuxer=aac --enable-demuxer=ac3 --enable-demuxer=aiff --enable-demuxer=asf --enable-demuxer=avi --enable-demuxer=dts --enable-demuxer=dv --enable-demuxer=eac3 --enable-demuxer=flac --enable-demuxer=flv --enable-demuxer=h261 --enable-demuxer=h263 --enable-demuxer=h264 --enable-demuxer=matroska --enable-demuxer=mjpeg --enable-demuxer=mov --enable-demuxer=m4v --enable-demuxer=mp3 --enable-demuxer=mpegps --enable-demuxer=mpegts --enable-demuxer=mpegtsraw --enable-demuxer=mpegvideo --enable-demuxer=ogg --enable-demuxer=rtsp --enable-demuxer=vc1 --enable-demuxer=wav --disable-decoders --enable-decoder=aac --enable-decoder=alac --enable-decoder=eac3 --enable-decoder=flac --enable-decoder=flv --enable-decoder=h264 --enable-decoder=mp3 --enable-decoder=mpeg2video --enable-decoder=mpeg4 --enable-decoder=pcm_s16be --enable-decoder=pcm_s16le --enable-decoder=vorbis --enable-decoder=wmalossless --enable-decoder=wmapro --enable-decoder=wmav1 --enable-decoder=wmav2 --disable-muxers --enable-muxer=mp3 --enable-muxer=pcm_s16be --enable-muxer=pcm_s16le --disable-encoders --enable-libmp3lame --enable-encoder=libmp3lame --enable-encoder=pcm_s16be --enable-encoder=pcm_s16le --disable-filters --enable-filter=aresample
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/Videos/Movies/Saludos Amigos (1942)/Saludos Amigos (1942).m4v':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2018-07-18T02:20:39.000000Z
    encoder         : HandBrake 0.9.5 2011010300
  Duration: 00:42:04.01, start: 0.000000, bitrate: 4175 kb/s
    Chapter #0:0: start 0.000000, end 0.000000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 0.000000, end 180.973000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 180.973000, end 608.984000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 608.984000, end 661.954000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 661.954000, end 1150.984000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 1150.984000, end 1344.011000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 1344.011000, end 1809.935000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 1809.935000, end 1969.011000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 1969.011000, end 2523.941000
    Metadata:
      title           : Chapter 9
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 944x720 [SAR 119:118 DAR 119:90], 3625 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2018-07-18T02:20:39.000000Z
      encoder         : JVT/AVC Coding
    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 159 kb/s (default)
    Metadata:
      creation_time   : 2018-07-18T02:20:39.000000Z
    Stream #0:2(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Metadata:
      creation_time   : 2018-07-18T02:20:39.000000Z
    Side data:
      audio service type: main
    Stream #0:3(und): Data: bin_data (text / 0x74786574)
    Metadata:
      creation_time   : 2018-07-18T02:20:39.000000Z
[NULL @ 0x728000] Requested output format 'mp4' is not a suitable output format
/data/Videos/Movies/Saludos Amigos (1942)/Saludos Amigos (1942).mp4: Invalid argument
```

Here's my autoProcess.ini:

```
cat config/autoProcess.ini
[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 0
hwaccels = dxva2, cuvid, qsv, d3d11va
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = False
force-convert = False
post-process = True
preopts = 
postopts = 

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = False
tag-language = eng
download-artwork = poster
sanitize-disposition = 

[Video]
codec = h264, x264
max-bitrate = 40000
crf = -1
crf-profiles = 
max-width = 1280
profile = 
max-level = 0.0
pix-fmt = 

[Audio]
codec = ac3
languages = 
default-language = eng
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v

[Universal Audio]
codec = aac
channel-bitrate = 128
first-stream-only = False
move-after = False
filter = 

[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
download-subs = True
download-hearing-impaired-subs = True
download-providers = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
attachment-codec = 

[Sonarr]
host = localhost
port = 8989
apikey = 
ssl = False
webroot = 

[Radarr]
host = localhost
port = 7878
apikey = 
ssl = False
webroot = 

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
apikey = 
delay = 65
method = renamer
delete-failed = False
ssl = False
webroot = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
couchpotato-category = couchpotato
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 

[Deluge]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False

[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 

[uTorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 

[Plex]
host = localhost
port = 32400
refresh = False
token = 
```

Any help? I'm not sure if it's an issue with the script or FFMPEG, or if the problem is between the chair and the keyboard.

**Comment by mdhiggins** [comment]
This is an FFMPEG error usually because your FFMPEG build doesn't have the mp4 muxer. If you compiled from source you need to ensure you have that enabled. If you downloaded it from somewhere I would say find a new source

```
ffmpeg version 3.4.4 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10+deb8u1)
  configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --cc=cc --libdir=/usr/lib/x86_64-linux-gnu --shlibdir=/usr/lib/x86_64-linux-gnu --enable-shared --disable-stripping --enable-small --disable-amd3dnow --disable-cuvid --disable-cuda --disable-bsfs --disable-ffserver --enable-avresample --disable-devices --disable-protocols --enable-protocol=file --enable-protocol=pipe --disable-parsers --enable-parser=aac --enable-parser=ac3 --enable-parser=dvbsub --enable-parser=dvdsub --enable-parser=flac --enable-parser=h261 --enable-parser=h263 --enable-parser=h264 --enable-parser=mjpeg --enable-parser=mlp --enable-parser=mpeg4video --enable-parser=mpegaudio --enable-parser=mpegvideo --enable-parser=vc1 --enable-parser=vorbis --enable-parser=vp3 --enable-parser=vp8 --disable-demuxers --enable-demuxer=aac --enable-demuxer=ac3 --enable-demuxer=aiff --enable-demuxer=asf --enable-demuxer=avi --enable-demuxer=dts --enable-demuxer=dv --enable-demuxer=eac3 --enable-demuxer=flac --enable-demuxer=flv --enable-demuxer=h261 --enable-demuxer=h263 --enable-demuxer=h264 --enable-demuxer=matroska --enable-demuxer=mjpeg --enable-demuxer=mov --enable-demuxer=m4v --enable-demuxer=mp3 --enable-demuxer=mpegps --enable-demuxer=mpegts --enable-demuxer=mpegtsraw --enable-demuxer=mpegvideo --enable-demuxer=ogg --enable-demuxer=rtsp --enable-demuxer=vc1 --enable-demuxer=wav --disable-decoders --enable-decoder=aac --enable-decoder=alac --enable-decoder=eac3 --enable-decoder=flac --enable-decoder=flv --enable-decoder=h264 --enable-decoder=mp3 --enable-decoder=mpeg2video --enable-decoder=mpeg4 --enable-decoder=pcm_s16be --enable-decoder=pcm_s16le --enable-decoder=vorbis --enable-decoder=wmalossless --enable-decoder=wmapro --enable-decoder=wmav1 --enable-decoder=wmav2 --disable-muxers --enable-muxer=mp3 --enable-muxer=pcm_s16be --enable-muxer=pcm_s16le --disable-encoders --enable-libmp3lame --enable-encoder=libmp3lame --enable-encoder=pcm_s16be --enable-encoder=pcm_s16le --disable-filters --enable-filter=aresample
```

Looking at your FFMPEG build parameters confirms you only have 3 muxers enabled
`mp3 pcm_s16be pcm_s16le` and it also looks like a pretty old version of FFMPEG. You'll get this error because the mp4 muxer is absent

**Comment by mdhiggins** [comment]
https://ffmpeg.org/download.html
