### ISSUE TITLE
Passing tvdb parameters doesn't seem to work, still errors out not finding in tmdb

### ISSUE THREAD

**Issue by tsimmons** [mdhiggins/sickbeard_mp4_automator#1232]
Got a file that won't seem to tag. It appears the data is not available in TMDB; However, it does in TVDB; Passing the parameters to force it to use TVDB still errors out. Perhaps this is not how the option works?

```
-tvdb
```

```
$ manual.py -i the-tv-show.mp4 -s 2 -e 2 -tvdb 353025

Manual processor started.
Python 64-bit 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18)
[Clang 6.0 (clang-600.0.57)].
Guessit version: 3.1.0.
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3
Loading config file /Users/.../Documents/sickbeard_mp4_automator/config/autoProcess.ini.
Unable to guess movie information
Traceback (most recent call last):
  File "/Users/.../Documents/sickbeard_mp4_automator/manual.py", line 162, in guessInfo
    return tvInfo(guess, tmdbid=tmdbid, tvdbid=tvdbid, imdbid=imdbid, season=season, episode=episode)
  File "/Users/.../Documents/sickbeard_mp4_automator/manual.py", line 212, in tvInfo
    metadata = Metadata(MediaType.TV, tmdbid=tmdbid, imdbid=imdbid, tvdbid=tvdbid, season=season, episode=episode, language=settings.taglanguage, logger=log)
  File "/Users/.../Documents/sickbeard_mp4_automator/resources/metadata.py", line 94, in __init__
    self.episodedata = episodequery.info(language=self.language)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tmdbsimple/tv.py", line 477, in info
    response = self._GET(path, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/tv/83179/season/2/episode/2?language=en&api_key=...
Unable to determine identity based on filename, must enter manually
Select media type:
1. Movie (via TMDB)
2. Movie (via IMDB)
3. TV (via TMDB)
4. TV (via TVDB)
5. TV (via IMDB)
6. Convert without tagging
7. Skip file
#: 4
Enter TVDB ID (TV):
#: 353025
Enter Season Number:
#: 2
Enter Episode Number:
#: 2
Traceback (most recent call last):
  File "/Users/.../Documents/sickbeard_mp4_automator/manual.py", line 384, in <module>
    main()
  File "/Users/.../Documents/sickbeard_mp4_automator/manual.py", line 372, in main
    tagdata = getInfo(path, silent=silent, tmdbid=args.get('tmdbid'), tvdbid=args.get('tvdbid'), imdbid=args.get('imdbid'), season=args.get('season'), episode=args.get('episode'))
  File "/Users/.../Documents/sickbeard_mp4_automator/manual.py", line 131, in getInfo
    return Metadata(MediaType.TV, tvdbid=tvdbid, season=season, episode=episode, language=settings.taglanguage, logger=log)
  File "/Users/.../Documents/sickbeard_mp4_automator/resources/metadata.py", line 94, in __init__
    self.episodedata = episodequery.info(language=self.language)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tmdbsimple/tv.py", line 477, in info
    response = self._GET(path, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/tv/83179/season/2/episode/2?language=en&api_key=...
```

**Comment by mdhiggins** [comment]
Using the TVDB ID still ultimately resolves to the TMDB entry, just using that alternate ID
TVDB isn't supported anymore (they broke their API with V3 and refused to address it so migrated to TMDB)
TMDB is an open system though so you can add what's missing and support the project

**Comment by tsimmons** [comment]
Ah, roger that. Thanks!
