### ISSUE TITLE
can't get manual.py to work

### ISSUE THREAD

**Issue by mozzer502** [mdhiggins/sickbeard_mp4_automator#1240]
hey. Newb here. 
I've installed all the prereqs, except Requests[security] my macOS env reports that doesn't exist.
```
(sickbeard_mp4_automator) andy@MozzersMini sickbeard_mp4_automator-master % pip install requests[security]
zsh: no matches found: requests[security]
```

The error I get on running manual is to do with guessit. Can anyone help me?
Thanks

```
Manual processor started.
Python 64-bit 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)].
Guessit version: 1.0.3.
/Users/andy/sickbeard_mp4_automator/sickbeard_mp4_automator/bin/python
Loading config file /Users/andy/sickbeard_mp4_automator/config/autoProcess.ini.
Enter path to file:
#: /Users/andy/Downloads/Torrents/Complete/\ Dune1984Extended1080Pblurayremuxavcdtshdma51Rarbg.mp4 
Traceback (most recent call last):
  File "manual.py", line 384, in <module>
    main()
  File "manual.py", line 372, in main
    tagdata = getInfo(path, silent=silent, tmdbid=args.get('tmdbid'), tvdbid=args.get('tvdbid'), imdbid=args.get('imdbid'), season=args.get('season'), episode=args.get('episode'))
  File "manual.py", line 112, in getInfo
    tagdata = guessInfo(fileName, tvdbid=tvdbid, tmdbid=tmdbid, imdbid=imdbid, season=season, episode=episode)
  File "manual.py", line 157, in guessInfo
    guess = guessit.guessit(fileName)
AttributeError: module 'guessit' has no attribute 'guessit'
```

**Comment by mdhiggins** [comment]
You’re using a very old version of guessit

Guessit version: 1.0.3.

Update to the latest version

**Comment by mozzer502** [comment]
not sure how that happened, this is a brand new install. Ho hum.
thanks for the help. All working now. :-)
