### ISSUE TITLE
errors in postSonarr.py

### ISSUE THREAD

**Issue by mozzer502** [mdhiggins/sickbeard_mp4_automator#1241]
Hi
I've verified that manual.py works in my macOS Catalina terminal window. I've configured sonarr in what I assume is the correct way.
Episode renaming : Yes
Download Client: BitTorrent
Completed Download Handling: No
Connect - custom script. postSonarr, grab=no, download=yes, upgrade=yes, rename=no, path="/usr/local/bin/python3", arguments="/Users/andy/sickbeard_mp4_automator/postSonarr.py"

Nothing happens when the download is completed. So I opened a terminal and tried out the postSonarr script directly and got this. Any ideas?

```
andy@MozzersMini ~ % /usr/local/bin/python3 /Users/andy/sickbeard_mp4_automator/postSonarr.py
2020-05-12 10:15:59 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
2020-05-12 10:15:59 - resources.readsettings - INFO - /usr/local/opt/python/bin/python3.7
2020-05-12 10:15:59 - resources.readsettings - INFO - Loading config file /Users/andy/sickbeard_mp4_automator/config/autoProcess.ini.
Traceback (most recent call last):
  File "/Users/andy/sickbeard_mp4_automator/postSonarr.py", line 84, in <module>
    tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
thanks

**Comment by mozzer502** [comment]
in preparation for v3, and to ensure that sonarr executes the scripts with the correct environment, I've now created a mySonarr.zsh

```
#!/bin/zsh -v
/usr/local/bin/python3 /Users/andy/sickbeard_mp4_automator/postSonarr.py
```
Just so you can see what libraries I have loaded, here's the initial trace from manual.py
```
Manual processor started.
Python 64-bit 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)].
Guessit version: 3.1.1.
/usr/local/opt/python/bin/python3.7
Loading config file /Users/andy/sickbeard_mp4_automator/config/autoProcess.ini.
```

**Comment by mozzer502** [comment]
not that I've added python to the command line of qbittorrent I see this in the logs, though no indication that it was successful. 
`(N) 2020-05-12T15:24:03 - Torrent: The.Daily.Show.2020.05.07.1080p.WEB.x264-XLF[rarbg], running external program, command: /usr/local/bin/python3  /Users/andy/sickbeard_mp4_automator/qBittorrentPostProcess.py  "tv-sonarr" "udp://exodus.desync.com:6969/announce" "/Users/andy/Downloads/Torrents/tv-sonarr/The.Daily.Show.2020.05.07.1080p.WEB.x264-XLF[rarbg]" "/Users/andy/Downloads/Torrents/tv-sonarr/The.Daily.Show.2020.05.07.1080p.WEB.x264-XLF[rarbg]" "The.Daily.Show.2020.05.07.1080p.WEB.x264-XLF[rarbg]" "7a737abe1382e8ea74a2c8577d087051a75ca55f"
 `

**Comment by mdhiggins** [comment]
Running the commands manually without the required parameters or environment variables is destined to fail. 

When you run it via the correct software you should see something showing up in the log files for the script, (./config/sma.log)

Post that output to see if something is failing there.

**Comment by mozzer502** [comment]
ok, that makes sense. I deleted sma.log so we'd have easy to find results.
Then I downloaded a new show.
The logs show
```
2020-05-13 06:24:26 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2020-05-13 06:24:26 - resources.readsettings - INFO - /usr/local/opt/python/bin/python3.7
2020-05-13 06:24:26 - resources.readsettings - INFO - Loading config file /Users/andy/sickbeard_mp4_automator/config/autoProcess.ini.
2020-05-13 06:24:26 - qBittorrentPostProcess - ERROR - No valid label detected.
2020-05-13 06:24:26 - qBittorrentPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "/Users/andy/sickbeard_mp4_automator/qBittorrentPostProcess.py", line 48, in <module>
    sys.exit(1)
SystemExit: 1
```

**Comment by mdhiggins** [comment]
`2020-05-13 06:24:26 - qBittorrentPostProcess - ERROR - No valid label detected.`

You need to set a label for your torrent so it knows which program it came from. These are defined in autoProcess.ini and should be automatically set by the various programs

```
[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
port = 8080
ssl = False
host = localhost
username = 
password = 
output-directory =
```

**Comment by mozzer502** [comment]
woohoo and we have working system!!! (almost)
As far as I can tell everything now works. There's no "process completed" message in the log file so I'm assuming it ended well.
I do see this error though towards the end of the log.

```
2020-05-13 09:24:07 - resources.mediaprocessor - INFO - Starting conversion.
2020-05-13 09:25:25 - resources.mediaprocessor - INFO - /Users/andy/Downloads/Torrents/sonarr/Family.Guy.S18E19.Holly.Bibble.1080p.HULU.WEBRip.DDP5.1.x264-CtrlHD[rarbg]-convert/Family.Guy.S18E19.Holly.Bibble.1080p.HULU.WEB-DL.DD+5.1.H.264-CtrlHD.mp4 created.
2020-05-13 09:25:26 - qBittorrentPostProcess - INFO - Passing /Users/andy/Downloads/Torrents/sonarr/Family.Guy.S18E19.Holly.Bibble.1080p.HULU.WEBRip.DDP5.1.x264-CtrlHD[rarbg]-convert directory to Sonarr.
2020-05-13 09:25:26 - autoprocess.sonarr - INFO - Sonarr notifier started.
2020-05-13 09:25:26 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/Users/andy/Downloads/Torrents/sonarr/Family.Guy.S18E19.Holly.Bibble.1080p.HULU.WEBRip.DDP5.1.x264-CtrlHD[rarbg]-convert'.
2020-05-13 09:25:26 - autoprocess.sonarr - INFO - Sonarr response: queued.
2020-05-13 09:25:26 - qBittorrentPostProcess - ERROR - Unable to delete temporary directory
Traceback (most recent call last):
  File "/Users/andy/sickbeard_mp4_automator/qBittorrentPostProcess.py", line 197, in <module>
    os.rmdir(delete_dir)
OSError: [Errno 66] Directory not empty: '/Users/andy/Downloads/Torrents/sonarr/Family.Guy.S18E19.Holly.Bibble.1080p.HULU.WEBRip.DDP5.1.x264-CtrlHD[rarbg]-convert'
2020-05-13 09:25:28 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
2020-05-13 09:25:28 - resources.readsettings - INFO - /usr/local/opt/python/bin/python3.7
2020-05-13 09:25:28 - resources.readsettings - INFO - Loading config file /Users/andy/sickbeard_mp4_automator/config/autoProcess.ini.

```

Thank you for your help @mdhiggins I did not expect this kind of helpful, responsive service from a GitHub account :-)

**Comment by mdhiggins** [comment]
Yeah sonarr response queued is the last thing you should see. Sonarr should take things from there. 

Glad it’s working!
