### ISSUE TITLE
When I have tagging set to true I get this

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1251]
I was testing the tagging of files and this is what I get, The script now works perfect aslong as I have tag set to False.

```
Manual processor started.
Python 64-bit 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)].
Guessit version: 1.0.3.
C:\Program Files\Python\python.exe
Loading config file D:\Downloads\To Convert\Converter Stay\config\autoProcess.ini.
Enter path to file:
#: D:\downloads\to convert
Processing file D:\downloads\to convert\2 Broke Girls S01E01 Pilot Bluray-1080p.mp4
Traceback (most recent call last):
  File "D:\Downloads\To Convert\Converter Stay\manual.py", line 384, in <module>
    main()
  File "D:\Downloads\To Convert\Converter Stay\manual.py", line 360, in main
    walkDir(path, silent=silent, tmdbid=args.get('tmdbid'), tvdbid=args.get('tvdbid'), imdbid=args.get('imdbid'), preserveRelative=args['preserverelative'], tag=settings.tagfile, optionsOnly=args['optionsonly'])
  File "D:\Downloads\To Convert\Converter Stay\manual.py", line 268, in walkDir
    tagdata = getInfo(filepath, silent, tmdbid=tmdbid, tvdbid=tvdbid, imdbid=imdbid)
  File "D:\Downloads\To Convert\Converter Stay\manual.py", line 112, in getInfo
    tagdata = guessInfo(fileName, tvdbid=tvdbid, tmdbid=tmdbid, imdbid=imdbid, season=season, episode=episode)
  File "D:\Downloads\To Convert\Converter Stay\manual.py", line 157, in guessInfo
    guess = guessit.guessit(fileName)
AttributeError: module 'guessit' has no attribute 'guessit'
```

**Comment by morpheus2n2** [comment]
Fixed it, seems with all my messing around recently I accidently broke my python install, reinstalled python and then ran the requirements setup again and its now working 🤦‍♂️
