### ISSUE TITLE
DelugePostProcess Exception error

### ISSUE THREAD

**Issue by Killerherts** [mdhiggins/sickbeard_mp4_automator#1297]
My deluge post process script is being call but I am getting some kind of handshake error that a cannot figure out any suggestions are helpful.

2020-08-07` 08:34:53 - DelugePostProcess - INFO - Deluge post processing started.
2020-08-07 08:34:53 - resources.readsettings - INFO - /usr/bin/python3
2020-08-07 08:34:53 - resources.readsettings - INFO - Loading config file /home/killerherts/sickbeard_mp4_automator-master/sickbeard_mp4_automator-master/config/autoProcess.ini.
2020-08-07 08:35:13 - DelugePostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "/home/killerherts/sickbeard_mp4_automator-master/sickbeard_mp4_automator-master/delugePostProcess.py", line 35, in <module>
    client.connect()
  File "/home/killerherts/.local/lib/python3.8/site-packages/deluge_client/client.py", line 84, in connect
    self._connect()
  File "/home/killerherts/.local/lib/python3.8/site-packages/deluge_client/client.py", line 98, in _connect
    self._socket.connect((self.host, self.port))
  File "/usr/lib/python3.8/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.8/ssl.py", line 1333, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

**Comment by mdhiggins** [comment]
This is a generic connection timeout error when trying to connect to your deluge client via the API. You need to verify you have everything setup correctly in the deluge daemon and autoProcess.ini

https://github.com/mdhiggins/sickbeard_mp4_automator#deluge-daemon-setup

Have you done all these steps?

Post all your deluge info and your autoProcess deluge settings, auth file settings (feel free to censor password), and configured ports

**Comment by Killerherts** [comment]
yes I believe I have followed all the set up instructions 

autoProcess deluge as follows
[Deluge]
username = killerherts
sonarr-label = tv-sonarr
host = localhost
radarr-label = radarr
password = killpop
port = 8112
convert = True
sickbeard-label = sickbeard
remove = False
couchpotato-label = couchpotato
output-directory = 
bypass-label = bypass
sickrage-label = sickrage

Auth File looks as follows with different usernames and passwords
localclient:password:10
killerherts:password:10

deluge is set up to run on port 8112

**Comment by Killerherts** [comment]
yes I believe I have followed all the set up instructions

autoProcess deluge as follows
[Deluge]
username = killerherts
sonarr-label = tv-sonarr
host = localhost
radarr-label = radarr
password = password
port = 8112
convert = True
sickbeard-label = sickbeard
remove = False
couchpotato-label = couchpotato
output-directory =
bypass-label = bypass
sickrage-label = sickrage

Auth File looks as follows with different usernames and passwords
localclient:password:10
killerherts:password:10

deluge is set up to run on port 8112

**Comment by mdhiggins** [comment]
Think your port is probably wrong. 8112 is the WebUI but not the daemon port. You can see the daemon port on the connection manager of the webUI though. Default is `58846`

![image](https://user-images.githubusercontent.com/3608298/89667371-08afcb80-d8aa-11ea-88ba-5af359551e02.png)

**Comment by Killerherts** [comment]
wow ill put on my dunce cap for the day thanks mate

**Comment by mdhiggins** [comment]
All good, easy fix
