### ISSUE TITLE
SABnzbd failing with or without hwaccels enabled

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1306]
Making this its own issue now as it is presenting much frustration now, Sorry.

SABnzbd has in the last day started throwing up errors, I have done a fresh download/install of the script and also re-setup the autoprocess.ini and still run in to the same problems.
When SAB finishes the download the second (as in immediately there's no eclipsed time at all) it starts running the script it will display `SystemExit: 1`

The SMA log will show 
```
2020-08-19 05:16:42 - resources.mediaprocessor - INFO - Starting conversion.
2020-08-19 05:16:42 - resources.mediaprocessor - INFO - FFmpeg command:
2020-08-19 05:16:42 - resources.mediaprocessor - INFO - ======================
2020-08-19 05:16:42 - resources.mediaprocessor - INFO - C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -hwaccel dxva2 -i D:\Downloads\Completed\Jimmy.Kimmel.2020.08.17.Reese.Witherspoon.REPACK.720p.WEB.h264-ROBOTS\283db0990c8e4712a510e276ca507116.mkv -vcodec hevc_nvenc -map 0:0 -field_order progressive -vb 1500k -metadata:s:v BPS=1500000 -metadata:s:v BPS-eng=1500000 -metadata:s:v title=HD -level 5.1 -tag:v hvc1 -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y D:\Downloads\Completed\Jimmy.Kimmel.2020.08.17.Reese.Witherspoon.REPACK.720p.WEB.h264-ROBOTS\283db0990c8e4712a510e276ca507116.mp4
2020-08-19 05:16:42 - resources.mediaprocessor - INFO - ======================
2020-08-19 05:16:43 - resources.mediaprocessor - ERROR - Unexpected exception during conversion.
Traceback (most recent call last):
File "C:\Converter\resources\mediaprocessor.py", line 1418, in convert
progressOutput(timecode, debug)
File "C:\Converter\SABPostProcess.py", line 29, in progressOutput
print("%s%" % timecode)
ValueError: incomplete format
2020-08-19 05:16:43 - resources.mediaprocessor - ERROR - Error restoring original inputfile after FFMPEG error.
Traceback (most recent call last):
File "C:\Converter\resources\mediaprocessor.py", line 1418, in convert
progressOutput(timecode, debug)
File "C:\Converter\SABPostProcess.py", line 29, in progressOutput
print("%s%" % timecode)
ValueError: incomplete format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Converter\resources\mediaprocessor.py", line 1447, in convert
os.rename(inputfile, originalinputfile)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\Downloads\\Completed\\Jimmy.Kimmel.2020.08.17.Reese.Witherspoon.REPACK.720p.WEB.h264-ROBOTS\\283db0990c8e4712a510e276ca507116.mkv' -> 'D:\\Downloads\\Completed\\Jimmy.Kimmel.2020.08.17.Reese.Witherspoon.REPACK.720p.WEB.h264-ROBOTS\\283db0990c8e4712a510e276ca507116.mkv'
2020-08-19 05:16:43 - SABPostProcess - ERROR - Converting file failed D:\Downloads\Completed\Jimmy.Kimmel.2020.08.17.Reese.Witherspoon.REPACK.720p.WEB.h264-ROBOTS\283db0990c8e4712a510e276ca507116.mkv.
2020-08-19 05:16:43 - SABPostProcess - ERROR - No valid files found for conversion in download, aborting.
2020-08-19 05:16:43 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "C:\Converter\SABPostProcess.py", line 80, in <module>
sys.exit(1)
SystemExit: 1
```
^^This is with hwaccels.

```
2020-08-19 05:19:56 - resources.mediaprocessor - INFO - Starting conversion.
2020-08-19 05:19:56 - resources.mediaprocessor - INFO - FFmpeg command:
2020-08-19 05:19:56 - resources.mediaprocessor - INFO - ======================
2020-08-19 05:19:56 - resources.mediaprocessor - INFO - C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i D:\Downloads\Completed\The.Fugitive.2020.S01E13.When.Mike.Met.Colin.1080p.WEB-DL.AAC2.0.H.264-WELP\b3c850eab721439b9d525a3542ac7abc.mkv -vcodec hevc_nvenc -map 0:0 -field_order progressive -vb 1500k -metadata:s:v BPS=1500000 -metadata:s:v BPS-eng=1500000 -metadata:s:v title=FHD -level 5.1 -tag:v hvc1 -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:1 mov_text -map 0:3 -metadata:s:s:1 title= -metadata:s:s:1 language=eng -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y D:\Downloads\Completed\The.Fugitive.2020.S01E13.When.Mike.Met.Colin.1080p.WEB-DL.AAC2.0.H.264-WELP\b3c850eab721439b9d525a3542ac7abc.mp4
2020-08-19 05:19:56 - resources.mediaprocessor - INFO - ======================
2020-08-19 05:19:57 - resources.mediaprocessor - ERROR - Unexpected exception during conversion.
Traceback (most recent call last):
File "C:\Converter\resources\mediaprocessor.py", line 1418, in convert
progressOutput(timecode, debug)
File "C:\Converter\SABPostProcess.py", line 29, in progressOutput
print("%s%" % timecode)
ValueError: incomplete format
2020-08-19 05:19:57 - resources.mediaprocessor - ERROR - Error restoring original inputfile after FFMPEG error.
Traceback (most recent call last):
File "C:\Converter\resources\mediaprocessor.py", line 1418, in convert
progressOutput(timecode, debug)
File "C:\Converter\SABPostProcess.py", line 29, in progressOutput
print("%s%" % timecode)
ValueError: incomplete format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Converter\resources\mediaprocessor.py", line 1447, in convert
os.rename(inputfile, originalinputfile)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\Downloads\\Completed\\The.Fugitive.2020.S01E13.When.Mike.Met.Colin.1080p.WEB-DL.AAC2.0.H.264-WELP\\b3c850eab721439b9d525a3542ac7abc.mkv' -> 'D:\\Downloads\\Completed\\The.Fugitive.2020.S01E13.When.Mike.Met.Colin.1080p.WEB-DL.AAC2.0.H.264-WELP\\b3c850eab721439b9d525a3542ac7abc.mkv'
2020-08-19 05:19:57 - SABPostProcess - ERROR - Converting file failed D:\Downloads\Completed\The.Fugitive.2020.S01E13.When.Mike.Met.Colin.1080p.WEB-DL.AAC2.0.H.264-WELP\b3c850eab721439b9d525a3542ac7abc.mkv.
2020-08-19 05:19:57 - SABPostProcess - ERROR - No valid files found for conversion in download, aborting.
2020-08-19 05:19:57 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "C:\Converter\SABPostProcess.py", line 80, in <module>
sys.exit(1)
SystemExit: 1
```
^^This is without.
I have tried running this with and without hwaccels enabled, always the same result
I am running FFMpeg version `ffmpeg-20200816-5df9724-win64-static.zip`
All was fine but since installing Nvidia Drivers 452.06 I have noticed this problem!

The part that I find interesting is "resources.mediaprocessor - ERROR - Error restoring original inputfile after FFMPEG error."
As for the permission thing its because the file is in use however I can not find how by what other than ffmpeg

Really sorry to keep bothering you, just can't work out why even with a new download its suddenly stop working correctly after running fine for over 2 years.

**Comment by morpheus2n2** [comment]
Just wanted to add that I also get this even when using h264 and removing all traces of HW capabilities from the autoprocess.

**Comment by morpheus2n2** [comment]
Ok @mdhiggins I have found the problem and unfortunately it is something you have changed in the code in the last 9 days, luckily I have your script running on a different machine going through all my unsorted media, I last updated the script on it on 10/08/2020 at around 4pm GMT, I have just pulled this on over to my main downloading machine and ran SAB, just gone through 2 downloads absolutely perfect, one with all HW enabled and one without nether spat out a error.

Not sure if this helps you at all but it may give you a clue as to what's going on

**Comment by mdhiggins** [comment]
a84bb793afaa2bb8ca33d24ace055ba57dd6c37c

That should fix it

**Comment by morpheus2n2** [comment]
Cool, will test this in a bit and let you know :D

**Comment by morpheus2n2** [comment]
Yep all seems to be working now awesome stuff :D
