### ISSUE TITLE
Error when running manual

### ISSUE THREAD

**Issue by MrsAngelD** [mdhiggins/sickbeard_mp4_automator#1307]
I'm running Ubuntu 20.04 and when I use manual.py -i I get the following error

```
Traceback (most recent call last):
  File "/home/angel/.sickbeard_mp4_automator_manual/manual.py", line 15, in <module>
    from resources.mediaprocessor import MediaProcessor
  File "/home/angel/.sickbeard_mp4_automator_manual/resources/mediaprocessor.py", line 12, in <module>
    from resources.metadata import Metadata
  File "/home/angel/.sickbeard_mp4_automator_manual/resources/metadata.py", line 13, in <module>
    from mutagen.mp4 import MP4, MP4Cover, MP4StreamInfoError
ImportError: bad magic number in 'mutagen': b'\x03\xf3\r\n'
```

**Comment by mdhiggins** [comment]
Seems like you have a corrupted file related to your mutagen installation. The bad magic number error is a generic python error

https://stackoverflow.com/questions/514371/whats-the-bad-magic-number-error

**Comment by MrsAngelD** [comment]
Okay I fixed it by removing SMA and cloning it again. Thanks for that :)

**Comment by mdhiggins** [comment]
Good stuff. Will close
