### ISSUE TITLE
error ValueError: Not a boolean: Flase

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1320]
```
2020-09-08 19:46:06 - SABPostProcess - INFO - SAB post processing started.
2020-09-08 19:46:06 - resources.readsettings - INFO - /usr/bin/python3
2020-09-08 19:46:06 - resources.readsettings - INFO - Loading config file /opt/mp4automator/config/autoProcess.ini.
2020-09-08 19:46:06 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "/opt/mp4automator/SABPostProcess.py", line 33, in <module>
settings = ReadSettings()
File "/opt/mp4automator/resources/readsettings.py", line 576, in __init__
self.readConfig(config)
File "/opt/mp4automator/resources/readsettings.py", line 601, in readConfig
self.detailedprogress = config.getboolean(section, 'detailed-progress')
File "/usr/lib/python3.6/configparser.py", line 829, in getboolean
raw=raw, vars=vars, fallback=fallback, **kwargs)
File "/usr/lib/python3.6/configparser.py", line 809, in _get_conv
**kwargs)
File "/usr/lib/python3.6/configparser.py", line 803, in _get
return conv(self.get(section, option, **kwargs))
File "/usr/lib/python3.6/configparser.py", line 1155, in _convert_to_boolean
raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: Flase
```
i have also grabbed your latest files 2 hours ago. and still getting this error.

**Comment by mdhiggins** [comment]
```
self.detailedprogress = config.getboolean(section, 'detailed-progress')
...
ValueError: Not a boolean: Flase
```
You spelled False wrong in your config for the detailed progress option
