### ISSUE TITLE
Not an issue, want to check something.

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1326]
Sorry hit enter.
To go with the custom code you gave me a few weeks back to skip an already met codec, I was wondering if there was some I can use to convert an MKV even though it was the required codec?

Eg I am moving my entire library over to H265, however when I get a new file thats already H265 but in MKV format it obviously skips it I don't want this as I want it in MP4, but for pre-existing stuff I want it to skip if its already in the H265 Codec

Dose that make sence?

**Comment by mdhiggins** [comment]
?

**Comment by morpheus2n2** [comment]
> ?

Look at edit sorry I hit enter 🤦

**Comment by mdhiggins** [comment]
Got a link to the custom code issue? I don't recall specifically

**Comment by morpheus2n2** [comment]
Sure, This bit here.

At the moment I have 3 version of your script setup and I am trying to work that down to just 1 lol

**Comment by mdhiggins** [comment]
So if its mp4 and hevc you want to ignore it, if its mkv and hevc you want to remux?

**Comment by morpheus2n2** [comment]
Yep, cos the mkv still come in at a much larger file size.

I have one more thing I want to work out but that can wait for not lol

**Comment by mdhiggins** [comment]
that should have no impact on file size, the wrapper is negligible

but here's the code
```
    # Determine if a file can be read by FFPROBE
    def isValidSource(self, inputfile):
        try:
            extension = self.parseFile(inputfile)[2]
            if extension in self.settings.ignored_extensions:
                self.log.debug("Invalid source, extension is blacklisted [ignored-extensions].")
                return None
            if self.settings.minimum_size > 0 and os.path.getsize(inputfile) < (self.settings.minimum_size * 1000000):
                self.log.debug("Invalid source, below minimum size threshold [minimum-size].")
                return None
            info = self.converter.probe(inputfile)
            if not info:
                self.log.debug("Invalid source, no data returned.")
                return None
            if not info.video:
                self.log.debug("Invalid source, no video stream detected")
                return None
            if info.video.codec == 'hevc' and extension in ['mp4', 'm4v']:
                self.log.info("morpheus2n2 doesnt want you")
                return None
            if not info.audio or len(info.audio) < 1:
                self.log.debug("Invalid source, no audio stream detected")
                return None
            return info
        except:
            self.log.exception("isValidSource unexpectedly threw an exception, returning None")
            return None
```

**Comment by morpheus2n2** [comment]
Oh it dose cos I bring them down from about 20k bitrate to about 5k :D

**Comment by mdhiggins** [comment]
That has nothing to do with the container, you're probably reducing your stream quality substantially

**Comment by morpheus2n2** [comment]
yeah but not a massive amount that my users complain lmao, the main reason I don't do MKV is compatibility with devices mp4 is just so much more compatible and when streaming remotely I get no buffering at all on Plex compered to MKV :D 

Thanks for the code it seems to be working, not to sort out my 4k copy of the script, I'll no doubt be back pmsl

**Comment by morpheus2n2** [comment]
Ok I was wrong, only just noticed im now getting this from SAB

```
2020-09-23 22:39:21 - SABPostProcess - INFO - SAB post processing started.
2020-09-23 22:39:21 - resources.readsettings - INFO - C:\Program Files\Python38\python.exe
2020-09-23 22:39:21 - resources.readsettings - INFO - Loading config file C:\Converter\config\autoProcess.ini.
2020-09-23 22:39:21 - resources.readsettings - WARNING - Force-convert is true, so process-same-extensions is being overridden to true as well
2020-09-23 22:39:21 - SABPostProcess - INFO - Performing conversion
2020-09-23 22:39:21 - SABPostProcess - INFO - Processing file D:\Downloads\Completed\Youre.the.Worst.S03E13.No.Longer.Just.US.1080p.WEB-DL.DD5.1.H264-NTB\161102_14.mkv.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Input Data
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - {
"format": "matroska,webm",
"format-fullname": "Matroska / WebM",
"video": {
"index": 0,
"codec": "h264",
"pix_fmt": "yuv420p",
"profile": "high",
"fps": 23.976023976023978,
"dimensions": "1916x1076",
"level": 4.0,
"field_order": "progressive"
},
"audio": [
{
"index": 1,
"codec": "ac3",
"bitrate": 384000,
"channels": 6,
"samplerate": 48000,
"language": "eng",
"disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
}
],
"subtitle": [
{
"index": 2,
"codec": "subrip",
"disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
"language": "eng"
}
],
"attachment": []
}
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Reading video stream.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Video codec detected: h264.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Profile: high.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Video codec parameters None.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Creating h265_nvenc video stream from source stream 0.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Reading audio streams.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Audio detected for stream 1 - ac3 eng 6 channel.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Creating aac audio stream source audio stream 1 [universal-audio].
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Creating copy audio stream from source stream 1.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Default audio stream set to eng copy 6 channel stream [default-more-channels: True].
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Reading subtitle streams.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Text-based subtitle detected for stream 2 - subrip eng.
2020-09-23 22:39:21 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream from source stream 2.
2020-09-23 22:39:21 - resources.mediaprocessor - ERROR - Unable to generate options, unexpected exception occurred.
Traceback (most recent call last):
File "C:\Converter\resources\mediaprocessor.py", line 113, in process
options, preopts, postopts, ripsubopts, downloaded_subs = self.generateOptions(inputfile, info=info, original=original)
File "C:\Converter\resources\mediaprocessor.py", line 788, in generateOptions
valid_external_subs = self.scanForExternalSubs(inputfile, swl)
File "C:\Converter\resources\mediaprocessor.py", line 1141, in scanForExternalSubs
valid_external_sub = self.isValidSubtitleSource(os.path.join(dirName, fname))
AttributeError: 'MediaProcessor' object has no attribute 'isValidSubtitleSource'
2020-09-23 22:39:21 - SABPostProcess - ERROR - Converting file failed D:\Downloads\Completed\Youre.the.Worst.S03E13.No.Longer.Just.US.1080p.WEB-DL.DD5.1.H264-NTB\161102_14.mkv.
2020-09-23 22:39:21 - SABPostProcess - ERROR - No valid files found for conversion in download, aborting.
2020-09-23 22:39:21 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "C:\Converter\SABPostProcess.py", line 80, in <module>
sys.exit(1)
SystemExit: 1 
```

**Comment by mdhiggins** [comment]
You broke something in your code or deleted something you shouldn't have, looks like you deleted or messed up isValidSubtitleSource

**Comment by morpheus2n2** [comment]
pmsl, I just Copy and pasted opps

**Comment by morpheus2n2** [comment]
Fixed it that was me rushing things lol sorry about that
