### ISSUE TITLE
updated ffmpeg generates errors on conversion

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1328]
Nvidia cuda driver updates came out which I upgraded on my centos 7.x system which in turn meant I had to recompile ffmpeg. Now conversions results in sporadic errors. A snippet of the sma log file is below. The entire log file is uploaded but the errors are at the tail end of it.

If there is anything else needed or something I can do on my end please let me know.

```
2020-09-24 13:19:29 - NZBGetPostProcess - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/opt/mp4automator/resources/mediaprocessor.py", line 1485, in convert
    for timecode, debug in conv:
  File "/opt/mp4automator/converter/__init__.py", line 304, in convert
    for timecode, debug in self.ffmpeg.convert(outfile, optlist,
  File "/opt/mp4automator/converter/ffmpeg.py", line 706, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
2020-09-24 13:19:29 - NZBGetPostProcess - ERROR - /usr/bin/ffmpeg -i /dwnldr/nzb/comp/movie/Highlander.The.Final.Dimension.1994.1080p.BluRay.x264-HANDJOB/6a3692194b1f4e8c8633b1cd011a1e16.mkv -vcodec copy -map 0:0 -metadata:s:v title=FHD -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 title=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -max_muxing_queue_size 9999 -y /dwnldr/nzb/comp/movie/Highlander.The.Final.Dimension.1994.1080p.BluRay.x264-HANDJOB/6a3692194b1f4e8c8633b1cd011a1e16.mp4
2020-09-24 13:19:29 - NZBGetPostProcess - ERROR - ffmpeg version N-99352-gd8ce8e8 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-39)
  configuration: --prefix=/opt/ffmpeg_build --pkg-config-flags=--static --extra-cflags='-I/opt/ffmpeg_build/include -I/usr/local/cuda/include' --extra-ldflags='-L/opt/ffmpeg_build/lib -L/usr/local/cuda/lib64' --extra-libs=-lpthread --extra-libs=-lm --bindir=/usr/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-cuda --enable-cuvid --enable-nvenc --enable-libnpp
  libavutil      56. 59.100 / 56. 59.100
  libavcodec     58.106.100 / 58.106.100
  libavformat    58. 58.100 / 58. 58.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
```

[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5273457/sma.log)

**Comment by mdhiggins** [comment]
Its not printing much but appears to be an FFMPEG error, if you run the command that's generated manually what does FFMPEG say?

**Comment by johnwchambers** [comment]
I noticed in my ffmpeg update compile script that I was grabbing their nightly snapshot version. I changed it to pull down 4.3.1 instead and recompiled again. Everything is processing just fine now. Thanks for the quick response and for the project overall! ^^
