### ISSUE TITLE
Error on Downloading Subs. After a Re Image of server after a failed OS

### ISSUE THREAD

**Issue by Weezzel** [mdhiggins/sickbeard_mp4_automator#1331]
[sma - Copy.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5283899/sma.-.Copy.zip)

Made sure all PIP's were installed via requirements.txt
Python 3.8.6 - Sept. 24, 2020

2020-09-25 11:50:04 - MANUAL - INFO - Creating copy audio stream from source stream 1.
2020-09-25 11:50:04 - MANUAL - INFO - Default audio stream set to eng copy 2 channel stream [default-more-channels: True].
2020-09-25 11:50:04 - MANUAL - INFO - Reading subtitle streams.
2020-09-25 11:50:04 - MANUAL - INFO - Attempting to download subtitles.
2020-09-25 11:50:17 - MANUAL - ERROR - Unable to download subtitles.
Traceback (most recent call last):
  File "C:\Sick_MP4\resources\mediaprocessor.py", line 1233, in downloadSubtitles
    subtitles = subliminal.download_best_subtitles([video], languages, hearing_impaired=self.settings.hearing_impaired, providers=self.settings.subproviders)
  File "C:\Python38\lib\site-packages\subliminal\core.py", line 651, in download_best_subtitles
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
  File "C:\Python38\lib\site-packages\subliminal\core.py", line 202, in download_best_subtitles
    scored_subtitles = sorted([(s, compute_score(s, video, hearing_impaired=hearing_impaired))
  File "C:\Python38\lib\site-packages\subliminal\core.py", line 202, in <listcomp>
    scored_subtitles = sorted([(s, compute_score(s, video, hearing_impaired=hearing_impaired))
  File "C:\Python38\lib\site-packages\subliminal\score.py", line 112, in compute_score
    matches = subtitle.get_matches(video)
  File "C:\Python38\lib\site-packages\subliminal\providers\podnapisi.py", line 50, in get_matches
    matches = guess_matches(video, {
  File "C:\Python38\lib\site-packages\subliminal\matches.py", line 226, in guess_matches
    if key in matches_manager and matches_manager[key](video, partial=partial, **guess):
  File "C:\Python38\lib\site-packages\subliminal\matches.py", line 20, in series_matches
    return video.series and sanitize(title) in (
  File "C:\Python38\lib\site-packages\subliminal\matches.py", line 21, in <genexpr>
    sanitize(name) for name in [video.series] + video.alternative_series
  File "C:\Python38\lib\site-packages\subliminal\utils.py", line 122, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "C:\Python38\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2020-09-25 11:50:17 - MANUAL - INFO - cuda hwaccel is supported by this ffmpeg build and will be used [hwaccels].
2020-09-25 11:50:17 - MANUAL - INFO - Output Data
2020-09-25 11:50:17 - MANUAL - INFO - {

**Comment by mdhiggins** [comment]
https://github.com/Diaoul/subliminal/issues/974

Make sure you're using latest version of everything but seems like a guessit or subliminal but

Also this might help
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1221

**Comment by mdhiggins** [comment]
Closing for now but feel free to reopen if that doesn't work
