### ISSUE TITLE
Specifying an output directory breaks automator

### ISSUE THREAD

**Issue by liamdemafelix** [mdhiggins/sickbeard_mp4_automator#1349]
Hi.

I've tried adding an output directory in the config, since I'm mounting my library over rclone and I figured it's not as reliable as transcoding locally then pushing.

For some reason, it's throwing the following:

```
2020-10-19 11:59:32 - resources.mediaprocessor - ERROR - Error processing
Traceback (most recent call last):
  File "/path/to/automator/resources/mediaprocessor.py", line 65, in fullprocess
    output['output'] = self.restoreFromOutput(inputfile, output['output'])
  File "/path/to/automator/resources/mediaprocessor.py", line 1257, in restoreFromOutput
    newoutputfile, _ = self.getOutputFile(input_dir, filename, input_extension, output_directory=None)
TypeError: getOutputFile() got an unexpected keyword argument 'output_directory'
2020-10-19 11:59:32 - SonarrPostProcess - INFO - Processing returned False.
2020-10-19 11:59:32 - SonarrPostProcess - ERROR - Error processing file
Traceback (most recent call last):
  File "/path/to/automator/postSonarr.py", line 226, in <module>
    sys.exit(1)
```

Entirely new to Python so if you need any other log I can pull it out for you if needed. I'm on Python 3.8.5.

**Comment by mdhiggins** [comment]
4e5875fbfc650240de4823a50b3507a75bca73cc

See if that fixes things

**Comment by liamdemafelix** [comment]
That fixed it.

Thanks!
