### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Spankythemusical** [mdhiggins/sickbeard_mp4_automator#1361]
I'm at a complete loss.  I'm running the most recent version of SMA.  Replaced everything.  Now, trying to run manual.py, I keep receiving this error (This did work before, but I've already deleted those files...oops):

`There was an error tagging the file
Traceback (most recent call last):
  File "manual.py", line 235, in processFile
    tagdata.writeTags(output['output'], mp.converter, settings.artwork, settings.thumbnail, width=output['x'], height=output['y'])
  File "F:\sickbeard_mp4_automator-master\resources\metadata.py", line 207, in writeTags
    video["\xa9nam"] = self.title  # Video title
  File "C:\Python38\lib\site-packages\mutagen\_file.py", line 74, in __setitem__
    self.tags[key] = value
  File "C:\Python38\lib\site-packages\mutagen\mp4\__init__.py", line 374, in __setitem__
    self._render(key, value)
  File "C:\Python38\lib\site-packages\mutagen\mp4\__init__.py", line 390, in _render
    return render_func(self, key, value, *render_args)
  File "C:\Python38\lib\site-packages\mutagen\mp4\__init__.py", line 821, in __render_text
    for v in value:
TypeError: 'NoneType' object is not iterable`

The conversion and old-file-deletion is occuring.  The tagging, however, is failing.

For reference, I have run manual.py with both of these commands:

`python manual.py -i "F:\Ended TV Shows\Can't Pay! We'll Take It Away!\Season 4\Can't Pay! We'll Take It Away! - S04E07 - Episode 7.mkv" -tvdb 278635 -s 4 -e 7`

and 

`python manual.py -i "F:\Ended TV Shows\Can't Pay! We'll Take It Away!\Season 4\Can't Pay! We'll Take It Away! - S04E07 - Episode 7.mkv" -a`

My config is:

```
[Converter]
ffmpeg = ffmpeg.exe
ffprobe = ffprobe.exe
threads = 0
hwaccels = dxva2, cuvid, qsv, d3d11va, vaapi
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi, h264_vaapi
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
preopts = 
postopts = 

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = poster
sanitize-disposition = 

[Video]
codec = h264, x264
max-bitrate = 0
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
filter = 
force-filter = False

[HDR]
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False

[Audio]
codec = ac3
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
force-filter = False
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions = 
unique-dispositions = False

[Universal Audio]
codec = aac
channel-bitrate = 128
first-stream-only = False
move-after = False
filter = 
force-filter = False

[Subtitle]
codec = mov_text
codec-image-based = 
languages = 
default-language = 
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
download-subs = False
download-hearing-impaired-subs = False
download-providers = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = 

[Sonarr]
host = localhost
port = 8989
apikey = 
ssl = False
webroot = 
force-rename = False

[Radarr]
host = localhost
port = 7878
apikey = 
ssl = False
webroot = 
force-rename = False

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
apikey = 
delay = 65
method = renamer
delete-failed = False
ssl = False
webroot = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
couchpotato-category = couchpotato
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 
path-mapping = 

[uTorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token = 
```

**Comment by Spankythemusical** [comment]
It works as expected if the episode title is not "Episode #".  

Another show I tried resulted in the same error, but with this additional message:

```
Matched TV episode as Can't Pay? We'll Take It Away! (TMDB ID: 64091) S04E14
Processing Can't Pay? We'll Take It Away! Season 04 Episode 15 None.
```

But a different episode showed:

```
Matched TV episode as The Transformers (TMDB ID: 4269) S03E29
Processing The Transformers Season 03 Episode 29 - The Return of Optimus Prime (1)
```

**Comment by mdhiggins** [comment]
Seems that this is a problem with the metadata for these episodes being wrong, TMDB appears to return `None` for title instead of `'Episode #'`

Added a catch to manually use the episode number as title if `None` is encountered

5a523155d1e1ad0436afe29171645639a2f90f23
