### ISSUE TITLE
Mutagen fails with [Errno 13] No Permission

### ISSUE THREAD

**Issue by Deddiekoel** [mdhiggins/sickbeard_mp4_automator#1362]
I've had this problem for a while on my Synology running python3. Everytime I process a file using postSickbeard.py it doesn't fail but in the logs it says it could write tags nor download subtitles. 
From what I can gather the resulting file has very limited permissions (-rw-r--r--) which it didn't have before the post-processing started (-rwxrwxrwx+)

The medusa user (sc-medusa) had full control over the input and output folders and when I skip the postSickbeard.py script it sets the permissions a little less strict and usable (-rw-rw-rw-).

I've already tried settings the Permissions in the autoprocess.ini to 0655.

The error:
ERROR - There was an error writing the tags.\nTraceback (most recent call last):\n File "/var/packages/python3/target/lib/python3.7/site-packages/mutagen/_util.py", line 251, in _openfile\n fileobj = open(filename, "rb+" if writable else "rb")\nPermissionError: [Errno 13] Permission denied:xxx During handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/volume1/process/Process/sickbeard_mp4_automator/resources/metadata.py", line 245, in writeTags\n video.save()\n File "/var/packages/python3/target/lib/python3.7/site-packages/mutagen/mp4/__init__.py", line 1221, in save\n super(MP4, self).save(*args, **kwargs)\n File "/var/packages/python3/target/lib/python3.7/site-packages/mutagen/_util.py", line 155, in wrapper\n writable, create) as h:\n File "/var/packages/python3/target/lib/python3.7/contextlib.py", line 112, in __enter__\n return next(self.gen)\n File "/var/packages/python3/target/lib/python3.7/site-packages/mutagen/_util.py", line 272, in _openfile\n raise MutagenError(e)\nmutagen.MutagenError: [Errno 13] Permission denied

**Comment by Deddiekoel** [comment]
Fixed it by setting the Permissions in the autoprocess.ini to 0666 (stupid mistake).
Still weird that the default config does not allow for tag writing and subtitles.
