### ISSUE TITLE
Possible to disable hwaccel vaapi?

### ISSUE THREAD

**Issue by ravensorb** [mdhiggins/sickbeard_mp4_automator#1371]
I am running your script inside a container that does not have access to any hardware so I was curios if there is a way to disable it completely from the command line params you generate for ffmeg.  I have tired removing and commenting it out in autoProcess.ini and it just gets added anyways.

**Comment by mdhiggins** [comment]
Don't comment it out just leave the hwaccel options set to blank

**Comment by mdhiggins** [comment]
Additionally the hwaccel options should not be applied if the FFMpeg build does not support them even if they're left in

**Comment by ravensorb** [comment]
I did try leaving it blank 

Tried
```
hwaccels = dxva2, cuvid, qsv, d3d11va #, vaapi
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid #, hevc_qsv, h264_qsv, hevc_vaapi, h264_vaapi
hwdevices = #vaapi:/dev/dri/renderD128
hwaccel-output-format = #vaapi:vaapi
```

and

```
hwaccels = dxva2, cuvid, qsv, d3d11va 
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid 
hwdevices = 
hwaccel-output-format = 
```

And yet I am getting a lot of errors like this

```
2020-12-02 10:14:51 - NZBGetPostProcess - INFO - FFmpeg command:
2020-12-02 10:14:51 - NZBGetPostProcess - INFO - ======================
2020-12-02 10:14:51 - NZBGetPostProcess - INFO - /usr/bin/ffmpeg -hwaccel vaapi -i video.mkv -vcodec libx264 -map 0:0 -vb 11485k -metadata:s:v BPS=11485000 -metadata:s:v BPS-eng=11485000 -metadata:s:v title=FHD -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 BPS=1536000 -metadata:s:a:1 BPS-eng=1536000 -metadata:s:a:1 title=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y video.m4v
2020-12-02 10:14:51 - NZBGetPostProcess - INFO - ======================
2020-12-02 10:14:53 - NZBGetPostProcess - INFO - 0
2020-12-02 10:14:53 - NZBGetPostProcess - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/mnt/scripts/sickbeard_mp4_automator/resources/mediaprocessor.py", line 1488, in convert
    for timecode, debug in conv:
  File "/mnt/scripts/sickbeard_mp4_automator/converter/__init__.py", line 308, in convert
    for timecode, debug in self.ffmpeg.convert(outfile, optlist,
  File "/mnt/scripts/sickbeard_mp4_automator/converter/ffmpeg.py", line 706, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
```

Any thoughts?

**Comment by mdhiggins** [comment]
```
hwaccels = 
hwaccel-decoders = 
hwdevices = 
hwaccel-output-format = 
```

Try that

**Comment by ravensorb** [comment]
Seems like it is still generating a command line with hwaccel in it.

```
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p10le.
Profile: main 10.
Video codec parameters None.
Creating h264 video stream from source stream 0.
Reading audio streams.
Audio detected for stream 1 - dts eng 6 channel.
Creating aac audio stream source audio stream 1 [universal-audio].
Creating ac3 audio stream from source stream 1.
Default audio stream set to eng ac3 6 channel stream [default-more-channels: True].
Reading subtitle streams.
Image-based subtitle detected for stream 2 - dvd_subtitle eng.
Scanned for external subtitles and found 0 results in your approved languages.
vaapi hwaccel is supported by this ffmpeg build and will be used [hwaccels].
Output Data
```
and
```
/usr/bin/ffmpeg -hwaccel vaapi -i video.mkv -vcodec libx264 -map 0:0 -vb 14221k -metadata:s:v BPS=14221000 -metadata:s:v BPS-eng=14221000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 BPS=1536000 -metadata:s:a:1 BPS-eng=1536000 -metadata:s:a:1 title=5.1 Channel -metadata:s:a:1 handler_name=5.1 Channel -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y video.m4v
```

**Comment by mdhiggins** [comment]
And you're sure the config file you're using is actually the applied file?

Can you post a full conversion log using DEBUG level logging?

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging
