### ISSUE TITLE
ValueError: unused keyword argument 'formatter'

### ISSUE THREAD

**Issue by barbequesauce** [mdhiggins/sickbeard_mp4_automator#1388]
First time using the tool, so I'm sure it's either PEBCAK or ID10T errors...

Converting IMAX 1080p WEB-DL H264 Atmos MKV to 1080p H264 AAC MP4 with a 4k bitrate ceiling. ffmpeg 

```
======================
/usr/bin/ffmpeg -I /file/name/redacted.mkv -vcodec copy -map 0:0 -metadata:s:v title="FHD" -metadata:s:v handler_name="FHD" -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title="Stereo" -metadata:s:a:0 handler_name="Stereo" -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 aac -map 0:1 -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 BPS=1536000 -metadata:s:a:1 BPS-eng=1536000 -metadata:s:a:1 title="5.1 Channel" -metadata:s:a:1 handler_name="5.1 Channel" -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /file/name/redacted.mp4
======================
[####################] 100%
/file/name/redacted.mp4 created.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/local/lib/python3.8/site-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/local/lib/python3.8/site-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/local/lib/python3.8/site-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/local/lib/python3.8/site-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/local/lib/python3.8/site-packages/regex/regex.py", line 349, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/local/lib/python3.8/site-packages/regex/regex.py", line 586, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manual.py", line 425, in <module>
    main()
  File "./manual.py", line 414, in main
    processFile(path, mp, info=info, silent=silent, tag=settings.tagfile, tmdbid=args.get('tmdbid'), tvdbid=args.get('tvdbid'), imdbid=args.get('imdbid'), season=args.get('season'), episode=args.get('episode'), original=args.get('original'))
  File "./manual.py", line 244, in processFile
    tagdata = getInfo(inputfile, silent, tag=tag, tmdbid=tmdbid, tvdbid=tvdbid, imdbid=imdbid, season=season, episode=episode, language=language, original=original)
  File "./manual.py", line 128, in getInfo
    tagdata = guessInfo(fileName, tvdbid=tvdbid, tmdbid=tmdbid, imdbid=imdbid, season=season, episode=episode, language=language, original=original)
  File "./manual.py", line 173, in guessInfo
    guess = guessit.guessit(original or fileName)
  File "/usr/local/lib/python3.8/site-packages/guessit/api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "/usr/local/lib/python3.8/site-packages/guessit/api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=/file/name/redacted.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/usr/local/lib/python3.8/site-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/local/lib/python3.8/site-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/local/lib/python3.8/site-packages/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/local/lib/python3.8/site-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/local/lib/python3.8/site-packages/regex/regex.py", line 349, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/local/lib/python3.8/site-packages/regex/regex.py", line 586, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

**Comment by mdhiggins** [comment]
This is actually a guessit error

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1221

See

**Comment by mdhiggins** [comment]
https://github.com/guessit-io/guessit/issues/656

https://github.com/guessit-io/guessit/issues/650

And actually it looks like the REGEX_DISABLED env variable isn't needed anymore, the default behavior is disabled

Updating rebulk should fix things

https://github.com/Toilal/rebulk/commit/d5a8cad6281533ee549a46ca70e1a25e5777eda3

**Comment by barbequesauce** [comment]
Thanks - had to update both guest and rebulk, works like a charm now!
