### ISSUE TITLE
Need help with an error.

### ISSUE THREAD

**Issue by DatsiK96** [mdhiggins/sickbeard_mp4_automator#1416]
Not sure what's going on here. Might just be a bad source, but what do you think? Full log is here: https://pastebin.com/FjxS5Fc3

```
2021-02-21 14:01:11 - resources.mediaprocessor - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "D:\sickbeard_mp4_automator\resources\mediaprocessor.py", line 1580, in convert
    for timecode, debug in conv:
  File "D:\sickbeard_mp4_automator\converter\__init__.py", line 303, in convert
    for timecode, debug in self.ffmpeg.convert(outfile, optlist,
  File "D:\sickbeard_mp4_automator\converter\ffmpeg.py", line 715, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
2021-02-21 14:01:11 - resources.mediaprocessor - ERROR - D:\FFMPEG\ffmpeg.exe -hwaccel dxva2 -i \\BSDSrv01\Heartsbane\Movies\Into the Wild (2007)\Into the Wild (2007) [Bluray-1080p] [8bit] [x264] [DTS-5.1] [EN+TR]-PRoDJi.mkv -vcodec libx264 -map 0:0 -field_order progressive -crf 28 -metadata:s:v BPS=11598000 -metadata:s:v BPS-eng=11598000 -metadata:s:v title="FHD" -metadata:s:v handler_name="FHD" -profile:v high10 -level 3.1 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -metadata:s:a:0 title="Stereo" -metadata:s:a:0 handler_name="Stereo" -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 aac -map 0:1 -ac:a:1 6 -b:a:1 768k -metadata:s:a:1 BPS=768000 -metadata:s:a:1 BPS-eng=768000 -metadata:s:a:1 title="5.1 Channel" -metadata:s:a:1 handler_name="5.1 Channel" -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:2 aac -map 0:2 -ac:a:2 2 -b:a:2 256k -metadata:s:a:2 BPS=256000 -metadata:s:a:2 BPS-eng=256000 -metadata:s:a:2 title="Stereo" -metadata:s:a:2 handler_name="Stereo" -metadata:s:a:2 language=tur -disposition:a:2 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:3 aac -map 0:2 -ac:a:3 6 -b:a:3 768k -metadata:s:a:3 BPS=768000 -metadata:s:a:3 BPS-eng=768000 -metadata:s:a:3 title="5.1 Channel" -metadata:s:a:3 handler_name="5.1 Channel" -metadata:s:a:3 language=tur -disposition:a:3 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y \\BSDSrv01\Heartsbane\Movies\Into the Wild (2007)\Into the Wild (2007) [Bluray-1080p] [8bit] [x264] [DTS-5.1] [EN+TR]-PRoDJi.temp
2021-02-21 14:01:11 - resources.mediaprocessor - ERROR - ffmpeg version 4.3.2-2021-02-02-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
```

There is also this

```
[AVHWFramesContext @ 000002b7794d5fc0] Error creating an internal frame pool

[h264 @ 000002b77957e080] Failed setup for format dxva2_vld: hwaccel initialisation returned error.
[h264 @ 000002b77957e080] Failed setup for format dxva2_vld: hwaccel initialisation returned error.

[libx264 @ 000002b778afa540] using SAR=1/1

[libx264 @ 000002b778afa540] frame MB size (120x50) > level limit (3600)

[libx264 @ 000002b778afa540] DPB size (4 frames, 24000 mbs) > level limit (3 frames, 18000 mbs)

[libx264 @ 000002b778afa540] MB rate (143856) > level limit (108000)

[libx264 @ 000002b778afa540] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2

[libx264 @ 000002b778afa540] profile High, level 3.1, 4:2:0, 8-bit

[libx264 @ 000002b778afa540] 264 - core 161 r3043 59c0609 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=25 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

frame=   11 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=   43 fps= 43 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
Too many packets buffered for output stream 0:1.

[aac @ 000002b778afa9c0] Qavg: 65093.676

[aac @ 000002b778afa9c0] 2 frames left in the queue on closing

[aac @ 000002b778afb780] Qavg: 65291.316

[aac @ 000002b778afb780] 2 frames left in the queue on closing

Conversion failed!


2021-02-21 14:01:12 - resources.mediaprocessor - ERROR - \\BSDSrv01\Heartsbane\Movies\Into the Wild (2007)\Into the Wild (2007) [Bluray-1080p] [8bit] [x264] [DTS-5.1] [EN+TR]-PRoDJi.temp deleted.
2021-02-21 14:01:14 - RadarrPostProcess - INFO - Processing returned False.
2021-02-21 14:01:14 - RadarrPostProcess - ERROR - Error processing file
Traceback (most recent call last):
  File "D:\sickbeard_mp4_automator\postRadarr.py", line 212, in <module>
    sys.exit(1)
SystemExit: 1
```

No other video is having this issue. Thoughts?

Guess I should give some info on the system...

It's on Windows running on a VMWare VM.

**Comment by mdhiggins** [comment]
I believe this error can be addressed by increasing your max_muxing_queue_size in FFmpeg
Try setting post-opts to `postopts = -max_muxing_queue_size, 9999` to achieve this (assuming you're using `,` as your `opts-separator`. Make sure to include the comma

**Comment by DatsiK96** [comment]
That indeed fixed it. I copied it exactly as you put it into the config and it encoded no issue.

Thanks man. Really great work! :)
