### ISSUE TITLE
Incorrect installation/configuration

### ISSUE THREAD

**Issue by Clifford10** [mdhiggins/sickbeard_mp4_automator#1422]
I used

pip install -r c:/mp4_automator/setup/requirememts.txt

However, when I run it against a test mkv file, I get the following:
```

D:\Work>python c:\mp4_automator\manual.py -i test.mkv -a
Traceback (most recent call last):
  File "c:\mp4_automator\manual.py", line 5, in <module>
    import guessit
  File "C:\Python3\lib\site-packages\guessit\__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "C:\Python3\lib\site-packages\guessit\plugins\transformers.py", line 222, in <module>
    reload()
  File "C:\Python3\lib\site-packages\guessit\plugins\transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "C:\Python3\lib\site-packages\guessit\plugins\transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "C:\Python3\lib\site-packages\guessit\plugins\transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "C:\Python3\lib\site-packages\stevedore\extension.py", line 291, in map
    raise NoMatches('No %s extensions found' % self.namespace)
stevedore.exception.NoMatches: No guessit.transformer extensions found
```

I obviously have something incorrect, but I don't know what it could be.

**Comment by mdhiggins** [comment]
I'm thinking you've got some old version of some of the requirements installed

Try `pip install --upgrade -r c:/mp4_automator/setup/requirements.txt`

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/643

This is a leftover error from a very old version of guessit that required an old verson of stevedore, if you update both of these packages the latest for each should be compatible

**Comment by Clifford10** [comment]
Thanks for the guidance. This did indeed clean it up.
