### ISSUE TITLE
The Radarr Fix last night broke Sonarr lol

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1448]
It seems the radarr fix last night has somehow broken Sonarr
2021-06-06 10:41:52 - autoprocess.sonarr - ERROR - Update to Sonarr failed, check if Sonarr is running, autoProcess.ini settings and make sure your Sonarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "A:\PlexBackend\Converter\autoprocess\sonarr.py", line 82, in accessAPI
log.info("%sSonarr response: %s." % (infoprefix, rstate['state']))

lmao

**Comment by mdhiggins** [comment]
cb10cef38639c70f09d15a531966cdaebbc93371

Does that fix it?

**Comment by morpheus2n2** [comment]
Think its working 

```
2021-06-06 17:47:02 - resources.mediaprocessor - INFO - D:\Downloads\Completed\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT.mp4 created.
--- Logging error ---
Traceback (most recent call last):
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 74, in emit
self.doRollover()
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 177, in doRollover
self.rotate(self.baseFilename, dfn)
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 115, in rotate
os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'A:\\PlexBackend\\Converter\\config\\sma.log' -> 'A:\\PlexBackend\\Converter\\config\\sma.log.1'
Call stack:
File "A:\PlexBackend\Converter\SABPostProcess.py", line 69, in <module>
output = mp.process(inputfile, reportProgress=True, info=info, progressOutput=progressOutput)
File "A:\PlexBackend\Converter\resources\mediaprocessor.py", line 160, in process
outputfile, inputfile = self.convert(options, preopts, postopts, reportProgress, progressOutput)
File "A:\PlexBackend\Converter\resources\mediaprocessor.py", line 1626, in convert
self.log.info("%s created." % outputfile)
Message: 'D:\\Downloads\\Completed\\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT\\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT.mp4 created.'
Arguments: ()
2021-06-06 17:47:02 - SABPostProcess - INFO - Successfully processed D:\Downloads\Completed\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT.mkv.
--- Logging error ---
Traceback (most recent call last):
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 74, in emit
self.doRollover()
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 177, in doRollover
self.rotate(self.baseFilename, dfn)
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 115, in rotate
os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'A:\\PlexBackend\\Converter\\config\\sma.log' -> 'A:\\PlexBackend\\Converter\\config\\sma.log.1'
Call stack:
File "A:\PlexBackend\Converter\SABPostProcess.py", line 71, in <module>
log.info("Successfully processed %s." % inputfile)
Message: 'Successfully processed D:\\Downloads\\Completed\\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT\\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT.mkv.'
Arguments: ()
2021-06-06 17:47:02 - SABPostProcess - INFO - Passing D:\Downloads\Completed\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT directory to Sonarr.
--- Logging error ---
Traceback (most recent call last):
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 74, in emit
self.doRollover()
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 177, in doRollover
self.rotate(self.baseFilename, dfn)
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 115, in rotate
os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'A:\\PlexBackend\\Converter\\config\\sma.log' -> 'A:\\PlexBackend\\Converter\\config\\sma.log.1'
Call stack:
File "A:\PlexBackend\Converter\SABPostProcess.py", line 94, in <module>
log.info("Passing %s directory to Sonarr." % path)
Message: 'Passing D:\\Downloads\\Completed\\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT directory to Sonarr.'
Arguments: ()
2021-06-06 17:47:02 - autoprocess.sonarr - INFO - Sonarr notifier started.
--- Logging error ---
Traceback (most recent call last):
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 74, in emit
self.doRollover()
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 177, in doRollover
self.rotate(self.baseFilename, dfn)
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 115, in rotate
os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'A:\\PlexBackend\\Converter\\config\\sma.log' -> 'A:\\PlexBackend\\Converter\\config\\sma.log.1'
Call stack:
File "A:\PlexBackend\Converter\SABPostProcess.py", line 95, in <module>
sonarr.processEpisode(path, settings, importMode="Move", pathMapping=path_mapping)
File "A:\PlexBackend\Converter\autoprocess\sonarr.py", line 18, in processEpisode
log.info("%sSonarr notifier started." % infoprefix)
Message: 'Sonarr notifier started.'
Arguments: ()
2021-06-06 17:47:02 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\Downloads\Completed\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT'.
--- Logging error ---
Traceback (most recent call last):
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 74, in emit
self.doRollover()
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 177, in doRollover
self.rotate(self.baseFilename, dfn)
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 115, in rotate
os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'A:\\PlexBackend\\Converter\\config\\sma.log' -> 'A:\\PlexBackend\\Converter\\config\\sma.log.1'
Call stack:
File "A:\PlexBackend\Converter\SABPostProcess.py", line 95, in <module>
sonarr.processEpisode(path, settings, importMode="Move", pathMapping=path_mapping)
File "A:\PlexBackend\Converter\autoprocess\sonarr.py", line 66, in processEpisode
log.info("%sRequesting Sonarr to scan directory '%s'." % (infoprefix, dirName))
Message: "Requesting Sonarr to scan directory 'D:\\Downloads\\Completed\\The.Girlfriend.Experience.S03E06.MULTi.1080p.WEB.H264-SHEEEIT'."
Arguments: ()
2021-06-06 17:47:02 - autoprocess.sonarr - INFO - Sonarr response: queued.
--- Logging error ---
Traceback (most recent call last):
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 74, in emit
self.doRollover()
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 177, in doRollover
self.rotate(self.baseFilename, dfn)
File "C:\Users\morph\AppData\Local\Programs\Python\Python39\lib\logging\handlers.py", line 115, in rotate
os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'A:\\PlexBackend\\Converter\\config\\sma.log' -> 'A:\\PlexBackend\\Converter\\config\\sma.log.1'
Call stack:
File "A:\PlexBackend\Converter\SABPostProcess.py", line 95, in <module>
sonarr.processEpisode(path, settings, importMode="Move", pathMapping=path_mapping)
File "A:\PlexBackend\Converter\autoprocess\sonarr.py", line 67, in processEpisode
return accessAPI(url, payload, headers, log, requests, nzbGet)
File "A:\PlexBackend\Converter\autoprocess\sonarr.py", line 82, in accessAPI
log.info("%sSonarr response: %s." % (infoprefix, rstate['status']))
Message: 'Sonarr response: queued.'
Arguments: ()
```
