### ISSUE TITLE
sickchill supported?

### ISSUE THREAD

**Issue by snakerman** [mdhiggins/sickbeard_mp4_automator#1449]
I am having an issue with sickchill and deluged working together I never get pasted the conversion process where it says the dir cannot be deleted.

2021-06-05 09:10:12 - DelugePostProcess - INFO - Passing /var/lib/mythtv/videos/Flix/tvtime/xxxxxxx.mkv-convert directory to Sickbeard.
2021-06-05 09:10:12 - autoprocess.autoProcessTV - INFO - Opening URL: http://localhost:8081/home/postprocess/processEpisode?quiet=1&dir=%2Fvar%2Flib%2Fmythtv%2Fvideos%2FFlix%2Ftvtime%2FSxxxxxxxxxx.mkv-convert.
2021-06-05 09:10:12 - autoprocess.autoProcessTV - INFO - b'</html>'
2021-06-05 09:10:12 - DelugePostProcess - ERROR - Unable to delete temporary directory.
Traceback (most recent call last):
  File "/home/owner/.sickchill/sickbeard_mp4_automator/delugePostProcess.py", line 172, in <module>
    os.rmdir(delete_dir)
OSError: [Errno 39] Directory not empty: '/var/lib/mythtv/videos/Flix/tvtime/xxxxxxx.mkv-convert'

currently tried sickrage and sickbeard settings same info in the logs!

xxxxxxxxxx presented to hide the name of conversion file

**Comment by snakerman** [comment]
Sorry, running Debian with python3/pip3

**Comment by mdhiggins** [comment]
Sickchill should be supported unless they changed something or deviated from Sickrage's API style. The directory error isn't a big deal and isn't breaking things. I'm guessing the API call isn't working and it looks like you're not getting any return from the API call

`2021-06-05 09:10:12 - autoprocess.autoProcessTV - INFO - b''`

I looks like you're routing this through Sickbeard which used a different API, try using this like its Sickrage instead

**Comment by snakerman** [comment]
Trying it now,

**Comment by snakerman** [comment]
Great it worked using sickrage, but I still get this......

2021-06-07 11:29:03 - SickbeardPostProcess - ERROR - Couldn't refresh Sickbeard, check your autoProcess.ini settings.
Traceback (most recent call last):
  File "//home//owner//.sickchill//sickbeard_mp4_automator//postSickbeard.py", line 47, in <module>
    refresh = json.load(urlopen(sickbeard_url))
  File "//usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "//usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "//usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "//usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by mdhiggins** [comment]
So it gets a little more tricky here since Sickchill and Sickrage sort of exist in this half compatible state with Sickbeard

autoprocessTV uses sickbeard settings, autoprocessTVSR uses sickrage settings

7d15b5aacdc21a1277e2e23f8d1f166bfc90691d

This patch I just uploaded should allow postSickbeard.py to fallback to sickrage settings if sickbeard fails allowing it to work with both programs

The old solution would have been to just include your Sickchill settings in both the Sickrage and Sickbeard section of autoProcess.ini (that would also probably still work but please test out this new update)

**Comment by snakerman** [comment]
Nothing happened so far blank log!

**Comment by mdhiggins** [comment]
Not sure what to make of that, does that mean its working or failing

**Comment by snakerman** [comment]
Sorry it finally finished, with no error messages, don't know what the delay was about!

**Comment by mdhiggins** [comment]
Good stuff. Going to close this then
