### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1451]
Hi,

I'm starting to get this issue just a week ago. First I thought I had to reinstall `requests`. Then I figure perhaps it was a SAB issue, so I created a whole new container using your MOD. It all works fins until it starts requesting Radarr to update. So that made me think that Radarr perhaps is the issue, as I'm getting this on qBit+SMAMOD as well. So I created another radarr, completely new. And I'm still getting the same issue as pasted below:

```
2021-06-08 09:01:19 - autoprocess.radarr - ERROR - Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 170, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 73, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/lib/python3.6/http/client.py", line 1281, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
self.send(msg)
File "/usr/lib/python3.6/http/client.py", line 980, in send
self.connect()
File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 200, in connect
conn = self._new_conn()
File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 182, in _new_conn
self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7efc84404940>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 574, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='radarr', port=7878): Max retries exceeded with url: /api/v3/command (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc84404940>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/sma/autoprocess/radarr.py", line 68, in processMovie
r = requests.post(url, json=payload, headers=headers)
File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 119, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='radarr', port=7878): Max retries exceeded with url: /api/v3/command (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc84404940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

Any thoughts mate?

**Comment by mdhiggins** [comment]
Are you able to access your Radarr API? 

Are you using SSL?

**Comment by mdhiggins** [comment]
Also what version of Radarr are you on? Does it have the v3 API? (if its super old it might not)

**Comment by morganzero** [comment]
I think this happened after I switched to linuxservers master after been using the nightly for a long time.

I'm currently on master branch and Version 3.2.1.5070.

I can connect to the Radarr API. I tried configuring Hydra to setup indexer to it and it successfully connected to it.

Radarr is behind a reverse proxy. And I have been able to connect to host `radarr` and port `7878` for over a year. I tried connecting to my domain host and port 443, but it ends up in the same error. Which confuses me.

--
Regards,
Movio Support Tram

Join us on Discord!

**Comment by morganzero** [comment]
Perhaps worth to mention that I don't have this issue with sonarr which I'm running on the latest tag.

Best,
Morgan

**Comment by mdhiggins** [comment]
Can you connect to the Radarr API through curl from inside the container that's failing?

The error `socket.gaierror: [Errno -2] Name or service not known` suggests that this is a failure due to DNS resolution so I think this issue is on your reverse proxy and DNS server not resolving 'radarr' to an IP address but this all seems to indicate a networking problem on your end unrelated to this script

If you try and run `ping` from inside the failing container does it resolve to the correct IP? If you replace the name with the correct IP does it work?

**Comment by morganzero** [comment]
Hmm I don't get an output when trying to request radarr:7878 from inside the container. I do get output when trying to request sonarr:8989, and that seem to work!
```
HTTP/1.1 303 See Other
X-Application-Version: 3.0.6.1196
Location: /login?returnUrl=/
Content-Type: text/html
Server: Mono-HTTPAPI/1.0
Date: Wed, 09 Jun 2021 07:11:54 GMT
Content-Length: 0
Keep-Alive: timeout=15,max=100
```
But if I request radarr.domain.com:443 I get this output:
```
HTTP/1.1 400 Bad Request
Server: cloudflare
Date: Wed, 09 Jun 2021 07:15:17 GMT
Content-Type: text/html
Content-Length: 253
Connection: close
CF-RAY: -

<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>cloudflare</center>
</body>
</html>
```
I also tried requesting radarr API from my 2nd sab client that I use for sonarr, Same issue there for Radarr.

**Comment by morganzero** [comment]
Ofcourse! It hit me when you mentioned network. The Sab container wasn't joined in the same network as Radarr. Oh man I feel so stupid now.

**Comment by morganzero** [comment]
Now that I connected sab to the same network, it seems like I get a different issue `KeyError: 'state'`. I tried reinstalling `requests`. And I also tripple-checked that I have the correct API typed in autoProcess.ini. Any ideas what else I can do?
```
2021-06-09 10:03:40 - resources.mediaprocessor - INFO - /mnt/downloads/nzb/radarr/Video/Video.mkv created.
2021-06-09 10:03:41 - SABPostProcess - INFO - Successfully processed /mnt/downloads/nzb/radarr/Video/Video.mkv.
2021-06-09 10:03:41 - SABPostProcess - INFO - Passing /mnt/downloads/nzb/radarr/Video directory to Radarr.
2021-06-09 10:03:41 - autoprocess.radarr - INFO - Radarr notifier started.
2021-06-09 10:03:41 - autoprocess.radarr - INFO - Requesting Radarr to scan directory '/mnt/downloads/nzb/radarr/Video'.
2021-06-09 10:04:26 - autoprocess.radarr - ERROR - Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "/usr/local/sma/autoprocess/radarr.py", line 71, in processMovie
log.info("%sRadarr response: %s." % (infoprefix, rstate['state']))
KeyError: 'state'
```

**Comment by mdhiggins** [comment]
This has been fixed in a recent update

**Comment by morganzero** [comment]
I'm getting this after I rebuilt the container actually.

**Comment by mdhiggins** [comment]
Update from github, set `SMA_UPDATE=true` in your environment variables, it may be that the sma-mod container hasn't rebuilt yet

**Comment by morganzero** [comment]
Thanks. I'll put that in. Any other suggestions that's worth to put in ENV? :)

--
Regards,
Movio Support Tram

Join us on Discord!
