### ISSUE TITLE
ffmpeg binary not found: /usr/local/bin/ffmpeg

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1457]
Hi mate, freshly new containers, on a fresh server, using your SMA-MOD gives me this in SAB.

I tried bounding sma folder like this: `/opt/scripts/sma/nzb:/usr/local/sma` and when that didn't work, like this: `/opt/scripts/sma/nzb/config:/usr/local/sma/config`. Didn't help!

I also tried rebuilding containers. Still, getting below:
```
2021-07-10 22:32:39 - SABPostProcess - INFO - SAB post processing started.
2021-07-10 22:32:39 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
2021-07-10 22:32:39 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2021-07-10 22:32:39 - SABPostProcess - INFO - Performing conversion
2021-07-10 22:32:39 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "/usr/local/sma/SABPostProcess.py", line 60, in <module>
mp = MediaProcessor(settings)
File "/usr/local/sma/resources/mediaprocessor.py", line 51, in __init__
self.converter = Converter(settings.ffmpeg, settings.ffprobe)
File "/usr/local/sma/converter/__init__.py", line 27, in __init__
ffprobe_path=ffprobe_path)
File "/usr/local/sma/converter/ffmpeg.py", line 475, in __init__
raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path)
converter.ffmpeg.FFMpegError: ffmpeg binary not found: /usr/local/bin/ffmpeg
```

What am I missing? :)

**Comment by morganzero** [comment]
Ok, so I bashed in and deleted `venv` and rebuilt. Now they work as intended. Not sure why this behavior was on new containers.

**Comment by morganzero** [comment]
Actually! the fix was only a one-time thing. I had to recreate the container for another reason, and it went back to `script exit code 1` with the log above. I checked container logs, and usually when downloading and installing ffmpeg it takes 3-5 minutes, but everytime I delete the `venv` and recreate the container the process of downloading and installing ffmpeg takes less than 10 seconds, which is odd to me.

Not sure if this is helpful! But could it be that the ffmpeg repo in the mod perhaps is outdated or something?

**Comment by mdhiggins** [comment]
You might be getting throttled from too many download attempts

**Comment by morganzero** [comment]
So I'll be good recreating them tomorrow you think? :)

**Comment by mdhiggins** [comment]
FFMpeg is handled at container start and has nothing to do with the container being rebuilt. No need to rebuild

**Comment by morganzero** [comment]
Ah that makes sense. Thanks!

Best,
Morgan
