### ISSUE TITLE
HEVC Converting From 1080p to H264 720p

### ISSUE THREAD

**Issue by coolvicky2** [mdhiggins/sickbeard_mp4_automator#1471]
I'm using NVIDIA TESLA P4 with Ubuntu 18.04 it's giving me error , while , i'm trying to convert HEVC 1080p to H264 720p with acc audio , here are my logs , everything else is working just having issues with this conversion only

2021-08-12 02:13:44 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
2021-08-12 02:13:44 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
2021-08-12 02:13:44 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Processing /Black/Season 2/Blacke S02E08.mkv.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Input Data
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - {
    "format": "matroska,webm",
    "format-fullname": "unknown",
    "video": {
        "index": 0,
        "codec": "hevc",
        "pix_fmt": "yuv420p",
        "profile": "1",
        "fps": 23.976023976023978,
        "framedata": {
            "pix_fmt": "yuv420p",
            "side_data_list": [
                {
                    "side_data_type": "H.26[45] User Data Unregistered SEI message"
                }
            ]
        },
        "dimensions": "1920x1080",
        "level": 4.0,
        "field_order": "unknown"
    },
    "audio": [
        {
            "index": 1,
            "codec": "aac",
            "channels": 2,
            "samplerate": 48000,
            "language": "und",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
        }
    ],
    "subtitle": [
        {
            "index": 2,
            "codec": "ass",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "language": "und"
        }
    ],
    "attachment": []
}
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Reading video stream.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Video codec detected: hevc.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Profile: 1.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Video codec parameters None.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Creating h264_nvenc video stream from source stream 0.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Reading audio streams.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Audio detected for stream 1 - aac und 2 channel.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Creating copy audio stream from source stream 1.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Default audio stream set to und copy 2 channel stream [default-more-channels: True].
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Reading subtitle streams.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Text-based subtitle detected for stream 2 - ass und.
2021-08-12 02:13:44 - resources.mediaprocessor - INFO - Attempting to download subtitles.
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 0 results in your approved languages.
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - cuda hwaccel is supported by this ffmpeg build and will be used [hwaccels].
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - Output Data
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - {
    "source": [
        "/Black/Season 2/Blacke S02E08.mkv"
    ],
    "format": "mp4",
    "video": {
        "codec": "h264_nvenc",
        "map": 0,
        "bitrate": 2181.723,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "preset": null,
        "pix_fmt": "yuv420p",
        "field_order": "unknown",
        "width": 1280,
        "filter": null,
        "params": null,
        "framedata": null,
        "title": "HD",
        "debug": "video.max-width"
    },
    "audio": [
        {
            "map": 1,
            "codec": "copy",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "und",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "Stereo",
            "debug": "universal-audio"
        }
    ],
    "subtitle": [],
    "attachment": []
}
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - Preopts
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - [
    "-hwaccel",
    "cuda"
]
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - Postopts
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - Downloaded Subtitles
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - []
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - Starting conversion.
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - FFmpeg command:
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - ======================
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - /usr/local/bin/ffmpeg -hwaccel cuda -i "/Black/Season 2/Blacke S02E08.mkv" -vcodec h264_nvenc -map 0:0 -pix_fmt yuv420p -vb 2181k -metadata:s:v BPS=2181000 -metadata:s:v BPS-eng=2181000 -metadata:s:v title=HD -metadata:s:v handler_name=HD -vf scale_npp=1280:720 -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=und -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y "/Black/Season 2/Blacke S02E08.incomplete"
2021-08-12 02:13:57 - resources.mediaprocessor - INFO - ======================
2021-08-12 02:13:57 - resources.mediaprocessor - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1680, in convert
    for timecode, debug in conv:
  File "/usr/local/sma/converter/__init__.py", line 317, in convert
    for timecode, debug in self.ffmpeg.convert(outfile,
  File "/usr/local/sma/converter/ffmpeg.py", line 723, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
2021-08-12 02:13:57 - resources.mediaprocessor - ERROR - /usr/local/bin/ffmpeg -hwaccel cuda -i /Black/Season 2/Blacke S02E08.mkv -vcodec h264_nvenc -map 0:0 -pix_fmt yuv420p -vb 2181k -metadata:s:v BPS=2181000 -metadata:s:v BPS-eng=2181000 -metadata:s:v title=HD -metadata:s:v handler_name=HD -vf scale_npp=1280:720 -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=und -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /Black/Season 2/Blacke S02E08.incomplete
2021-08-12 02:13:57 - resources.mediaprocessor - ERROR - ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from '/Black/Season 2/Blacke S02E08.mkv':
  Metadata:
    ENCODER         : Lavf57.82.100
  Duration: 00:30:25.39, start: 0.000000, bitrate: 2181 kb/s
  Stream #0:0: Video: hevc, yuv420p(tv), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      DURATION        : 00:30:25.386000000
  Stream #0:1: Audio: aac, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:30:25.215000000
  Stream #0:2: Subtitle: ass
    Metadata:
      ENCODER         : Lavc57.106.101 ssa
      DURATION        : 00:30:20.205000000
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
Conversion failed!

2021-08-12 02:13:57 - resources.mediaprocessor - ERROR - /Black/Season 2/Blacke S02E08.incomplete deleted.
2021-08-12 02:13:57 - SonarrPostProcess - INFO - Processing returned False.
2021-08-12 02:13:57 - SonarrPostProcess - ERROR - Error processing file.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 307, in <module>
    sys.exit(1)
SystemExit: 1

and this is my autoprocess.ini looks like 

[Converter]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = 0
hwaccels = cuda, nvenc, cuvid
hwaccel-decoders = h264_cuda, hevc_cuda, h264_nvenc, h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi, h264_vaapi
hwdevices = vaapi:/dev/dri/card1
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = incomplete
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = False
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0777
uid = 1001
gid = 1001

[Metadata]
relocate-moov = False
full-path-guess = False
tag = False
tag-language = 
download-artwork = False
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = h264_nvenc, h264
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 
preset =
codec-parameters = 
dynamic-parameters = False
max-width = 1280
profile = 
max-level = 0.0
pix-fmt =
filter = 
force-filter = False

[HDR]
codec = 
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset =
codec-parameters =
filter = 
force-filter = False
profile = 

[Audio]
codec = aac
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
copy-original-before = False
aac-adtstoasc = False
ignore-truehd = 
ignored-dispositions = 
unique-dispositions = False

[Universal Audio]
codec = aac
channel-bitrate = 128
first-stream-only = False
move-after = False
filter = 
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = 
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = 

[Subtitle.Subliminal]
download-subs = True
download-hearing-impaired-subs = False
providers = 

[Subtitle.Subliminal.Auth]
opensubtitles = c:u
tvsubtitles =

**Comment by mdhiggins** [comment]
This is an FFMPEG error related to the scale npp filter that has very little to do with the script. You're passing a hardware accelerated decoded format that the scaler doesn't support. You'll need to read up more on hardware encoding and decoding and controlling your formats. Quick fix would be to try without the decoding option (set `hwaccels` to blank)

Otherwise you'll need to set your cuda format to something else using the `hwaccel-output-format` option, something like `cuda:cuda` though you'll need to figure out what ffmpeg formats are supported, I believe the scale_npp filter doesn't support cuda input though

Can try cuvid

http://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by coolvicky2** [comment]
Setting My autoprocess.ini fixed my issue


[Converter]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = 0
hwaccels = nvdec
hwaccel-decoders = h264_cuvid, hevc_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi, h264_vaapi
hwdevices = cuda:/dev/dri/card1
hwaccel-output-format = cuda:cuda
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = incomplete
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = False
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0777
uid = 1001
gid = 1001

[Metadata]
relocate-moov = False
full-path-guess = False
tag = False
tag-language = 
download-artwork = False
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = h264_nvenc
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = True
max-width = 0
profile = 
max-level = 0.0
pix-fmt = nv12
filter = 
force-filter = False

[HDR]
codec = 
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = aac
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
copy-original-before = False
aac-adtstoasc = False
ignore-truehd = 
ignored-dispositions = 
unique-dispositions = False

[Universal Audio]
codec = aac
channel-bitrate = 128
first-stream-only = False
move-after = False
filter = 
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = 

[Subtitle.Subliminal]
download-subs = True
download-hearing-impaired-subs = False
providers = 

[Subtitle.Subliminal.Auth]
opensubtitles = coolvicky2:a44W720BROnu
tvsubtitles = 

[Sonarr]
host = localhost
port = 8989
apikey = 
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

[Radarr]
host = 127.0.0.1
port = 7878
apikey = bf71340abe3d4c4783477562db60b10e
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
apikey = 
delay = 65
method = renamer
delete-failed = False
ssl = False
webroot = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
couchpotato-category = couchpotato
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 
path-mapping = 

[uTorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token =

**Comment by mdhiggins** [comment]
If you post an FFMpeg command that works for what you want to do I'll post how to achieve that with the config

**Comment by coolvicky2** [comment]
This has been fixed as well , by doing the Above

**Comment by mdhiggins** [comment]
Good stuff
