### ISSUE TITLE
Restart of qBittorrent results in error

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1476]
Hi,
Just a heads up!
After a restart of qBittorrent, I'm getting this error. Seems like it's not able to pull from your github.
```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 50-gid-video: executing... 
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 90-sma-config: executing... 
[90-sma-config] Pulling SMA from github master
Traceback (most recent call last):
  File "/usr/local/sma/update.py", line 8, in <module>
    from resources.readsettings import ReadSettings
  File "/usr/local/sma/resources/readsettings.py", line 1033
    config.get(k).get(sk) = old
    ^
SyntaxError: cannot assign to function call
[cont-init.d] 90-sma-config: exited 1.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by mdhiggins** [comment]
b4e9435e3d48f66b64e3eedda0f0108a7e5c7250

Fixed
