### ISSUE TITLE
Files nolonger being picked up and moved by Sonarr/Radarr

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1497]
for some reason I have suddenly been getting this all the time.
2021-11-19 18:36:15 - resources.mediaprocessor - INFO - D:\Downloads\Completed\Jimmy.Fallon.2021.11.18.Simu.Liu.1080p.WEB.H264-GLHF\Jimmy.Fallon.2021.11.18.Simu.Liu.1080p.WEB.H264-GLHF.mp4 created.
2021-11-19 18:36:16 - SABPostProcess - INFO - Successfully processed D:\Downloads\Completed\Jimmy.Fallon.2021.11.18.Simu.Liu.1080p.WEB.H264-GLHF\Jimmy.Fallon.2021.11.18.Simu.Liu.1080p.WEB.H264-GLHF.mkv.
2021-11-19 18:36:16 - SABPostProcess - INFO - Passing D:\Downloads\Completed\Jimmy.Fallon.2021.11.18.Simu.Liu.1080p.WEB.H264-GLHF directory to Sonarr.
2021-11-19 18:36:16 - autoprocess.sonarr - INFO - Sonarr notifier started.
2021-11-19 18:36:16 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\Downloads\Completed\Jimmy.Fallon.2021.11.18.Simu.Liu.1080p.WEB.H264-GLHF'.
2021-11-19 18:36:16 - autoprocess.sonarr - ERROR - Update to Sonarr failed, check if Sonarr is running, autoProcess.ini settings and make sure your Sonarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "D:\PlexBackend\Converter\autoprocess\sonarr.py", line 82, in accessAPI
log.info("%sSonarr response: %s." % (infoprefix, rstate['status']))
TypeError: list indices must be integers or slices, not str

**Comment by mdhiggins** [comment]
Did your api key for sonar change

**Comment by morpheus2n2** [comment]
Nope, will get sonarr to produce a new one and see

**Comment by mdhiggins** [comment]
That or sonarr changed their api response. If both radarr and sonarr started failing at the same time it's more likely a network problem


Turn on debug logging which should show the raw response

**Comment by morpheus2n2** [comment]
[logs.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/7572581/logs.zip)

Hope this helps I have updated both the API keys and still the same

**Comment by mdhiggins** [comment]
de45932b3e328b75248947cf5c27b25ef3bec84e

See if that update helps

**Comment by morpheus2n2** [comment]
> [de45932](https://github.com/mdhiggins/sickbeard_mp4_automator/commit/de45932b3e328b75248947cf5c27b25ef3bec84e)
> 
> See if that update helps

Still getting 
"2021-11-20 09:31:21 - MANUAL - ERROR - D:\Downloads\To Convert\New folder\Teen.Mom.Young.and.Pregnant.S03E10.Come.Correct.1080p.WEB.h264-KOMPOST.mp4 deleted.
2021-11-20 09:31:22 - MANUAL - ERROR - There was an error processing file D:\Downloads\To Convert\New folder\Teen.Mom.Young.and.Pregnant.S03E10.Come.Correct.1080p.WEB.h264-KOMPOST.mkv, no output data received
2021-11-20 09:35:06 - resources.mediaprocessor - INFO - D:\Downloads\Completed\Gabby.Duran.and.the.Unsittables.S02E19.Magic.Hours.1080p.HULU.WEBRip.DDP5.1.x264-LAZY\Gabby.Duran.and.the.Unsittables.S02E19.Magic.Hours.1080p.HULU.WEBRip.DDP5.1.x264-LAZY.mp4 created.
2021-11-20 09:35:07 - SABPostProcess - INFO - Successfully processed D:\Downloads\Completed\Gabby.Duran.and.the.Unsittables.S02E19.Magic.Hours.1080p.HULU.WEBRip.DDP5.1.x264-LAZY\Gabby.Duran.and.the.Unsittables.S02E19.Magic.Hours.1080p.HULU.WEBRip.DDP5.1.x264-LAZY.mkv.
2021-11-20 09:35:07 - SABPostProcess - INFO - Passing D:\Downloads\Completed\Gabby.Duran.and.the.Unsittables.S02E19.Magic.Hours.1080p.HULU.WEBRip.DDP5.1.x264-LAZY directory to Sonarr.
2021-11-20 09:35:07 - autoprocess.sonarr - INFO - Sonarr notifier started.
2021-11-20 09:35:07 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\Downloads\Completed\Gabby.Duran.and.the.Unsittables.S02E19.Magic.Hours.1080p.HULU.WEBRip.DDP5.1.x264-LAZY'.
2021-11-20 09:35:07 - autoprocess.sonarr - ERROR - Update to Sonarr failed, check if Sonarr is running, autoProcess.ini settings and make sure your Sonarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
  File "D:\PlexBackend\Converter\autoprocess\sonarr.py", line 82, in accessAPI
    log.info("%sSonarr response: %s." % (infoprefix, rstate['status']))
TypeError: list indices must be integers or slices, not str"

**Comment by mdhiggins** [comment]
e1434231765de8b480139834f2a0228d978f49dc

Made a small error on the sonarr.py fix, try now

**Comment by morpheus2n2** [comment]
Nope still a issue lol.

2021-11-20 15:51:21 - MANUAL - INFO - Starting conversion.
2021-11-20 15:51:21 - MANUAL - INFO - FFmpeg command:
2021-11-20 15:51:21 - MANUAL - INFO - ======================
2021-11-20 15:51:21 - MANUAL - INFO - D:\PlexBackend\FFmpeg\bin\ffmpeg.exe -fix_sub_duration -hwaccel dxva2 -i "d:\downloads\to convert\Marvels.Hit-Monkey.S01E10.1080p.WEB.H264-CAKES.mkv" -map_metadata -1 -vcodec hevc_nvenc -map 0:0 -field_order progressive -vb 1962k -metadata:s:v BPS=1962000 -metadata:s:v BPS-eng=1962000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -level 5.2 -tag:v hvc1 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -filter:a:0 pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 aac -map 0:1 -ac:a:1 6 -b:a:1 768k -metadata:s:a:1 BPS=768000 -metadata:s:a:1 BPS-eng=768000 -metadata:s:a:1 "title=5.1 Channel" -metadata:s:a:1 "handler_name=5.1 Channel" -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:s:0 mov_text -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 1 -metadata:g encoding_tool=SMA -y "d:\downloads\to convert\Marvels.Hit-Monkey.S01E10.1080p.WEB.H264-CAKES.mp4"
2021-11-20 15:51:21 - MANUAL - INFO - ======================
2021-11-20 15:52:45 - resources.mediaprocessor - INFO - D:\Downloads\To Convert\The Sky Crawlers _2008_ _BluRay.1080p.x264.FLAC.ITA.JPN.TrueHD.JPN.Subs.Ita.Eng.Jpn_ by stress.mkv-convert\The Sky Crawlers (2008) [BluRay.1080p.x264.FLAC.ITA.JPN.TrueHD.JPN.Subs.Ita.Eng.Jpn] by stress.mp4 created.
2021-11-20 15:52:45 - qBittorrentPostProcess - INFO - Passing D:\Downloads\To Convert\The Sky Crawlers _2008_ _BluRay.1080p.x264.FLAC.ITA.JPN.TrueHD.JPN.Subs.Ita.Eng.Jpn_ by stress.mkv-convert directory to Radarr.
2021-11-20 15:52:45 - autoprocess.radarr - INFO - Radarr notifier started.
2021-11-20 15:52:45 - autoprocess.radarr - INFO - Requesting Radarr to scan directory 'D:\Downloads\To Convert\The Sky Crawlers _2008_ _BluRay.1080p.x264.FLAC.ITA.JPN.TrueHD.JPN.Subs.Ita.Eng.Jpn_ by stress.mkv-convert'.
2021-11-20 15:52:45 - autoprocess.radarr - INFO - Radarr response: completed.
2021-11-20 15:52:45 - qBittorrentPostProcess - ERROR - Unable to delete temporary directory
Traceback (most recent call last):
  File "D:\PlexBackend\Converter\qBittorrentPostProcess.py", line 198, in <module>
    os.rmdir(delete_dir)

**Comment by mdhiggins** [comment]
Not seeing the error anymore looks like radarr returned completed

The directory removal error is normal for torrents

**Comment by morpheus2n2** [comment]
Fixed it I had to restart my Hosting machine pmsl

**Comment by mdhiggins** [comment]
Yeah after looking at the original error, it was just a logging error and wouldn't have impacted the Sonarr/Radarr API call itself so it was probably unrelated but at least that's fixed now lol it was probably a networking issue all along
