### ISSUE TITLE
Any reason why no matter what video I toss at this it's not working?

### ISSUE THREAD

**Issue by DatsiK96** [mdhiggins/sickbeard_mp4_automator#1507]
Config: https://pastebin.com/H1UnbXnQ

These are the only 4 lines I get when a video is processed.

```
2021-12-17 00:57:28 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
2021-12-17 00:57:28 - resources.readsettings - INFO - D:\Python3.10.1\python.exe
2021-12-17 00:57:28 - resources.readsettings - DEBUG - Loading default config file.
2021-12-17 00:57:28 - resources.readsettings - INFO - Loading config file D:\sickbeard_mp4_automator.sonarr\config\autoProcess.ini.

```

Some info...

Windows Server 2019, Python 3.10.1, requirements.txt all satisfied as of writing this.

Thoughts?

Thanks!

Edit: should mention, that is with debug mode turned on in the logging for filelogging as per the instructions.

**Comment by DatsiK96** [comment]
`manual.py
Manual processor started.
Python 64-bit 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)].
Guessit version: 3.4.3.
D:\Python3.10.1\python.exe
Loading config file D:\sickbeard_mp4_automator.sonarr\config\autoProcess.ini.
Traceback (most recent call last):
  File "D:\sickbeard_mp4_automator.sonarr\manual.py", line 438, in <module>
    main()
  File "D:\sickbeard_mp4_automator.sonarr\manual.py", line 376, in main
    settings = ReadSettings(logger=log)
  File "D:\sickbeard_mp4_automator.sonarr\resources\readsettings.py", line 569, in __init__
    config.read(configFile)
  File "D:\Python3.10.1\lib\configparser.py", line 698, in read
    self._read(fp, filename)
  File "D:\Python3.10.1\lib\configparser.py", line 1097, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from 'D:\\sickbeard_mp4_automator.sonarr\\config\\autoProcess.ini' [line 28]: option 'preopts' in section 'Converter' already exists`

Yeah, you know... lol I ran it... but i still expected it to log something... and it didn't... so I just thought something else was wrong. But actually looking at the output, looks like I had duplicate preopts and postopts in there.

**Comment by mdhiggins** [comment]
Included a new exception catch so this will make it into the logs in the future
