### ISSUE TITLE
.rnm added to file name

### ISSUE THREAD

**Issue by tjfriese** [mdhiggins/sickbeard_mp4_automator#1514]
I've got everything setup on a Synology NAS (SABnzbd does the conversion). I've noticed that all renamed files have .rnm added to the filename before the file type. Is this intended behaviour?

**Comment by mdhiggins** [comment]
This is part of the sonarr/radarr workflow during processing, but those files should be restored by a rename API call to their final names. If your API isn't configured properly or you're getting some error that's preventing that final step, you'll be left with .rnm files. I would check the logs and see if you're getting some error that's preventing the script from finishing or making that rename API call

You can also disable this rename feature in autoProcess.ini under the radarr/sonarr settings, though it's designed to prevent other programs from accessing the file during processing so you might create new issues by shutting it off

**Comment by tjfriese** [comment]
I am getting the following error from Sonarr:

2022-01-06 13:53:26.1|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1342] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x0008b] in <798dd06330af4ca3886d7d2be5573af7>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41

**Comment by tjfriese** [comment]
The beginning of the NzbDrone error shows "Series with ID 0" does not exist". Could that have something to do with the error?

**Comment by mdhiggins** [comment]
Could you also post the log files from SMA (sma.log) for this same job/failure? Definitely looks like the API function is failing but its unclear exactly why at this point, can't tell if the issue is on Sonarr's end or something is wrong with the API request

**Comment by tjfriese** [comment]
I couldn't find the exact log, but have noticed the following consistently in the logs:

2022-01-07 21:32:37 - SonarrPostProcess - INFO - Sonarr response from RescanSeries command: ID 4681 queued.
2022-01-07 21:32:47 - SonarrPostProcess - INFO - Rescan command completed.
2022-01-07 21:32:47 - SonarrPostProcess - INFO - Sonarr monitoring information updated for episode The Smell of Sweat and Desperation.
2022-01-07 21:32:47 - SonarrPostProcess - INFO - Sonarr response RenameSeries command: ID 4683 queued.
2022-01-07 21:36:31 - SABPostProcess - INFO - SAB post processing started.
2022-01-07 21:36:31 - resources.readsettings - INFO - /volume1/@appstore/sabnzbd/env/bin/python3
2022-01-07 21:36:31 - resources.readsettings - INFO - Loading config file /volume1/Downloads/sickbeard_mp4_automator-master/config/autoProcess.ini.
2022-01-07 21:36:31 - SABPostProcess - INFO - Performing conversion
2022-01-07 21:36:32 - resources.mediaprocessor - ERROR - Pymediainfo exception.
Traceback (most recent call last):
  File "/volume1/Downloads/sickbeard_mp4_automator-master/resources/mediaprocessor.py", line 315, in isValidSource
    media_info = MediaInfo.parse(inputfile)
  File "/var/packages/python38/target/lib/python3.8/site-packages/pymediainfo/__init__.py", line 431, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/var/packages/python38/target/lib/python3.8/site-packages/pymediainfo/__init__.py", line 329, in _get_library
    raise OSError(
OSError: Failed to load library from libmediainfo.so.0 - libmediainfo.so.0: cannot open shared object file: No such file or directory

I am running your sonarr through docker.

**Comment by mdhiggins** [comment]
That exception is just a non-important pymediainfo exception, not the source of your problem

Can you turn on debug level logging and send the logs for a conversion from Sonarr? I'm just trying to see if its failing to get the correct Series ID but need debug level logging to see that

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

**Comment by tjfriese** [comment]
The log is here:

https://www.toptal.com/developers/hastebin/zenuqikuga.sql

**Comment by mdhiggins** [comment]
I need the sma.log info not the Sonarr debug logs

**Comment by tjfriese** [comment]
Sorry about that. https://www.toptal.com/developers/hastebin/obikorelus.sql

**Comment by mdhiggins** [comment]
Thanks

So it looks like the requests and IDs are all being passed appropriately and no issues on the script side of things, so it might be a Sonarr problem. I did make one small tweak to the script so you can update from the repo and try and see if it helps (docker container will take a little to update so you can use the SMA_UPDATE variable).

Were you seeing this on every file or just rare instances?

**Comment by mdhiggins** [comment]
Found a bug related to an undocumented parameter in the Sonarr API, latest update should hopefully resolved this issue

See #1530
