### ISSUE TITLE
Sonarr V3 and Radarr V3 Connect/PostProcess Exit1 Using Script

### ISSUE THREAD

**Issue by infamouswb** [mdhiggins/sickbeard_mp4_automator#1544]
**Describe the bug**

Sonarr V3 and Radarr V3 Connect/PostProcess Exit1 Using Script. I looked through various threads, and closed issues herein and been banging my head against the wall trying to figure this out. I am running Ubuntu 16.04 and calling Python3.5.

Here is the log from SonarrV3:

```
<html>
<body>
<!--StartFragment-->

SonarrErrorPipeline | Invalid request Validation failed: -- : Script exited with code: 1 | 5:02pm |  
-- | -- | -- | --
  | postSonarr.py | SyntaxError: invalid syntax | 5:02pm |  
  | postSonarr.py | ^ | 5:02pm |  
  | postSonarr.py | return f"{type(self).__name__}({list(self)})" | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/rebulk/utils.py", line 153 | 5:02pm |  
  | postSonarr.py | from .utils import is_iterable | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/rebulk/loose.py", line 18, in <module> | 5:02pm |  
  | postSonarr.py | from .loose import set_defaults | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/rebulk/builder.py", line 11, in <module> | 5:02pm |  
  | postSonarr.py | from .builder import Builder | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/rebulk/rebulk.py", line 8, in <module> | 5:02pm |  
  | postSonarr.py | from .rebulk import Rebulk | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/rebulk/__init__.py", line 7, in <module> | 5:02pm |  
  | postSonarr.py | from rebulk.match import Match | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/guessit/monkeypatch.py", line 9, in <module> | 5:02pm |  
  | postSonarr.py | from . import monkeypatch as _monkeypatch | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/guessit/__init__.py", line 6, in <module> | 5:02pm |  
  | postSonarr.py | from guessit import guessit | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/subliminal/core.py", line 12, in <module> | 5:02pm |  
  | postSonarr.py | from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles, | 5:02pm |  
  | postSonarr.py | File "/usr/local/lib/python3.5/dist-packages/subliminal/__init__.py", line 11, in <module> | 5:02pm |  
  | postSonarr.py | import subliminal | 5:02pm |  
  | postSonarr.py | File "/home/(removed)/Desktop/MKV_2_MP4/resources/mediaprocessor.py", line 21, in <module> | 5:02pm |  
  | postSonarr.py | from resources.mediaprocessor import MediaProcessor | 5:02pm |  
  | postSonarr.py | File "/home/(removed)/Desktop/MKV_2_MP4/postSonarr.py", line 10, in <module> | 5:02pm |  
  | postSonarr.py | Traceback (most recent call last):

<!--EndFragment-->
</body>
</html>
```

.sh Script

```
#!/bin/bash
/usr/bin/python3.5 [path to postsonarr.py]

**Command or context you are trying to run**


**autoProcess.ini settings**
**Please sensor API keys/private information but include all other settings**

**System Information**
 - OS: Ubuntu 16.04
 - Python version 3.5
 - FFMPEG version

**Expected behavior**
No error on test in sonarr and radarr.

**Comment by mdhiggins** [comment]
Really nothing to do with the script specifically, your guessit installation isn't working and its failing on import and crashing the script, I'm wondering if this is the same old rebulk/regex error

See here

https://github.com/guessit-io/guessit/issues/639
https://github.com/Toilal/rebulk/issues/20
https://github.com/Diaoul/subliminal/issues/992

**Comment by mdhiggins** [comment]
Try removing regex and see if that helps. Otherwise you might need to open an issue with guessit cause this is a dependency problem that's crashing on import

**Comment by mdhiggins** [comment]
Actually it looks like guessit has dropped python 3.5 support. That might be the main issue. Does migrating to a newer version help?

**Comment by infamouswb** [comment]
> Actually it looks like guessit has dropped python 3.5 support. That might be the main issue. Does migrating to a newer version help?

I see that too, but I tried installing python 3.9 and had a whole bunch of issues, I tried finding if there was support for 16.04, but  I dont think its officially supported and it stopped at 3.5

**Comment by mdhiggins** [comment]
Try rolling back to an earlier version of guessit then

**Comment by mdhiggins** [comment]
Closing this out since its more of a problem with a dependency but feel free to continue discussion
