### ISSUE TITLE
ffmpeg Binary not found error on latest script while on same server old script working ok

### ISSUE THREAD

**Issue by jahmac23** [mdhiggins/sickbeard_mp4_automator#1547]
I am getting ffmpeg Binary not found error on latest script. in my same server old script working ok and I have ffmpeg installed on that same server.
These error I am getting.
2022-02-24 01:02:25 - SABPostProcess - INFO - SAB post processing started.
2022-02-24 01:02:25 - resources.readsettings - INFO - /usr/bin/python3
2022-02-24 01:02:25 - resources.readsettings - INFO - Loading config file /downloads/scripts/sickbeard_mp4_automator-master_latest/config/autoProcess.ini.
2022-02-24 01:02:25 - SABPostProcess - INFO - Performing conversion
2022-02-24 01:02:25 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/SABPostProcess.py", line 60, in <module>
mp = MediaProcessor(settings)
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/resources/mediaprocessor.py", line 52, in __init__
self.converter = Converter(settings.ffmpeg, settings.ffprobe)
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/converter/__init__.py", line 27, in __init__
ffprobe_path=ffprobe_path)
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/converter/ffmpeg.py", line 481, in __init__
raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path)
converter.ffmpeg.FFMpegError: ffmpeg binary not found: ffmpeg.exe

**Comment by mdhiggins** [comment]
`converter.ffmpeg.FFMpegError: ffmpeg binary not found: ffmpeg.exe`

Looks like you're on linux but have ffmpeg.exe which would be a windows path

If you had used the issue template and included your autoProcess settings I could see if that's the case but without settings its hard to tell, but looks like you just have ffmpeg.exe as your ffmpeg path which will obviously not work on linux

**Comment by jahmac23** [comment]
thanks. sorted it on autoprocess.ini file. Now  am getting another error as I am trying with libfdk_aac audio encoder and looks like my ffmpeg build is not supporting libfdk_aac. conversion failing. How do I install ffmpeg with libfdk_aac enabled.

2022-02-24 16:20:04 - resources.mediaprocessor - WARNING - ===========WARNING===========
2022-02-24 16:20:04 - resources.mediaprocessor - WARNING - The encoder you have chosen libfdk_aac (libfdk_aac) is not listed as supported in your FFMPEG build, conversion will likely fail, please use a build of FFMPEG that supports libfdk_aac or choose a different encoder.
2022-02-24 16:20:04 - resources.mediaprocessor - WARNING - Other encoders your current FFMPEG build does support for codec aac:
2022-02-24 16:20:04 - resources.mediaprocessor - WARNING - ['aac']
2022-02-24 16:20:04 - resources.mediaprocessor - WARNING - ===========WARNING===========

in the end this error.

2022-02-24 16:20:04 - resources.mediaprocessor - INFO - Starting conversion.
2022-02-24 16:20:04 - resources.mediaprocessor - ERROR - Unexpected exception encountered during conversion
Traceback (most recent call last):
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/resources/mediaprocessor.py", line 172, in process
outputfile, inputfile = self.convert(options, preopts, postopts, reportProgress, progressOutput)
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/resources/mediaprocessor.py", line 1847, in convert
_, cmds = next(conv)
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/converter/__init__.py", line 283, in convert
raise ConverterError("Can't get information about source file")
converter.ConverterError: Can't get information about source file
2022-02-24 16:20:04 - SABPostProcess - ERROR - Converting file failed /downloads/sabnzbd/Completed/The Sky Is Everywhere 2022 2160p WEB H265-NAISU/ce0085651126429aa63b5f90ce024314.mkv.
2022-02-24 16:20:04 - SABPostProcess - ERROR - No valid files found for conversion in download, aborting.
2022-02-24 16:20:04 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/SABPostProcess.py", line 81, in <module>
sys.exit(1)
SystemExit: 1

**Comment by mdhiggins** [comment]
You'll need to build ffmpeg from source or find a prebuilt source that includes that library, same with any other encoder

For your other error, looks like your ffprobe build isn't reading the file

The error `raise ConverterError("Can't get information about source file")` is called when ffprobe returns no valid data

The command is essentially `ffprobe -show_format -show_streams pathtofile.mkv` so you should try running that command manually and see what the output is. If you're getting some kind of error, you'll need to fix your ffprobe build

**Comment by jahmac23** [comment]
thanks. its sorted. cheers.

**Comment by jahmac23** [comment]
can I open this again. getting error on sonarr renaming from sabnzbd. getting error KeyError: 'status'.

2022-02-24 20:27:58 - resources.mediaprocessor - INFO - /downloads/sabnzbd/Completed/****/f1f7991c15354a4ca6f91b5050d061c8.mp4 created.
2022-02-24 20:27:58 - SABPostProcess - INFO - Successfully processed /downloads/sabnzbd/Completed/****/f1f7991c15354a4ca6f91b5050d061c8.mkv.
2022-02-24 20:27:58 - SABPostProcess - INFO - Passing /downloads/sabnzbd/Completed/**** directory to Sonarr.
2022-02-24 20:27:58 - autoprocess.sonarr - INFO - Sonarr notifier started.
2022-02-24 20:27:58 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/downloads/sabnzbd/Completed/****'.
2022-02-24 20:27:58 - autoprocess.sonarr - ERROR - Update to Sonarr failed, check if Sonarr is running, autoProcess.ini settings and make sure your Sonarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/autoprocess/sonarr.py", line 86, in accessAPI
log.info("%sSonarr response: %s." % (infoprefix, rstate['status']))
KeyError: 'status'

**Comment by mdhiggins** [comment]
Your sonarr api isn't returning valid response. Check your sonarr settings in autoProcess.ini

**Comment by jahmac23** [comment]
my sonarr api key and all setup looks ok on autoprocess.ini. same setup on same server if I use your old script its working fine. so cant see any issue on sonarr credentials on autoprocess.ini.

**Comment by mdhiggins** [comment]
Then post your current settings and some debug logs. Can't help without that

**Comment by mdhiggins** [comment]
Also if you're using a very old version of Sonarr without the V3 API (probably >1 year old) that might be part of it
