### ISSUE TITLE
I'm getting file permission not set error (self.settings.permissions.get('chmod', int('0664', 8)))

### ISSUE THREAD

**Issue by coolvicky2** [mdhiggins/sickbeard_mp4_automator#1557]
Im using dockers on Ubuntu 18 , it's all freshly installed

This is the autoprocess.ini i'm using
[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 0
hwaccels = 
hwaccel-decoders = 
hwdevices = 
hwaccel-output-format = 
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = incomplete
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = True
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = False
full-path-guess = False
tag = False
tag-language = 
download-artwork = False
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = copy
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
prioritize-source-pix-fmt = True
filter = 
force-filter = False

[HDR]
codec = copy
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = ac3, aac
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
variable-bitrate = 0
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
profile = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
copy-original-before = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions = 
unique-dispositions = False
stream-codec-combinations = 

[Universal Audio]
codec = 
channel-bitrate = 128
variable-bitrate = 0
first-stream-only = False
move-after = False
filter = 
profile = 
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = mov_text,srt,subrip
codec-image-based = 
languages = eng,hin,ara,por,ben,spa,ita,pol,urd,fra,nld,dan,tur,tel,tam,mal
default-language = 
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = 

[Subtitle.Subliminal]
download-subs = True
download-hearing-impaired-subs = False
providers = 

[Subtitle.Subliminal.Auth]
opensubtitles = 
tvsubtitles = 

This is the log out i've got 

2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Reading video stream.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Video codec detected: h264.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Profile: high.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Video codec parameters None.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Creating copy video stream from source stream 0.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Reading audio streams.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Audio detected for stream 1 - aac und 6 channel.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Creating copy audio stream from source stream 1.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Found 0 streams that can be removed from the output file since they will dupcliates [stream-codec-combinations].
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Default audio stream set to und copy 6 channel stream [default-more-channels: True].
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Reading subtitle streams.
2022-03-12 00:09:17 - resources.mediaprocessor - INFO - Attempting to download subtitles.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.ar.srt.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.pl.srt.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.nl.srt.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.it.srt.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.da.srt.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.fr.srt.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.hi.srt.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.bn.srt.
2022-03-12 00:09:40 - resources.mediaprocessor - INFO - Downloaded new subtitle /home/data/transmission/VOD.2022.ml.srt.
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 9 results in your approved languages.
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).hi.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).ar.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).bn.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).it.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).pl.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).fr.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).nl.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).da.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based VOD.2022 (2022).ml.srt [embed-subs].
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Output Data
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - {
    "source": [
        "/home/data/transmission/VOD.2022.mp4",
        "/home/data/transmission/VOD.2022.hi.srt",
        "/home/data/transmission/VOD.2022.ar.srt",
        "/home/data/transmission/VOD.2022.bn.srt",
        "/home/data/transmission/VOD.2022.it.srt",
        "/home/data/transmission/VOD.2022.pl.srt",
        "/home/data/transmission/VOD.2022.fr.srt",
        "/home/data/transmission/VOD.2022.nl.srt",
        "/home/data/transmission/VOD.2022.da.srt",
        "/home/data/transmission/VOD.2022.ml.srt"
    ],
    "format": "mp4",
    "video": {
        "codec": "copy",
        "map": 0,
        "bitrate": 2136.77135,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "preset": null,
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "framedata": null,
        "title": "FHD",
        "debug": "video"
    },
    "audio": [
        {
            "map": 1,
            "codec": "copy",
            "channels": 6,
            "bitrate": 768,
            "profile": null,
            "quality": 0,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "und",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "bsf": null,
            "title": "5.1 Channel",
            "debug": "audio"
        }
    ],
    "subtitle": [
        {
            "source": 1,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced+hearing_impaired-visual_impaired-captions",
            "title": "Hearing Impaired",
            "language": "hin",
            "debug": "subtitle.embed-subs"
        },
        {
            "source": 2,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "title": null,
            "language": "ara",
            "debug": "subtitle.embed-subs"
        },
        {
            "source": 3,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "title": null,
            "language": "ben",
            "debug": "subtitle.embed-subs"
        },
        {
            "source": 4,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "title": null,
            "language": "ita",
            "debug": "subtitle.embed-subs"
        },
        {
            "source": 5,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "title": null,
            "language": "pol",
            "debug": "subtitle.embed-subs"
        },
        {
            "source": 6,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "title": null,
            "language": "fra",
            "debug": "subtitle.embed-subs"
        },
        {
            "source": 7,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "title": null,
            "language": "nld",
            "debug": "subtitle.embed-subs"
        },
        {
            "source": 8,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "title": null,
            "language": "dan",
            "debug": "subtitle.embed-subs"
        },
        {
            "source": 9,
            "map": 0,
            "codec": "mov_text",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "title": null,
            "language": "mal",
            "debug": "subtitle.embed-subs"
        }
    ],
    "attachment": []
}
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Preopts
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - [
    "-fix_sub_duration"
]
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Postopts
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Downloaded Subtitles
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - [
    "/home/data/transmission/VOD.2022.ar.srt",
    "/home/data/transmission/VOD.2022.pl.srt",
    "/home/data/transmission/VOD.2022.nl.srt",
    "/home/data/transmission/VOD.2022.it.srt",
    "/home/data/transmission/VOD.2022.da.srt",
    "/home/data/transmission/VOD.2022.fr.srt",
    "/home/data/transmission/VOD.2022.hi.srt",
    "/home/data/transmission/VOD.2022.bn.srt",
    "/home/data/transmission/VOD.2022.ml.srt"
]
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - Starting conversion.
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - FFmpeg command:
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - ======================
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - /usr/local/bin/ffmpeg -fix_sub_duration -i "/home/data/transmission/VOD.2022.mp4.original" -i "/home/data/transmission/VOD.2022.hi.srt" -i "/home/data/transmission/VOD.2022.ar.srt" -i "/home/data/transmission/VOD.2022.bn.srt" -i "/home/data/transmission/VOD.2022.it.srt" -i "/home/data/transmission/VOD.2022.pl.srt" -i "/home/data/transmission/VOD.2022.fr.srt" -i "/home/data/transmission/VOD.2022.nl.srt" -i "/home/data/transmission/VOD.2022.da.srt" -i "/home/data/transmission/VOD.2022.ml.srt" -vcodec copy -map 0:0 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -c:a:0 copy -map 0:1 -metadata:s:a:0 "title=5.1 Channel" -metadata:s:a:0 "handler_name=5.1 Channel" -metadata:s:a:0 language=und -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 1:0 -metadata:s:s:0 "title=Hearing Impaired" -metadata:s:s:0 "handler_name=Hearing Impaired" -metadata:s:s:0 language=hin -disposition:s:0 -default-dub-original-comment-lyrics-karaoke-forced+hearing_impaired-visual_impaired-captions -c:s:1 mov_text -map 2:0 -metadata:s:s:1 title= -metadata:s:s:1 handler_name= -metadata:s:s:1 language=ara -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:2 mov_text -map 3:0 -metadata:s:s:2 title= -metadata:s:s:2 handler_name= -metadata:s:s:2 language=ben -disposition:s:2 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:3 mov_text -map 4:0 -metadata:s:s:3 title= -metadata:s:s:3 handler_name= -metadata:s:s:3 language=ita -disposition:s:3 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:4 mov_text -map 5:0 -metadata:s:s:4 title= -metadata:s:s:4 handler_name= -metadata:s:s:4 language=pol -disposition:s:4 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:5 mov_text -map 6:0 -metadata:s:s:5 title= -metadata:s:s:5 handler_name= -metadata:s:s:5 language=fra -disposition:s:5 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:6 mov_text -map 7:0 -metadata:s:s:6 title= -metadata:s:s:6 handler_name= -metadata:s:s:6 language=nld -disposition:s:6 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:7 mov_text -map 8:0 -metadata:s:s:7 title= -metadata:s:s:7 handler_name= -metadata:s:s:7 language=dan -disposition:s:7 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:8 mov_text -map 9:0 -metadata:s:s:8 title= -metadata:s:s:8 handler_name= -metadata:s:s:8 language=mal -disposition:s:8 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y "/home/data/transmission/VOD.2022.incomplete"
2022-03-12 00:09:41 - resources.mediaprocessor - INFO - ======================
2022-03-12 00:09:49 - resources.mediaprocessor - INFO - /home/data/transmission/VOD.2022.incomplete created.
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.ar.srt'
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.pl.srt'
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.nl.srt'
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.it.srt'
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.da.srt'
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.fr.srt'
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.hi.srt'
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.bn.srt'
2022-03-12 00:09:51 - resources.mediaprocessor - ERROR - Unable to set new file permissions.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 1641, in setPermissions
    os.chmod(path, self.settings.permissions.get('chmod', int('0664', 8)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/transmission/VOD.2022.ml.srt'
2022-03-12 00:10:01 - RadarrPostProcess - INFO - Rescan command completed successfully.
2022-03-12 00:10:01 - RadarrPostProcess - INFO - Radarr monitoring information updated for movie VOD.2022.
2022-03-12 00:10:01 - RadarrPostProcess - INFO - Radarr response Rename command: ID 66755 queued.
2022-03-12 00:10:12 - RadarrPostProcess - INFO - Radarr extra script post processing started.

**Comment by mdhiggins** [comment]
The permission error just appears to be that the subtitle files that are downloaded by subliminal are all deleted by the time it goes to set permissions on them since they are merged back into the final output file. Doesn't break anything and shouldn't be causing any problems but I pushed an update that will prevent this error in the future

820d431f795d900d05a941b2f6ef842fd8099b59

**Comment by coolvicky2** [comment]
the issue still presist , both in radarr and sonarr

**Comment by mdhiggins** [comment]
Can you post some fresh logs? the latest update should not attempt to apply permissions to files that are absent

**Comment by mdhiggins** [comment]
And I guess can you verify that you have updated the script? Make sure you have these changes

820d431f795d900d05a941b2f6ef842fd8099b59

**Comment by coolvicky2** [comment]
The issue has been fixed , thanks for all the help
