### ISSUE TITLE
manual.py: OverflowError: cannot fit 'long' into an index-sized integer

### ISSUE THREAD

**Issue by ErebusBat** [mdhiggins/sickbeard_mp4_automator#157]
On some files (mostly seems to be movies) the file will process then error out when tagging.  It also does not matter if I use `--auto` or specify the `IMDB` id directly.

I just updated and I am on SHA fb63e049581281720e93d1a4711a5a7ac44a53f3

```
$ manual.py -i movie.mkv --auto
Matched movie title as: movie 2013-12-06
Processing movie
Video codec detected: h264
Audio stream detected: dca eng [Stream 1]
Creating dual audio channels for iOS compatability for this stream
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "eng"
        },
        "1": {
            "channels": 6,
            "map": 1,
            "codec": "ac3",
            "bitrate": 1536,
            "language": "eng"
        }
    },
    "video": {
        "map": 0,
        "codec": "copy",
        "bitrate": 5859871.0
    },
    "format": "mp4"
}
/var/media/movies/movie (2013)/movie.mp4 created
Tagging file :/var/media/movies/movie (2013)/movie.mp4
Trying to write tags
Traceback (most recent call last):
  File "/opt/sickbeard_mp4_automator/manual.py", line 287, in <module>
    main()
  File "/opt/sickbeard_mp4_automator/manual.py", line 278, in main
    processFile(path, tagdata)
  File "/opt/sickbeard_mp4_automator/manual.py", line 185, in processFile
    tagmp4.writeTags(output['output'], settings.artwork)
  File "/opt/sickbeard_mp4_automator/tmdb_mp4.py", line 91, in writeTags
    video.save()
  File "/opt/sickbeard_mp4_automator/mutagen/__init__.py", line 134, in save
    return self.tags.save(filename, **kwargs)
  File "/opt/sickbeard_mp4_automator/mutagen/mp4.py", line 299, in save
    self.__save_existing(fileobj, atoms, path, data)
  File "/opt/sickbeard_mp4_automator/mutagen/mp4.py", line 352, in __save_existing
    insert_bytes(fileobj, delta, offset)
  File "/opt/sickbeard_mp4_automator/mutagen/_util.py", line 226, in insert_bytes
    map = mmap.mmap(fobj.fileno(), filesize + size)
OverflowError: cannot fit 'long' into an index-sized integer
```

**Comment by mdhiggins** [comment]
As of commit 8375e799c53cfa9a0d87d62cccf747072875ee97 a workaround for this issue has been found and tagging should work on 32 bit systems regardless of file size
