### ISSUE TITLE
Universal Audio, first-stream-only flag ignored

### ISSUE THREAD

**Issue by dingho** [mdhiggins/sickbeard_mp4_automator#1586]
I have a file with 2 AC3 audio tracks (movie + commentary).  
My goal is to output 3 audio tracks:
1. movie original AC3
2. movie aac-universal
3. commentary original AC3

I have first-stream-only set to True, however I am still getting the following audio tracks: 
1. movie original AC3
2. movie aac-universal
3. commentary-orginal AC3
4. commentary-aac. (unwanted)

Here are the audio sections of my autoprocess file:
[Audio]
codec = aac, ac3, eac3, dts, vorbis
languages = eng
default-language = eng
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
variable-bitrate = 0
max-bitrate = 0
max-channels = 0
filter =
profile =
force-filter = False
sample-rates =
sample-format =
copy-original = True
aac-adtstoasc = False
ignored-dispositions =
unique-dispositions = False
stream-codec-combinations =

[Audio.Sorting]
sorting = language, channels.a, map, d.comment
default-sorting = channels.a, map, d.comment
codecs =

[Universal Audio]
codec = aac
channel-bitrate = 128
variable-bitrate = 0
first-stream-only = True
filter =
profile =
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

**Command or context you are trying to run**
./manual.py -i filename.ext

Relative audio output section:

Reading audio streams.
The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
Audio detected for stream 1 - ac3 eng 6 channel.
Creating copy audio stream from source stream 1.
Creating aac audio stream from source audio stream 1 [universal-audio].
Audio detected for stream 2 - ac3 eng 2 channel.
Creating aac audio stream from source stream 2.
Copying audio stream from source stream 2 format ac3 [audio-copy-original].
Found 0 streams that can be removed from the output file since they will be duplicates [stream-codec-combinations].
Final sorting:
['0->1', '1->0', '2->2', '3->3']
Final sorting:
['0->0', '1->1', '2->2', '3->3']
Default audio stream set to eng aac 2 channel stream [audio-default-sorting: ['channels.a', 'map', 'd.comment']].

Any help is appreciated. Sorry if this isn't a bug, but my own misconfiguration.  I had this working previously in an older version of SMA with the same autoprocess settings.

**Comment by mdhiggins** [comment]
Post the whole log of the conversion if you could

**Comment by dingho** [comment]
2022-05-26 07:55:29 - MANUAL - INFO - Manual processor started.
2022-05-26 07:55:29 - MANUAL - INFO - Python 64-bit 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0].
2022-05-26 07:55:29 - MANUAL - INFO - Guessit version: 3.4.3.
2022-05-26 07:55:29 - MANUAL - INFO - /usr/bin/python3
2022-05-26 07:55:29 - MANUAL - INFO - Loading config file /home/dingho/sickbeard_mp4_automator/config/autoProcess.ini.
2022-05-26 07:55:32 - MANUAL - INFO - Matched movie title as: Journey to the Center of the Earth 1959-12-15 (TMDB ID: 11571)
2022-05-26 07:55:33 - MANUAL - INFO - Processing Journey to the Center of the Earth
2022-05-26 07:55:33 - MANUAL - INFO - Input Data
2022-05-26 07:55:33 - MANUAL - INFO - {
    "format": "matroska,webm",
    "format-fullname": "Matroska / WebM",
    "video": {
        "index": 0,
        "codec": "h264",
        "pix_fmt": "yuv420p",
        "profile": "high",
        "fps": 23.976023976023978,
        "framedata": {
            "pix_fmt": "yuv420p",
            "side_data_list": [
                {
                    "side_data_type": "H.26[45] User Data Unregistered SEI message"
                }
            ]
        },
        "dimensions": "1920x816",
        "level": 4.1,
        "field_order": "progressive"
    },
    "audio": [
        {
            "index": 1,
            "codec": "ac3",
            "bitrate": 640000,
            "channels": 6,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
        },
        {
            "index": 2,
            "codec": "ac3",
            "bitrate": 192000,
            "channels": 2,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "-default-dub-original+comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
        }
    ],
    "subtitle": [
        {
            "index": 3,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "language": "eng"
        },
        {
            "index": 4,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced+hearing_impaired-visual_impaired",
            "language": "eng"
        }
    ],
    "attachment": []
}
2022-05-26 07:55:33 - MANUAL - INFO - Reading video stream.
2022-05-26 07:55:33 - MANUAL - INFO - Video codec detected: h264.
2022-05-26 07:55:33 - MANUAL - INFO - Pix Fmt: yuv420p.
2022-05-26 07:55:33 - MANUAL - INFO - Profile: high.
2022-05-26 07:55:33 - MANUAL - INFO - Video codec parameters None.
2022-05-26 07:55:33 - MANUAL - INFO - Creating copy video stream from source stream 0.
2022-05-26 07:55:33 - MANUAL - INFO - Reading audio streams.
2022-05-26 07:55:33 - MANUAL - INFO - The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
2022-05-26 07:55:33 - MANUAL - INFO - Audio detected for stream 1 - ac3 eng 6 channel.
2022-05-26 07:55:33 - MANUAL - INFO - Creating copy audio stream from source stream 1.
2022-05-26 07:55:33 - MANUAL - INFO - Creating aac audio stream from source audio stream 1 [universal-audio].
2022-05-26 07:55:33 - MANUAL - INFO - Audio detected for stream 2 - ac3 eng 2 channel.
2022-05-26 07:55:33 - MANUAL - INFO - Creating aac audio stream from source stream 2.
2022-05-26 07:55:33 - MANUAL - INFO - Copying audio stream from source stream 2 format ac3 [audio-copy-original].
2022-05-26 07:55:33 - MANUAL - INFO - Found 0 streams that can be removed from the output file since they will be duplicates [stream-codec-combinations].
2022-05-26 07:55:33 - MANUAL - INFO - Final sorting:
2022-05-26 07:55:33 - MANUAL - INFO - ['0->1', '1->0', '2->2', '3->3']
2022-05-26 07:55:33 - MANUAL - INFO - Final sorting:
2022-05-26 07:55:33 - MANUAL - INFO - ['0->0', '1->1', '2->2', '3->3']
2022-05-26 07:55:33 - MANUAL - INFO - Default audio stream set to eng aac 2 channel stream [audio-default-sorting: ['channels.a', 'map', 'd.comment']].
2022-05-26 07:55:33 - MANUAL - INFO - Reading subtitle streams.
2022-05-26 07:55:33 - MANUAL - INFO - Subtitle detected for stream 3 - subrip eng.
2022-05-26 07:55:34 - MANUAL - INFO - Stream 3 is text-based subtitle for codec subrip.
2022-05-26 07:55:34 - MANUAL - INFO - Creating mov_text subtitle stream from source stream 3.
2022-05-26 07:55:34 - MANUAL - INFO - Subtitle detected for stream 4 - subrip eng.
2022-05-26 07:55:34 - MANUAL - INFO - Stream 4 is text-based subtitle for codec subrip.
2022-05-26 07:55:34 - MANUAL - INFO - Creating mov_text subtitle stream from source stream 4.
2022-05-26 07:55:35 - MANUAL - INFO - Scanned for external subtitles and found 0 results in your approved languages.
2022-05-26 07:55:35 - MANUAL - INFO - Final sorting:
2022-05-26 07:55:35 - MANUAL - INFO - ['0->0', '1->1']
2022-05-26 07:55:35 - MANUAL - INFO - Output Data
2022-05-26 07:55:35 - MANUAL - INFO - {
    "source": [
        "/mnt/torrents/incomplete/Journey.to.the.Center.of.the.Earth.1959.1080p.BluRay.DD5.1.x264-NTb.mkv"
    ],
    "format": "mp4",
    "video": {
        "codec": "copy",
        "map": 0,
        "bitrate": 20332.3693,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": null,
        "preset": null,
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "framedata": null,
        "bsf": null,
        "title": "FHD",
        "debug": "video"
    },
    "audio": [
        {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "quality": 0,
            "profile": null,
            "samplerate": null,
            "sampleformat": "",
            "filter": "pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE",
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "title": "Stereo",
            "debug": "universal-audio"
        },
        {
            "map": 1,
            "codec": "copy",
            "channels": 6,
            "bitrate": 768,
            "profile": null,
            "quality": 0,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "5.1 Channel",
            "debug": "audio"
        },
        {
            "map": 2,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "profile": null,
            "quality": 0,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "eng",
            "disposition": "-default-dub-original+comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "bsf": null,
            "title": "Stereo (Commentary)",
            "debug": "universal-audio"
        },
        {
            "map": 2,
            "codec": "copy",
            "channels": 2,
            "language": "eng",
            "disposition": "-default-dub-original+comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "title": "Stereo (Commentary)",
            "debug": "audio-copy-original"
        }
    ],
    "subtitle": [
        {
            "map": 3,
            "codec": "mov_text",
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
            "title": null,
            "debug": "subtitle.embed-subs"
        },
        {
            "map": 4,
            "codec": "mov_text",
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced+hearing_impaired-visual_impaired",
            "title": "Hearing Impaired",
            "debug": "subtitle.embed-subs"
        }
    ],
    "attachment": []
}
2022-05-26 07:55:35 - MANUAL - INFO - Preopts
2022-05-26 07:55:35 - MANUAL - INFO - [
    "-fix_sub_duration"
]
2022-05-26 07:55:35 - MANUAL - INFO - Postopts
2022-05-26 07:55:35 - MANUAL - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
2022-05-26 07:55:35 - MANUAL - INFO - Starting conversion.
2022-05-26 07:55:35 - MANUAL - ERROR - Unable to make output directory /mnt/temp.
Traceback (most recent call last):
  File "/home/dingho/sickbeard_mp4_automator/resources/mediaprocessor.py", line 1973, in getOutputFile
    os.makedirs(output_dir)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/mnt/temp'
2022-05-26 07:55:35 - MANUAL - ERROR - Unable to make output directory /mnt/temp.
Traceback (most recent call last):
  File "/home/dingho/sickbeard_mp4_automator/resources/mediaprocessor.py", line 1973, in getOutputFile
    os.makedirs(output_dir)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/mnt/temp'
2022-05-26 07:55:35 - MANUAL - INFO - FFmpeg command:
2022-05-26 07:55:35 - MANUAL - INFO - ======================
2022-05-26 07:55:35 - MANUAL - INFO - /usr/bin/ffmpeg -fix_sub_duration -i /mnt/torrents/incomplete/Journey.to.the.Center.of.the.Earth.1959.1080p.BluRay.DD5.1.x264-NTb.mkv -vcodec copy -map 0:0 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -filter:a:0 "pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE" -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 "title=5.1 Channel" -metadata:s:a:1 "handler_name=5.1 Channel" -metadata:s:a:1 language=eng -disposition:a:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:a:2 aac -map 0:2 -ac:a:2 2 -b:a:2 256k -metadata:s:a:2 BPS=256000 -metadata:s:a:2 BPS-eng=256000 -metadata:s:a:2 "title=Stereo (Commentary)" -metadata:s:a:2 "handler_name=Stereo (Commentary)" -metadata:s:a:2 language=eng -disposition:a:2 -default-dub-original+comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:a:3 copy -map 0:2 -metadata:s:a:3 "title=Stereo (Commentary)" -metadata:s:a:3 "handler_name=Stereo (Commentary)" -metadata:s:a:3 language=eng -disposition:a:3 -default-dub-original+comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 0:3 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:1 mov_text -map 0:4 -metadata:s:s:1 "title=Hearing Impaired" -metadata:s:s:1 "handler_name=Hearing Impaired" -metadata:s:s:1 language=eng -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced+hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /mnt/temp/Journey.to.the.Center.of.the.Earth.1959.1080p.BluRay.DD5.1.x264-NTb.mp4

**Comment by mdhiggins** [comment]
So it looks like you're getting 2 versions because you have the "copy-original" option enabled which will always create a copy of the original stream

If you add ac3 to a compatible UA track codec you should get what you want

```
[Universal Audio]
codec = aac, ac3
```

**Comment by dingho** [comment]
Thank you.  That does get my desired outcome.

For some reason the behavior has changed since a previous version, as in my old VM I can see I only had it set as:
[Universal Audio]
codec = aac
first-stream-only = True

Thanks again.  Appreciate your software.
