### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/ffmpeg'

### ISSUE THREAD

**Issue by jahmac23** [mdhiggins/sickbeard_mp4_automator#1588]
getting SystemExit: 1 error on Sabnzbd.

ffmpeg is installed but still getting "FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/ffmpeg'"

**Describe the bug**
Its Apline OS, latest sonarr  Version 3.0.8.1507, mp4_automator script setup on Sabnzbd. Latest sickbeard_mp4_automator script on sabnzbd.
Getting 2 error. 
2022-05-30 08:25:39 - resources.mediaprocessor - ERROR - Pymediainfo exception.
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/ffmpeg'

Full log:
2022-05-30 08:25:38 - SABPostProcess - INFO - SAB post processing started.
2022-05-30 08:25:38 - resources.readsettings - INFO - /usr/bin/python3
2022-05-30 08:25:38 - resources.readsettings - INFO - Loading config file /downloads/scripts/sickbeard_mp4_automator-master/config/autoProcess.ini.
2022-05-30 08:25:38 - SABPostProcess - INFO - Performing conversion
2022-05-30 08:25:39 - resources.mediaprocessor - ERROR - Pymediainfo exception.
2022-05-30 08:25:39 - SABPostProcess - INFO - Processing file /downloads/sabnzbd/Completed/*** *** 720p WEB H264-PECULATE/00994fa959294d3aaf30629f6ea2d11b.mkv.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Input Data
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - {
"format": "matroska,webm",
"format-fullname": "Matroska / WebM",
"video": {
"index": 0,
"codec": "h264",
"bitrate": 3390164,
"pix_fmt": "yuv420p",
"profile": "high",
"fps": 23.976023976023978,
"framedata": {
"pix_fmt": "yuv420p",
"color_space": "bt709",
"color_primaries": "bt709",
"color_transfer": "bt709"
},
"dimensions": "1280x720",
"level": 3.1,
"field_order": "progressive"
},
"audio": [
{
"index": 1,
"codec": "eac3",
"bitrate": 640000,
"channels": 6,
"samplerate": 48000,
"language": "eng",
"disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
}
],
"subtitle": [
{
"index": 2,
"codec": "subrip",
"disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
"language": "eng"
}
],
"attachment": []
}
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Reading video stream.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Video codec detected: h264.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Profile: high.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Video codec parameters None.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Creating copy video stream from source stream 0.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Reading audio streams.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Audio detected for stream 1 - eac3 eng 6 channel.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Creating ac3 audio stream from source stream 1.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Creating libfdk_aac audio stream from source audio stream 1 [universal-audio].
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Found 0 streams that can be removed from the output file since they will dupcliates [stream-codec-combinations].
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Default audio stream set to eng ac3 6 channel stream [default-more-channels: True].
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Reading subtitle streams.
2022-05-30 08:25:39 - resources.mediaprocessor - ERROR - Unknown error occurred while trying to determine if subtitle is text or image based. Probably corrupt, skipping.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 0 results in your approved languages.
2022-05-30 08:25:39 - resources.mediaprocessor - WARNING - ===========WARNING===========
2022-05-30 08:25:39 - resources.mediaprocessor - WARNING - The encoder you have chosen libfdk_aac (libfdk_aac) is not listed as supported in your FFMPEG build, conversion will likely fail, please use a build of FFMPEG that supports libfdk_aac or choose a different encoder.
2022-05-30 08:25:39 - resources.mediaprocessor - WARNING - Other encoders your current FFMPEG build does support for codec aac:
2022-05-30 08:25:39 - resources.mediaprocessor - WARNING - ['aac']
2022-05-30 08:25:39 - resources.mediaprocessor - WARNING - ===========WARNING===========
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Output Data
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - {
"source": [
"/downloads/sabnzbd/Completed/*** *** 720p WEB H264-PECULATE/00994fa959294d3aaf30629f6ea2d11b.mkv"
],
"format": "mp4",
"video": {
"codec": "copy",
"map": 0,
"bitrate": 3222.5843,
"crf": -1,
"maxrate": null,
"bufsize": null,
"level": 0.0,
"profile": null,
"preset": null,
"pix_fmt": null,
"field_order": "progressive",
"width": null,
"filter": null,
"params": null,
"framedata": null,
"title": "HD",
"debug": "video"
},
"audio": [
{
"map": 1,
"codec": "libfdk_aac",
"channels": 2,
"bitrate": 256,
"quality": 0,
"profile": null,
"samplerate": null,
"sampleformat": "",
"filter": "pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE",
"language": "eng",
"disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
"title": "Stereo",
"debug": "universal-audio"
},
{
"map": 1,
"codec": "ac3",
"channels": 6,
"bitrate": 768,
"profile": null,
"quality": 0,
"filter": null,
"samplerate": null,
"sampleformat": "",
"language": "eng",
"disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
"bsf": null,
"title": "5.1 Channel",
"debug": "audio"
}
],
"subtitle": [],
"attachment": []
}
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Preopts
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - []
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Postopts
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - [
"-threads",
"0",
"-metadata:g",
"encoding_tool=SMA"
]
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - Starting conversion.
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - FFmpeg command:
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - ======================
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - /usr/local/bin/ffmpeg -i "/downloads/sabnzbd/Completed/*** *** 720p WEB H264-PECULATE/00994fa959294d3aaf30629f6ea2d11b.mkv" -vcodec copy -map 0:0 -metadata:s:v title=HD -metadata:s:v handler_name=HD -c:a:0 libfdk_aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 BPS=256000 -metadata:s:a:0 BPS-eng=256000 -filter:a:0 pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:a:1 ac3 -map 0:1 -ac:a:1 6 -b:a:1 768k -metadata:s:a:1 BPS=768000 -metadata:s:a:1 BPS-eng=768000 -metadata:s:a:1 "title=5.1 Channel" -metadata:s:a:1 "handler_name=5.1 Channel" -metadata:s:a:1 language=eng -disposition:a:1 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y "/downloads/sabnzbd/Completed/*** *** 720p WEB H264-PECULATE/00994fa959294d3aaf30629f6ea2d11b.mp4"
2022-05-30 08:25:39 - resources.mediaprocessor - INFO - ======================
2022-05-30 08:25:39 - resources.mediaprocessor - ERROR - Unexpected exception during conversion.
Traceback (most recent call last):
File "/downloads/scripts/sickbeard_mp4_automator-master/converter/ffmpeg.py", line 660, in convert
p = self._spawn(cmds)
File "/downloads/scripts/sickbeard_mp4_automator-master/converter/ffmpeg.py", line 530, in _spawn
return Popen(cmds, shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE,
File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/downloads/scripts/sickbeard_mp4_automator-master/resources/mediaprocessor.py", line 1856, in convert
for timecode, debug in conv:
File "/downloads/scripts/sickbeard_mp4_automator-master/converter/__init__.py", line 318, in convert
for timecode, debug in self.ffmpeg.convert(outfile,
File "/downloads/scripts/sickbeard_mp4_automator-master/converter/ffmpeg.py", line 662, in convert
raise FFMpegError('Error while calling ffmpeg binary')
converter.ffmpeg.FFMpegError: Error while calling ffmpeg binary
2022-05-30 08:25:39 - SABPostProcess - ERROR - Converting file failed /downloads/sabnzbd/Completed/*** *** 720p WEB H264-PECULATE/00994fa959294d3aaf30629f6ea2d11b.mkv.
2022-05-30 08:25:39 - SABPostProcess - ERROR - No valid files found for conversion in download, aborting.
2022-05-30 08:25:39 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "/downloads/scripts/sickbeard_mp4_automator-master/SABPostProcess.py", line 81, in <module>
sys.exit(1)
SystemExit: 1

**Comment by mdhiggins** [comment]
Is that path where your FFMPEG binary is located? Is it actually there?

Does your FFMPEG build actually work or open?

FFPROBE appears to be working fine

Also this looks like an old version of the script since pymediainfo isn't used anymore

**Comment by jahmac23** [comment]
when I run which ffmpeg....it shows /usr/local/bin . Is your script updated latest. I will re download the file.
    On Monday, 30 May 2022, 15:06:19 BST, Michael Higgins ***@***.***> wrote:  
 
 


Is that path where your FFMPEG binary is located? Is it actually there?

Does your FFMPEG build actually work or open?

FFPROBE appears to be working fine

Also this looks like an old version of the script since pymediainfo isn't used anymore

**Comment by mdhiggins** [comment]
Does your FFMPEG binary actually launch?

**Comment by jahmac23** [comment]
even though mp4 conversion, audio aac and also file rename everything done, stream plays ok but I get these errors on my sabnzbd while converting TV shows from sonarr. Butt movies from radarr on sabnzbd mp4 conversion no error.Please take a look the error I get on my sabnzbd TV shows conversion in the end. On sabnzbd error  ": 0".
"2022-06-01 00:34:57 - resources.mediaprocessor - INFO - /downloads/sabnzbd/Completed/*** S06E18 Us 720p AMZN WEB-DL DDP5 1 H 264-NTb/9e77c97b7b6d4e9db36111f513e2ce00.mp4 created.
2022-06-01 00:34:57 - SABPostProcess - INFO - Successfully processed /downloads/sabnzbd/Completed/*** S06E18 Us 720p AMZN WEB-DL DDP5 1 H 264-NTb/9e77c97b7b6d4e9db36111f513e2ce00.mkv.
2022-06-01 00:34:57 - SABPostProcess - INFO - Passing /downloads/sabnzbd/Completed/*** S06E18 Us 720p AMZN WEB-DL DDP5 1 H 264-NTb directory to Sonarr.
2022-06-01 00:34:57 - autoprocess.sonarr - INFO - Sonarr notifier started.
2022-06-01 00:34:57 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/downloads/sabnzbd/Completed/*** S06E18 Us 720p AMZN WEB-DL DDP5 1 H 264-NTb'.
2022-06-01 00:34:57 - autoprocess.sonarr - ERROR - Update to Sonarr failed, check if Sonarr is running, autoProcess.ini settings and make sure your Sonarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/downloads/scripts/sickbeard_mp4_automator-master_latest/autoprocess/sonarr.py", line 80, in accessAPI
rstate = r.json()
File "/usr/lib/python3.9/site-packages/requests/models.py", line 917, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
: 0
"

    On Tuesday, 31 May 2022, 16:32:28 BST, Jahidul Islam ***@***.***> wrote:  
 
  Thanks mate. I found out ffmpeg was on /usr/bin not on /usr/local/bin as default. Updated ffmpeg location and its ok. Only thing i need to build ffmpeg with libfdk_aac enables as libfdk_aac not working. But ac3 and aac working.
    On Tuesday, 31 May 2022, 00:17:00 BST, Jahidul Islam ***@***.***> wrote:  
 
  
What command I can check whether it actually runs or not. Basically its on seedbox container OS Alpine and I need to ask support team to check. They showed me withh which ffmpeg.The same seedbox I was using last 2 years with your script and all was ok. Just last 2 weeks issue since they upgraded sonarr to latest vversion.    On Tuesday, 31 May 2022, 00:05:21 BST, Michael Higgins ***@***.***> wrote:  
 
 


Does your FFMPEG binary actually launch?

**Comment by jahmac23** [comment]
i am already using non ssl port of sabnzbd in sonarr Download client settings. My Sabnzbd SSL port not even active.
    On Wednesday, 1 June 2022, 14:08:07 BST, Michael Higgins ***@***.***> wrote:  
 
 


Glad you fixed your main issue

This new issue is an API error and the message is right there for why its failing
400 Bad Request
The plain HTTP request was sent to HTTPS port

Can't mix and match HTTP/HTTPS ports and requests

Set ssl = True in your [Sonarr] autoProcess.ini settings or change your port to the non-SSL port

**Comment by jahmac23** [comment]
Thanks mate. I found out ffmpeg was on /usr/bin not on /usr/local/bin as default. Updated ffmpeg location and its ok. Only thing i need to build ffmpeg with libfdk_aac enables as libfdk_aac not working. But ac3 and aac working.
    On Tuesday, 31 May 2022, 00:17:00 BST, Jahidul Islam ***@***.***> wrote:  
 
  
What command I can check whether it actually runs or not. Basically its on seedbox container OS Alpine and I need to ask support team to check. They showed me withh which ffmpeg.The same seedbox I was using last 2 years with your script and all was ok. Just last 2 weeks issue since they upgraded sonarr to latest vversion.    On Tuesday, 31 May 2022, 00:05:21 BST, Michael Higgins ***@***.***> wrote:  
 
 


Does your FFMPEG binary actually launch?

**Comment by jahmac23** [comment]
What command I can check whether it actually runs or not. Basically its on seedbox container OS Alpine and I need to ask support team to check. They showed me withh which ffmpeg.The same seedbox I was using last 2 years with your script and all was ok. Just last 2 weeks issue since they upgraded sonarr to latest vversion.    On Tuesday, 31 May 2022, 00:05:21 BST, Michael Higgins ***@***.***> wrote:  
 
 


Does your FFMPEG binary actually launch?

**Comment by mdhiggins** [comment]
Just run the binary and you should get the headers and basic exe info, if you don't get that info its not executing


```
ffmpeg version 2022-02-03-git-e1a14479a8-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 19.100 / 57. 19.100
  libavcodec     59. 20.100 / 59. 20.100
  libavformat    59. 17.101 / 59. 17.101
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 26.101 /  8. 26.101
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

Linuxserver has switched around their Sonarr images quite a bit recently, bouncing from Ubuntu to Alpine then back to Ubuntu

The sonarr-sma package has been adjusted accordingly but if you're using custom binaries these switches will cause problems and the container won't be able to fix it automatically like it normally does
