### ISSUE TITLE
Trouble when attempting to convert to AV1

### ISSUE THREAD

**Issue by GeekItTillItMhz** [mdhiggins/sickbeard_mp4_automator#1589]
As the title says trying to convert to AV1 but getting an error I am not sure how to solve.
```

],
    "format": "mp4",
    "video": {
        "codec": "av1",
        "map": 1,
        "bitrate": 1178.07885,
        "crf": 50,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": "baseline",
        "preset": "8",
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "framedata": null,
        "bsf": null,
        "debug": "video.profile",
        "title": "HD"
    },
    "audio": [
        {
            "map": 0,
            "codec": "flac",
            "channels": 2,
            "bitrate": 512,
            "profile": null,
            "quality": 0,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "bsf": null,
            "debug": "audio",
            "title": "Stereo"
        }
    ],
    "subtitle": [],
    "attachment": []
}
2022-05-30 06:26:18 - resources.mediaprocessor - INFO - Preopts
2022-05-30 06:26:18 - resources.mediaprocessor - INFO - []
2022-05-30 06:26:18 - resources.mediaprocessor - INFO - Postopts
2022-05-30 06:26:18 - resources.mediaprocessor - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
2022-05-30 06:26:18 - resources.mediaprocessor - INFO - Starting conversion.
2022-05-30 06:26:18 - resources.mediaprocessor - ERROR - Unexpected exception encountered during conversion
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 164, in process
    outputfile, inputfile = self.convert(options, preopts, postopts, reportProgress, progressOutput)
  File "/usr/local/sma/resources/mediaprocessor.py", line 2164, in convert
    _, cmds = next(conv)
  File "/usr/local/sma/converter/__init__.py", line 328, in convert
    optlist = self.parse_options(options, twopass, strip_metadata=strip_metadata)
  File "/usr/local/sma/converter/__init__.py", line 191, in parse_options
    video_options = self.video_codecs[c]().parse_options(x)
  File "/usr/local/sma/converter/avcodecs.py", line 1816, in parse_options
    if p < 0 or p > 13:
TypeError: '<' not supported between instances of 'str' and 'int'
2022-05-30 06:26:18 - RadarrPostProcess - INFO - Processing returned False.
2022-05-30 06:26:18 - RadarrPostProcess - ERROR - Error processing file.
Traceback (most recent call last):
  File "/usr/local/sma/postRadarr.py", line 304, in <module>
    sys.exit(1)
SystemExit: 1
```
```
[Video]
codec = av1
max-bitrate = 4000
crf = 50
crf-profiles = 
preset = 8
codec-parameters = 
dynamic-parameters = False
max-width = 1280
profile = baseline
max-level = 0.0
pix-fmt = 
filter = 
force-filter = False
bitrate-ratio = 
prioritize-source-pix-fmt = True
```

**Comment by mdhiggins** [comment]
511b2c5a90b814479a65da3821c7ba493595bf55

See if that fixes it, AV1 support is new to SMA

Migrated the issue from the radarr-sma repo since it was an SMA problem not a docker proble

**Comment by GeekItTillItMhz** [comment]
Works! Thank you for you prompt help.
