### ISSUE TITLE
ImportError: No module named apport.fileutils on Ubuntu 14.04

### ISSUE THREAD

**Issue by alexs77** [mdhiggins/sickbeard_mp4_automator#161]
``` shell
$ python2.7 ~/Repos/sickbeard_mp4_automator/manual.py -i /extern/JD/Breaking\ Bad/Breaking.Bad.S03E11.720p-TVP/Breaking.Bad.S03E11.Offene.Worte.GERMAN.5.1.DUBBED.DL.720p.BluRay.x264-TVP.mkv.bak.original.mkv -a 
Matched TV episode as Breaking Bad (TVDB ID:81189) S03E11
Processing Breaking Bad Season 03 Episode 11 - Abiquiu
Traceback (most recent call last):
  File "/home/ask/Repos/sickbeard_mp4_automator/manual.py", line 287, in <module>
    main()
  File "/home/ask/Repos/sickbeard_mp4_automator/manual.py", line 278, in main
    processFile(path, tagdata)
  File "/home/ask/Repos/sickbeard_mp4_automator/manual.py", line 182, in processFile
    output = converter.process(inputfile, True)
  File "/.sys/Data/HOME/Repos/sickbeard_mp4_automator/mkvtomp4.py", line 106, in process
    options = self.generateOptions(inputfile, original=original)
  File "/.sys/Data/HOME/Repos/sickbeard_mp4_automator/mkvtomp4.py", line 181, in generateOptions
    print "Video codec detected: " + info.video.codec
AttributeError: 'NoneType' object has no attribute 'video'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 64, in apport_excepthook
ImportError: No module named apport.fileutils

Original exception was:
Traceback (most recent call last):
  File "/home/ask/Repos/sickbeard_mp4_automator/manual.py", line 287, in <module>
    main()
  File "/home/ask/Repos/sickbeard_mp4_automator/manual.py", line 278, in main
    processFile(path, tagdata)
  File "/home/ask/Repos/sickbeard_mp4_automator/manual.py", line 182, in processFile
    output = converter.process(inputfile, True)
  File "/.sys/Data/HOME/Repos/sickbeard_mp4_automator/mkvtomp4.py", line 106, in process
    options = self.generateOptions(inputfile, original=original)
  File "/.sys/Data/HOME/Repos/sickbeard_mp4_automator/mkvtomp4.py", line 181, in generateOptions
    print "Video codec detected: " + info.video.codec
AttributeError: 'NoneType' object has no attribute 'video'
```

I used python2.7, ie. Python 2.7.6. Same error also with Python 3.4.

**Comment by ehaus** [comment]
I had the same issue.  I have avprobe, not ffprobe.  Much thanks for the links to binaries.
