### ISSUE TITLE
 SonarrPostProcess - ERROR - Rescan command timed out

### ISSUE THREAD

**Issue by Whereamnow** [mdhiggins/sickbeard_mp4_automator#1632]
Running on Windows 10, Sonarr v3

2022-12-01 01:42:28 - qtfaststart - INFO - Writing output...
2022-12-01 01:49:54 - resources.mediaprocessor - INFO - Plex refreshed: show
2022-12-01 01:49:54 - SonarrPostProcess - INFO - Sonarr response from RescanSeries command: ID 1753632 started.
2022-12-01 01:50:54 - SonarrPostProcess - ERROR - Rescan command timed out.
2022-12-01 01:50:54 - SonarrPostProcess - ERROR - Sonarr monitor status update failed.
Traceback (most recent call last):
  File "C:\Operator\sickbeard_mp4_automator-master\postSonarr.py", line 323, in <module>
    sys.exit(1)
SystemExit: 1

**Comment by mdhiggins** [comment]
Might need to check your sonarr logs to see why your rescan timed out. That would suggest a Sonarr problem the script is just waiting for Sonarr

**Comment by mdhiggins** [comment]
That might be the problem then. The API did respond with "started" so it at least received the command. Have you tried verifying all your Sonarr settings in autoProcess.ini and restarting Sonarr to make sure you don't have any tasks that are stuck preventing it from running commands? Ultimately this seems like a Sonarr issue

**Comment by Whereamnow** [comment]
Sonarr settings in autoProcess.ini look correct. I reinstall Sonarr but the issue remains. I thought about switching to v4 beta but I don’t know if it is supported yet.

**Comment by mdhiggins** [comment]
I believe even on the latest beta the API version is v3 which was only recently implemented

**Comment by mdhiggins** [comment]
For what its worth I just pulled the latest dev image which is

Sonarr Version    4.0.0.205

And ran a test and the script worked fine and all the API commands processed without issue

```
2022-12-01 19:25:32 - SonarrPostProcess - DEBUG - Requesting command status from Sonarr for command ID 3725742.
2022-12-01 19:25:32 - SonarrPostProcess - DEBUG - Status: started.
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - {'name': 'RescanSeries', 'commandName': 'Rescan Series', 'message': 'Completed', 'body': {'seriesId': 223, 'sendUpdatesToClient': True, 'updateScheduledTask': True, 'completionMessage': 'Completed', 'requiresDiskAccess': False, 'isExclusive': False, 'isLongRunning': False, 'name': 'RescanSeries', 'trigger': 'manual', 'suppressMessages': False}, 'priority': 'normal', 'status': 'completed', 'queued': '2022-12-02T00:25:32Z', 'started': '2022-12-02T00:25:32Z', 'ended': '2022-12-02T00:25:33Z', 'duration': '00:00:00.3391894', 'trigger': 'manual', 'stateChangeTime': '2022-12-02T00:25:32Z', 'sendUpdatesToClient': True, 'updateScheduledTask': True, 'id': 3725742}
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - Final status: completed.
2022-12-01 19:25:42 - SonarrPostProcess - INFO - Rescan command completed.
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - Requesting episode from Sonarr via http://127.0.0.1:8989/api/v3/episode/18942.
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - {'seriesId': 223, 'tvdbId': 9360914, 'episodeFileId': 25038, 'seasonNumber': 17, 'episodeNumber': 8, 'title': 'The Shooting Star Project (Zero Mix)', 'airDate': '2022-11-29', 'airDateUtc': '2022-11-28T15:00:00Z', 'overview': 'Rescue operations are being carried out across the Seireitei to find and help those who have survived the onslaught of the Sternritter.', 'episodeFile': {'seriesId': 223, 'seasonNumber': 17, 'relativePath': 'Season 17/Bleach - S17E08 - The Shooting Star Project (Zero Mix) WEBDL-1080p AAC.rnm.mp4', 'path': '/tv/Bleach/Season 17/Bleach - S17E08 - The Shooting Star Project (Zero Mix) WEBDL-1080p AAC.rnm.mp4', 'size': 935458897, 'dateAdded': '2022-12-02T00:25:33Z', 'languages': [{'id': 8, 'name': 'Japanese'}], 'quality': {'quality': {'id': 3, 'name': 'WEBDL-1080p', 'source': 'web', 'resolution': 1080}, 'revision': {'version': 1, 'real': 0, 'isRepack': False}}, 'mediaInfo': {'audioBitrate': 125375, 'audioChannels': 2, 'audioCodec': 'AAC', 'audioLanguages': 'jpn', 'audioStreamCount': 1, 'videoBitDepth': 8, 'videoBitrate': 4945067, 'videoCodec': 'h264', 'videoFps': 23.976, 'videoDynamicRange': '', 'videoDynamicRangeType': '', 'resolution': '1920x1080', 'runTime': '24:33', 'scanType': 'Progressive', 'subtitles': 'eng'}, 'qualityCutoffNotMet': False, 'id': 25038}, 'hasFile': True, 'monitored': True, 'absoluteEpisodeNumber': 374, 'sceneAbsoluteEpisodeNumber': 8, 'sceneEpisodeNumber': 8, 'sceneSeasonNumber': 2, 'unverifiedSceneNumbering': False, 'series': {'title': 'Bleach', 'sortTitle': 'bleach', 'status': 'continuing', 'ended': False, 'overview': 'For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever when Rukia transfers most of her powers to him. Now a Soul Reaper himself with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.', 'network': 'TV Tokyo', 'airTime': '00:00', 'images': [{'coverType': 'banner', 'url': 'https://artworks.thetvdb.com/banners/graphical/74796-g4.jpg'}, {'coverType': 'poster', 'url': 'https://artworks.thetvdb.com/banners/posters/74796-3.jpg'}, {'coverType': 'fanart', 'url': 'https://artworks.thetvdb.com/banners/fanart/original/74796-1.jpg'}], 'originalLanguage': {'id': 1, 'name': 'English'}, 'seasons': [{'seasonNumber': 0, 'monitored': False}, {'seasonNumber': 1, 'monitored': False}, {'seasonNumber': 2, 'monitored': False}, {'seasonNumber': 3, 'monitored': False}, {'seasonNumber': 4, 'monitored': False}, {'seasonNumber': 5, 'monitored': False}, {'seasonNumber': 6, 'monitored': False}, {'seasonNumber': 7, 'monitored': False}, {'seasonNumber': 8, 'monitored': False}, {'seasonNumber': 9, 'monitored': False}, {'seasonNumber': 10, 'monitored': False}, {'seasonNumber': 11, 'monitored': False}, {'seasonNumber': 12, 'monitored': False}, {'seasonNumber': 13, 'monitored': False}, {'seasonNumber': 14, 'monitored': False}, {'seasonNumber': 15, 'monitored': False}, {'seasonNumber': 16, 'monitored': False}, {'seasonNumber': 17, 'monitored': True}], 'year': 2004, 'path': '/tv/Bleach', 'qualityProfileId': 9, 'seasonFolder': True, 'monitored': True, 'useSceneNumbering': True, 'runtime': 25, 'tvdbId': 74796, 'tvRageId': 2825, 'tvMazeId': 1905, 'firstAired': '2004-10-05T00:00:00Z', 'seriesType': 'anime', 'cleanTitle': 'bleach', 'imdbId': 'tt0434665', 'titleSlug': 'bleach', 'certification': 'TV-MA', 'genres': ['Action', 'Adventure', 'Animation', 'Anime', 'Fantasy', 'Martial Arts'], 'tags': [3], 'added': '2022-10-15T05:39:27Z', 'ratings': {'votes': 16544, 'value': 7.9}, 'languageProfileId': 1, 'id': 223}, 'images': [{'coverType': 'screenshot', 'url': 'https://artworks.thetvdb.com/banners/v4/episode/9360914/screencap/637f8a1b87f00.jpg'}], 'grabbed': False, 'id': 18942}
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - Requesting episode update to Sonarr via http://127.0.0.1:8989/api/v3/episode/18942.
2022-12-01 19:25:42 - SonarrPostProcess - INFO - Sonarr monitoring information updated for episode The Shooting Star Project (Zero Mix).
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - Trying to restore scene information.
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - Requesting episodefile from Sonarr for episodefile via http://127.0.0.1:8989/api/v3/episodefile/25038.
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - Requesting episodefile update to Sonarr via http://127.0.0.1:8989/api/v3/episodefile/25038.
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - Restored releaseGroup to NTb.
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - Queueing rename command to Sonarr via http://127.0.0.1:8989/api/v3/command.
2022-12-01 19:25:42 - SonarrPostProcess - DEBUG - {'name': 'RenameFiles', 'files': [25038], 'seriesId': 223}
2022-12-01 19:25:42 - SonarrPostProcess - INFO - Sonarr response RenameFiles command: ID 3725744 queued.
```

**Comment by Whereamnow** [comment]
So i upgraded to v4

still fail but now Sonarr log is different

2022-12-01 22:17:12.4|Error|python.exe|--- Logging error ---
2022-12-01 22:17:12.4|Error|python.exe|Traceback (most recent call last):
2022-12-01 22:17:12.4|Error|python.exe|  File "C:\Users\(removed)\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 74, in emit
2022-12-01 22:17:12.4|Error|python.exe|    self.doRollover()
2022-12-01 22:17:12.4|Error|python.exe|  File "C:\Users\(removed)\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 179, in doRollover
2022-12-01 22:17:12.4|Error|python.exe|    self.rotate(self.baseFilename, dfn)
2022-12-01 22:17:12.4|Error|python.exe|  File "C:\Users\(removed)\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 115, in rotate
2022-12-01 22:17:12.4|Error|python.exe|    os.rename(source, dest)
2022-12-01 22:17:12.4|Error|python.exe|PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Operator\\sickbeard_mp4_automator-master\\config\\sma.log' -> 'C:\\Operator\\sickbeard_mp4_automator-master\\config\\sma.log.1'
2022-12-01 22:17:12.4|Error|python.exe|Call stack:
2022-12-01 22:17:12.4|Error|python.exe|  File "C:\Operator\sickbeard_mp4_automator-master\postSonarr.py", line 233, in <module>
2022-12-01 22:17:12.4|Error|python.exe|    success = mp.fullprocess(inputfile, MediaType.TV, tvdbid=tvdb_id, imdbid=imdb_id, season=season, episode=episode, original=original)
2022-12-01 22:17:12.4|Error|python.exe|  File "C:\Operator\sickbeard_mp4_automator-master\resources\mediaprocessor.py", line 61, in fullprocess
2022-12-01 22:17:12.4|Error|python.exe|    output = self.process(inputfile, original=original, info=info, tagdata=tagdata, reportProgress=reportProgress)
2022-12-01 22:17:12.4|Error|python.exe|  File "C:\Operator\sickbeard_mp4_automator-master\resources\mediaprocessor.py", line 136, in process
2022-12-01 22:17:12.4|Error|python.exe|    options, preopts, postopts, ripsubopts, downloaded_subs = self.generateOptions(inputfile, info=info, original=original, tagdata=tagdata)
2022-12-01 22:17:12.4|Error|python.exe|  File "C:\Operator\sickbeard_mp4_automator-master\resources\mediaprocessor.py", line 662, in generateOptions
2022-12-01 22:17:12.4|Error|python.exe|    self.log.info(json.dumps(info.json, sort_keys=False, indent=4))
2022-12-01 22:17:12.4|Error|python.exe|Message: '{\n    "format": "matroska,webm",\n    "format-fullname": "Matroska / WebM",\n    "video": {\n        "index": 0,\n        "codec": "h264",\n        "pix_fmt": "yuv420p",\n        "profile": "high",\n        "fps": 23.976023976023978,\n        "framedata": {\n            "pix_fmt": "yuv420p",\n            "side_data_list": [\n                {\n                    "side_data_type": "ATSC A53 Part 4 Closed Captions"\n                },\n                {\n                    "side_data_type": "H.26[45] User Data Unregistered SEI message"\n                }\n            ]\n        },\n        "dimensions": "1920x1080",\n        "level": 4.0,\n        "field_order": "progressive"\n    },\n    "audio": [\n        {\n            "index": 1,\n            "codec": "aac",\n            "channels": 2,\n            "samplerate": 44100,\n            "language": "eng",\n            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"\n        }\n    ],\n    "subtitle": [\n        {\n            "index": 2,\n            "codec": "subrip",\n            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",\n            "language": "eng"\n        }\n    ],\n    "attachment": []\n}'
2022-12-01 22:17:12.4|Error|python.exe|Arguments: ()

**Comment by mdhiggins** [comment]
No idea what to make of that. Can you post the sma log

**Comment by mdhiggins** [comment]
Actually it looks like python is failing to rotate the sma log files. Might need to check your permissions on them and maybe clear them out or increase the size on logging.ini

**Comment by Whereamnow** [comment]
i tried downgrading back but same issue. I'll leave it alone since it still converts automatically.

**Comment by mdhiggins** [comment]
Yeah the Sonarr API functions are mostly just to update the database with some additional details after conversion so not required for conversion
