### ISSUE TITLE
OSError: [WinError 17] The system cannot move the file to a different disk drive

### ISSUE THREAD

**Issue by neilanthonystuckey** [mdhiggins/sickbeard_mp4_automator#1636]
**Describe the bug**

```
2022-12-20 12:09:35 - qtfaststart - INFO - Writing output...
2022-12-20 12:13:17 - resources.mediaprocessor - INFO - Output file is in output_dir W:\convert, moving back to original directory X:\tvshows\Andor\Season 1\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4.
2022-12-20 12:14:15 - resources.mediaprocessor - ERROR - First attempt to move the file has failed.
Traceback (most recent call last):
  File "C:\Users\nstuckey\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'W:\\convert\\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4' -> 'X:\\tvshows\\Andor\\Season 1\\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nstuckey\Documents\mp4_automator\resources\mediaprocessor.py", line 1972, in restoreFromOutput
    shutil.move(outputfile, newoutputfile)
  File "C:\Users\nstuckey\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "C:\Users\nstuckey\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 437, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\nstuckey\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 382, in copystat
    lookup("chmod")(dst, mode, follow_symlinks=follow)
OSError: [WinError 50] The request is not supported: 'X:\\tvshows\\Andor\\Season 1\\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4'
2022-12-20 12:14:15 - resources.mediaprocessor - ERROR - Unable to move W:\convert\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4 to X:\tvshows\Andor\Season 1\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4
Traceback (most recent call last):
  File "C:\Users\nstuckey\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'W:\\convert\\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4' -> 'X:\\tvshows\\Andor\\Season 1\\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nstuckey\Documents\mp4_automator\resources\mediaprocessor.py", line 1972, in restoreFromOutput
    shutil.move(outputfile, newoutputfile)
  File "C:\Users\nstuckey\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "C:\Users\nstuckey\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 437, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\nstuckey\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 382, in copystat
    lookup("chmod")(dst, mode, follow_symlinks=follow)
OSError: [WinError 50] The request is not supported: 'X:\\tvshows\\Andor\\Season 1\\Andor.S01E12.FiNAL.MULTi.1080p.WEB.H264-STRINGERBELL.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nstuckey\Documents\mp4_automator\resources\mediaprocessor.py", line 1980, in restoreFromOutput
    shutil.move(outputfile.decode(sys.getfilesystemencoding()), newoutputfile)
```

**Command or context you are trying to run**
For manual.py include the full command, for integrated commands please include relavent logs from those programs (IE for postSonarr.py please include relevant Sonarr logs)

**autoProcess.ini settings**
***Please sensor API keys/private information but include all other settings***

[Converter]
ffmpeg = C:\Users\nstuckey\Documents\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\Users\nstuckey\Documents\ffmpeg\bin\ffprobe.exe
threads = 0
hwaccels = 
hwaccel-decoders = 
hwdevices = 
hwaccel-output-format = 
output-directory = W:\convert
output-directory-space-ratio = 0.0
output-format = mp4
output-extension = mp4
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
process-same-extensions = False
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = True

[Video]
codec = h264_qsv, hevc_qsv
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
prioritize-source-pix-fmt = True
filter = 
force-filter = False

**Log files**
Include log files *for the specific job (not just a dump of all your logs for the past month)* that's causing the issue. Please turn on [debug level logging](https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging)
Log files are found in your script root config folder `./sma/config/sma.log`

**FFMpeg headers**
Run ffmpeg and post the headers, example [headers]https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/FFMPEG-Headers

**System Information**
 - OS: Windows
 - Python version Python\Python311
 - Docker config (if relevant) NA

**Expected behavior**
A clear and concise description of what you expected to happen. I think there are linux commands being ran.  What do i need to change to make this run on Windows 10 ?

**Additional context**

I am Running Sonarr and Radarr as executable not as a service.

*Issues posted without any logs or autoProcess settings will be closed*

**Comment by mdhiggins** [comment]
`shutil.move` is supported on Windows and is the preferred method on Python for moving files especially between drives. This strikes me as maybe a Windows permission problem, do you definitely have write permission to the external drive? shutil.move will use os.rename internally in some cases but internally it has logic to deal with different drives. It seems if there is a write permission error the os.rename error is the final exception that gets reported though

Moving between windows drives works fine on my machine, I used D:\convert as my temporary directory and it moved the files back to the C:\ drive when completed (Win 11 2H22) Python 3.10.4

```
Output directory: C:\Users\***\Videos\encoding tests.
Output extension: C:\Users\***\Videos\encoding tests.
Output file: C:\Users\***\Videos\encoding tests\test.mp4.
Output file is in output_dir D:\temp, moving back to original directory C:\Users\***\Videos\encoding tests\test.mp4.
Final output file: C:\Users\***\Videos\encoding tests\test.mp4.
```
