### ISSUE TITLE
Feature Request: Scanning specific path on plex refresh rather than the entire library

### ISSUE THREAD

**Issue by claptrapjargon** [mdhiggins/sickbeard_mp4_automator#1650]
**Is your feature request related to a problem? Please describe.**
I have a somewhat large media library (100's of series and episodes in the 10.000's for example) so scanning that library after every download is not desirable. My python/programming knowledge is pretty basic, but after reading through plex.py it looks like it is only intended to refresh the relevant library after downloading/processing.

**Describe the solution you'd like**
It would be very convenient if the Plex refresh function scanned only the series or movie that was downloaded instead of the entire library.

**Describe alternatives you've considered**
Currently I'm the API to refresh a specific item, see following:
curl -G -H "X-Plex-Token: $TOKEN" --data-urlencode "path=$SCAN_PATH" http://$PLEX_IP:$PLEX_PORT/library/sections/$SECTION_ID/refresh

Is the path scan something that can be implemented?

**Additional context**
Like I already mentioned, my programming knowledge is rudimentary so it's very possible I'm asking for a feature that's already available.

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/tree/plexrefresh

Made a branch and rewrote the plex refresh using PlexAPI and pass the outputfile basedir to the refresh command

See if that works and I can merge it back to master

You'll need plexAPI though

`pip install plexapi`

**Comment by mdhiggins** [comment]
Instead of filtering the librarysection by type this instead looks to see if the path that needs to be refreshed is contained in a librarysection and refreshes that section (at the path) if true and just ignores the type completely

**Comment by claptrapjargon** [comment]
This looks very promising but unfortunately I can't get it to work on my end. Currently, I'm getting the following error in sma.log:

`2023-03-31 17:52:35 - resources.mediaprocessor - ERROR - Unable to connect to Plex server
Traceback (most recent call last):
  File "/usr/local/sma/autoprocess/plex.py", line 23, in refreshPlex
    plex = PlexServer("https://" + settings.address + ':' + str(settings.port), settings.token)
AttributeError: 'ReadSettings' object has no attribute 'address'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/sma/autoprocess/plex.py", line 26, in refreshPlex
    plex = PlexServer("http://" + settings.address + ':' + str(settings.port), settings.token)
AttributeError: 'ReadSettings' object has no attribute 'address'`

The steps to the current setup from my normal setup are as follows:
1. Removed script from Sonarr category in SABnzbd
2. Enabled CDH in Sonarr (Using sonarr-sma docker image)
3. Manually replaced plex.py, postRadarr.py, postSonarr.py and mediaprocessor.py with edited versions within container
4. Installed plexapi in venv

Do you have an idea what I'm missing/doing wrong?

**Comment by mdhiggins** [comment]
Not your fault, mistake with my branch (working remotely so haven't tested)

Just pushed a small update that fixes that

**Comment by mdhiggins** [comment]
I went ahead and just merged this into the master branch, should make updating and testing much easier

If you're using sonarr-sma/radarr-sma just set `SMA_UPDATE=true` in your environment variables and it should pull down the latest git

**Comment by claptrapjargon** [comment]
That's much more convenient. I'm now using the sonarr-sma with SMA_UPDATE=true to test (had to install plexapi manually though).

We have now moved on to this error in sma.log:
```
2023-03-31 21:57:35 - resources.mediaprocessor - INFO - Connected to Plex server --REDACTED-- using server settings
2023-03-31 21:57:35 - resources.mediaprocessor - ERROR - Error refreshing Plex.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 128, in post
    plex.refreshPlex(self.settings, refreshpath, self.log)
  File "/usr/local/sma/autoprocess/plex.py", line 36, in refreshPlex
    for section in sections:
TypeError: 'method' object is not iterable
```

**Comment by mdhiggins** [comment]
Getting closer, fixed that issue too, one more update

**Comment by claptrapjargon** [comment]
Alrighty, so now the only line in sma.lag is:
`resources.mediaprocessor - INFO - Connected to Plex server --REDACTED-- using server settings`

The item is not refreshed by Plex though, I can't find any other related log entries.

**Comment by mdhiggins** [comment]
6d59c57f5c1f37476a6a2613f70bbe55a4ab9486

Borrowed some code from PlexAutoSkip for better options for actually connecting to the Plex server over SSL, this results in expansion of the Plex options

Instead of specifying an IP address etc you can just give you plex username and token and auth that way

I also added a "path-mapping" option similar to what's seen in some of the other downloaders so you can correct that variation

So if for example in your sonarr container its `/mnt/storage/tv/Bob's Burgers` and in plex its `/data/tv/Bob's Burgers` you can set

`path-mapping = /mnt/storage=/data`

```
[Plex]
username = 
password = 
servername = 
host = localhost
port = 32400
refresh = False
token = 
ssl = True
ignore-certs = False
path-mapping = 
```

**Comment by Whereamnow** [comment]
It seem to still require port. But Plex doesn't seem to try to refresh at all anymore. I dont see a log of Plex trying to connect or refresh. Last update that worked for me was when you move the refresh at the end of Sonnar/Radarr rename.

**Comment by mdhiggins** [comment]
Should be fixed in the latest update
You need something in the settings for port since its an integer data element but port is not used if server is obtained via myPlexAccount (I recommend using username, servername, and token as your 3 datapoints to connect to server)

I just tested with the latest update and I'm getting this

```
2023-04-02 10:05:00 - resources.mediaprocessor - INFO - Starting Plex refresh.
2023-04-02 10:05:00 - resources.mediaprocessor - DEBUG - PathMapping match found, replacing /tv with /data/tv, final directory is /data/tv/Yellowjackets/Season 02.
2023-04-02 10:05:00 - resources.mediaprocessor - INFO - Connecting to Plex server...
2023-04-02 10:05:31 - resources.mediaprocessor - INFO - Connected to Plex server Plexrack using plex.tv account.
2023-04-02 10:05:31 - resources.mediaprocessor - INFO - Checking if any sections contain the path /data/tv/Yellowjackets/Season 02.
2023-04-02 10:05:31 - resources.mediaprocessor - DEBUG - Checking section Movies path /data/movies.
2023-04-02 10:05:31 - resources.mediaprocessor - DEBUG - Checking section TV Shows path /data/tv.
2023-04-02 10:05:31 - resources.mediaprocessor - INFO - Refreshing TV Shows with path /tv/Yellowjackets/Season 02/Yellowjackets - S02E02 - Edible Complex WEBDL-1080p EAC3.rnm.mp4
2023-04-02 10:05:31 - resources.mediaprocessor - DEBUG - Checking section Audiobooks path /data/audiobooks.
```

**Comment by Whereamnow** [comment]
latest update worked for me.

**Comment by mdhiggins** [comment]
Working fine on my end, disabled all automatic refreshing and new test episode was picked up without issue

**Comment by Whereamnow** [comment]
works now!

**Comment by Whereamnow** [comment]
When the script ask sonnar to RenameEpsiode, if there a way to wait for Sonnar to reply that "RenameEpisodeFileService | Selected episode files renamed ..." before running Plex Refresh.

Even though Sonnar rename starts first, sometimes Plex Refresh still beats it so it reads "rnm.mp4" then Sonnar renames which deletes rnm so that file become unavaiable.

**Comment by claptrapjargon** [comment]
This is looking good so far!

The scripts works brilliantly with only one path-map but behaves oddly when I add more. So I'm wondering if the path-mapping supports multiple mappings?

I have five mounts separated by , in autoProcess.ini. 

Current settings in autoProcess.ini:
`path-mapping = /sonarrMount01=/plexMount01/tv,/sonarrMount02=/plexMount02/tv,*three more mappings follow*`

Log entry:
`resources.mediaprocessor - INFO - Refreshing tv with path /plexMount01/tv/../sonarrMount02/Vikings/Season 1`

It looks like it doesn't know what to do with the paths as I've written them, is there a way to handle this?

**Comment by mdhiggins** [comment]
It should be able to handle those paths just fine and its passing in my test script

```py
import os

testPaths = [
    "/sonarrMount01/Vikings/Season 1",
    "/sonarrMount02/Vikings/Season 1",
    "/sonarrMount03/Vikings/Season 1",
    "/sonarrMount04/Vikings/Season 1",
]

pathMapping = {
    "/sonarrMount01": "/plexMount01/tv",
    "/sonarrMount02": "/plexMount02/tv",
    "/sonarrMount03": "/plexMount03/tv",
    "/sonarrMount04": "/plexMount04/tv",
}

for targetpath in testPaths:
    # Path Mapping
    for k in pathMapping:
        if os.path.commonprefix([targetpath, k]) == k:
            targetpath = os.path.join(pathMapping[k], os.path.relpath(targetpath, k))
            print("PathMapping match found, replacing %s with %s, final directory is %s." % (k, pathMapping[k], targetpath))
            break

```

Does that not reflect your environment?
Some debug level logs from your test might be helpful

**Comment by claptrapjargon** [comment]
I just noticed that I made a mistake in my previous post, I edited the paths in an attempt to make it more clear what/where the folders were. So here are the real mounts to avoid confusion:

`path-mapping = /Thaettir=/PlexStorage/Thaettir,/Thaettir02=/PlexStorage02/Thaettir,/OnlineThaettir=/OnlinDatabase/Thaettir,/Kvikmyndir=/PlexStorage/Kvikmyndir,/Kvikmyndir02=/PlexStorage02/Kvikmyndir`

And here is the the final debug lines of sma.log:
[](https://pastebin.com/hgW2BfF8)

(I know the folder structure is messy, it's an environment that has grown over time and I haven't gotten around to fixing yet :p)

**Comment by mdhiggins** [comment]
Applied some sorting that might overcome this issue, it stems from your paths having the same prefix but the object coming later in the list actually being a better match

See if that works or if I need a more complex solution

**Comment by claptrapjargon** [comment]
Definite improvements on the paths, although there are some errors when testing. I moved the updated plex.py, postSonarr.py and postRadarr.py from plexrefresh to the proper places within the containers before testing.

Sonarr:
Mostly works, downloads and converts just fine and it figured out the paths and is able to refresh the series correctly. Log ends with the following though:
```
2023-04-05 22:00:35 - SonarrPostProcess - ERROR - Sonarr monitor status update failed.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 265, in <module>
    sys.exit(0)
SystemExit: 0
```

Radarr:
Similar situation, downloads and converts just fine but does not refresh plex. Final log entries:

```
2023-04-06 23:03:32 - RadarrPostProcess - DEBUG - Found a matching path scan in progress /Plex/Radarr/From.Hell.2001.1080p.BluRay.DTS.x264-FANDANGO.
2023-04-06 23:03:32 - RadarrPostProcess - INFO - DownloadedMoviesScan command is in process for this movie, cannot wait for rescan but will queue.
2023-04-06 23:03:32 - RadarrPostProcess - ERROR - Radarr monitor status update failed.
Traceback (most recent call last):
  File "/usr/local/sma/postRadarr.py", line 256, in <module>
    rescanRequest(baseURL, headers, movieid, log, retries=0)
TypeError: rescanRequest() got an unexpected keyword argument 'retries'
```

**Comment by claptrapjargon** [comment]
Okay, so these are the results from testing Sonarr and Radarr after updating changed files from plexrefresh:

*Sonarr:*
Downloads, converts and updates both Plex and Sonarr correctly, log returns this:
```
2023-04-10 00:12:22 - SonarrPostProcess - ERROR - Sonarr monitor status update failed.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 265, in <module>
    sys.exit(0)
SystemExit: 0
```

*Radarr:*
Downloads and converts movie, updates Radarr status but does not refresh Plex. 
Final related log entries from sma.log: [](https://pastebin.com/SiCVkZ02)
Log entries from Radarr docker container: [](https://pastebin.com/ijBLAAu9)

**Comment by mdhiggins** [comment]
Hm so this isn't really a good example test. This process had to abort because you already had a download scan triggered for that directory in progress so it doesn't go through its usual routine

That being said... the new restructuring of these commands does allow me to pull that command ID and wait for it so I just pushed an update that implements that, might help make these edge cases even more rare

297ac61cf7265e20360b91910a5fbaeeecac6c84

**Comment by mdhiggins** [comment]
Let me know when you get a chance to test on your end, looks like things are working for me

I'll merge back to the master branch if there's no issues

**Comment by mdhiggins** [comment]
The problem with your radarr setup is

```
{
  "name": "DownloadedMoviesScan",
  "commandName": "Downloaded Movies Scan",
  "body": {
    "sendUpdatesToClient": false,
    "sendUpdates": false,
    "path": "/Plex/Radarr/Shotgun.Wedding.2022.REPACK.MULTi.1080p.WEB.H264-DEAL",
    "importMode": "auto",
    "updateScheduledTask": true,
    "completionMessage": "Completed",
    "requiresDiskAccess": false,
    "isExclusive": false,
    "isTypeExclusive": false,
    "isLongRunning": false,
    "name": "DownloadedMoviesScan",
    "trigger": "manual",
    "suppressMessages": true
  },
  "priority": "normal",
  "status": "started",
  "queued": "2023-04-13T12:18:01Z",
  "started": "2023-04-13T12:18:01Z",
  "trigger": "manual",
  "stateChangeTime": "2023-04-13T12:18:01Z",
  "sendUpdatesToClient": false,
  "updateScheduledTask": true,
  "id": 461671
}
```

Before SMA can even start you have a manually triggered "DownloadedMoviesScan" and I'm not sure where its coming from. This scan is also going very slow and despite the script waiting for 60 seconds for it to finish it never does and thus it get stuck and can't run its usual commands

Are you running any other scripts that might be triggering this scan?

The DownloadedMoviesScancommand is not called from postRadarr at all, but it is called by autoProcess/radarr.py which is used by the deluge/sab/nzbget/qtbittorrent/utorrent scripts. Are you using them? and are you using any of those scripts with completed download handling also turned on for Radarr?

**Comment by claptrapjargon** [comment]
Interesting, that's definitely the case. I am using SABPostProcess.py (in SABNZBD) for both Sonarr and Radarr with Completed Download Handling disabled for both.

I tested Radarr after turning off SABPostProcess.py for Radarr and enabling CDH and everything worked as intended.

**Comment by mdhiggins** [comment]
The weird thing is the download scan should be done by the time postRadarr is getting called. The scan is what triggers the file move to the final destination and renaming and then postRadarr gets executed. Are there any errors on Radarr or any possibility the SAB script is getting called more than once?

**Comment by claptrapjargon** [comment]
If the SAB script is getting called more than once then I don't know where from. I believe I have a standard SABNZBD, sonarr-sma and radarr-sma setup, configured per your instructions. I have not added any other scripts or made any alterations.

There are errors in the radarr container logs though, perhaps this can shed some light on the issue?
[https://pastebin.com/hGP3JFRd](https://pastebin.com/hGP3JFRd)

**Comment by mdhiggins** [comment]
If you also happen to have the SMA logs including the SABPostProcess stuff for this same job and can send them over that will be helpful. I'll try and cross reference

**Comment by claptrapjargon** [comment]
Of course, I should have included it to begin with :)
This should be the complete SMA log for this job:
[https://pastebin.com/R1W9hDJh](https://pastebin.com/R1W9hDJh)

**Comment by claptrapjargon** [comment]
@mdhiggins 
I hope I don't come off as pushy but I was wondering if there is any more information I can provide or assistance with testing I could do that would help?

Earlier today I reviewed all my settings and updated all changed files from plexrefresh to make sure there wasn't any configuration errors on my side causing this, but I'm still getting the same errors as in the logs I posted earlier.

**Comment by mdhiggins** [comment]
Sorry I was out of town and didn't have time to work on this

I do see that Radarr is throwing an error

```
[Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 
[v4.3.2.6857] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Radarr.Api.V3.Commands.CommandController.StartCommand(CommandResource commandResource) in D:\a\1\s\src\Radarr.Api.V3\Commands\CommandController.cs:line 54
   at lambda_method346(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[Fatal] RadarrErrorPipeline: Request Failed. POST /api/v3/command 
[v4.3.2.6857] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Radarr.Api.V3.Commands.CommandController.StartCommand(CommandResource commandResource) in D:\a\1\s\src\Radarr.Api.V3\Commands\CommandController.cs:line 54
   at lambda_method346(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

That being said I have no idea why this error is thrown or if its even related. The weird thing is the DownloadedMoviesScan is what should be kicking things off and having Radarr movie the file to its final destination and subsequently trigger the postRadarr thing long after that's done.

In this case the logs are missing some things that make it difficult to tell. 

SAB kicks off the scan with ID 464736
And then 464736 is still marked as "started" which is ultimately what causes the downstream failure since it never finishes, but postRadarr really shouldn't even be running or initiated until 464736 is finished since its dependent on it

So you see anything in the logs to command 464736? I know its been a while so you might need to run another job and get a fresh ID. The Radarr logs you sent don't have any references to this idea and don't have any timestamps so its hard to infer.

Also what does your Radarr SMA config look like?

![image](https://user-images.githubusercontent.com/3608298/236694219-f8adff73-0753-4c93-a8bc-51fb52781b79.png)

Having it being triggered on the wrong notification could cause this

Finally, if you want to try just disabling the inProcess check, try commenting out this code in postRadarr.py and see if it impacts anything

```
        inProcess = downloadedMoviesScanInProgress(baseURL, headers, moviefile_sourcefolder, log)
        if inProcess and not waitForCommand(baseURL, headers, inProcess, log):
            log.info("DownloadedMoviesScan command is in process for this movie, timed out for rescan but will queue.")
            rescanRequest(baseURL, headers, movieid, log)
            renameRequest(baseURL, headers, None, movieid, log)
            mp.post(success, MediaType.Movie, tmdbid=tmdbid, imdbid=imdbid)
            sys.exit(0)
```

I also just included the improved pathmapping approach to the other areas of the script where pathmapping was implemented, though I don't think that's causing your issue it might be worth checking. Are you using pathmapping when going from SAB to Radarr? `/Plex/Radarr/Mad.Max-Fury.Road.2015.1080p.BluRay.AC-3.TrueHD7.1.Atmos.AVC-PiR8` is the directory that Radarr is being told to scan via its API, does that mirror what Radarr sees inside its container for where that file should be?

50144dc5c6022d222748d167b454e8f44352f239

**Comment by mdhiggins** [comment]
69a0c8c559b80bfcc8208048c3a09c5e9912fd1c

Seems like something broken in your Radarr install that's causing that API call to hang but don't know why but I went ahead and made the in-progress check optional for both Sonarr and Radarr (in-progress-check) so you can now just configure that to be off and bypass this whole issue hopefully

Give that a try and see if things are still working then I can probably just merge this into master

**Comment by claptrapjargon** [comment]
Great, worked like a charm!

I'll try to figure out what's wrong with my setup but this solves that issue for now. Thanks a bunch for the help.

**Comment by mdhiggins** [comment]
Merged into master
