### ISSUE TITLE
Plex refresh/connect errors in logs

### ISSUE THREAD

**Issue by cryo-kronos** [mdhiggins/sickbeard_mp4_automator#1654]
**Describe the issue**
Plex refresh/connect errors in logs

**Command or context you are trying to run**
I updated to the most recent version of mp4_automator and now I'm seeing Plex refresh/connect errors in the logs after Sonarr runs and mp4_automator remuxes the video file. It looks like changes were made to Plex.py and autoProcess.ini but I have no idea if I'm supposed to change anything on my end.

Any suggestions for fixing this?

**autoProcess.ini settings**
I've tried with ssl = False and also ssl = True.
I've toggled between True/False with ignore-certs and ssl

[Plex]
username = 
password = 
servername = 
host = localhost
port = 32400
refresh = True
token = redacted
ssl = True
ignore-certs = False
path-mapping = 

[Plex]
username = 
password = 
servername = 
host = localhost
port = 32400
refresh = True
token = redacted
ssl = False
ignore-certs = True
path-mapping = 

[Sonarr]
host = 10.0.0.101
port = 8989
apikey = redacted
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

**Log files**
Two debug log files depending on with Plex settings were True/False in autoProcess.ini:

2023-04-21 13:32:18 - resources.mediaprocessor - INFO - Starting Plex refresh.
2023-04-21 13:32:18 - resources.mediaprocessor - INFO - Connecting to Plex server...
2023-04-21 13:32:19 - resources.mediaprocessor - ERROR - Error connecting to Plex server.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'localhost' doesn't match '*.448f523e13a741d8a2a6df0eb2238e14.plex.direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'localhost' doesn't match '*.448f523e13a741d8a2a6df0eb2238e14.plex.direct'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/redacted/sickbeard_mp4_automator/autoprocess/plex.py", line 88, in getPlexServer
    plex = PlexServer(protocol + settings.Plex.get('host') + ':' + str(settings.Plex.get('port')), settings.Plex.get('token'), session=session)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'localhost' doesn't match '*.448f523e13a741d8a2a6df0eb2238e14.plex.direct'")))
2023-04-21 13:32:19 - resources.mediaprocessor - INFO - Checking if any sections contain the path /Volumes/media/video/redacted tv show.
2023-04-21 13:32:19 - resources.mediaprocessor - ERROR - Unable to establish Plex server connection.

The second log file with ssl = False, ignore-certs = True:

2023-04-21 13:39:06 - resources.mediaprocessor - INFO - Starting Plex refresh.
2023-04-21 13:39:06 - resources.mediaprocessor - INFO - Connecting to Plex server...
2023-04-21 13:39:08 - resources.mediaprocessor - ERROR - Error connecting to Plex server.
Traceback (most recent call last):
  File "/Users/redacted/sickbeard_mp4_automator/autoprocess/plex.py", line 88, in getPlexServer
    plex = PlexServer(protocol + settings.Plex.get('host') + ':' + str(settings.Plex.get('port')), settings.Plex.get('token'), session=session)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 751, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; http://localhost:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
2023-04-21 13:39:08 - resources.mediaprocessor - INFO - Checking if any sections contain the path /Volumes/media/video/tv-series/Atlanta/Season 01.
2023-04-21 13:39:08 - resources.mediaprocessor - ERROR - Unable to establish Plex server connection.

**FFMpeg headers**
ffmpeg version 5.1.2-tessus Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**System Information**
 - OS: macOS 14 Mojave
 - Python version: 3.10.9

*Issues posted without any logs or autoProcess settings will be closed*

**Comment by mdhiggins** [comment]
Is your Plex server set to "Secure Connections: Required"? If so trying to access the APh using just the host name and post won't work cause you won't have SSL

You can make it work using a token and your Plex username / server name though if that's the case

**Comment by cryo-kronos** [comment]
> Is your Plex server set to "Secure Connections: Required"? If so trying to access the API using just the host name and post won't work cause you won't have SSL
> 
> You can make it work using a token and your Plex username / server name though if that's the case

It's set to "Preferred." 

I also tested using my Plex username and password plus a token. Made no difference.

**Comment by mdhiggins** [comment]
If you use token you don't need a password but you do need to specify your server name

**Comment by cryo-kronos** [comment]
> If you use token you don't need a password but you do need to specify your server name

Servername (case sensitive) plus token did not work.

**Comment by Weezzel** [comment]
![image](https://user-images.githubusercontent.com/67742562/233788341-32e39ad8-5390-4ac7-8585-635b8ca48c55.png)


Says No module named plexapi

**Comment by mdhiggins** [comment]
Could you share the logs of the token server name based authentication

**Comment by cryo-kronos** [comment]
> Could you share the logs of the token server name based authentication

Where would I find this? Do you mean certain entries in the sma.log file? Or is this a Plex Media Server log?

**Comment by mdhiggins** [comment]
Just the SMA logs, similar to what you shared initially. Preferably with debug level logging (see wiki). Mostly just looking to see what auth method it's actually using

**Comment by cryo-kronos** [comment]
> Just the SMA logs, similar to what you shared initially. Preferably with debug level logging (see wiki). Mostly just looking to see what auth method it's actually using

Here's the log, minus all the Sonarr and mp4_utomator processing stuff that's not relevant:

`2023-04-22 19:08:38 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
2023-04-22 19:08:38 - resources.readsettings - INFO - /usr/local/opt/python@3.10/bin/python3.10
2023-04-22 19:08:38 - resources.readsettings - DEBUG - Loading default config file.
2023-04-22 19:08:38 - resources.readsettings - INFO - Loading config file /Users/redacted_user/sickbeard_mp4_automator/config/autoProcess.ini.
2023-04-22 19:10:55 - SonarrPostProcess - DEBUG - Requesting episode update to Sonarr via http://localhost:8989
2023-04-22 19:10:55 - SonarrPostProcess - DEBUG - Requesting episodefile update to Sonarr via http://localhost:8989/api/v3/episodefile/88615.
2023-04-22 19:10:55 - SonarrPostProcess - DEBUG - Queueing rename command to Sonarr via http://localhost:8989/api/v3/command.
2023-04-22 19:10:55 - SonarrPostProcess - DEBUG - {'name': 'RenameFiles', 'files': [88615], 'seriesId': 462}
2023-04-22 19:10:55 - SonarrPostProcess - INFO - Sonarr response RenameFiles command: ID 2938380 queued.
2023-04-22 19:10:55 - resources.mediaprocessor - INFO - Starting Plex refresh.
2023-04-22 19:10:55 - resources.mediaprocessor - INFO - Connecting to Plex server...
2023-04-22 19:10:55 - resources.mediaprocessor - ERROR - Error connecting to Plex server.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'localhost' doesn't match '*.448f523e13a741d8a2a6df0eb2238e14.plex.direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'localhost' doesn't match '*.448f523e13a741d8a2a6df0eb2238e14.plex.direct'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/redacted_user/sickbeard_mp4_automator/autoprocess/plex.py", line 88, in getPlexServer
    plex = PlexServer(protocol + settings.Plex.get('host') + ':' + str(settings.Plex.get('port')), settings.Plex.get('token'), session=session)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'localhost' doesn't match '*.448f523e13a741d8a2a6df0eb2238e14.plex.direct'")))
2023-04-22 19:10:55 - resources.mediaprocessor - INFO - Checking if any sections contain the path /Volumes/media/video/tv-series/The TV Show/Season 01.
2023-04-22 19:10:55 - resources.mediaprocessor - ERROR - Unable to establish Plex server connection.
`

**Comment by cryo-kronos** [comment]
Strangely, Plex Media Server does update the library after mp4_automator runs and processes the video but there are errors in the logs. In Sonarr, I have two active "Connect" connections: postSonarr and PMS Library Update.

**Comment by mdhiggins** [comment]
Sorry was out of town

Looking at the logs, your Plex script is still trying to connect via the localhost and port, and localhost isn't a valid https address hence the failure

It should be trying to connect using your username, servername, and token if provided but there's nothing in the logs indicating that was attempted. Do you have those parameters included in autoProcess.ini? All 3 are required

I would make sure you have the `username` `servername` and `token` parameters all filled out so that it can use the HTTPS compatible auth

**Comment by cryo-kronos** [comment]
> Sorry was out of town
> 
> Looking at the logs, your Plex script is still trying to connect via the localhost and port, and localhost isn't a valid https address hence the failure
> 
> It should be trying to connect using your username, servername, and token if provided but there's nothing in the logs indicating that was attempted. Do you have those parameters included in autoProcess.ini? All 3 are required
> 
> I would make sure you have the `username` `servername` and `token` parameters all filled out so that it can use the HTTPS compatible auth (password not required)

It's working now. Thank you.

I wasn't using "username" because I had previously tested it with a username and still got the error.

This time I reset my Plex token AND changed my username name and servername and now it seems to be working properly.
