### ISSUE TITLE
Conversion failed! error

### ISSUE THREAD

**Issue by jakanaka** [mdhiggins/sickbeard_mp4_automator#1661]
**Describe the bug**
Convert failed

**Command or context you are trying to run**
I am trying to convert h265 mkv to h264 mp4

**autoProcess.ini settings**
***Please sensor API keys/private information but include all other settings***

**Log files**
```
Processing file D:\temp\Dororo (2019) [tvdbid-354167]\S01\Dororo (2019) - S01E24 - 1080p.mkv
Input Data
{
    "format": "matroska,webm",
    "format-fullname": "Matroska / WebM",
    "video": {
        "index": 0,
        "codec": "hevc",
        "bitrate": 2032964,
        "pix_fmt": "yuv420p10le",
        "profile": "main10",
        "fps": 23.976023976023978,
        "framedata": {
            "pix_fmt": "yuv420p10le",
            "color_space": "bt709",
            "color_primaries": "bt709",
            "color_transfer": "bt709",
            "side_data_list": [
                {
                    "side_data_type": "H.26[45] User Data Unregistered SEI message"
                },
                {
                    "side_data_type": "H.26[45] User Data Unregistered SEI message"
                }
            ]
        },
        "dimensions": "1920x1080",
        "level": 4.1,
        "field_order": "unknown"
    },
    "audio": [
        {
            "index": 1,
            "codec": "aac",
            "bitrate": 256000,
            "channels": 2,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 2,
            "codec": "eac3",
            "bitrate": 224000,
            "channels": 2,
            "samplerate": 48000,
            "language": "jpn",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        }
    ],
    "subtitle": [
        {
            "index": 3,
            "codec": "ass",
            "bitrate": 85686,
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "eng"
        },
        {
            "index": 4,
            "codec": "ass",
            "bitrate": 83559,
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "eng"
        }
    ],
    "attachment": [
        {
            "index": 6,
            "codec": "ttf",
            "filename": "lt_1.ttf",
            "mimetype": "application/x-truetype-font"
        },
        {
            "index": 7,
            "codec": "ttf",
            "filename": "splatter.ttf",
            "mimetype": "application/x-truetype-font"
        },
        {
            "index": 8,
            "codec": "ttf",
            "filename": "annbrush.ttf",
            "mimetype": "application/x-truetype-font"
        },
        {
            "index": 9,
            "codec": "otf",
            "filename": "arnopro-regular.otf",
            "mimetype": "application/vnd.ms-opentype"
        },
        {
            "index": 10,
            "codec": "ttf",
            "filename": "junge-regular.ttf",
            "mimetype": "application/x-truetype-font"
        },
        {
            "index": 11,
            "codec": "ttf",
            "filename": "learningtotrust.ttf",
            "mimetype": "application/x-truetype-font"
        },
        {
            "index": 12,
            "codec": "ttf",
            "filename": "levirebrushed.ttf",
            "mimetype": "application/x-truetype-font"
        }
    ]
}
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p10le.
Profile: main10.
Pix-fmt adjusted to yuv420p in order to maintain compatible bit-depth <=8.
Video codec parameters None.
Creating h264_nvenc video stream from source stream 0.
Reading audio streams.
The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
Audio detected for stream 1 - aac eng 2 channel.
Creating aac audio stream from source stream 1.
Audio detected for stream 2 - eac3 jpn 2 channel.
Creating aac audio stream from source stream 2.
Found 0 streams that can be removed from the output file since they will be duplicates [stream-codec-combinations].
Final sorting:
['0->0', '1->1']
Final sorting:
['0->0', '1->1']
Default audio stream set to eng aac 2 channel stream [audio-default-sorting: ['channels.d', 'map', 'd.comment']].
Reading subtitle streams.
Subtitle detected for stream 3 - ass eng.

Stream 3 is text-based subtitle for codec ass.
Creating mov_text subtitle stream from source stream 3.
Subtitle detected for stream 4 - ass eng.

Stream 4 is text-based subtitle for codec ass.
Creating mov_text subtitle stream from source stream 4.
Attempting to download subtitles.
Scanned for external subtitles and found 0 results in your approved languages.
Final sorting:
['0->0', '1->1']
hevc_cuvid decoder is supported by this ffmpeg build and will also be used [hwaccel-decoders].
Output Data
{
    "source": [
        "D:\\temp\\Dororo (2019) [tvdbid-354167]\\S01\\Dororo (2019) - S01E24 - 1080p.mkv"
    ],
    "format": "mp4",
    "video": {
        "codec": "h264_nvenc",
        "map": 0,
        "bitrate": 2032.964,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": "high",
        "preset": "slow",
        "pix_fmt": "yuv420p",
        "field_order": "unknown",
        "width": null,
        "filter": null,
        "params": null,
        "framedata": null,
        "bsf": null,
        "debug": "video.profile",
        "title": "FHD"
    },
    "audio": [
        {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 160,
            "profile": null,
            "quality": 0,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "bsf": null,
            "debug": "audio",
            "title": "Stereo"
        },
        {
            "map": 2,
            "codec": "aac",
            "channels": 2,
            "bitrate": 160,
            "profile": null,
            "quality": 0,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "jpn",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "bsf": null,
            "debug": "audio",
            "title": "Stereo"
        }
    ],
    "subtitle": [
        {
            "map": 3,
            "codec": "mov_text",
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "debug": "subtitle.embed-subs",
            "title": null
        },
        {
            "map": 4,
            "codec": "mov_text",
            "language": "eng",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "debug": "subtitle.embed-subs",
            "title": null
        }
    ],
    "attachment": []
}
Preopts
[
    "-fix_sub_duration",
    "-vcodec",
    "hevc_cuvid"
]
Postopts
[
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
Downloaded Subtitles
[]
Starting conversion.

FFmpeg command:
======================
C:\utils\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -vcodec hevc_cuvid -i "D:\temp\Dororo (2019) [tvdbid-354167]\S01\Dororo (2019) - S01E24 - 1080p.mkv" -vcodec h264_nvenc -map 0:0 -pix_fmt yuv420p -vb 2032k -metadata:s:v BPS=2032000 -metadata:s:v BPS-eng=2032000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset slow -profile:v high -tag:v avc1 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 160k -metadata:s:a:0 BPS=160000 -metadata:s:a:0 BPS-eng=160000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:a:1 aac -map 0:2 -ac:a:1 2 -b:a:1 160k -metadata:s:a:1 BPS=160000 -metadata:s:a:1 BPS-eng=160000 -metadata:s:a:1 title=Stereo -metadata:s:a:1 handler_name=Stereo -metadata:s:a:1 language=jpn -disposition:a:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 0:3 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:1 mov_text -map 0:4 -metadata:s:s:1 title= -metadata:s:s:1 handler_name= -metadata:s:s:1 language=eng -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -strict -2 -y "d:\temp\Dororo (2019) - S01E24 - 1080p.tmp"
======================
[#                   ] 3% Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\utils\sickbeard_mp4_automator2\resources\mediaprocessor.py", line 2314, in convert
    for timecode, debug in conv:
  File "C:\utils\sickbeard_mp4_automator2\converter\__init__.py", line 329, in convert
    for timecode, debug in self.ffmpeg.convert(outfile,
  File "C:\utils\sickbeard_mp4_automator2\converter\ffmpeg.py", line 795, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <exception str() failed>
C:\utils\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -vcodec hevc_cuvid -i D:\temp\Dororo (2019) [tvdbid-354167]\S01\Dororo (2019) - S01E24 - 1080p.mkv -vcodec h264_nvenc -map 0:0 -pix_fmt yuv420p -vb 2032k -metadata:s:v BPS=2032000 -metadata:s:v BPS-eng=2032000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset slow -profile:v high -tag:v avc1 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 160k -metadata:s:a:0 BPS=160000 -metadata:s:a:0 BPS-eng=160000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:a:1 aac -map 0:2 -ac:a:1 2 -b:a:1 160k -metadata:s:a:1 BPS=160000 -metadata:s:a:1 BPS-eng=160000 -metadata:s:a:1 title=Stereo -metadata:s:a:1 handler_name=Stereo -metadata:s:a:1 language=jpn -disposition:a:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 0:3 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:1 mov_text -map 0:4 -metadata:s:s:1 title= -metadata:s:s:1 handler_name= -metadata:s:s:1 language=eng -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -strict -2 -y d:\temp\Dororo (2019) - S01E24 - 1080p.tmp
ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[extract_extradata @ 000001ebbe8b9640] Invalid NAL unit 42, skipping.
[extract_extradata @ 000001ebbe8b9640] Invalid NAL unit 16, skipping.
[extract_extradata @ 000001ebbe8b9640] Invalid NAL unit 35, skipping.
[extract_extradata @ 000001ebbe8b9640] Invalid NAL unit 0, skipping.
    Last message repeated 2 times
[extract_extradata @ 000001ebbe8b9640] Invalid NAL unit 16, skipping.
[extract_extradata @ 000001ebbe8b9640] Invalid NAL unit 0, skipping.
    Last message repeated 1 times
[hevc @ 000001ebbe9725c0] Invalid NAL unit 42, skipping.
[hevc @ 000001ebbe9725c0] Invalid NAL unit 16, skipping.
[hevc @ 000001ebbe9725c0] Invalid NAL unit 35, skipping.
[hevc @ 000001ebbe9725c0] Invalid NAL unit 0, skipping.
    Last message repeated 2 times
[hevc @ 000001ebbe9725c0] Invalid NAL unit 16, skipping.
[hevc @ 000001ebbe9725c0] Invalid NAL unit 0, skipping.
    Last message repeated 1 times
[hevc @ 000001ebbe9725c0] PPS id out of range: 1
[hevc @ 000001ebbe9725c0] Error parsing NAL unit #4.
[matroska,webm @ 000001ebbe8e4ec0] Could not find codec parameters for stream 5 (Video: hevc, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'D:\temp\Dororo (2019) [tvdbid-354167]\S01\Dororo (2019) - S01E24 - 1080p.mkv':
  Metadata:
    title           : S01E24-EMBER
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-07-30T19:31:16.000000Z
  Duration: 00:23:46.59, start: 0.000000, bitrate: 2871 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 51.927000
      Metadata:
        title           : Chapter 1
    Chapter #0:1: start 51.927000, end 142.017000
      Metadata:
        title           : Chapter 2
    Chapter #0:2: start 142.017000, end 856.022000
      Metadata:
        title           : Chapter 3
    Chapter #0:3: start 856.022000, end 1331.038000
      Metadata:
        title           : Chapter 4
    Chapter #0:4: start 1331.038000, end 1421.045000
      Metadata:
        title           : Chapter 5
    Chapter #0:5: start 1421.045000, end 1426.425000
      Metadata:
        title           : Chapter 6
    Chapter #0:6: start 1426.425000, end 1516.515000
      Metadata:
        title           : Chapter 7
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      title           : Presented By EMBER
      BPS             : 2032964
      DURATION        : 00:23:46.592000000
      NUMBER_OF_FRAMES: 34204
      NUMBER_OF_BYTES : 362526280
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      BPS             : 256000
      DURATION        : 00:23:45.322000000
      NUMBER_OF_FRAMES: 66812
      NUMBER_OF_BYTES : 45610326
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(jpn): Audio: eac3, 48000 Hz, stereo, fltp, 224 kb/s
    Metadata:
      title           : ER
      BPS             : 224000
      DURATION        : 00:23:45.056000000
      NUMBER_OF_FRAMES: 44533
      NUMBER_OF_BYTES : 39901568
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: ass (default)
    Metadata:
      title           : Signs & Songs@EMBER
      BPS             : 85686
      DURATION        : 00:22:54.080000000
      NUMBER_OF_FRAMES: 1020
      NUMBER_OF_BYTES : 14717473
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(eng): Subtitle: ass
    Metadata:
      title           : Dialogue@GSK
      BPS             : 83559
      DURATION        : 00:23:30.280000000
      NUMBER_OF_FRAMES: 1259
      NUMBER_OF_BYTES : 14730218
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5: Video: hevc, none, 90k tbr, 90k tbn (attached pic)
    Metadata:
      filename        : cover.png
      mimetype        : image/png
  Stream #0:6: Attachment: ttf
    Metadata:
      filename        : LT_1.TTF
      mimetype        : application/x-truetype-font
  Stream #0:7: Attachment: ttf
    Metadata:
      filename        : SPLATTER.TTF
      mimetype        : application/x-truetype-font
  Stream #0:8: Attachment: ttf
    Metadata:
      filename        : ANNBRUSH.TTF
      mimetype        : application/x-truetype-font
  Stream #0:9: Attachment: otf
    Metadata:
      filename        : ArnoPro-Regular.otf
      mimetype        : application/vnd.ms-opentype
  Stream #0:10: Attachment: ttf
    Metadata:
      filename        : JUNGE-REGULAR.TTF
      mimetype        : application/x-truetype-font
  Stream #0:11: Attachment: ttf
    Metadata:
      filename        : LEARNINGTOTRUST.TTF
      mimetype        : application/x-truetype-font
  Stream #0:12: Attachment: ttf
    Metadata:
      filename        : LeviReBrushed.ttf
      mimetype        : application/x-truetype-font
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_cuvid) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
  Stream #0:2 -> #0:2 (eac3 (native) -> aac (native))
  Stream #0:3 -> #0:3 (ass (ssa) -> mov_text (native))
  Stream #0:4 -> #0:4 (ass (ssa) -> mov_text (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'd:\temp\Dororo (2019) - S01E24 - 1080p.tmp':
  Metadata:
    title           : S01E24-EMBER
    encoding_tool   : SMA
    encoder         : Lavf60.3.100
  Chapters:
    Chapter #0:0: start 0.000000, end 51.927000
      Metadata:
        title           : Chapter 1
    Chapter #0:1: start 51.927000, end 142.017000
      Metadata:
        title           : Chapter 2
    Chapter #0:2: start 142.017000, end 856.022000
      Metadata:
        title           : Chapter 3
    Chapter #0:3: start 856.022000, end 1331.038000
      Metadata:
        title           : Chapter 4
    Chapter #0:4: start 1331.038000, end 1421.045000
      Metadata:
        title           : Chapter 5
    Chapter #0:5: start 1421.045000, end 1426.425000
      Metadata:
        title           : Chapter 6
    Chapter #0:6: start 1426.425000, end 1516.515000
      Metadata:
        title           : Chapter 7
  Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 2032 kb/s, 23.98 fps, 24k tbn (default)
    Metadata:
      BPS-eng         : 2032000
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:23:46.592000000
      NUMBER_OF_FRAMES: 34204
      NUMBER_OF_BYTES : 362526280
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      BPS             : 2032000
      title           : FHD
      handler_name    : FHD
      encoder         : Lavc60.3.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/2032000 buffer size: 4064000 vbv_delay: N/A
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 160 kb/s (default)
    Metadata:
      handler_name    : Stereo
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:23:45.322000000
      NUMBER_OF_FRAMES: 66812
      NUMBER_OF_BYTES : 45610326
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      BPS             : 160000
      BPS-eng         : 160000
      title           : Stereo
      encoder         : Lavc60.3.100 aac
  Stream #0:2(jpn): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 160 kb/s
    Metadata:
      handler_name    : Stereo
      BPS-eng         : 160000
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 00:23:45.056000000
      NUMBER_OF_FRAMES: 44533
      NUMBER_OF_BYTES : 39901568
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      BPS             : 160000
      title           : Stereo
      encoder         : Lavc60.3.100 aac
  Stream #0:3(eng): Subtitle: mov_text (tx3g / 0x67337874) (default)
    Metadata:
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS             : 85686
      DURATION        : 00:22:54.080000000
      NUMBER_OF_FRAMES: 1020
      NUMBER_OF_BYTES : 14717473
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      encoder         : Lavc60.3.100 mov_text
  Stream #0:4(eng): Subtitle: mov_text (tx3g / 0x67337874)
    Metadata:
      _STATISTICS_WRITING_DATE_UTC: 2021-07-30 19:31:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS             : 83559
      DURATION        : 00:23:30.280000000
      NUMBER_OF_FRAMES: 1259
      NUMBER_OF_BYTES : 14730218
      _STATISTICS_WRITING_APP: mkvmerge v57.0.0 ('Till The End') 64-bit
      encoder         : Lavc60.3.100 mov_text
[sost#0:3/mov_text @ 000001ebc118a980] Subtitle encoding failedrate=1803.8kbits/s speed=3.63x
[aac @ 000001ebc0fae9c0] Qavg: 841.987
[aac @ 000001ebc0fae9c0] 2 frames left in the queue on closing
[aac @ 000001ebc0fb11c0] Qavg: 2096.504
[aac @ 000001ebc0fb11c0] 2 frames left in the queue on closing
Conversion failed!

d:\temp\Dororo (2019) - S01E24 - 1080p.tmp deleted
```

**FFMpeg headers**
Run ffmpeg and post the headers, example [headers]https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/FFMPEG-Headers

**System Information**
 - OS:  Windows
 - Python version Python 3.11.2
 - Docker config (if relevant)

**Expected behavior**

**Additional context**

*Issues posted without any logs or autoProcess settings will be closed*

**Comment by jakanaka** [comment]
i've clean it turned off. might be related to subtitle ?

**Comment by mdhiggins** [comment]
Try adding

postopts= -probesize, 50M, -analyzeduration, 100M, -max_muxing_queue_size, 9999
