### ISSUE TITLE
UnboundLocalError: local variable 'dirName' referenced before assignment

### ISSUE THREAD

**Issue by nogardvfx** [mdhiggins/sickbeard_mp4_automator#1672]
**Describe the bug**
After a TV show is finished converting and is about to send the file to the proper location I get the following error:
UnboundLocalError: local variable 'dirName' referenced before assignment.

**Command or context you are trying to run**
I am using Sickgear (attaching log).  Here is the error I get in SabNZBD
***************************************************************************************************************
2023-08-28 04:07:39 - SABPostProcess - INFO - SAB post processing started.
2023-08-28 04:07:39 - resources.readsettings - INFO - /usr/bin/python3
2023-08-28 04:07:39 - resources.readsettings - INFO - Loading config file /usr/serverApps/sabScripts/config/autoProcess.ini.
2023-08-28 04:07:39 - SABPostProcess - INFO - Performing conversion
2023-08-28 04:07:58 - SABPostProcess - INFO - Processing file /mnt/entHDD6/Downloads/Complete/60.Minutes.S55E52.1080p.WEB.H264-BAE/RPxXvedQtKMoZHn2F82O5b0Hc.mkv.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Input Data
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - {
"format": "matroska,webm",
"format-fullname": "Matroska / WebM",
"video": {
"index": 0,
"codec": "h264",
"bitrate": 2883381,
"pix_fmt": "yuv420p",
"profile": "high",
"fps": 29.97002997002997,
"framedata": {
"pix_fmt": "yuv420p",
"color_space": "bt709",
"color_primaries": "bt709",
"color_transfer": "bt709"
},
"dimensions": "1920x1080",
"level": 4.0,
"field_order": "progressive"
},
"audio": [
{
"index": 1,
"codec": "aac",
"bitrate": 124683,
"channels": 2,
"samplerate": 48000,
"language": "eng",
"disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired"
}
],
"subtitle": [
{
"index": 2,
"codec": "subrip",
"disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
"language": "eng"
}
],
"attachment": []
}
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Reading video stream.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Video codec detected: h264.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Pix Fmt: yuv420p.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Profile: high.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Video codec parameters None.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Creating h265 video stream from source stream 0.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Reading audio streams.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Audio detected for stream 1 - aac eng 2 channel.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Creating copy audio stream from source stream 1.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Found 0 streams that can be removed from the output file since they will be duplicates [stream-codec-combinations].
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Final sorting:
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - ['0->0']
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Final sorting:
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - ['0->0']
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Default audio stream set to eng copy 2 channel stream [audio-default-sorting: ['channels.d', 'map', 'd.comment']].
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Reading subtitle streams.
2023-08-28 04:07:58 - resources.mediaprocessor - INFO - Subtitle detected for stream 2 - subrip eng.

2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Stream 2 is text-based subtitle for codec subrip.
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream from source stream 2.
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Attempting to download subtitles.
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 0 results in your approved languages.
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Final sorting:
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - ['0->0']
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Output Data
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - {
"source": [
"/mnt/entHDD6/Downloads/Complete/60.Minutes.S55E52.1080p.WEB.H264-BAE/RPxXvedQtKMoZHn2F82O5b0Hc.mkv"
],
"format": "mp4",
"video": {
"codec": "h265",
"map": 0,
"bitrate": 2741.8633999999997,
"crf": 23,
"maxrate": null,
"bufsize": null,
"level": 0.0,
"profile": null,
"preset": "medium",
"pix_fmt": "yuv420p10le",
"field_order": "progressive",
"width": null,
"filter": null,
"params": null,
"framedata": null,
"bsf": null,
"debug": "video.pix_fmt",
"title": "FHD"
},
"audio": [
{
"map": 1,
"codec": "copy",
"channels": 2,
"bitrate": 256,
"profile": null,
"quality": 0,
"filter": null,
"samplerate": null,
"sampleformat": "",
"language": "eng",
"disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
"bsf": null,
"debug": "universal-audio",
"title": "Stereo"
}
],
"subtitle": [
{
"map": 2,
"codec": "mov_text",
"language": "eng",
"disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired",
"debug": "subtitle.embed-subs",
"title": null
}
],
"attachment": []
}
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Preopts
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - [
"-fix_sub_duration"
]
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Postopts
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - [
"-threads",
"0",
"-metadata:g",
"encoding_tool=SMA"
]
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Downloaded Subtitles
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - []
2023-08-28 04:07:59 - resources.mediaprocessor - INFO - Starting conversion.

2023-08-28 04:08:00 - resources.mediaprocessor - INFO - FFmpeg command:
2023-08-28 04:08:00 - resources.mediaprocessor - INFO - ======================
2023-08-28 04:08:00 - resources.mediaprocessor - INFO - /usr/bin/ffmpeg -fix_sub_duration -i /mnt/entHDD6/Downloads/Complete/60.Minutes.S55E52.1080p.WEB.H264-BAE/RPxXvedQtKMoZHn2F82O5b0Hc.mkv -vcodec libx265 -map 0:0 -pix_fmt yuv420p10le -field_order progressive -crf 23 -metadata:s:v BPS=2741000 -metadata:s:v BPS-eng=2741000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset medium -tag:v hvc1 -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 mov_text -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /mnt/entHDD6/Downloads/Complete/60.Minutes.S55E52.1080p.WEB.H264-BAE/RPxXvedQtKMoZHn2F82O5b0Hc.mp4
2023-08-28 04:08:00 - resources.mediaprocessor - INFO - ======================
0%
<skipping all of this>
100%
2023-08-28 05:00:32 - resources.mediaprocessor - INFO - /mnt/entHDD6/Downloads/Complete/60.Minutes.S55E52.1080p.WEB.H264-BAE/RPxXvedQtKMoZHn2F82O5b0Hc.mp4 created.
2023-08-28 05:00:32 - SABPostProcess - INFO - Successfully processed /mnt/entHDD6/Downloads/Complete/60.Minutes.S55E52.1080p.WEB.H264-BAE/RPxXvedQtKMoZHn2F82O5b0Hc.mkv.
2023-08-28 05:00:34 - SABPostProcess - INFO - Passing /mnt/entHDD6/Downloads/Complete/60.Minutes.S55E52.1080p.WEB.H264-BAE directory to Sickrage.
2023-08-28 05:00:34 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "/usr/serverApps/sabScripts/SABPostProcess.py", line 98, in <module>
autoProcessTVSR.processEpisode(path, settings, nzb, pathMapping=path_mapping)
File "/usr/serverApps/sabScripts/autoprocess/autoProcessTVSR.py", line 20, in processEpisode
targetdirs = dirName.split(os.sep)
UnboundLocalError: local variable 'dirName' referenced before assignment
*****************************************************************************************************************************

**autoProcess.ini settings**
Attached below

**Log files**
I have included the log file for the day.  I hope that is ok?

**FFMpeg headers**
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**System Information**
 - OS: Ubuntu 20.04.6 LTS x86_64
 - Python version: Python 3.8.10
 - Docker config (if relevant): NA

**Expected behavior**
After the "60.Minutes.S55E52.1080p" is converted to h265, I am expecting it to be copied to the proper drive and 60 minutes folder.  Looks like there is an communication issue(?) after the conversion and being sent back to Sickgear.  I will say, I just upgraded to the latest version.  The previous version I was using, which worked, was from July 2021.  Only reason I switched was due to some issues I had converting HDR files to H265 (but that works perfect now).  I love the program and has become a standard on my server.  Thank you so much.

Let me know if there is anything else I can provide.

[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12454400/autoProcess.txt)
[sickgear.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/12454421/sickgear.zip)

**Comment by nogardvfx** [comment]
Changed some setting, getting  anew issues.  Will post.

**Comment by mdhiggins** [comment]
096e258738cadebc693ae37a0c7d76f766e88d60

This should fix that exception
