### ISSUE TITLE
Keep all audio in sonarr radarr post process

### ISSUE THREAD

**Issue by jakanaka** [mdhiggins/sickbeard_mp4_automator#1686]
**Describe the bug**
I want to keep all the audio track of a file in sonarr radarr post process. Supposes i have 3 audio tracks in the file. Sometimes 1 is kept, sometime 2 sometimes all. Many torrent i use does not level torrent as dual audio. I am not sure how the post process is selecting the tracks. Probably following the sonarr radarr config. I want keep all audio regardless of config, like it does with manual run

**Command or context you are trying to run**
Sonarrr Radarr post process

**autoProcess.ini settings**

```
[Converter]
ffmpeg = ffmpeg.exe
ffprobe = ffprobe.exe
threads = 0
hwaccels = 
hwaccel-decoders = hevc_cuvid, h264_cuda, hevc_cuda, h264_cuvid
hwdevices = 
hwaccel-output-format = cuda:cuda
output-directory =  <reducted>
output-directory-space-ratio = 0.0
output-format = mp4
output-extension = mp4
temp-extension = tmp
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
process-same-extensions = False
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = False
full-path-guess = False
tag = False
tag-language = eng
download-artwork = poster
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = h264_nvenc, x264, h264
max-bitrate = 3560
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = slow
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = high
max-level = 0.0
pix-fmt = 
prioritize-source-pix-fmt = True
filter = 
force-filter = False

[HDR]
codec = 
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = high
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = aac
languages = 
default-language = eng
include-original-language = True
first-stream-of-language = False
channel-bitrate = 256
variable-bitrate = 0
max-bitrate = 256
max-channels = 2
filter = 
profile = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
aac-adtstoasc = False
ignored-dispositions = 
force-default = True
unique-dispositions = False
stream-codec-combinations = 

[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs = 

[Universal Audio]
codec = 
channel-bitrate = 256
variable-bitrate = 0
first-stream-only = True
filter = 
profile = 
force-filter = False

[Audio.ChannelFilters]

[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
include-original-language = False
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
force-default = False
unique-dispositions = False
attachment-codec = 
remove-bitstream-subs = False

[Subtitle.Sorting]
sorting = language, d.comment, d.default.d, d.forced.d
codecs = 
burn-sorting = language, d.comment, d.default.d, d.forced.d

[Subtitle.CleanIt]
enabled = False
config-path = 
tags = 

[Subtitle.FFSubsync]
enabled = True

[Subtitle.Subliminal]
download-subs = True
download-forced-subs = False
include-hearing-impaired-subs = False
providers = 

[Subtitle.Subliminal.Auth]
opensubtitles =  <reducted>

[Sonarr]
host = localhost
port =  <reducted>
apikey =  <reducted>
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = True
in-progress-check = True

[Radarr]
host = localhost
port =  <reducted>
apikey =  <reducted>
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = True
in-progress-check = True

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username =  <reducted>
password =  <reducted>
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port =  <reducted>
ssl = False
username = <reducted>
password =  <reducted>
output-directory = 
path-mapping = 

[uTorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8182
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token = 
username = 
password = 
servername = 
ssl = True
ignore-certs = False
path-mapping = 

```

**Log files**
Include log files *for the specific job (not just a dump of all your logs for the past month)* that's causing the issue. Please turn on [debug level logging](https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging)
Log files are found in your script root config folder `./sma/config/sma.log`

**FFMpeg headers**
Run ffmpeg and post the headers, example [headers]https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/FFMPEG-Headers

**System Information**
 - OS: [e.g. Windows]
 - Python version
 - Docker config (if relevant)

**Expected behavior**

**Additional context**

*Issues posted without any logs or autoProcess settings will be closed*

**Comment by jakanaka** [comment]
> aac audio is selected, if you want the script to keep other audio tracks replace aac with `copy` or audio1, audio2, Audio3, and you also have eng set as language
> 
> ```
> [Audio]
> codec = aac, eac3
> languages = 
> default-language = 
> include-original-language = True
> first-stream-of-language = False
> channel-bitrate = 256
> variable-bitrate = 0
> max-bitrate = 256
> max-channels = 2
> filter = 
> profile = 
> force-filter = False
> sample-rates = 
> sample-format = 
> copy-original = False
> aac-adtstoasc = False
> ignored-dispositions = 
> force-default = True
> unique-dispositions = False
> stream-codec-combinations = 
> 
> [Audio.Sorting]
> sorting = language, channels.d, map, d.comment
> default-sorting = channels.d, map, d.comment
> codecs = 
> ```

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/AutoProcess-Settings#audio

according to the wiki, 


codec | csv | ac3 | Approved audio codecs. Codecs not on this list are converted to the first codec on the list
-- | -- | -- | --

languages | csv |   | Approved audio stream languages. Languages not on this list will not be used. Leave blank to approve all languages
-- | -- | -- | --


default-language | str |   | If audio stream language is undefined, assumed this language
-- | -- | -- | --



so my

```
codec = aac
languages = 
default-language = eng
```

setting should catch all audios

**Comment by jakanaka** [comment]
@mdhiggins sir, can you help me with this? this problem only occurs on the post processing. it works fine if added manually

**Comment by mdhiggins** [comment]
There is no difference between manual and postSonarr/postRadarr they all use the same functions to perform the conversion. Post some logs of conversions not behaving as expected if you want further assistance 

The codec is irrelevant though the only thing that would not include an audio track from source material would be language or ignore-disposition settings but this behavior is not different across the various scripts. They all point to mediaprocessor.py

**Comment by jakanaka** [comment]
> There is no difference between manual and postSonarr/postRadarr they all use the same functions to perform the conversion. Post some logs of conversions not behaving as expected if you want further assistance
> 
> The codec is irrelevant though the only thing that would not include an audio track from source material would be language or ignore-disposition settings but this behavior is not different across the various scripts. They all point to mediaprocessor.py

Yes, i have take a look at the mediaprocessor.py file. They all seem to call it. 


Here is the log from the sonarr post process. The error related to to the ffsubsyc is related to https://github.com/mdhiggins/sickbeard_mp4_automator/blob/ced493e63fcc32f353e76d9d8fe14398eb703770/resources/mediaprocessor.py#L1817 , making it ".sync.srt" solves the issue

```
2023-11-03 21:46:04 - SonarrPostProcess - INFO - Sonarr extra script post processing started.
2023-11-03 21:46:04 - resources.readsettings - INFO - C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe
2023-11-03 21:46:04 - resources.readsettings - INFO - Loading config file C:\utils\sickbeard_mp4_automator\config\autoProcess.ini.
2023-11-03 21:46:05 - resources.mediaprocessor - INFO - Processing K:\TV\Scam 2003 - The Telgi Story (2023) [tvdbid-436591]\S01\Scam 2003 - The Telgi Story - S01E09 - 1080p.mkv.
2023-11-03 21:46:05 - resources.metadata - ERROR - Unable to retrieve rating.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Input Data
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - {
    "format": "matroska,webm",
    "format-fullname": "Matroska / WebM",
    "video": {
        "index": 0,
        "codec": "h264",
        "bitrate": 3190407,
        "pix_fmt": "yuvj420p",
        "profile": "main",
        "fps": 25.0,
        "framedata": {
            "pix_fmt": "yuvj420p",
            "color_space": "bt709",
            "color_primaries": "bt709",
            "color_transfer": "bt709",
            "side_data_list": [
                {
                    "side_data_type": "H.26[45] User Data Unregistered SEI message"
                }
            ]
        },
        "dimensions": "1920x1080",
        "level": 4.0,
        "field_order": "progressive"
    },
    "audio": [
        {
            "index": 1,
            "codec": "eac3",
            "bitrate": 448000,
            "channels": 6,
            "samplerate": 48000,
            "language": "hin",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 2,
            "codec": "eac3",
            "bitrate": 256000,
            "channels": 6,
            "samplerate": 48000,
            "language": "ben",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 3,
            "codec": "eac3",
            "bitrate": 256000,
            "channels": 6,
            "samplerate": 48000,
            "language": "guj",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 4,
            "codec": "eac3",
            "bitrate": 256000,
            "channels": 6,
            "samplerate": 48000,
            "language": "kan",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 5,
            "codec": "eac3",
            "bitrate": 256000,
            "channels": 6,
            "samplerate": 48000,
            "language": "mal",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 6,
            "codec": "eac3",
            "bitrate": 256000,
            "channels": 6,
            "samplerate": 48000,
            "language": "mar",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 7,
            "codec": "eac3",
            "bitrate": 256000,
            "channels": 6,
            "samplerate": 48000,
            "language": "tam",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        },
        {
            "index": 8,
            "codec": "eac3",
            "bitrate": 256000,
            "channels": 6,
            "samplerate": 48000,
            "language": "tel",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        }
    ],
    "subtitle": [
        {
            "index": 9,
            "codec": "subrip",
            "disposition": "-default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "eng"
        }
    ],
    "attachment": [
        {
            "index": 11,
            "codec": "unknown",
            "filename": "kodi-metadata",
            "mimetype": "application/xml"
        }
    ]
}
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Reading video stream.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Video codec detected: h264.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Pix Fmt: yuvj420p.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Profile: main.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Video codec parameters None.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Creating h264_nvenc video stream from source stream 0.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Reading audio streams.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Audio detected for stream 1 - eac3 hin 6 channel.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Creating aac audio stream from source stream 1.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Audio detected for stream 2 - eac3 ben 6 channel.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Audio detected for stream 3 - eac3 guj 6 channel.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Audio detected for stream 4 - eac3 kan 6 channel.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Audio detected for stream 5 - eac3 mal 6 channel.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Audio detected for stream 6 - eac3 mar 6 channel.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Audio detected for stream 7 - eac3 tam 6 channel.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Audio detected for stream 8 - eac3 tel 6 channel.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Found 0 streams that can be removed from the output file since they will be duplicates [stream-codec-combinations].
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Final sorting:
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - ['0->0']
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Final sorting:
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - ['0->0']
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Default audio stream set to hin aac 2 channel stream [audio-default-sorting: ['channels.d', 'map', 'd.comment']].
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Reading subtitle streams.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Subtitle detected for stream 9 - subrip eng.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Stream 9 is text-based subtitle for codec subrip.
2023-11-03 21:46:06 - resources.mediaprocessor - INFO - Ripping eng subtitle from source stream 9 into external file.
2023-11-03 21:46:10 - resources.mediaprocessor - INFO - D:\temp\Scam 2003 - The Telgi Story - S01E09 - 1080p.eng.srt created.
2023-11-03 21:46:10 - resources.mediaprocessor - INFO - Subtitle D:\temp\Scam 2003 - The Telgi Story - S01E09 - 1080p.eng.srt extracted for cleaning/syncing [subtitles.cleanit, subtitles.ffsubsync].
2023-11-03 21:46:13 - resources.mediaprocessor - ERROR - Exception syncing subtitle D:\temp\Scam 2003 - The Telgi Story - S01E09 - 1080p.eng.srt.
Traceback (most recent call last):
  File "C:\utils\sickbeard_mp4_automator\resources\mediaprocessor.py", line 1823, in syncExternalSub
    result = ffsubsync.run(self.args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\ffsubsync\ffsubsync.py", line 509, in run
    sync_was_successful = _run_impl(args, result)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\ffsubsync\ffsubsync.py", line 458, in _run_impl
    return try_sync(args, reference_pipe, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\ffsubsync\ffsubsync.py", line 225, in try_sync
    raise exc
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\ffsubsync\ffsubsync.py", line 207, in try_sync
    out_subs.write_file(srtout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\ffsubsync\generic_subtitles.py", line 159, in write_file
    raise NotImplementedError("unsupported output format: %s" % out_format)
NotImplementedError: unsupported output format: sync
2023-11-03 21:46:13 - resources.mediaprocessor - INFO - Attempting to download subtitles.
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - Scanned for external subtitles and found 1 results in your approved languages.
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - Creating mov_text subtitle stream by importing Text-based subtitle Scam 2003 - The Telgi Story - S01E09 - 1080p.eng.srt [embed-subs].
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - Final sorting:
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - ['0->0']
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - h264_cuvid decoder is supported by this ffmpeg build and will also be used [hwaccel-decoders].
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - Output Data
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - {
    "source": [
        "K:\\TV\\Scam 2003 - The Telgi Story (2023) [tvdbid-436591]\\S01\\Scam 2003 - The Telgi Story - S01E09 - 1080p.mkv",
        "D:\\temp\\Scam 2003 - The Telgi Story - S01E09 - 1080p.eng.srt"
    ],
    "format": "mp4",
    "video": {
        "codec": "h264_nvenc",
        "map": 0,
        "bitrate": 2560,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 0.0,
        "profile": "high",
        "preset": "slow",
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "framedata": null,
        "bsf": null,
        "debug": "video.max-bitrate.profile",
        "title": "FHD"
    },
    "audio": [
        {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 160,
            "profile": null,
            "quality": 0,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "hin",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "bsf": null,
            "debug": "audio.max-channels",
            "title": "Stereo"
        }
    ],
    "subtitle": [
        {
            "source": 1,
            "map": 0,
            "codec": "mov_text",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "eng",
            "debug": "subtitle.embed-subs",
            "title": null
        }
    ],
    "attachment": []
}
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - Preopts
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - [
    "-fix_sub_duration",
    "-vcodec",
    "h264_cuvid"
]
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - Postopts
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - Downloaded Subtitles
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - []
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - Starting conversion.
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - FFmpeg command:
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - ======================
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - C:\utils\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -vcodec h264_cuvid -i "K:\TV\Scam 2003 - The Telgi Story (2023) [tvdbid-436591]\S01\Scam 2003 - The Telgi Story - S01E09 - 1080p.mkv" -i "D:\temp\Scam 2003 - The Telgi Story - S01E09 - 1080p.eng.srt" -vcodec h264_nvenc -map 0:0 -field_order progressive -vb 2560k -metadata:s:v BPS=2560000 -metadata:s:v BPS-eng=2560000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset slow -profile:v high -tag:v avc1 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 160k -metadata:s:a:0 BPS=160000 -metadata:s:a:0 BPS-eng=160000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=hin -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:s:0 mov_text -map 1:0 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y "D:\temp\Scam 2003 - The Telgi Story - S01E09 - 1080p.tmp"
2023-11-03 21:46:15 - resources.mediaprocessor - INFO - ======================
2023-11-03 21:50:46 - resources.mediaprocessor - INFO - D:\temp\Scam 2003 - The Telgi Story - S01E09 - 1080p.tmp created.
2023-11-03 21:50:46 - resources.mediaprocessor - INFO - Output file is in output_dir D:\temp, moving back to original directory K:\TV\Scam 2003 - The Telgi Story (2023) [tvdbid-436591]\S01.
2023-11-03 21:50:47 - SonarrPostProcess - ERROR - Sonarr monitor status update failed.
Traceback (most recent call last):
  File "C:\utils\sickbeard_mp4_automator\postSonarr.py", line 260, in <module>
    inProcess = settings.Sonarr['in-progress-check'] and downloadedEpisodesScanInProgress(baseURL, headers, episodefile_sourcefolder, log)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\utils\sickbeard_mp4_automator\postSonarr.py", line 80, in downloadedEpisodesScanInProgress
    if c.get('name') == "DownloadedEpisodesScan":
       ^^^^^
AttributeError: 'str' object has no attribute 'get'

```

**Comment by mdhiggins** [comment]
Are you running manual.py with any command line parameters?

**Comment by mdhiggins** [comment]
So the issue here is most likely languages being filtered out based on your settings but I'm not sure why it would be different between the two scripts unless something is modifying the settings before it gets to mediaprocessor.py

Can you potentially re-run things from both sonarr and manual just like above with debug level logging enableed? (see the wiki for how to turn this on)

**Comment by mdhiggins** [comment]
Have you implemented a custom skipStream function?

**Comment by mdhiggins** [comment]
Custom functions aren't in the config file, hence the ask, I have looked at your config I'm not seeing anything obvious that should be causing it, I have a suspicion where the problem may be though I don't have an explanation for why it would be different between manual and postSonarr though so if you could post the debug logs that would help me narrow it down

**Comment by mdhiggins** [comment]
From your previous example logs, did you change any settings in between? Specifically did you modify the `include-original-language` setting by any chance?

**Comment by mdhiggins** [comment]
Think I found the problem, but I still don't have a reason for manual.py differing hence why I was asking if its possible you changed that one specific setting in between the previous tests

Can you run that same Loki episode through manual.py with debug logging and see if the result differs

**Comment by mdhiggins** [comment]
Figured it out

076bbdd39f26e586874165e018aee306386e4200 should fix it

This is a bug with the `include-original-language` option

This option looks at the tag data for the file to determine what the original language is and adds it to your language whitelist if its not there. Problem was I wasn't checking if the list was empty (in which case all languages get allowed) so it was  going from `[]` which would allow all languages to `['eng']` which only allowed english as a result of that option unintentionally

The final piece is that when you were running manual.py it looks like you were NOT tagging the file and thus not including the metadata (I can tell this from `2023-11-05 02:01:30 - MANUAL - INFO - Processing file Loki.S02E05.Science.Fiction.REPACK.1080p.WEB-DL.DUAL.DDP5.1.Atmos.H.264-AmarHSCookieNai.mkv` because if it had data it would say `"Processing %s Season %02d Episode %02d - %s"` . Because mediaprocessor.py didn't have any tagdata to use to determine the original language, that option was ignored and thus the bug was bypassed

Adding a simple check to make sure the language whitelist isn't empty before hand should fix it

**Comment by mdhiggins** [comment]
ff289e112fb46b8ca2e0dcbf79234a619ee51120 applies the same fix approach for subtitles

**Comment by mdhiggins** [comment]
1122cc3e7681c520debff4a307cfb40602243cb2

Like that?

Also not sure what that unrelated Sonarr error is

https://sonarr.tv/docs/api/#/Command/get_api_v3_command

Command shouldn't be returning a string but I adjust the exception catch

7477a8e3acdffcca1e7c596db2fe5bbdfadebe96
