### ISSUE TITLE
Error in postSonarr with recent Sonarr update (4.0.1.929 — Jan 19 2024)

### ISSUE THREAD

**Issue by JasonMeudt** [mdhiggins/sickbeard_mp4_automator#1699]
An issue/error was raised on the recent update of Sonarr to 4.0.1.929.

While I can grab  my settings, it does not appear to be any of my specific settings, but rather(?) an api difference/change in Sonarr?

`024-01-27 10:37:12 - SonarrPostProcess - ERROR - Sonarr monitor status update failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/data/git-clone/sickbeard_mp4_automator1/postSonarr.py", line 260, in <module>
    inProcess = settings.Sonarr['in-progress-check'] and downloadedEpisodesScanInProgress(baseURL, headers, episodefile_sourcefolder, log)
  File "/media/data/git-clone/sickbeard_mp4_automator1/postSonarr.py", line 76, in downloadedEpisodesScanInProgress
    commands = r.json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by mdhiggins** [comment]
Not seeing this error on my end, just pulled the latest version of sonarr and ran a test and everything worked fine

Might want to double check your API and see if its working manually, and if it is, then enable debug logging and post the output

**Comment by JasonMeudt** [comment]
> Might want to double check your API 

Thank you for the input and that is exactly the issue... Somehow (operator related I'm sure...) the API had changed in Sonarr.

This can be closed.
