### ISSUE TITLE
SAB Stating it is unable to run script

### ISSUE THREAD

**Issue by astlaurent** [mdhiggins/sickbeard_mp4_automator#1703]
I was running this set of scripts fine before but reloaded my OS and now when attempting to post process from SAB I get the following error

Exit(-1): Cannot run script C:\PlexTools\MP4Automator\SABPostProcess.py

I was able to get it to run by picking a batch file which then run the sabpostprocess.py so I am pretty sure it is a problem with SAB not finding the python installation. 

**System Information**
 - OS: Windows
 - Python version: 3.1.2

[Converter]
ffmpeg = C:\PlexTools\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\PlexTools\ffmpeg\bin\ffprobe.exe
threads = 0
hwaccels = dxva2, cuvid, qsv, d3d11va
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = False
force-convert = False
post-process = False
preopts = 
postopts = 
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
bypass-if-copying-all = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
regex-directory-replace = [^\w\-_\. ]
output-directory-space-ratio = 0.0

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = poster
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
max-bitrate = 0
crf = -1
crf-profiles = 
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
filter = 
force-filter = False
codec = h264qsv, h264, x264, h265, x265, hevc
bitrate-ratio = 
preset = 
codec-parameters = 
dynamic-parameters = False
prioritize-source-pix-fmt = True

[HDR]
space = bt2020nc
transfer = smpte2084
primaries = bt2020
filter = 
force-filter = False
codec = 
pix-fmt = 
preset = 
codec-parameters = 
profile = 

[Audio]
codec = ac3
languages = eng
default-language = eng
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
filter = 
force-filter = False
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions = 
unique-dispositions = False
include-original-language = True
variable-bitrate = 0
profile = 
sample-format = 
force-default = False
stream-codec-combinations = 

[Universal Audio]
codec = aac
channel-bitrate = 128
first-stream-only = False
filter = 
force-filter = False
variable-bitrate = 0
profile = 

[Subtitle]
codec = mov_text
codec-image-based = 
languages = eng
default-language = eng
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
attachment-codec = 
ignored-dispositions = 
unique-dispositions = False
include-original-language = False
force-default = False
remove-bitstream-subs = False

[Sonarr]
host = localhost
port = 8081
apikey =  
ssl = False
webroot = /sonarr
force-rename = False
rescan = True
block-reprocess = False
in-progress-check = True

[Radarr]
host = localhost
port = 8082
apikey =  
ssl = False
webroot = /radarr
force-rename = False
rescan = True
block-reprocess = False
in-progress-check = True

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
apikey = 
delay = 65
method = renamer
delete-failed = False
ssl = False
webroot = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
couchpotato-category = couchpotato
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 
path-mapping = 

[uTorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token = 
username = 
password = 
servername = 
ssl = True
ignore-certs = False
path-mapping = 

[Subtitle.Subliminal]
download-subs = False
download-hearing-impaired-subs = False
providers = 
download-forced-subs = False
include-hearing-impaired-subs = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle.Subliminal.Auth]
opensubtitles = 
tvsubtitles = 

[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs = 

[Subtitle.Sorting]
sorting = language, d.comment, d.default.d, d.forced.d
codecs = 
burn-sorting = language, d.comment, d.default.d, d.forced.d

[Subtitle.CleanIt]
enabled = False
config-path = 
tags = 

[Subtitle.FFSubsync]
enabled = False

**Comment by astlaurent** [comment]
also noticed in debug logs it shows this

2024-02-13 15:36:23,668::DEBUG::[newsunpack:261] Failed script C:\PlexTools\MP4Automator\SABPostProcess.py, Traceback: 
Traceback (most recent call last):
  File "sabnzbd\newsunpack.py", line 246, in external_processing
  File "sabnzbd\misc.py", line 1232, in build_and_run_command
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by astlaurent** [comment]
looks like it was a problem with sab, reinstalled and rebooted. it is working now
