### ISSUE TITLE
Error processing some anime

### ISSUE THREAD

**Issue by powerdude** [mdhiggins/sickbeard_mp4_automator#1711]
**Describe the bug**
I see an error in the log and I noticed certain videos didn't have the show's cover art as the preview image.

**Command or context you are trying to run**
n/a

**autoProcess.ini settings**
***Please sensor API keys/private information but include all other settings***
n/a

**Log files**
```
2024-05-03 22:03:38 - resources.mediaprocessor - INFO - Processing /data/videos/tv/tv-anime/Cardfight!! Vanguard (2011) [tvdb-245821]/Season 15/Cardfight!! Vanguard (2011) - S15E15 - 532 - Witch of the Starry Skies [WEBDL-1080p][8bit][x264][AAC 2.0][JA+EN]-S1PH3R.mkv.
2024-05-03 22:03:39 - resources.mediaprocessor - ERROR - Unable to get metadata.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 53, in fullprocess
    tagdata = tagdata or Metadata(mediatype, tvdbid=tvdbid, tmdbid=tmdbid, imdbid=imdbid, season=season, episode=episode, original=original, language=language)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/sma/resources/metadata.py", line 105, in __init__
    self.seasondata = seasonquery.info(language=self.language)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/sma/venv/lib/python3.11/site-packages/tmdbsimple/tv.py", line 524, in info
    response = self._GET(path, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/sma/venv/lib/python3.11/site-packages/tmdbsimple/base.py", line 110, in _GET
    return self._request('GET', path, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/sma/venv/lib/python3.11/site-packages/tmdbsimple/base.py", line 105, in _request
    response.raise_for_status()
  File "/usr/local/sma/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/tv/35442/season/15?language=en&api_key=<redacted>
```

**FFMpeg headers**
n/a

**System Information**
Docker 

**Expected behavior**
at least no error, I think

**Additional context**
none

*Issues posted without any logs or autoProcess settings will be closed*

**Comment by mdhiggins** [comment]
This is probably just TMBD not having the season info for that show

Does the conversion continue onward otherwise?

**Comment by powerdude** [comment]
yes, it continues onward.

**Comment by mdhiggins** [comment]
Yeah can confirm looks like TMBD only has 9 seasons hence the error when you try to search for season 15

**Comment by powerdude** [comment]
Thanks.  I seem to get this a lot for some of the anime I've been getting recently and the shows seemed to be present when I looked manually.  Oh well, I guess as long as the file is converted I can live without synopsis, title info or episode show art

**Comment by powerdude** [comment]
Yeah, I understand.  I have recent one with [MASHLE](https://www.themoviedb.org/tv/204832-mashle/season/1/episode/19), where Sonarr thinks there are 2 seasons but TMDB only thinks there is 1.  So, the most recent dubbed episode with absolute number of 19 is season 2, ep 7 in Sonarr, but season 1, ep 19 on TMDB.  It's too bad absolute episode numbers can't be used.
