### ISSUE TITLE
Can't use script on new machine not sure why

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1720]
This is the log thats been kicked out, its on a Beelink EQ12 minni PC with a intel N100 CPU.

```
2024-09-08 15:20:59 - MANUAL - INFO - Manual processor started.
2024-09-08 15:20:59 - MANUAL - INFO - Python 64-bit 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)].
2024-09-08 15:20:59 - MANUAL - INFO - Guessit version: 3.8.0.
2024-09-08 15:20:59 - MANUAL - INFO - C:\Users\Paul\AppData\Local\Programs\Python\Python312\python.exe
2024-09-08 15:20:59 - MANUAL - INFO - Loading config file A:\PlexBackend\Converter\config\autoProcess.ini.
2024-09-08 15:20:59 - MANUAL - WARNING - Force-convert is true, so process-same-extensions is being overridden to true as well
2024-09-08 15:21:08 - MANUAL - INFO - Processing file D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv
2024-09-08 15:21:08 - MANUAL - INFO - Processing file D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv
2024-09-08 15:21:08 - MANUAL - INFO - Input Data
2024-09-08 15:21:08 - MANUAL - INFO - {
    "format": "matroska,webm",
    "format-fullname": "Matroska / WebM",
    "video": {
        "index": 0,
        "codec": "h264",
        "bitrate": 9189417,
        "pix_fmt": "yuv420p",
        "profile": "high",
        "fps": 23.976023976023978,
        "framedata": {
            "pix_fmt": "yuv420p",
            "color_space": "bt709",
            "color_primaries": "bt709",
            "color_transfer": "bt709"
        },
        "dimensions": "1920x1080",
        "level": 4.0,
        "field_order": "progressive"
    },
    "audio": [
        {
            "index": 1,
            "codec": "eac3",
            "bitrate": 224000,
            "channels": 2,
            "samplerate": 48000,
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions"
        }
    ],
    "subtitle": [
        {
            "index": 2,
            "codec": "subrip",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "language": "eng"
        }
    ],
    "attachment": []
}
2024-09-08 15:21:08 - MANUAL - INFO - Reading video stream.
2024-09-08 15:21:08 - MANUAL - INFO - Video codec detected: h264.
2024-09-08 15:21:08 - MANUAL - INFO - Pix Fmt: yuv420p.
2024-09-08 15:21:08 - MANUAL - INFO - Profile: high.
2024-09-08 15:21:08 - MANUAL - INFO - Video codec parameters None.
2024-09-08 15:21:08 - MANUAL - INFO - Creating h265 video stream from source stream 0.
2024-09-08 15:21:08 - MANUAL - INFO - Reading audio streams.
2024-09-08 15:21:08 - MANUAL - INFO - The following stream indexes have been identified as being copies: [] [stream-codec-combinations].
2024-09-08 15:21:08 - MANUAL - INFO - Audio detected for stream 1 - eac3 eng 2 channel.
2024-09-08 15:21:08 - MANUAL - INFO - Creating aac audio stream from source stream 1.
2024-09-08 15:21:08 - MANUAL - INFO - Found 0 streams that can be removed from the output file since they will be duplicates [stream-codec-combinations].
2024-09-08 15:21:08 - MANUAL - INFO - Final sorting:
2024-09-08 15:21:08 - MANUAL - INFO - ['0->0']
2024-09-08 15:21:08 - MANUAL - INFO - Final sorting:
2024-09-08 15:21:08 - MANUAL - INFO - ['0->0']
2024-09-08 15:21:08 - MANUAL - INFO - Default audio stream set to eng aac 2 channel stream [audio-default-sorting: ['channels.d', 'map', 'd.comment']].
2024-09-08 15:21:08 - MANUAL - INFO - Reading subtitle streams.
2024-09-08 15:21:08 - MANUAL - INFO - Subtitle detected for stream 2 - subrip eng.
2024-09-08 15:21:09 - MANUAL - INFO - Stream 2 is text-based subtitle for codec subrip.
2024-09-08 15:21:09 - MANUAL - INFO - Creating srt subtitle stream from source stream 2.
2024-09-08 15:21:09 - MANUAL - INFO - Scanned for external subtitles and found 0 results in your approved languages.
2024-09-08 15:21:09 - MANUAL - INFO - Final sorting:
2024-09-08 15:21:09 - MANUAL - INFO - ['0->0']
2024-09-08 15:21:09 - MANUAL - INFO - qsv hwaccel is supported by this ffmpeg build and will be used [hwaccels].
2024-09-08 15:21:09 - MANUAL - INFO - Output Data
2024-09-08 15:21:09 - MANUAL - INFO - {
    "source": [
        "D:\\Media\\Converting\\bypass\\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv"
    ],
    "format": "mkv",
    "video": {
        "codec": "h265",
        "map": 0,
        "bitrate": 4000,
        "crf": -1,
        "maxrate": null,
        "bufsize": null,
        "level": 5.2,
        "profile": null,
        "preset": null,
        "pix_fmt": null,
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "framedata": null,
        "bsf": null,
        "debug": "video.max-bitrate",
        "title": "FHD"
    },
    "audio": [
        {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 224.0,
            "profile": null,
            "quality": 0,
            "filter": null,
            "samplerate": null,
            "sampleformat": "",
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "bsf": null,
            "debug": "universal-audio",
            "title": "Stereo"
        }
    ],
    "subtitle": [
        {
            "map": 2,
            "codec": "srt",
            "language": "eng",
            "disposition": "+default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions",
            "debug": "subtitle.embed-subs",
            "title": null
        }
    ],
    "attachment": []
}
2024-09-08 15:21:09 - MANUAL - INFO - Preopts
2024-09-08 15:21:09 - MANUAL - INFO - [
    "-hwaccel",
    "qsv"
]
2024-09-08 15:21:09 - MANUAL - INFO - Postopts
2024-09-08 15:21:09 - MANUAL - INFO - [
    "-threads",
    "0",
    "-metadata:g",
    "encoding_tool=SMA"
]
2024-09-08 15:21:09 - MANUAL - INFO - Starting conversion.
2024-09-08 15:21:09 - MANUAL - INFO - FFmpeg command:
2024-09-08 15:21:09 - MANUAL - INFO - ======================
2024-09-08 15:21:09 - MANUAL - INFO - A:\PlexBackend\FFmpeg\bin\ffmpeg.exe -hwaccel qsv -fix_sub_duration -i D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv.original -map_metadata -1 -vcodec libx265 -map 0:0 -field_order progressive -vb 4000k -metadata:s:v BPS=4000000 -metadata:s:v BPS-eng=4000000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -level 5.2 -tag:v hvc1 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 224k -metadata:s:a:0 BPS=224000 -metadata:s:a:0 BPS-eng=224000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:s:0 srt -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f matroska -threads 0 -metadata:g encoding_tool=SMA -y D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv
2024-09-08 15:21:09 - MANUAL - INFO - ======================
2024-09-08 15:21:11 - MANUAL - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "A:\PlexBackend\Converter\resources\mediaprocessor.py", line 2313, in convert
    for timecode, debug in conv:
                           ^^^^
  File "A:\PlexBackend\Converter\converter\__init__.py", line 335, in convert
    for timecode, debug in self.ffmpeg.convert(outfile,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\PlexBackend\Converter\converter\ffmpeg.py", line 798, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <exception str() failed>
2024-09-08 15:21:11 - MANUAL - ERROR - A:\PlexBackend\FFmpeg\bin\ffmpeg.exe -hwaccel qsv -fix_sub_duration -i D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv.original -map_metadata -1 -vcodec libx265 -map 0:0 -field_order progressive -vb 4000k -metadata:s:v BPS=4000000 -metadata:s:v BPS-eng=4000000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -level 5.2 -tag:v hvc1 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 224k -metadata:s:a:0 BPS=224000 -metadata:s:a:0 BPS-eng=224000 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -strict experimental -c:s:0 srt -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f matroska -threads 0 -metadata:g encoding_tool=SMA -y D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv
2024-09-08 15:21:11 - MANUAL - ERROR - ffmpeg version 2024-08-26-git-98610fe95f-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers

  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)

  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint

  libavutil      59. 34.100 / 59. 34.100

  libavcodec     61. 11.100 / 61. 11.100

  libavformat    61.  5.101 / 61.  5.101

  libavdevice    61.  2.100 / 61.  2.100

  libavfilter    10.  2.102 / 10.  2.102

  libswscale      8.  2.100 /  8.  2.100

  libswresample   5.  2.100 /  5.  2.100

  libpostproc    58.  2.100 / 58.  2.100

[vist#0:0/h264 @ 00000279ef87c140] WARNING: defaulting hwaccel_output_format to qsv for compatibility with old commandlines. This behaviour is DEPRECATED and will be removed in the future. Please explicitly set "-hwaccel_output_format qsv".

[vist#0:3/png @ 00000279efe17980] WARNING: defaulting hwaccel_output_format to qsv for compatibility with old commandlines. This behaviour is DEPRECATED and will be removed in the future. Please explicitly set "-hwaccel_output_format qsv".

Input #0, matroska,webm, from 'D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv.original':

  Metadata:

    GENRE           : Suspense;Action;Biting;Malicious

    encoder         : libebml v1.4.2 + libmatroska v1.6.4

    creation_time   : 2024-07-03T05:00:24.000000Z

    ACTORS          : 

    DATE            : 2014

    DESCRIPTION     : Below the streets of New York is a dark world hidden in the shadows of abandoned subway tunnels. When a young documentary filmmaker goes to uncover the unseen stories, she finds a mysterious figure (Danny Trejo), living beyond the reach of the law.

    TITLE           : 20 Feet Below

    SHOW            : 20 Feet Below

    EPISODE_ID      : 

    COMMENT         : 

    SEASON          : 

  Duration: 01:35:54.53, start: 0.000000, bitrate: 9416 kb/s

  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)

      Metadata:

        BPS             : 9189417

        DURATION        : 01:35:54.499000000

        NUMBER_OF_FRAMES: 137970

        NUMBER_OF_BYTES : 6610061493

        _STATISTICS_WRITING_APP: mkvmerge v68.0.0 ('The Curtain') 64-bit

        _STATISTICS_WRITING_DATE_UTC: 2024-07-03 05:00:24

        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

  Stream #0:1(eng): Audio: eac3, 48000 Hz, stereo, fltp, 224 kb/s (default)

      Metadata:

        title           : English

        BPS             : 224000

        DURATION        : 01:35:54.528000000

        NUMBER_OF_FRAMES: 179829

        NUMBER_OF_BYTES : 161126784

        _STATISTICS_WRITING_APP: mkvmerge v68.0.0 ('The Curtain') 64-bit

        _STATISTICS_WRITING_DATE_UTC: 2024-07-03 05:00:24

        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

  Stream #0:2(eng): Subtitle: subrip (srt) (default)

      Metadata:

        title           : English [CC]

        BPS             : 60

        DURATION        : 01:31:58.165000000

        NUMBER_OF_FRAMES: 1241

        NUMBER_OF_BYTES : 41654

        _STATISTICS_WRITING_APP: mkvmerge v68.0.0 ('The Curtain') 64-bit

        _STATISTICS_WRITING_DATE_UTC: 2024-07-03 05:00:24

        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

  Stream #0:3: Video: png, rgb24(pc, gbr/unknown/unknown), 1080x608 [SAR 3780:3780 DAR 135:76], 90k tbr, 90k tbn (attached pic)

      Metadata:

        filename        : cover.png

        mimetype        : image/png

[AVHWDeviceContext @ 00000279f0497cc0] Using device 8086:46d1 (Intel(R) UHD Graphics).

Stream mapping:

  Stream #0:0 -> #0:0 (h264 (h264_qsv) -> hevc (libx265))

  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))

  Stream #0:2 -> #0:2 (subrip (srt) -> subrip (srt))

Press [q] to stop, [?] for help

Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scale_0'

[vf#0:0 @ 00000279efe18040] Error reinitializing filters!

[vf#0:0 @ 00000279efe18040] Task finished with error code: -40 (Function not implemented)

[vf#0:0 @ 00000279efe18040] Terminating thread with return code -40 (Function not implemented)

[vost#0:0/libx265 @ 00000279efede240] Could not open encoder before EOF

[vost#0:0/libx265 @ 00000279efede240] Task finished with error code: -22 (Invalid argument)

[vost#0:0/libx265 @ 00000279efede240] Terminating thread with return code -22 (Invalid argument)

[out#0/matroska @ 00000279efe17c40] Nothing was written into output file, because at least one of its streams received no packets.

frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    

[aac @ 00000279ef92dc00] Qavg: 50305.758

Conversion failed!


2024-09-08 15:21:11 - MANUAL - ERROR - D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv deleted.
2024-09-08 15:21:11 - MANUAL - ERROR - There was an error processing file D:\Media\Converting\bypass\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020\20.Ft.Below.The.Darkness.Descending.2014.1080p.AMZN.WEB-DL.DDP.2.0.H.264-edge2020.mkv, no output data received

```

**Comment by morpheus2n2** [comment]
[autoProcess.txt](https://github.com/user-attachments/files/17001333/autoProcess.txt)


Here you go
