### ISSUE TITLE
-imdb and -tvdb args don't work

### ISSUE THREAD

**Issue by cod3fr3ak** [mdhiggins/sickbeard_mp4_automator#185]
[root@processor mp4-automator]# time /opt/mp4-automator/manual.py -i "/shared/video/movies/Kiss the Girls (1997).mkv" -imdb tt0119468
Traceback (most recent call last):
  File "/opt/mp4-automator/manual.py", line 287, in <module>
    main()
  File "/opt/mp4-automator/manual.py", line 271, in main
    imdbid = int(args['imdbid'])
ValueError: invalid literal for int() with base 10: 'tt0119468'

real    0m0.555s
user    0m0.373s
sys     0m0.048s

[root@processor mp4-automator]# time /opt/mp4-automator/manual.py -i "/shared/video/movies/Kiss the Girls (1997).mkv" --imdb tt0119468
Traceback (most recent call last):
  File "/opt/mp4-automator/manual.py", line 287, in <module>
    main()
  File "/opt/mp4-automator/manual.py", line 271, in main
    imdbid = int(args['imdbid'])
ValueError: invalid literal for int() with base 10: 'tt0119468'

real    0m0.461s
user    0m0.314s
sys     0m0.039s

So I see its complaining about int() and sure enough the IMDB number has some ascii in it, so I figure no problem remove the ascii and just send chars, the program must assume anything coming in after --imdb is a valid movieid. No go:

[root@processor mp4-automator]# time /opt/mp4-automator/manual.py -i "/shared/video/movies/Kiss the Girls (1997).mkv" --imdb 0119468
Traceback (most recent call last):
  File "/opt/mp4-automator/manual.py", line 287, in <module>
    main()
  File "/opt/mp4-automator/manual.py", line 278, in main
    processFile(path, tagdata)
  File "/opt/mp4-automator/manual.py", line 153, in processFile
    tagmp4 = tmdb_mp4(imdbid)
  File "/opt/mp4-automator/tmdb_mp4.py", line 14, in __init__
    if tmdbid is False and imdbid.startswith('tt') is not True:
AttributeError: 'int' object has no attribute 'startswith'

real    0m0.500s
user    0m0.378s
sys     0m0.046s

Using -a works however.

**Comment by mdhiggins** [comment]
I'm wondering if you're using an older version of the script that's causing
your current error, becasue that line `imdbid = int(args['imdbid'])`
doesn't seem to exist anymore and was changed for the bug you're
mentioning. Just double check that for me before I dive into this any
further.

Thanks

**Comment by cod3fr3ak** [comment]
No problem I'll grab a more recent copy and try it. Thanks!

**Comment by cod3fr3ak** [comment]
Also tried to install the subliminal piece as well, didn't work, but this is more important at the moment.
