### ISSUE TITLE
Error when using Manual.py

### ISSUE THREAD

**Issue by the8thsign** [mdhiggins/sickbeard_mp4_automator#202]
I got the script up and running on OS X so I wanted to see if I could get it running on my Synology. Here is the error i get why I run it.

DiskStation> ./manual.py -i ../../Movies/Wanted\ \(2008\).mkv 
Traceback (most recent call last):
  File "./manual.py", line 10, in <module>
    from readSettings import ReadSettings
  File "/volume1/Videos/Downloads/mp4_automator/readSettings.py", line 5, in <module>
    from babelfish import Language
  File "/volume1/Videos/Downloads/mp4_automator/babelfish/__init__.py", line 13, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/volume1/Videos/Downloads/mp4_automator/babelfish/converters/__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ImportError: No module named pkg_resources

**Comment by mdhiggins** [comment]
Your python installation does not have setup tools installed.

Follow the instructions here to install it:
https://pypi.python.org/pypi/setuptools#installation-instructions

**Comment by the8thsign** [comment]
That worked!! Thank You.
