### ISSUE TITLE
manual.py: No handlers could be found for logger "readSettings"

### ISSUE THREAD

**Issue by KaHooli** [mdhiggins/sickbeard_mp4_automator#227]
When performing a manual conversion using manual.py, I get the following error...
`No handlers could be found for logger "readSettings"`
...and I can't see the normal details that used to come up about the audio, video and subtitle tracks.

Example...
```
C:\Users\Administrator>C:\autoProcess\manual.py -i "G:\Public\Videos\Movies\xxxxxxxxxx (2011)\xxxxxxxxxx.mkv" -imdb tt#######
No handlers could be found for logger "readSettings"
64
Processing xxxxxxxxxx
[######### ] 99%
```
Is this how it is meant to work now?  I did like seeing the detailed information, especially when manually converting media.

**Comment by mdhiggins** [comment]
It looks to me like you haven't update the script too recently or maybe you're running with a mix of files from different versions. Try updating to the latest version. 



—

**Comment by mdhiggins** [comment]
I found the problem. There was a pull request I recently merged to update guessit that for some reason reverted manual.py back to a really old version and created problems. It should be fixed now.

**Comment by KaHooli** [comment]
I did a `git pull` successfully and got the error below.  I also deleted the directory, did a new 'git clone <url> C:\autoProcess`, set up the ini file again and still got the error below.
```
C:\>C:\autoProcess\manual.py --input "G:\Public\Videos\TV Shows\xxxxxxxxxx\Seaso
n 01\xxxxxxxxxx - S01E01 - yyyyyyyyyy.avi" --auto
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Traceback (most recent call last):
  File "C:\autoProcess\manual.py", line 318, in <module>
    main()
  File "C:\autoProcess\manual.py", line 308, in main
    tagdata = getinfo(path, silent=silent)
  File "C:\autoProcess\manual.py", line 74, in getinfo
    if fileName is not None: tagdata = guessInfo(fileName, tvdbid)
  File "C:\autoProcess\manual.py", line 108, in guessInfo
    guess = guessit.guess_file_info(fileName)
  File "C:\autoProcess\guessit\__init__.py", line 291, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "C:\autoProcess\guessit\__init__.py", line 111, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "C:\autoProcess\guessit\__init__.py", line 118, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "C:\autoProcess\guessit\matcher.py", line 109, in __init__
    from guessit.plugins import transformers
  File "C:\autoProcess\guessit\plugins\transformers.py", line 24, in <module>
    from stevedore import ExtensionManager
ImportError: No module named stevedore```

**Comment by KaHooli** [comment]
Just saw that the README was updated and that `stevedore` module is required in Python.  I've added it, and it seems like it converting now, but I'm getting this output on the screen...
```
C:\Users\Administrator>C:\autoProcess\manual.py --input "G:\Public\Videos\TV Shows\xxxxxxxxxx\Season 01\xxxxxxxxxx - S01E02 - yyyyyyyyyy.avi" --auto
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
2015-04-04 21:08:59 - stevedore.extension - ERROR - Could not load u'guess_date'
: No module named dateutil
2015-04-04 21:08:59 - stevedore.extension - ERROR - No module named dateutil
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\stevedore\extension.py", line 162, in _load_plugins
    verify_requirements,
  File "C:\autoProcess\guessit\plugins\transformers.py", line 92, in _load_one_plugin
    plugin = ep.resolve()
  File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\autoProcess\guessit\transfo\guess_date.py", line 25, in <module>
    from guessit.date import search_date
  File "C:\autoProcess\guessit\date.py", line 27, in <module>
    from dateutil import parser
ImportError: No module named dateutil
2015-04-04 21:09:00 - stevedore.extension - ERROR - Could not load u'guess_weak_
episodes_rexps': No module named dateutil
2015-04-04 21:09:00 - stevedore.extension - ERROR - No module named dateutil
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\stevedore\extension.py", line 162, in _load_plugins
    verify_requirements,
  File "C:\autoProcess\guessit\plugins\transformers.py", line 92, in _load_one_plugin
    plugin = ep.resolve()
  File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\autoProcess\guessit\transfo\guess_weak_episodes_rexps.py", line 28, in <module>
    from guessit.date import valid_year
  File "C:\autoProcess\guessit\date.py", line 27, in <module>
    from dateutil import parser
ImportError: No module named dateutil
2015-04-04 21:09:00 - stevedore.extension - ERROR - Could not load u'guess_year'
: No module named dateutil
2015-04-04 21:09:00 - stevedore.extension - ERROR - No module named dateutil
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\stevedore\extension.py", line 162, in _load_plugins
    verify_requirements,
  File "C:\autoProcess\guessit\plugins\transformers.py", line 92, in _load_one_plugin
    plugin = ep.resolve()
  File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\autoProcess\guessit\transfo\guess_year.py", line 25, in <module>
    from guessit.date import search_year, valid_year
  File "C:\autoProcess\guessit\date.py", line 27, in <module>
    from dateutil import parser
ImportError: No module named dateutil
Matched TV episode as xxxxxxxxxx (TVDB ID:#####) S01E02
Processing xxxxxxxxxx Season 01 Episode 02 - yyyyyyyyyy
Reading video stream.
Video codec detected: mpeg4
Reading audio streams.
Audio detected for stream #1: mp2 [und].
Creating audio stream 0 from source audio stream 1.
Reading subtitle streams.
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "eng"
        }
    },
    "video": {
        "map": 0,
        "codec": "h264",
        "bitrate": 1588685.0
    },
    "format": "mp4"
}
Starting conversion.
[          ] 0%```

**Comment by KaHooli** [comment]
Found the solution, I think.  For me to get rid of these errors, I had to install Subliminal even though I have the `embed-subs = False`.  Once I did this, I no longer had the errors.  The README states that you only need to install Subliminal if `embed-subs = True`

**Comment by mdhiggins** [comment]
Yeah the recent update to guessit has created some new dependencies that I wasn't aware of because subliminal includes all of  that as part of its install process. I'll update the readme to indicate `dateutil` is also required. Thanks for the info.
