### ISSUE TITLE
Failure during srt extraction

### ISSUE THREAD

**Issue by KurtisVargas** [mdhiggins/sickbeard_mp4_automator#247]
I have about 25 files that the script fails during conversion at the point where it extracts SRT files from th MP4. The source files are all files that were converted by the script already (I am re-ripping to lower bitrate).   I can't figure out what's going on.  
Running the exact command line manually does not fail and all the resulting SRTs seem well formed.  
I assumed it was an issue parsing the output so I tried older versions of ffmpeg but they didn't help.

Any ideas?  

---
Running this command:
`./manual.py -nd -nt -i /smb/media/Temp/test-file.mp4`

First up is the console output.  I added in a 'print total_output' so you'd have the complete ffmpeg output.  Below this is debug log
```
Manual processor started.
64bit Python.
No-delete enabled
No-tagging enabled
Reading video stream.
Video codec detected: h264
Reading audio streams.
Audio detected for stream #1: aac [eng].
Creating audio stream 0 from source audio stream 1.
Audio detected for stream #2: aac [eng].
Creating audio stream 1 from source audio stream 2.
Reading subtitle streams.
Subtitle detected for stream #3: mov_text [eng].
Ripping [eng] subtitle from source into external file.
ffmpeg version N-45942-gfbdaebb-   http://johnvansickle.com/ffmpeg/    Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --enable-gpl --enable-version3 --disable-shared --disable-debug --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libfreetype --enable-fontconfig --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-gray --enable-libopenjpeg --enable-libopus --enable-libass --enable-gnutls --enable-libvidstab --enable-libsoxr --cc=gcc-4.9
  libavutil      54. 22.101 / 54. 22.101
  libavcodec     56. 34.100 / 56. 34.100
  libavformat    56. 30.100 / 56. 30.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 14.100 /  5. 14.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/smb/media/Temp/test-file.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf55.42.100
  Duration: 02:11:35.32, start: 0.021333, bitrate: 8787 kb/s
    Chapter #0:0: start 0.000000, end 213.338000
    Metadata:
      title           : 00:00:00.000
    Chapter #0:1: start 213.338000, end 480.689000
    Metadata:
      title           : 00:03:33.338
    Chapter #0:2: start 480.689000, end 628.628000
    Metadata:
      title           : 00:08:00.689
    Chapter #0:3: start 628.628000, end 838.046000
    Metadata:
      title           : 00:10:28.628
    Chapter #0:4: start 838.046000, end 1022.021000
    Metadata:
      title           : 00:13:58.046
    Chapter #0:5: start 1022.021000, end 1216.090000
    Metadata:
      title           : 00:17:02.021
    Chapter #0:6: start 1216.090000, end 1331.330000
    Metadata:
      title           : 00:20:16.090
    Chapter #0:7: start 1331.330000, end 1597.888000
    Metadata:
      title           : 00:22:11.330
    Chapter #0:8: start 1597.888000, end 1832.038000
    Metadata:
      title           : 00:26:37.888
    Chapter #0:9: start 1832.038000, end 2069.776000
    Metadata:
      title           : 00:30:32.038
    Chapter #0:10: start 2069.776000, end 2160.992000
    Metadata:
      title           : 00:34:29.776
    Chapter #0:11: start 2160.992000, end 2298.087000
    Metadata:
      title           : 00:36:00.992
    Chapter #0:12: start 2298.087000, end 2437.101000
    Metadata:
      title           : 00:38:18.087
    Chapter #0:13: start 2437.101000, end 2753.793000
    Metadata:
      title           : 00:40:37.101
    Chapter #0:14: start 2753.793000, end 2933.848000
    Metadata:
      title           : 00:45:53.793
    Chapter #0:15: start 2933.848000, end 3118.157000
    Metadata:
      title           : 00:48:53.848
    Chapter #0:16: start 3118.157000, end 3283.113000
    Metadata:
      title           : 00:51:58.157
    Chapter #0:17: start 3283.113000, end 3471.426000
    Metadata:
      title           : 00:54:43.113
    Chapter #0:18: start 3471.426000, end 3648.186000
    Metadata:
      title           : 00:57:51.426
    Chapter #0:19: start 3648.186000, end 3806.594000
    Metadata:
      title           : 01:00:48.186
    Chapter #0:20: start 3806.594000, end 4029.567000
    Metadata:
      title           : 01:03:26.594
    Chapter #0:21: start 4029.567000, end 4183.596000
    Metadata:
      title           : 01:07:09.567
    Chapter #0:22: start 4183.596000, end 4391.470000
    Metadata:
      title           : 01:09:43.596
    Chapter #0:23: start 4391.470000, end 4531.861000
    Metadata:
      title           : 01:13:11.470
    Chapter #0:24: start 4531.861000, end 4647.726000
    Metadata:
      title           : 01:15:31.861
    Chapter #0:25: start 4647.726000, end 4770.099000
    Metadata:
      title           : 01:17:27.726
    Chapter #0:26: start 4770.099000, end 5090.711000
    Metadata:
      title           : 01:19:30.099
    Chapter #0:27: start 5090.711000, end 5218.255000
    Metadata:
      title           : 01:24:50.711
    Chapter #0:28: start 5218.255000, end 5464.250000
    Metadata:
      title           : 01:26:58.255
    Chapter #0:29: start 5464.250000, end 5643.680000
    Metadata:
      title           : 01:31:04.250
    Chapter #0:30: start 5643.680000, end 5853.181000
    Metadata:
      title           : 01:34:03.680
    Chapter #0:31: start 5853.181000, end 6114.817000
    Metadata:
      title           : 01:37:33.181
    Chapter #0:32: start 6114.817000, end 6292.995000
    Metadata:
      title           : 01:41:54.817
    Chapter #0:33: start 6292.995000, end 6439.808000
    Metadata:
      title           : 01:44:52.995
    Chapter #0:34: start 6439.808000, end 6689.766000
    Metadata:
      title           : 01:47:19.808
    Chapter #0:35: start 6689.766000, end 7002.746000
    Metadata:
      title           : 01:51:29.766
    Chapter #0:36: start 7002.746000, end 7212.413000
    Metadata:
      title           : 01:56:42.746
    Chapter #0:37: start 7212.413000, end 7354.973000
    Metadata:
      title           : 02:00:12.413
    Chapter #0:38: start 7354.973000, end 7831.907000
    Metadata:
      title           : 02:02:34.973
    Chapter #0:39: start 7831.907000, end 7895.263000
    Metadata:
      title           : 02:10:31.907
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x800 [SAR 1:1 DAR 12:5], 8004 kb/s, 23.98 fps, 23.98 tbr, 16k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 382 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 383 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:3(eng): Subtitle: mov_text (text / 0x74786574)
    Metadata:
      handler_name    : SubtitleHandler
Output #0, srt, to '/smb/media/Temp/test-file.eng.srt':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.30.100
    Chapter #0:0: start 0.021000, end 213.359000
    Metadata:
      title           : 00:00:00.000
    Chapter #0:1: start 213.359000, end 480.710000
    Metadata:
      title           : 00:03:33.338
    Chapter #0:2: start 480.710000, end 628.649000
    Metadata:
      title           : 00:08:00.689
    Chapter #0:3: start 628.649000, end 838.067000
    Metadata:
      title           : 00:10:28.628
    Chapter #0:4: start 838.067000, end 1022.042000
    Metadata:
      title           : 00:13:58.046
    Chapter #0:5: start 1022.042000, end 1216.111000
    Metadata:
      title           : 00:17:02.021
    Chapter #0:6: start 1216.111000, end 1331.351000
    Metadata:
      title           : 00:20:16.090
    Chapter #0:7: start 1331.351000, end 1597.909000
    Metadata:
      title           : 00:22:11.330
    Chapter #0:8: start 1597.909000, end 1832.059000
    Metadata:
      title           : 00:26:37.888
    Chapter #0:9: start 1832.059000, end 2069.797000
    Metadata:
      title           : 00:30:32.038
    Chapter #0:10: start 2069.797000, end 2161.013000
    Metadata:
      title           : 00:34:29.776
    Chapter #0:11: start 2161.013000, end 2298.108000
    Metadata:
      title           : 00:36:00.992
    Chapter #0:12: start 2298.108000, end 2437.122000
    Metadata:
      title           : 00:38:18.087
    Chapter #0:13: start 2437.122000, end 2753.814000
    Metadata:
      title           : 00:40:37.101
    Chapter #0:14: start 2753.814000, end 2933.869000
    Metadata:
      title           : 00:45:53.793
    Chapter #0:15: start 2933.869000, end 3118.178000
    Metadata:
      title           : 00:48:53.848
    Chapter #0:16: start 3118.178000, end 3283.134000
    Metadata:
      title           : 00:51:58.157
    Chapter #0:17: start 3283.134000, end 3471.447000
    Metadata:
      title           : 00:54:43.113
    Chapter #0:18: start 3471.447000, end 3648.207000
    Metadata:
      title           : 00:57:51.426
    Chapter #0:19: start 3648.207000, end 3806.615000
    Metadata:
      title           : 01:00:48.186
    Chapter #0:20: start 3806.615000, end 4029.588000
    Metadata:
      title           : 01:03:26.594
    Chapter #0:21: start 4029.588000, end 4183.617000
    Metadata:
      title           : 01:07:09.567
    Chapter #0:22: start 4183.617000, end 4391.491000
    Metadata:
      title           : 01:09:43.596
    Chapter #0:23: start 4391.491000, end 4531.882000
    Metadata:
      title           : 01:13:11.470
    Chapter #0:24: start 4531.882000, end 4647.747000
    Metadata:
      title           : 01:15:31.861
    Chapter #0:25: start 4647.747000, end 4770.120000
    Metadata:
      title           : 01:17:27.726
    Chapter #0:26: start 4770.120000, end 5090.732000
    Metadata:
      title           : 01:19:30.099
    Chapter #0:27: start 5090.732000, end 5218.276000
    Metadata:
      title           : 01:24:50.711
    Chapter #0:28: start 5218.276000, end 5464.271000
    Metadata:
      title           : 01:26:58.255
    Chapter #0:29: start 5464.271000, end 5643.701000
    Metadata:
      title           : 01:31:04.250
    Chapter #0:30: start 5643.701000, end 5853.202000
    Metadata:
      title           : 01:34:03.680
    Chapter #0:31: start 5853.202000, end 6114.838000
    Metadata:
      title           : 01:37:33.181
    Chapter #0:32: start 6114.838000, end 6293.016000
    Metadata:
      title           : 01:41:54.817
    Chapter #0:33: start 6293.016000, end 6439.829000
    Metadata:
      title           : 01:44:52.995
    Chapter #0:34: start 6439.829000, end 6689.787000
    Metadata:
      title           : 01:47:19.808
    Chapter #0:35: start 6689.787000, end 7002.767000
    Metadata:
      title           : 01:51:29.766
    Chapter #0:36: start 7002.767000, end 7212.434000
    Metadata:
      title           : 01:56:42.746
    Chapter #0:37: start 7212.434000, end 7354.994000
    Metadata:
      title           : 02:00:12.413
    Chapter #0:38: start 7354.994000, end 7831.928000
    Metadata:
      title           : 02:02:34.973
    Chapter #0:39: start 7831.928000, end 7895.284000
    Metadata:
      title           : 02:10:31.907
    Stream #0:0(eng): Subtitle: subrip (srt)
    Metadata:
      handler_name    : SubtitleHandler
      encoder         : Lavc56.34.100 srt
Stream mapping:
  Stream #0:3 -> #0:0 (mov_text (native) -> subrip (srt))
Press [q] to stop, [?] for help
size=       2kB time=02:10:31.92 bitrate=   0.0kbits/s
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 289.743591%

Traceback (most recent call last):
  File "./manual.py", line 353, in <module>
    main()
  File "./manual.py", line 344, in main
    processFile(path, tagdata)
  File "./manual.py", line 223, in processFile
    output = converter.process(inputfile, True)
  File "/root/sickbeard_mp4_automator/mkvtomp4.py", line 134, in process
    options = self.generateOptions(inputfile, original=original)
  File "/root/sickbeard_mp4_automator/mkvtomp4.py", line 417, in generateOptions
    for timecode in conv:
  File "/root/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/root/sickbeard_mp4_automator/converter/ffmpeg.py", line 535, in convert
    total_output, line, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <FFMpegConvertError error="video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 289.743591%", pid=8296, cmd="/root/ffmpeg/bin/ffmpeg -i /smb/media/Temp/test-file.mp4 -an -c:s:0 srt -map 0:3 -metadata:s:s:0 language=eng -f srt -y /smb/media/Temp/test-file.eng.srt">
```

Debug info.log
```
2015-04-15 22:51:17 - MANUAL - INFO - Manual processor started.
2015-04-15 22:51:17 - MANUAL - DEBUG - Settings imported.
2015-04-15 22:51:17 - MANUAL - DEBUG - /smb/media/Temp/test-file.mp4 is valid.
2015-04-15 22:54:33 - MANUAL - INFO - Manual processor started.
2015-04-15 22:54:33 - MANUAL - DEBUG - Settings imported.
2015-04-15 22:54:33 - MANUAL - DEBUG - /smb/media/Temp/test-file.mp4 is valid.
2015-04-15 22:55:23 - MANUAL - INFO - Manual processor started.
2015-04-15 22:55:23 - MANUAL - DEBUG - Settings imported.
2015-04-15 22:55:23 - MANUAL - DEBUG - /smb/media/Temp/test-file.mp4 is valid.
2015-04-15 22:55:23 - MANUAL - DEBUG - Settings imported.
2015-04-15 22:55:23 - MANUAL - DEBUG - /smb/media/Temp/test-file.mp4 is valid.
2015-04-15 22:55:23 - MANUAL - DEBUG - Settings imported.
2015-04-15 22:55:23 - MANUAL - DEBUG - Process started.
2015-04-15 22:55:23 - MANUAL - DEBUG - /smb/media/Temp/test-file.mp4 is valid.
2015-04-15 22:55:23 - MANUAL - DEBUG - /smb/media/Temp/test-file.mp4 needs processing.
2015-04-15 22:55:23 - MANUAL - INFO - Reading video stream.
2015-04-15 22:55:23 - MANUAL - INFO - Video codec detected: h264
2015-04-15 22:55:23 - MANUAL - DEBUG - Total bitrate is 8787398.0.
2015-04-15 22:55:23 - MANUAL - DEBUG - Total audio bitrate is 766563.
2015-04-15 22:55:23 - MANUAL - DEBUG - Estimated video bitrate is 8020835.0.
2015-04-15 22:55:23 - MANUAL - DEBUG - Overriding video bitrate. Codec cannot be copied because video bitrate is too high.
2015-04-15 22:55:23 - MANUAL - DEBUG - Video width is over the max width, it will be downsampled. Video stream can no longer be copied.
2015-04-15 22:55:23 - MANUAL - DEBUG - Video codec: h264
2015-04-15 22:55:23 - MANUAL - DEBUG - Video bitrate: 2200
2015-04-15 22:55:23 - MANUAL - INFO - Reading audio streams.
2015-04-15 22:55:23 - MANUAL - INFO - Audio detected for stream #1: aac [eng].
2015-04-15 22:55:23 - MANUAL - INFO - Creating audio stream 0 from source audio stream 1.
2015-04-15 22:55:23 - MANUAL - DEBUG - Audio codec: copy.
2015-04-15 22:55:23 - MANUAL - DEBUG - Channels: 2.
2015-04-15 22:55:23 - MANUAL - DEBUG - Bitrate: 256.
2015-04-15 22:55:23 - MANUAL - DEBUG - Language: eng
2015-04-15 22:55:23 - MANUAL - INFO - Audio detected for stream #2: aac [eng].
2015-04-15 22:55:23 - MANUAL - INFO - Creating audio stream 1 from source audio stream 2.
2015-04-15 22:55:23 - MANUAL - DEBUG - Audio codec: aac.
2015-04-15 22:55:23 - MANUAL - DEBUG - Channels: 2.
2015-04-15 22:55:23 - MANUAL - DEBUG - Bitrate: 256.
2015-04-15 22:55:23 - MANUAL - DEBUG - Language: eng
2015-04-15 22:55:23 - MANUAL - INFO - Reading subtitle streams.
2015-04-15 22:55:23 - MANUAL - INFO - Subtitle detected for stream #3: mov_text [eng].
2015-04-15 22:55:23 - MANUAL - INFO - Ripping [eng] subtitle from source into external file.
```

---
And autoProcess.ini
```
[MP4]
ffmpeg = /root/ffmpeg/bin/ffmpeg
ffprobe = /root/ffmpeg/bin/ffprobe
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
audio-codec = aac
video-codec = h264,x264
video-bitrate = 2200
video-max-width = 1280
ios-audio = False
ios-first-track-only = False
max-audio-channels = 2
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 128
subtitle-language =
subtitle-default-language =
fullpathguess = True
convert-mp4 = True
tagfile = False
tag-language = en
download-artwork = False
download-subs = False
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
subtitle-codec = srt
relocate_moov = True
```

**Comment by mdhiggins** [comment]
Can you send me one of the files or email me a Dropbox link or something so I can do some testing and find out what's going on. 



—

**Comment by KurtisVargas** [comment]
Fixed in latest build.
