### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by wraith1385** [mdhiggins/sickbeard_mp4_automator#263]
I'm getting the following error when it tries to process:

       Traceback (most recent call last):
  File "C:\Program Files (x86)\SABnzbd\scripts\SABPostProcess.py", line 11, in <module>
    fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log').replace("\\", "/")})
  File "C:\Python27\lib\logging\config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "C:\Python27\lib\logging\config.py", line 163, in _install_handlers
    h = klass(*args)
  File "C:\Python27\lib\logging\handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python27\lib\logging\__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\SABnzbd\\scripts\\info.log'

**Comment by mdhiggins** [comment]
Script is having trouble writing the log file to the directory, likely because you're in Program Files.

I would adjust the permissions of your C:\Program Files (x86)\SABnzbd\scripts\ folder so the script can write to its log file. The error should then go away.

**Comment by wraith1385** [comment]
Ok, I fixed the permissions error, but now I have a new error.  What exactly is the config file looking for in the path for ffmpeg?  This is what I have but I keep getting the error below.  "C:\\Program Files (x86)\\FFMPEG\\bin"

2015-05-12 22:33:01 - SABPostProcess - INFO - SAB post processing started.
2015-05-12 22:33:01 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-05-12 22:33:01 - readSettings - WARNING - Invalid external subtitle codec mov_text, defaulting to 'srt'.
2015-05-12 22:33:01 - SABPostProcess - INFO - Performing conversion
2015-05-12 22:33:01 - SABPostProcess - INFO - Processing file F:\Torrents\ShowRSS\NCIS.S12E24.720p.HDTV.X264-DIMENSION-2\NCIS.S12E24.720p.HDTV.X264-DIMENSION.mkv.
Traceback (most recent call last):
  File "C:\Program Files (x86)\SABnzbd\scripts\SABPostProcess.py", line 57, in <module>
    converter.process(inputfile)
  File "C:\Program Files (x86)\SABnzbd\scripts\mkvtomp4.py", line 134, in process
    options = self.generateOptions(inputfile, original=original)
  File "C:\Program Files (x86)\SABnzbd\scripts\mkvtomp4.py", line 242, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "C:\Program Files (x86)\SABnzbd\scripts\converter\__init__.py", line 27, in __init__
    ffprobe_path=ffprobe_path)
  File "C:\Program Files (x86)\SABnzbd\scripts\converter\ffmpeg.py", line 361, in __init__
    raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path)
converter.ffmpeg.FFMpegError: ffmpeg binary not found: \"C:\Program Files (x86)\FFMPEG\bin\"

**Comment by mdhiggins** [comment]
It wants the path to ffmpeg.exe (and ffprobe.exe for the ffprobe option)

**Comment by wraith1385** [comment]
Isn't "C:\\Program Files (x86)\\FFMPEG\\bin" the path?  That's the folder where I have the ffmpeg.exe located.

**Comment by mdhiggins** [comment]
Just edited my above comment, take a look

**Comment by wraith1385** [comment]
Hey thanks for answering all of my stupid questions.  I finally got it working.  

One last question, if I leave the Sick Beard section of autoProcess.ini blanks, will the script process correctly without trying to handoff back to Sick Beard?  I use Sick Beard to snatch my files, but I generally don't let it manage my media.

**Comment by mdhiggins** [comment]
Without passing back to Sickbeard the script won't tag the files, but it will be able to convert no problem if that's how you have your settings configured. The script depends on Sickbeard to pass the tvdb information for tagging so if you don't pass it back it won't tag.



—

**Comment by wraith1385** [comment]
I'm fine with that. In case you couldn't tell I have a weird setup.

Once again thank you for all of your help.
