### ISSUE TITLE
Error converting MKV

### ISSUE THREAD

**Issue by belim** [mdhiggins/sickbeard_mp4_automator#271]
Having an issue converting MKV files when running manually, details below

```
$ ./manual.py -i /data/tv/House/Season\ 01/House\ -\ S01E01\ -\ Pilot.mkv
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Matched TV episode as House (TVDB ID:73255) S01E01
Proceed using guessed identification from filename?
# [y/n]: y
Processing House Season 01 Episode 01 - Pilot
Reading video stream.
Video codec detected: h264
Reading audio streams.
Audio detected for stream #1: ac3 [eng].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source audio stream 1.
Reading subtitle streams.
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "eng"
        },
        "1": {
            "channels": 6,
            "map": 1,
            "codec": "copy",
            "bitrate": 1536,
            "language": "eng"
        }
    },
    "video": {
        "map": 0,
        "codec": "copy",
        "bitrate": 4060.4766999999997
    },
    "format": "mp4"
}
Starting conversion.
Traceback (most recent call last):
  File "./manual.py", line 331, in <module>
    main()
  File "./manual.py", line 322, in main
    processFile(path, tagdata)
  File "./manual.py", line 198, in processFile
    output = converter.process(inputfile, True)
  File "/home/media/.mp4_automator/mkvtomp4.py", line 144, in process
    outputfile, inputfile = self.convert(inputfile, options, reportProgress)
  File "/home/media/.mp4_automator/mkvtomp4.py", line 528, in convert
    for timecode in conv:
  File "/home/media/.mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/home/media/.mp4_automator/converter/ffmpeg.py", line 541, in convert
    total_output, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=23940, cmd="/usr/bin/ffmpeg -fix_sub_duration -i /data/tv/House/Season 01/House - S01E01 - Pilot.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -f mp4 -threads auto -y /data/tv/House/Season 01/House - S01E01 - Pilot.mp4">
```
And when running the command manually for more detail I get:

```
$ /usr/bin/ffmpeg -i "/data/tv/House/Season 01/House - S01E01 - Pilot.mkv" -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -f mp4 -threads auto -y "/data/tv/House/Season 01/House - S01E01 - Pilot.mp4"
ffmpeg version 2.3.4 Copyright (c) 2000-2014 the FFmpeg developers
  built on Feb 25 2015 16:24:30 with gcc 4.8.2 (GCC) 20140120 (Red Hat 4.8.2-16)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --enable-bzlib --disable-crystalhd --enable-gnutls --enable-libass --enable-libcdio --enable-libdc1394 --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libx264 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      52. 92.100 / 52. 92.100
  libavcodec     55. 69.100 / 55. 69.100
  libavformat    55. 48.100 / 55. 48.100
  libavdevice    55. 13.102 / 55. 13.102
  libavfilter     4. 11.100 /  4. 11.100
  libavresample   1.  3.  0 /  1.  3.  0
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100
Input #0, matroska,webm, from '/data/tv/House/Season 01/House - S01E01 - Pilot.mkv':
  Metadata:
    title           : House, M.D. - S01E01 - Pilot - Everybody Lies
    encoder         : libebml v1.3.0 + libmatroska v1.4.0
    creation_time   : 2013-07-13 00:12:30
  Duration: 00:44:02.94, start: 0.000000, bitrate: 4658 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      title           : House, M.D. - S01E01 - Pilot - Everybody Lies
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s
    Metadata:
      title           : AC3 5.1 384 kbps
[AVFilterGraph @ 0x135bae0] [Eval @ 0x7fff66be75b0] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0x135bae0] Unable to parse option value "auto"
[mp4 @ 0x135b300] track 2: codec frame size is not set
Output #0, mp4, to '/data/tv/House/Season 01/House - S01E01 - Pilot.mp4':
  Metadata:
    title           : House, M.D. - S01E01 - Pilot - Everybody Lies
    encoder         : Lavf55.48.100
    Stream #0:0(eng): Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 16k tbn, 1k tbc (default)
    Metadata:
      title           : House, M.D. - S01E01 - Pilot - Everybody Lies
    Stream #0:1(eng): Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp, 256 kb/s
    Metadata:
      title           : AC3 5.1 384 kbps
      encoder         : Lavc55.69.100 aac
    Stream #0:2(eng): Audio: ac3 ([165][0][0][0] / 0x00A5), 48000 Hz, 5.1(side), 384 kb/s
    Metadata:
      title           : AC3 5.1 384 kbps
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (native))
  Stream #0:1 -> #0:2 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x135b300] Invalid DTS: 8000 PTS: 6672 in output stream 0:0
[mp4 @ 0x135b300] Encoder did not produce proper pts, making some up.
[mp4 @ 0x135b300] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 7360 >= 6672
av_interleaved_write_frame(): Invalid argument
frame=   13 fps=0.0 q=-1.0 Lsize=     271kB time=00:00:00.64 bitrate=3464.5kbits/s
video:253kB audio:49kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
```

**Comment by mdhiggins** [comment]
Are you getting this with every file or just this one specific one?

https://trac.ffmpeg.org/ticket/1154

It appears to be a bug with FFMPEG but it should be exceedingly rare.
