### ISSUE TITLE
strange error in SickRage log

### ISSUE THREAD

**Issue by andyblac** [mdhiggins/sickbeard_mp4_automator#281]
getting this on every post process 
```
2015-06-29 10:01:17 INFO     POSTPROCESSER :: Processing succeeded for /volume1/downloads/Complete/TVShows/Ready/Falling.Skies.S05E01.1080p.WEB-DL.DD5.1.H.264.HKD.mkv
AA
AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/usr/local/python/lib/python2.7/json/decoder.py", line 384, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/usr/local/python/lib/python2.7/json/decoder.py", line 366, in decode
AA    return _default_decoder.decode(s)
AA  File "/usr/local/python/lib/python2.7/json/__init__.py", line 338, in loads
AA    **kw)
AA  File "/usr/local/python/lib/python2.7/json/__init__.py", line 290, in load
AA    refresh = json.load(urllib.urlopen(settings.getRefreshURL(tvdb_id)))
AA  File "/var/services/homes/sickrage/scripts/mp4_automator/postConversion.py", line 55, in <module>
AATraceback (most recent call last):
AA2015-06-29 10:01:14 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
AA2015-06-29 10:01:14 - mkvtomp4 - INFO - /volume3/media/TVShows/Falling Skies/Falling.Skies.S05E01.Find.Your.Warrior.1080p.WEB-DL.m4v created.
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Starting conversion.
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Creating subtitle stream 0 from source subtitle stream 2.
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Subtitle detected for stream #2: srt [eng].
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Reading subtitle streams.
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Creating audio stream 1 from source audio stream 1.
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng].
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Reading audio streams.
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Video codec detected: h264
AA2015-06-29 09:59:41 - mkvtomp4 - INFO - Reading video stream.
AA2015-06-29 09:59:41 - SickbeardPostConversion - INFO - Processing /volume3/media/TVShows/Falling Skies/Falling.Skies.S05E01.Find.Your.Warrior.1080p.WEB-DL.mkv.
AA
AAAttributeError: 'Home' object has no attribute 'api/********************************'
AA    method = getattr(self, route)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 241, in get
2015-06-29 09:59:39 INFO     POSTPROCESSER :: Executing command [u'/var/services/homes/sickrage/scripts/mp4_automator/postConversion.py', u'/volume3/media/TVShows/Falling Skies/Falling.Skies.S05E01.Find.Your.Warrior.1080p.WEB-DL.mkv', u'/volume1/downloads/Complete/TVShows/Ready/Falling.Skies.S05E01.1080p.WEB-DL.DD5.1.H.264.HKD.mkv', '205281', '5', '1', '2015-06-28']
2015-06-29 09:59:35 INFO     POSTPROCESSER :: Processing /volume1/downloads/Complete/TVShows/Ready/Falling.Skies.S05E01.1080p.WEB-DL.DD5.1.H.264.HKD.mkv (None)
```

any ideas what is causing it, it does not seem to be doing any harm, everything seems to run ok.

**Comment by mdhiggins** [comment]
I see multiple instances in the log that suggest your autoProcess.ini settings that provide the information for Sickrage aren't correct, perhaps the username or password, or maybe an HTTPS issue. The script seems to be failing to pass the final notice back to Sickrage, which isn't really an important step other than for tidying up the final path so Sickrage is informed of the file extension change, which is probably why it seems to work.

I would go back and verify this information in the config and see if it resolves

**Comment by andyblac** [comment]
i had it sietup with no user / pass i have just added a user/[ass will let you know the result.

**Comment by andyblac** [comment]
just the same result, could you so me sample of a sickrage setting block so i can check against mine

**Comment by andyblac** [comment]
here is output
```
2015-07-02 15:40:56 INFO     POSTPROCESSER :: Processing completed
2015-07-02 15:40:56 INFO     POSTPROCESSER :: PostProcessing Path: /volume1/downloads/Complete/TVShows/Ready
2015-07-02 15:38:31 INFO     POSTPROCESSER :: [Bonus.rar : Nothing was unpacked (file permissions?)]
2015-07-02 15:38:31 INFO     POSTPROCESSER :: I did encounter some unprocessable items: 
2015-07-02 15:38:31 INFO     POSTPROCESSER :: Processing completed
2015-07-02 15:38:31 INFO     POSTPROCESSER :: Deleting folder (if it's empty): /volume1/downloads/Complete/TVShows/Ready/Luther.S01E04.UNCUT.720p.BluRay.X264-iNGOT
2015-07-02 15:38:31 INFO     POSTPROCESSER :: Processing succeeded for /volume1/downloads/Complete/TVShows/Ready/Luther.S01E04.UNCUT.720p.BluRay.X264-iNGOT/luther.s01e04.uncut.720p.bluray.x264-ingot.mkv
AA
AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/usr/local/python/lib/python2.7/json/decoder.py", line 384, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/usr/local/python/lib/python2.7/json/decoder.py", line 366, in decode
AA    return _default_decoder.decode(s)
AA  File "/usr/local/python/lib/python2.7/json/__init__.py", line 338, in loads
AA    **kw)
AA  File "/usr/local/python/lib/python2.7/json/__init__.py", line 290, in load
AA    refresh = json.load(urllib.urlopen(settings.getRefreshURL(tvdb_id)))
AA  File "/var/services/homes/sickrage/scripts/mp4_automator/postConversion.py", line 55, in <module>
AATraceback (most recent call last):
AA2015-07-02 15:38:24 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
AA2015-07-02 15:38:24 - mkvtomp4 - INFO - /volume3/media/TVShows/Luther/Luther.S01E04.Episode.4.720p.BluRay.m4v created.
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Starting conversion.
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Creating subtitle stream 1 from source subtitle stream 3.
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Subtitle detected for stream #3: srt [eng].
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Creating subtitle stream 0 from source subtitle stream 2.
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Subtitle detected for stream #2: srt [eng].
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Reading subtitle streams.
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Creating audio stream 1 from source audio stream 1.
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Audio detected for stream #1: dca [eng].
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Reading audio streams.
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Video codec detected: h264
AA2015-07-02 15:36:16 - mkvtomp4 - INFO - Reading video stream.
AA2015-07-02 15:36:16 - SickbeardPostConversion - INFO - Processing /volume3/media/TVShows/Luther/Luther.S01E04.Episode.4.720p.BluRay.mkv.
2015-07-02 15:37:40 INFO     TORNADO :: User logged into the SickRage web interface from IP: 192.168.2.22
2015-07-02 15:36:15 INFO     POSTPROCESSER :: Executing command [u'/var/services/homes/sickrage/scripts/mp4_automator/postConversion.py', u'/volume3/media/TVShows/Luther/Luther.S01E04.Episode.4.720p.BluRay.mkv', u'/volume1/downloads/Complete/TVShows/Ready/Luther.S01E04.UNCUT.720p.BluRay.X264-iNGOT/luther.s01e04.uncut.720p.bluray.x264-ingot.mkv', '159591', '1', '4', '2010-05-25']
2015-07-02 15:36:04 INFO     POSTPROCESSER :: Trying to clean any empty folders under /volume3/media/TVShows/Luther
2015-07-02 15:36:04 INFO     POSTPROCESSER :: Processing /volume1/downloads/Complete/TVShows/Ready/Luther.S01E04.UNCUT.720p.BluRay.X264-iNGOT/luther.s01e04.uncut.720p.bluray.x264-ingot.mkv (None)
```

**Comment by mdhiggins** [comment]
Try updating to the latest commit and see if you're getting the same error. This still looks like an issue of the refresh command not working with Sickrage (its possible they've changed this and it no longer functions the same way the Sickbeard refresh command works)

**Comment by mdhiggins** [comment]
Actually I think I know what's wrong. Do the update and also try putting your same Sickrage settings (host port api user pass) into the SickBEARD section of autoProcess.ini

I think that will likely be what fixes it

**Comment by andyblac** [comment]
just same
```
2015-07-03 15:17:09 INFO     POSTPROCESSER :: Processing succeeded for /volume1/downloads/Complete/TVShows/Ready/Graceland.S03E02.Chester.Cheeto.1080p.WEB-DL.DD5.1.H.264-GL/Graceland.S03E02.Chester.Cheeto.1080p.WEB-DL.DD5.1.H.264-GL.mkv
AA
AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/usr/local/python/lib/python2.7/json/decoder.py", line 384, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/usr/local/python/lib/python2.7/json/decoder.py", line 366, in decode
AA    return _default_decoder.decode(s)
AA  File "/usr/local/python/lib/python2.7/json/__init__.py", line 338, in loads
AA    **kw)
AA  File "/usr/local/python/lib/python2.7/json/__init__.py", line 290, in load
AA    refresh = json.load(urllib.urlopen(settings.getRefreshURL(tvdb_id)))
AA  File "/var/services/homes/********/scripts/mp4_automator/postConversion.py", line 55, in <module>
AATraceback (most recent call last):
AA2015-07-03 15:17:09 - SickbeardPostConversion - ERROR - Couldn't refresh Sickbeard, check your autoProcess.ini settings.
AA2015-07-03 15:17:06 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
AA2015-07-03 15:17:06 - mkvtomp4 - INFO - /volume3/media/TVShows/Graceland/Graceland.S03E02.Chester.Cheeto.1080p.WEB-DL.m4v created.
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Starting conversion.
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Creating subtitle stream 0 from source subtitle stream 2.
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Subtitle detected for stream #2: srt [eng].
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Reading subtitle streams.
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Creating audio stream 1 from source audio stream 1.
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng].
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Reading audio streams.
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Video codec detected: h264
AA2015-07-03 15:16:10 - mkvtomp4 - INFO - Reading video stream.
AA2015-07-03 15:16:10 - SickbeardPostConversion - INFO - Processing /volume3/media/TVShows/Graceland/Graceland.S03E02.Chester.Cheeto.1080p.WEB-DL.mkv.
2015-07-03 15:16:09 INFO     POSTPROCESSER :: Executing command [u'/var/services/homes/********/scripts/mp4_automator/postConversion.py', u'/volume3/media/TVShows/Graceland/Graceland.S03E02.Chester.Cheeto.1080p.WEB-DL.mkv', u'/volume1/downloads/Complete/TVShows/Ready/Graceland.S03E02.Chester.Cheeto.1080p.WEB-DL.DD5.1.H.264-GL/Graceland.S03E02.Chester.Cheeto.1080p.WEB-DL.DD5.1.H.264-GL.mkv', '260338', '3', '2', '2015-07-02']
```

**Comment by andyblac** [comment]
might have been have i had '/home' in web_root, i have removed will let you know when i post process the next file.

**Comment by andyblac** [comment]
seems that was it :)
```
2015-07-04 13:05:43 INFO     POSTPROCESSER :: Processing completed
2015-07-04 13:05:43 INFO     POSTPROCESSER :: Deleting folder (if it's empty): /volume1/downloads/Complete/TVShows/Ready/Defiance.S03E05.1080p.WEB-DL.DD5.1.H.264-ECI[rarbg]
2015-07-04 13:05:43 INFO     POSTPROCESSER :: Processing succeeded for /volume1/downloads/Complete/TVShows/Ready/Defiance.S03E05.1080p.WEB-DL.DD5.1.H.264-ECI[rarbg]/Defiance.S03E05.History.Rythmes.1080p.WEB-DL.DD5.1.H.264-ECI.mkv
AA
AA2015-07-04 13:05:40 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
AA2015-07-04 13:05:39 - mkvtomp4 - INFO - /volume3/media/TVShows/Defiance/Defiance.S03E05.History.Rhymes.1080p.WEB-DL.m4v created.
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Starting conversion.
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Creating subtitle stream 0 from source subtitle stream 2.
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Subtitle detected for stream #2: srt [eng].
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Reading subtitle streams.
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Creating audio stream 1 from source audio stream 1.
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng].
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Reading audio streams.
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Video codec detected: h264
AA2015-07-04 13:04:14 - mkvtomp4 - INFO - Reading video stream.
AA2015-07-04 13:04:14 - SickbeardPostConversion - INFO - Processing /volume3/media/TVShows/Defiance/Defiance.S03E05.History.Rhymes.1080p.WEB-DL.mkv.
2015-07-04 13:04:12 INFO     POSTPROCESSER :: Executing command [u'/var/services/homes/********/scripts/mp4_automator/postConversion.py', u'/volume3/media/TVShows/Defiance/Defiance.S03E05.History.Rhymes.1080p.WEB-DL.mkv', u'/volume1/downloads/Complete/TVShows/Ready/Defiance.S03E05.1080p.WEB-DL.DD5.1.H.264-ECI[rarbg]/Defiance.S03E05.History.Rythmes.1080p.WEB-DL.DD5.1.H.264-ECI.mkv', '255326', '3', '5', '2015-07-03']
2015-07-04 13:04:01 INFO     POSTPROCESSER :: Processing /volume1/downloads/Complete/TVShows/Ready/Defiance.S03E05.1080p.WEB-DL.DD5.1.H.264-ECI[rarbg]/Defiance.S03E05.History.Rythmes.1080p.WEB-DL.DD5.1.H.264-ECI.mkv (None)
2
```
