### ISSUE TITLE
Subliminal Not Installed...

### ISSUE THREAD

**Issue by screwzloose** [mdhiggins/sickbeard_mp4_automator#288]
Manual processor started.
Subliminal is not installed, automatically downloading of subs has been disabled.
Traceback (most recent call last):
  File "/mnt/mp4con/readSettings.py", line 231, in __init__
    import subliminal
  File "/mnt/mp4con/setup/subliminal/subliminal/__init__.py", line 9, in <module>
    from .api import list_subtitles, download_subtitles, download_best_subtitles, save_subtitles
  File "/mnt/mp4con/setup/subliminal/subliminal/api.py", line 9, in <module>
    from .providers import ProviderPool
  File "/mnt/mp4con/setup/subliminal/subliminal/providers/__init__.py", line 8, in <module>
    import requests
ImportError: No module named requests
64bit Python.

//

This issue started with when I upgraded to the latest version of Subliminal. Tried reinstalling. Any thoughts?

Thanks,
Screwz

**Comment by mdhiggins** [comment]
`ImportError: No module named requests`

You need to install the requests module. Do a `pip install requests` to fix this.

**Comment by strafer** [comment]
I'm getting the same error as the OP, except I have everything installed including requests. 

2016-04-28 10:21:32 - readSettings - ERROR - Subliminal is not installed, automatically downloading of subs has been disabled.
Traceback (most recent call last):
  File "/Users/user/sickbeard_mp4_automator/readSettings.py", line 262, in __init__
    import subliminal
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/subliminal/__init__.py", line 10, in <module>
    from .api import (ProviderPool, check_video, provider_manager, download_best_subtitles, download_subtitles,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/subliminal/api.py", line 13, in <module>
    from .subtitle import compute_score, get_subtitle_path
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/subliminal/subtitle.py", line 7, in <module>
    from guessit.matchtree import MatchTree
ImportError: No module named matchtree
