### ISSUE TITLE
subliminal - ValueError: The guess must be an episode or a movie guess

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#296]
on windows, python 2.7.5

command:
`python manual.py -i C:\test\showname.s28e07.720p.hdtv.x264-nogrp.mkv -a`

autoProcess.ini
```
[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
audio-codec = aac
video-codec = h264,x264
video-bitrate = 1400
h264-max-level = 3.1
ios-audio = True
max-audio-channels = 2
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 192
subtitle-language = eng
subtitle-default-language = eng
fullpathguess = True
convert-mp4 = False
tagfile = False
tag-language = en
download-artwork = False
download-subs = True
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
ios-first-track-only = False
subtitle-codec = mov_text
video-max-width = 720
```

results in:
```
Attempting to download subtitles.
Unable to download subtitles.
Traceback (most recent call last):
  File "C:\Program Files (x86)\sickbeard_mp4_automator\mkvtomp4.py", line 455, in generateOptions
    video = subliminal.scan_video(os.path.abspath(inputfile.decode(sys.getfilesystemencoding())), subtitles=True, embedded_subtitles=True, original=original)
  File "build\bdist.win32\egg\subliminal\video.py", line 207, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(original, 'autodetect'))
  File "build\bdist.win32\egg\subliminal\video.py", line 69, in fromguess
    raise ValueError('The guess must be an episode or a movie guess')
ValueError: The guess must be an episode or a movie guess
```

**Comment by thezoggy** [comment]
did
`pip uninstall subliminal`

then re-installed subliminal doing 'python setup.py install' from within the setup/subliminal folder, no change...

**Comment by thezoggy** [comment]
https://github.com/Diaoul/subliminal/issues/352
  >  'autodetect' has been removed from version 0.7.1 of guessit.

from `pip freeze`
subliminal==0.8.0-dev
guessit==0.10.3

**Comment by thezoggy** [comment]
installed latest subliminal (1.0.1) now I see:
```
Attempting to download subtitles.
Unable to download subtitles.
Traceback (most recent call last):
  File "C:\Program Files (x86)\sickbeard_mp4_automator\mkvtomp4.py", line 455, in generateOptions
    video = subliminal.scan_video(os.path.abspath(inputfile.decode(sys.getfilesystemencoding())), subtitles=True, embedded_subtitles=True, original=original)
TypeError: scan_video() got an unexpected keyword argument 'original'
```

**Comment by mdhiggins** [comment]
Subliminal fixed with latest commit
