### ISSUE TITLE
typo in autoprocess.ini.sample

### ISSUE THREAD

**Issue by moltra** [mdhiggins/sickbeard_mp4_automator#298]
I am getting the following error when I try and run the script

[code]Manual processor started.
Traceback (most recent call last):
  File "manual.py", line 31, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini", logger=log)
  File "/home/mark/Downloads/sickbeard_mp4_automator-master/readSettings.py", line 203, in __init__
    self.relocate_moov = config.getboolean(section, "relocate_moov")  # Relocate MOOV atom to start of file
  File "/usr/lib/python2.7/ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean: True1
[/code]

In line 26 the value is True1 should be True.

**Comment by mdhiggins** [comment]
Thanks. This has been fixed
