### ISSUE TITLE
TVDB tagging not working

### ISSUE THREAD

**Issue by Trixter69** [mdhiggins/sickbeard_mp4_automator#299]
Hello,

This has been working perfectly until a few days ago when i updated via GIT. Since then every show I run it on has the same error when trying to pull the TVDB info.

"Show-name search returned zero results (cannot find show on TVDB)"

now I've tried to specify the show, Season and episode but get this error when i do

"Failed to connect to TVDB, trying again in 20 seconds.
Traceback (most recent call last):
  File "C:\Scripts\tvdb_mp4.py", line 35, in __init__
    self.showdata = self.tvdb_show[self.show]
  File "C:\Scripts\tvdb_api\tvdb_api.py", line 948, in __getitem__
    self._getShowData(key, self.config['language'])
  File "C:\Scripts\tvdb_api\tvdb_api.py", line 854, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "C:\Scripts\tvdb_api\tvdb_api.py", line 621, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "C:\Scripts\tvdb_api\tvdb_api.py", line 588, in _loadUrl
    raise tvdb_error("Could not connect to server: %s" % (errormsg))
tvdb_error: Could not connect to server: HTTP Error 404: Not Found"

Ive tried re-basing and and even  did a new clone with the same results.
Thank you for any help
Trixter

**Comment by mdhiggins** [comment]
Hm I'm having trouble replicating this. My setup is working fine and I haven't changed anything related to the TVDB tagging in quite some time.

Might be an issue on your end? Did you try a clean install?

**Comment by Trixter69** [comment]
Yes i tried a clean install and on two different OS's MAC and Win 7.

I'm going to try and install using the zip next as I've been using GIT clone to check out the new install.

**Comment by mdhiggins** [comment]
Are you able to access the tvdb api through your web browser? Looks like it's failing to connect to the servers

**Comment by Trixter69** [comment]
yes i can access the server and run a API call correctly, its that the API call script is adding country code (hm) to all shows.

as soon as i removed HM from the country code from the recognized list the API calls started working. like a said in the previous post I don't know why the guessit is identifying all shows as country code HM.

**Comment by Trixter69** [comment]
ok i found the issue, i have my series broken up by alphabet. eg.
Series a-g/Series/Season/show.exe
Series h-m/Series/Season/show.exe

the issue is that guessit looks as the hole filepath so it sees the series h-m and tags the file as country code HM or AG or anything that it matches on the list.

**Comment by mdhiggins** [comment]
There's an option to disable full-path guess that should hopefully resolve your issue in autoProcess.ini

**Comment by totallyGreg** [comment]
I'm having the same issue with automatic tagging 
"Show-name search returned zero results (cannot find show on TVDB)" 

but if I specify the tvdb ID manually it tags everything fine.  How do I run manual.py -a in DEBUG mode to see what guessit is doing wrong?

**Comment by mdhiggins** [comment]
Is it doing it for every show or just one in particular? Also what is the full path?




And you can adjust logging levels in logging.ini

**Comment by totallyGreg** [comment]
It seems like lately it's been having issues with all my shows.   Here is one example of a laptop local file.  (I usually run it from my FreeNAS box.  )
/Users/totally/Music/iTunes/iTunes Media/TV Shows/Rick and Morty/Season 2/S02E04-Total\ Rickall-WEBDL-1080p.m4v 

I had changed handler_manualHandler to DEBUGi but I was not able to get anything more from Guessit 
Changing consoleHandler to DEBUG seemed to give me way more info.  Thanks. 

It seems to be getting the season and episode correctly but confusing the episode title with the show Title.  
fullpathguess = True 

S02E04-Total Rickall-WEBDL-1080p.m4v is valid.
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_idnumber = guessit.transfo.guess_idnumber:GuessIdnumber')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_bonus_features = guessit.transfo.guess_bonus_features:GuessBonusFeatures')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_date = guessit.transfo.guess_date:GuessDate')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('expected_title = guessit.transfo.expected_title:ExpectedTitle')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('expected_series = guessit.transfo.expected_series:ExpectedSeries')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('split_path_components = guessit.transfo.split_path_components:SplitPathComponents')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_properties = guessit.transfo.guess_properties:GuessProperties')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_release_group = guessit.transfo.guess_release_group:GuessReleaseGroup')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('split_explicit_groups = guessit.transfo.split_explicit_groups:SplitExplicitGroups')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_episode_details = guessit.transfo.guess_episode_details:GuessEpisodeDetails')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_episodes_rexps = guessit.transfo.guess_episodes_rexps:GuessEpisodesRexps')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_weak_episodes_rexps = guessit.transfo.guess_weak_episodes_rexps:GuessWeakEpisodesRexps')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_episode_info_from_position = guessit.transfo.guess_episode_info_from_position:GuessEpisodeInfoFromPosition')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('split_on_dash = guessit.transfo.split_on_dash:SplitOnDash')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_movie_title_from_position = guessit.transfo.guess_movie_title_from_position:GuessMovieTitleFromPosition')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_video_rexps = guessit.transfo.guess_video_rexps:GuessVideoRexps')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_country = guessit.transfo.guess_country:GuessCountry')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_language = guessit.transfo.guess_language:GuessLanguage')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_website = guessit.transfo.guess_website:GuessWebsite')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_year = guessit.transfo.guess_year:GuessYear')
2015-08-26 19:32:30 - stevedore.extension - DEBUG - found extension EntryPoint.parse('guess_filetype = guessit.transfo.guess_filetype:GuessFiletype')
2015-08-26 19:32:30 - GuessFiletype - DEBUG - Found guess_episodes_rexps: {u'season': 2, u'episodeNumber': 4} -> type = episode
2015-08-26 19:32:30 - GuessProperties - DEBUG - Property found: format=WEB-DL (WEBDL) (confidence=1.00)
2015-08-26 19:32:30 - GuessProperties - DEBUG - Property found: screenSize=1080p (1080p) (confidence=1.00)
2015-08-26 19:32:30 - GuessProperties - DEBUG - Property found: container=m4v (m4v) (confidence=0.30)
2015-08-26 19:32:30 - GuessEpisodesRexps - DEBUG - Property found: season=2 (S02E04) (confidence=1.00)
2015-08-26 19:32:30 - GuessEpisodesRexps - DEBUG - Property found: episodeNumber=4 (S02E04) (confidence=1.00)
2015-08-26 19:32:30 - GuessEpisodeInfoFromPosition - DEBUG - Property found: title=Total Rickall (Total Rickall) (confidence=0.50)
2015-08-26 19:32:30 - tvdb_api - DEBUG - Getting show total rickall
2015-08-26 19:32:30 - tvdb_api - DEBUG - Searching for show total%20rickall
2015-08-26 19:32:30 - tvdb_api - DEBUG - Retrieving URL http://thetvdb.com/api/GetSeries.php?seriesname=total%20rickall&language=en
2015-08-26 19:32:31 - tvdb_api - DEBUG - Series result returned zero
Show-name search returned zero results (cannot find show on TVDB)

**Comment by mdhiggins** [comment]
Seems like guessit doesn't like that you don't have the show name in the file title. Not sure if there's much we can do to fix that (since I'm not the guessit dev) other than opening an issue on their page. I would try just adjusting my file naming scheme to include the tv show title at the beginning of the file.

**Comment by totallyGreg** [comment]
Okay that does correspond with a success I have had with another show I was testing on my FreeNAS box.  Thanks for the help and as well maintaining this wonderful tool.

**Comment by mdhiggins** [comment]
No problem. Gonna close this since its more of an issue with guessit
