### ISSUE TITLE
output-directory isn't fuctioning

### ISSUE THREAD

**Issue by enz1ey** [mdhiggins/sickbeard_mp4_automator#301]
I'm putting a path in the output-directory line in autoProcess.ini and it's still using the original path to process the file. I also tried putting a directory in the move-to line and it doesn't do anything with that either. The logs show nothing about either line.

**Comment by mdhiggins** [comment]
Hm both of these options are working fine for me under the latest versions. Almost sounds like your config file isn't being recognized or loaded, or you're editing the wrong config file.

**Comment by enz1ey** [comment]
It's weird, it'll work correctly if I manually run the script, but not if SabNZBD runs it. It's okay, though, it's a cloud storage mount and it probably won't let the script write there anyways so I'm looking for a workaround.

**Comment by enz1ey** [comment]
Is it possible to run a bash script in the post_process directory? I'm trying to run an acd_cli upload command during processing so I don't run out of drive space, but it doesn't seem like the script runs. Permissions are 777.

**Comment by mdhiggins** [comment]
I'm surprised that the output directory function isn't working. You don't have multiple instances of the script on your setup where SAB is running its own version do you? Any information in the log file for SABs post processing stuff?




Also if there are any logs from the post process thing send me that too.

**Comment by enz1ey** [comment]
Does your script have its own logs stored anywhere? There doesn't seem to be anything in the SAB logs, just basically the output of the SABpostProcess.py script. I figured out why the output_directory switch wasn't working, it was a FUSE issue. But I'm trying to run a post_processing script and it just seems to get skipped over according to the output in SAB, however it runs the script when I use manual.py. The directories are all pointing to the same script folder.

**Comment by mdhiggins** [comment]
Info.log file in the scripts directory

**Comment by enz1ey** [comment]
2015-08-24 14:55:48 - SABPostProcess - INFO - SAB post processing started.
2015-08-24 14:55:48 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-08-24 14:55:48 - SABPostProcess - INFO - Performing conversion
2015-08-24 14:55:48 - SABPostProcess - INFO - Processing file /home/enzTV/Downloads/Complete/Southland.S05E03.720p.WEB-DL.DD5.1.H.264-KiNGS/Southland.S05E03.720p.WEB-DL.DD5.1.H.264-KiNGS.mkv.
2015-08-24 14:55:48 - mkvtomp4 - INFO - Reading video stream.
2015-08-24 14:55:48 - mkvtomp4 - INFO - Video codec detected: h264
2015-08-24 14:55:48 - mkvtomp4 - INFO - Pix Fmt: yuv420p
2015-08-24 14:55:48 - mkvtomp4 - INFO - Reading audio streams.
2015-08-24 14:55:48 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng].
2015-08-24 14:55:48 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2015-08-24 14:55:48 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2015-08-24 14:55:48 - mkvtomp4 - INFO - Reading subtitle streams.
2015-08-24 14:55:48 - mkvtomp4 - INFO - Subtitle detected for stream #2: srt [und].
2015-08-24 14:55:48 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 2.
2015-08-24 14:55:48 - mkvtomp4 - INFO - Starting conversion.
2015-08-24 14:57:36 - mkvtomp4 - INFO - /home/enzTV/Downloads/Complete/Southland.S05E03.720p.WEB-DL.DD5.1.H.264-KiNGS/Southland.S05E03.720p.WEB-DL.DD5.1.H.264-KiNGS.m4v created.
2015-08-24 14:57:36 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
2015-08-24 14:57:50 - SABPostProcess - INFO - Passing /home/enzTV/Downloads/Complete/Southland.S05E03.720p.WEB-DL.DD5.1.H.264-KiNGS directory to Sonarr.
2015-08-24 14:57:50 - autoprocess.sonarr - INFO - Sonarr notifier started.
2015-08-24 14:57:50 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/home/enzTV/Downloads/Complete/Southland.S05E03.720p.WEB-DL.DD5.1.H.264-KiNGS'.
2015-08-24 14:57:50 - urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2015-08-24 14:57:51 - autoprocess.sonarr - INFO - Sonarr response: queued.

**Comment by enz1ey** [comment]
2015-08-24 19:31:33 - MANUAL - INFO - Manual processor started.
2015-08-24 19:31:33 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-08-24 19:31:33 - stevedore.extension - ERROR - Could not load u'guess_date': No module named dateutil
2015-08-24 19:31:33 - stevedore.extension - ERROR - No module named dateutil
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 162, in _load_plugins
    verify_requirements,
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/plugins/transformers.py", line 96, in _load_one_plugin
    plugin = ep.load(require=False)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/transfo/guess_date.py", line 25, in <module>
    from guessit.date import search_date
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/date.py", line 27, in <module>
    from dateutil import parser
ImportError: No module named dateutil
2015-08-24 19:31:34 - stevedore.extension - ERROR - Could not load u'guess_weak_episodes_rexps': No module named dateutil
2015-08-24 19:31:34 - stevedore.extension - ERROR - No module named dateutil
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 162, in _load_plugins
    verify_requirements,
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/plugins/transformers.py", line 96, in _load_one_plugin
    plugin = ep.load(require=False)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/transfo/guess_weak_episodes_rexps.py", line 28, in <module>
    from guessit.date import valid_year
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/date.py", line 27, in <module>
    from dateutil import parser
ImportError: No module named dateutil
2015-08-24 19:31:34 - stevedore.extension - ERROR - Could not load u'guess_year': No module named dateutil
2015-08-24 19:31:34 - stevedore.extension - ERROR - No module named dateutil
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/stevedore/extension.py", line 162, in _load_plugins
    verify_requirements,
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/plugins/transformers.py", line 96, in _load_one_plugin
    plugin = ep.load(require=False)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/transfo/guess_year.py", line 25, in <module>
    from guessit.date import search_year, valid_year
  File "/home/enzTV/Downloads/sickbeard_mp4_automator/guessit/date.py", line 27, in <module>
    from dateutil import parser
ImportError: No module named dateutil
2015-08-24 19:31:38 - MANUAL - INFO - Reading video stream.
2015-08-24 19:31:38 - MANUAL - INFO - Video codec detected: h264
2015-08-24 19:31:38 - MANUAL - INFO - Pix Fmt: yuv420p
2015-08-24 19:31:38 - MANUAL - INFO - Reading audio streams.
2015-08-24 19:31:38 - MANUAL - INFO - Audio detected for stream #1: ac3 [eng].
2015-08-24 19:31:38 - MANUAL - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2015-08-24 19:31:38 - MANUAL - INFO - Creating audio stream 1 from source stream 1.
2015-08-24 19:31:38 - MANUAL - INFO - Reading subtitle streams.
2015-08-24 19:31:38 - MANUAL - INFO - Subtitle detected for stream #2: srt [und].
2015-08-24 19:31:38 - MANUAL - INFO - Creating subtitle stream 0 from source stream 2.
2015-08-24 19:31:38 - MANUAL - INFO - {
    "subtitle": {
        "0": {
            "map": 2, 
            "codec": "mov_text", 
            "language": "und"
        }
    }, 
    "audio": {
        "0": {
            "channels": 2, 
            "map": 1, 
            "codec": "aac", 
            "bitrate": 256, 
            "language": "eng"
        }, 
        "1": {
            "channels": 6, 
            "map": 1, 
            "codec": "copy", 
            "bitrate": 1536, 
            "language": "eng"
        }
    }, 
    "video": {
        "map": 0, 
        "codec": "copy", 
        "bitrate": 3709.1153999999997, 
        "level": null
    }, 
    "format": "mp4"
}
2015-08-24 19:31:38 - MANUAL - INFO - Starting conversion.
2015-08-24 19:33:43 - MANUAL - INFO - /home/enzTV/Downloads/Complete/Southland.S05E04.720p.WEB-DL.DD5.1.H.264-KiNGS/Southland.S05E04.720p.WEB-DL.DD5.1.H.264-KiNGS.m4v created.
2015-08-24 19:33:44 - MANUAL - INFO - Tagging file: /home/enzTV/Downloads/Complete/Southland.S05E04.720p.WEB-DL.DD5.1.H.264-KiNGS/Southland.S05E04.720p.WEB-DL.DD5.1.H.264-KiNGS.m4v.
2015-08-24 19:33:44 - MANUAL - INFO - Trying to write tags.
2015-08-24 19:33:44 - MANUAL - INFO - Tags written successfully.
2015-08-24 19:33:44 - MANUAL - INFO - Relocating MOOV atom to start of file.
2015-08-24 19:34:03 - post_processor - INFO - Running script '/home/enzTV/Downloads/sickbeard_mp4_automator/post_process/upload.sh'.

There is the output in info.log when manual.py is run

**Comment by mdhiggins** [comment]
Looks like there was a mistake in the SAB and NZBGet scripts that was setting the output_dir to none. This has been fixed. Give it a try and let me know if the issue is resolved

**Comment by enz1ey** [comment]
So I'm not crazy lol. Thanks, I'll test it out after work today.
