### ISSUE TITLE
AttributeError: 'module' object has no attribute 'STARTF-USESHOWWINDOW'

### ISSUE THREAD

**Issue by fntrsh13** [mdhiggins/sickbeard_mp4_automator#303]
Hi, I'm running the script via manual.py on windows with all the dependencies on board, every time I get the same error regardless of which video I am trying to process.

```Traceback (most recent call last):
  File "C:\Program Files\Sickbeard mp4 automator\manual.py", line 346, in <module>
    main()
  File "C:\Program Files\Sickbeard mp4 automator\manual.py", line 337, in main
    processFile(path, tagdata)
  File "C:\Program Files\Sickbeard mp4 automator\manual.py", line 199, in processFile
    output = converter.process(inputfile, True)
  File "C:\Program Files\Sickbeard mp4 automator\mkvtomp4.py", line 140, in process
    options = self.generateOptions(inputfile, original=original)
  File "C:\Program Files\Sickbeard mp4 automator\mkvtomp4.py", line 248, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "C:\Program Files\Sickbeard mp4 automator\converter\__init__.py", line 254, in probe
    return self.ffmpeg.probe(fname, posters_as_video)
  File "C:\Program Files\Sickbeard mp4 automator\converter\ffmpeg.py", line 411, in probe
    '-show_format', '-show_streams', fname])
  File "C:\Program Files\Sickbeard mp4 automator\converter\ffmpeg.py", line 375, in _spawn
    startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW' ```

Couldn't find basically anything with the attributeerror 'module'
Any ideas?

**Comment by mdhiggins** [comment]
What version of Python are you running?

**Comment by fntrsh13** [comment]
2.7.0, if I'm not mistaken that's the one mentioned in the guide

**Comment by fntrsh13** [comment]
Little mistake, it is just 2.7, not 2.7.0, 2.7.0 was the version of the requests .whl

**Comment by mdhiggins** [comment]
Try updating to the latest 2.7 version (I forget what the current one is) and see if the issue resolves.

**Comment by fntrsh13** [comment]
It is indeed converting now. Don't have a working video yet but the problem step above is definately fixed.
Thank you! Was stupid not to try upgrading python straight away.
