### ISSUE TITLE
guessit - guess_website error

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#308]
just updated to latest.. saw i need to make sure guessit is installed..
from pip freeze:
```
guessit==0.10.4
stevedore==1.7.0
```

I see the traceback:
```
Manual processor started.
2015-08-29 21:33:12 - stevedore.extension - ERROR - Could not load u'guess_website': [Errno 2] No such file or directory: u'guessit\\tlds-alpha-by-domain.txt'
2015-08-29 21:33:12 - stevedore.extension - ERROR - [Errno 2] No such file or directory: u'guessit\\tlds-alpha-by-domain.txt'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\stevedore-1.7.0-py2.7.egg\stevedore\extension.py", line 162, in _load_plugins
    verify_requirements,
  File "C:\Program Files (x86)\sickbeard_mp4_automator\guessit\plugins\transformers.py", line 96, in _load_one_plugin
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2237, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "C:\Program Files (x86)\sickbeard_mp4_automator\guessit\transfo\guess_website.py", line 29, in <module>
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 920, in resource_stream
    self, resource_name
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 1501, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
IOError: [Errno 2] No such file or directory: u'guessit\\tlds-alpha-by-domain.txt'
32bit Python.
```

**Comment by thezoggy** [comment]
figured out the problem, when it updated it left the old guessit folder still in the mp4 automator root folder.. thus it was trying to use that... deleted that dir and now all is fine.
