### ISSUE TITLE
FFMpegConvertError -- troubleshooting

### ISSUE THREAD

**Issue by thezoggy** [mdhiggins/sickbeard_mp4_automator#312]
When to convert file, ran into FFMpegConvertError.. modified logging.ini to do DEBUG instead of INFO but not seeing anything the helps figure out whats wrong.

Note that seeing `.` at the end of file name / extension / directory I think is wrong.. as people could mistakenly think its actually part of the filename/dir/etc. 

```
File name: shark.tank.s06e15.720p.hdtv.x264-bajskorv.
Input extension: mkv.
Output directory: F:\Shark.Tank.S06E15.720p.HDTV.x264-BAJSKORV.
Output file: F:\Shark.Tank.S06E15.720p.HDTV.x264-BAJSKORV\shark.tank.s06e15.720p.hdtv.x264-bajskorv.mp4.
An unexpected error occurred, processing of this file has failed
<FFMpegConvertError error="Exited with code 1", pid=15464, cmd="C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i F:\Shark.Tank.S06E15.720p.HDTV.x264-BAJSKORV\shark.tank.s06e15.720p.hdtv.x264-bajskorv.mkv -vcodec libx264 -map 0:0 -vb 1400k -level 3.1 -vf scale=720:trunc(ow/a/2)*2 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 192k -metadata:s:a:0 language=eng -strict experimental -c:a:1 libfdk_aac -map 0:1 -ac:a:1 2 -b:a:1 192k -metadata:s:a:1 language=eng -f mp4 -threads auto -y F:\Shark.Tank.S06E15.720p.HDTV.x264-BAJSKORV\shark.tank.s06e15.720p.hdtv.x264-bajskorv.mp4">
```

manually running the command,
```
Unknown encoder 'libfdk_aac'
```

**Comment by thezoggy** [comment]
was reading: https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio
where they mentioned that the best to worst quality for AAC is: `libfdk_aac > libfaac > aac > libvo_aacenc`

thus i changed mp4 .ini to:
`audio-codec = libfdk_aac,libfaac,aac,libvo_aacenc`

but didnt run into this issue until now...

**Comment by thezoggy** [comment]
changed audio-codec list to remove the libfdk_aac:
` audio-codec = libfaac,aac,libvo_aacenc`

Tried running it again, now I see a traceback (so why did I not get one for libfdk but now I do for libfaac):
```
Traceback (most recent call last):
  File "manual.py", line 346, in <module>
    main()
  File "manual.py", line 337, in main
    processFile(path, tagdata)
  File "manual.py", line 199, in processFile
    output = converter.process(inputfile, True)
  File "C:\Program Files (x86)\sickbeard_mp4_automator\mkvtomp4.py", line 150, in process
    outputfile, inputfile = self.convert(inputfile, options, reportProgress)
  File "C:\Program Files (x86)\sickbeard_mp4_automator\mkvtomp4.py", line 566, in convert
    for timecode in conv:
  File "C:\Program Files (x86)\sickbeard_mp4_automator\converter\__init__.py", line 241, in convert
    optlist = self.parse_options(options, twopass)
  File "C:\Program Files (x86)\sickbeard_mp4_automator\converter\__init__.py", line 106, in parse_options
    raise ConverterError('Requested unknown audio codec ' + str(c))
converter.ConverterError: Requested unknown audio codec libfaac
```

**Comment by mdhiggins** [comment]
Not sure why libfdk_aac isn't working except maybe your build of python doesn't have the codec? As far as libfaac goes, I'll push out a commit that adds support for that codec.

**Comment by mdhiggins** [comment]
e3495767d9eb2c72a6811fde93c01787e44beb5f

libfaac support
