### ISSUE TITLE
Unable to run script.

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#323]
Hi Im not sure whats going on but up until today the script has always worked perfect but now it keep getting errors no matter what I try and run.
If I run manual I get
C:\Python27\Converter>manual.py
Traceback (most recent call last):
  File "C:\Python27\Converter\manual.py", line 5, in <module>
    import guessit
  File "C:\Python27\lib\site-packages\guessit\__init__.py", line 88, in <module>
    from guessit.guess import Guess, smart_merge
  File "C:\Python27\lib\site-packages\guessit\guess.py", line 28, in <module>
    from babelfish import Language, Country
  File "C:\Python27\Converter\babelfish\__init__.py", line 7, in <module>
    from ..exceptions import LanguageConvertError, LanguageReverseError
ValueError: Attempted relative import beyond toplevel package

C:\Python27\Converter>

the automated scripts will also fail but noting it being put in the log file.

**Comment by morpheus2n2** [comment]
Fix did a full reinstall of python.
