### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'babelfish/data/iso-3166-1.txt'

### ISSUE THREAD

**Issue by HazCod** [mdhiggins/sickbeard_mp4_automator#337]
Latest git pull after babelfish removal. Did a pip install babelfish myself.
```
Traceback (most recent call last):
  File "SABPostProcess.py", line 6, in <module>
    from readSettings import ReadSettings
  File "/home/media/transcoder/readSettings.py", line 9, in <module>
    from babelfish import Language
  File "/home/media/transcoder/babelfish/__init__.py", line 22, in <module>
    
  File "/home/media/transcoder/babelfish/country.py", line 21, in <module>
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 960, in resource_stream
    self, resource_name
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1511, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')

```

**Comment by xpack90** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/335
