### ISSUE TITLE
Error when manually converting

### ISSUE THREAD

**Issue by KaHooli** [mdhiggins/sickbeard_mp4_automator#339]
When trying to perform a manual conversion, I'm getting an error, here is the output...
```
C:\autoProcess>manual.py -i "c:\Users\Administrator\Desktop\Gruen - S08E05.mp4"
Traceback (most recent call last):
  File "C:\autoProcess\manual.py", line 5, in <module>
    import guessit
  File "C:\autoProcess\guessit\__init__.py", line 89, in <module>

  File "C:\autoProcess\guessit\guess.py", line 24, in <module>
  File "C:\autoProcess\babelfish\__init__.py", line 22, in <module>

  File "C:\autoProcess\babelfish\country.py", line 21, in <module>
  File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 1167, in reso
urce_stream

  File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 1725, in get_
resource_stream

IOError: [Errno 2] No such file or directory: u'C:\\autoProcess\\babelfish\\data
\\iso-3166-1.txt'
```

**Comment by mdhiggins** [comment]
#335

**Comment by KaHooli** [comment]
Thanks, I tried to search for this, and didn't that ticket.  Will try it now.

**Comment by KaHooli** [comment]
Confirmed, this resolved my issue.
