### ISSUE TITLE
REQUEST: Sonarr Tagging?

### ISSUE THREAD

**Issue by PetSue** [mdhiggins/sickbeard_mp4_automator#342]
New to Sonarr as had enough of SB and see your script works on Sonarr but without Tagging. 

Am just wondering please if you are to re-check whether it is possible to now add Tagging to the script?

Thank you :)

**Comment by mdhiggins** [comment]
Tagging is supported if you're running the developer build of Sonarr, the readme simply hasn't been updated because the master build of sonarr still doesnt support post processing scripts.

If you change over the the `develop` branch and update you can configure post processing with tagging using the postSonarr.py file.

See #286

**Comment by PetSue** [comment]
Hi mate,

First off let me apologise to you for what I’m about to ask but I am stumped big time :(

I have had your Script running fine for ages now on SB with some great help from you.

I have had enough of SB as it now doesn’t run in Daemon mode so have switched over to Sonarr, which looks so much better.

So I would like to add your Script for the MP4 Automator but am totally stumped as to how to as there isn’t a folder like SB in Applications.

I am on Mac and wonder if you are able to help me out please as am totally confused on how tog et it working.

Thanks :)

Peter

**Comment by mdhiggins** [comment]
#286

**Comment by PetSue** [comment]
Ok thanks I'm lost but anyways.

**Comment by mdhiggins** [comment]
Quick summary:

- You need to be using the `develop` branch of Sonarr that supports post-processing, the current stable builds do not
- You need the postSonarr.py script which was recently added to the master branch of SMA
- You setup the post proceessing script under Settings > Connect > PostConversion under Sonarr

**Comment by PetSue** [comment]
Hi mate, 

Ok thank you yes I am running the developer build of Sonarr so that's a start. 

I'm just confused with where any files go along with running SABNzb+ 

Looking at it with Sonarr there isn't a folder for the app on Mac as such so not sure where the script goes, or does it just stay in its own folder that you have here or can I rename it?

Sorry am confused as stupid and seems harder than sb :(

**Comment by mdhiggins** [comment]
The script doesn't need to go anywhere specifically you just need to point to the script in the sonarr options as outlined above. The screenshots in the other issue (#286) should be helpful.

**Comment by PetSue** [comment]
Hi mate,

Ok am getting there slowly but still struggling.

Here is the location I have as per the image in #286 - 

Path = /Library/Frameworks/Python.framework/Versions/2.7/python 
Arguments = /Applications/sickbeard_mp4_automator-master/postSonarr.py

Test of that works fine according to Sonarr.

Then I get this error when going through SABNzb+ - 

Loading config from /Applications/Sick-Beard/autoProcessTV/autoProcessTV.cfg

Opening URL: http://localhost:8081/home/postprocess/processEpisode?nzbName=iZombie.S02E02.HDTV.x264-LOL.nzb&quiet=1&dir=%2FUsers%2FPetSue%2Fdownloads%2Fcomplete%2FTV%2FiZombie+S02E02+HDTV+x264-LOL
Unable to open URL: <urlopen error [Errno 61] Connection refused>

I am guessing it’s because of the SB location etc as listed above in the error.

So where have I gone wrong?

Sorry.

**Comment by PetSue** [comment]
Hi again,

Ok think I may have worked out something - I use SABNzb+ and found that the script was obviously in the SB folder which I am no longer using.

So for the Scripts location now do I just use this - /Applications/sickbeard_mp4_automator-master ?

Thanks.

**Comment by PetSue** [comment]
OK tried it again and now get this error - 

Traceback (most recent call last):
  File "/Applications/sickbeard_mp4_automator-master/postSonarr.py", line 5, in <module>
    from readSettings import ReadSettings
  File "/Applications/sickbeard_mp4_automator-master/readSettings.py", line 9, in <module>
    from babelfish import Language
ImportError: No module named babelfish

**Comment by PetSue** [comment]
Ok it appears my issue is which is the correct Script I need to run in settings in SABNzb+

**Comment by mdhiggins** [comment]
Your babel fish error is most likely because babel fish isn't installed. Use pip to install babel fish 

`pip install babelfish`

As far as SAB goes, you need to set the script to SABpostProcess.py and your category should be your sonarr category from the SABNZBD section of your autoProcess.ini

**Comment by PetSue** [comment]
Hey mate, ok babelfish installed no worries and did what you said but still no go. Now it’s not trying to convert and not getting any error.

Have attached my autoProcess.ini file along with 2 shots of my SABNzb+

Hopefully it’s something easy I’ve done.

Thanks again, you’re a champ :)

**Comment by PetSue** [comment]
Ok I've just spent 2 hours trying this and got nowhere :(  Obviously I've done something simple wrong ;(

**Comment by mdhiggins** [comment]
And the downloads added to SAB by Sonarr are properly set with the 'sonarr' category?
Is there anything in the log file from SABPostProcess.py?

**Comment by PetSue** [comment]
And the downloads added to SAB by Sonarr are properly set with the 'sonarr' category? - W=Sorry not sure what you mean by 'Properly Set?'

Here is the log from SAB for the SABPostProcess.py - 

2015-10-16 20:59:35,953::INFO::[postproc:284] Starting PostProcessing on Quantico S01E02 720p WEB-DL 2CH x265 HEVC-PSA => Repair:True, Unpack:True, Delete:True, Script:SABPostProcess.py, Cat:tv
2015-10-16 20:59:40,892::INFO::[newsunpack:150] Running external script /Applications/sickbeard_mp4_automator-master/SABPostProcess.py(/Users/PetSue/Music/iTunes/iTunes Music/Automatically Add to iTunes/TV/Quantico S01E02 720p WEB-DL 2CH x265 HEVC-PSA, Quantico.S01E02.720p.WEB-DL.2CH.x265.HEVC-PSA.nzb, Quantico S01E02 720p WEB-DL 2CH x265 HEVC-PSA, , tv, alt.binaries.cores, 0, )

**Comment by mdhiggins** [comment]
Looks like your 'user defined category' being passed to the script is "tv" when it should be "sonarr", make sure when the nzb is passed from sonarr to to SAB that sonarr is setting the category appropriately.

**Comment by mdhiggins** [comment]
![capture](https://cloud.githubusercontent.com/assets/3608298/10568727/129f05fc-75ea-11e5-910a-ab9632803de3.PNG)

**Comment by PetSue** [comment]
Ah ha ok that pic helped thanks you, just grabbing something now and will see what happens.

**Comment by PetSue** [comment]
Ok nope that didn't help and no log on SAB to show why :(

I know it's going to be something simple too, just can;t work out what it is sorry :(

**Comment by mdhiggins** [comment]
Can you snap a picture of the SAB download window while the download is in progress?

**Comment by PetSue** [comment]
![screen shot 2015-10-19 at 2 00 34 pm](https://cloud.githubusercontent.com/assets/6519959/10568882/d832edcc-7669-11e5-8519-841bddc7be92.png)

**Comment by mdhiggins** [comment]
See where it says "Script" on the far right? that needs to be set to SABPostProcess.py

**Comment by mdhiggins** [comment]
Also looks like your category isn't properly set either

**Comment by PetSue** [comment]
There ya go I just noticed that myself and seems that it may now be showing those 2 missing bits form before as just tried it wiht another show and they now show those.

A show I just grabbed though brings this reply up now - 

2015-10-19 14:04:33 - SABPostProcess - INFO - SAB post processing started.
2015-10-19 14:04:33 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-10-19 14:04:33 - SABPostProcess - INFO - Performing conversion
2015-10-19 14:04:33 - SABPostProcess - INFO - Processing file /Users/PetSue/downloads/complete/TV/Blood and Oil 2015 S01E04 720p HDTV x264-FLEET/Blood.and.Oil.2015.S01E04.720p.HDTV.x264-FLEET.mkv.
2015-10-19 14:04:33 - mkvtomp4 - INFO - Reading video stream.
2015-10-19 14:04:33 - mkvtomp4 - INFO - Video codec detected: h264.
2015-10-19 14:04:33 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2015-10-19 14:04:33 - mkvtomp4 - INFO - Reading audio streams.
2015-10-19 14:04:33 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng].
2015-10-19 14:04:33 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2015-10-19 14:04:33 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2015-10-19 14:04:33 - mkvtomp4 - INFO - Reading subtitle streams.
2015-10-19 14:04:33 - mkvtomp4 - INFO - Subtitle detected for stream #2: subrip [eng].
2015-10-19 14:04:33 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 2.
2015-10-19 14:04:33 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2015-10-19 14:04:33 - mkvtomp4 - INFO - Starting conversion.
2015-10-19 14:06:09 - mkvtomp4 - INFO - /Users/PetSue/downloads/complete/TV/Blood and Oil 2015 S01E04 720p HDTV x264-FLEET/Blood.and.Oil.2015.S01E04.720p.HDTV.x264-FLEET.mp4 created.
2015-10-19 14:06:09 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
2015-10-19 14:06:24 - SABPostProcess - INFO - Passing /Users/PetSue/downloads/complete/TV/Blood and Oil 2015 S01E04 720p HDTV x264-FLEET directory to Sonarr.
2015-10-19 14:06:24 - autoprocess.sonarr - INFO - Sonarr notifier started.
2015-10-19 14:06:25 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/Users/PetSue/downloads/complete/TV/Blood and Oil 2015 S01E04 720p HDTV x264-FLEET'.
2015-10-19 14:06:25 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2015-10-19 14:06:25 - autoprocess.sonarr - INFO - Sonarr response: queued.

**Comment by PetSue** [comment]
So the conversion is done and available but it's not moving it to the Auto Add to iTunes folder

**Comment by mdhiggins** [comment]
That should be done as part of Sonarr's final postSonarr.py routine, not as part of the SABPostProcess.py, do you have the postSonarr.py setup and configured to run?

**Comment by PetSue** [comment]
If that means a Custom Script in Sonarr then I have this a the Argument - /Applications/sickbeard_mp4_automator-master/postSonarr.py

I haven't edited anything though on postSonarr.py

**Comment by PetSue** [comment]
I also find that it's not Tagging the show, even though I am running the Dev version.

**Comment by mdhiggins** [comment]
It sounds like there's still an issue with your setup, something isn't quite right. Additionally, you no longer need to be on the dev version, the Sonarr people just pushed the update to the master branch and everything should be working. Readme update will follow soon.

**Comment by mdhiggins** [comment]
Gonna reopen this now since you're still having issues

**Comment by PetSue** [comment]
Hi mate and thanks and apologies for dragging this out :(

I installed latest version but still showing Develop version 2.0.0.3530 even after a restart.

Yes I am still having issues with it not working for me and have no idea why sorry.  here is what SAB shows - 

2015-10-22 12:40:05 - SABPostProcess - INFO - SAB post processing started.
2015-10-22 12:40:05 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-10-22 12:40:05 - SABPostProcess - INFO - Performing conversion
2015-10-22 12:40:05 - SABPostProcess - INFO - Processing file /Users/PetSue/downloads/complete/TV/Arrow S04E03 720p HDTV X264-DIMENSION/Arrow.S04E03.720p.HDTV.X264-DIMENSION.mkv.
2015-10-22 12:40:06 - mkvtomp4 - INFO - Reading video stream.
2015-10-22 12:40:06 - mkvtomp4 - INFO - Video codec detected: h264.
2015-10-22 12:40:06 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2015-10-22 12:40:06 - mkvtomp4 - INFO - Reading audio streams.
2015-10-22 12:40:06 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [und].
2015-10-22 12:40:06 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2015-10-22 12:40:06 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2015-10-22 12:40:06 - mkvtomp4 - INFO - Reading subtitle streams.
2015-10-22 12:40:06 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2015-10-22 12:40:06 - mkvtomp4 - INFO - Starting conversion.
2015-10-22 12:41:21 - mkvtomp4 - INFO - /Users/PetSue/downloads/complete/TV/Arrow S04E03 720p HDTV X264-DIMENSION/Arrow.S04E03.720p.HDTV.X264-DIMENSION.mp4 created.
2015-10-22 12:41:21 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
2015-10-22 12:41:44 - SABPostProcess - INFO - Passing /Users/PetSue/downloads/complete/TV/Arrow S04E03 720p HDTV X264-DIMENSION directory to Sonarr.
2015-10-22 12:41:44 - autoprocess.sonarr - INFO - Sonarr notifier started.
2015-10-22 12:41:45 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/Users/PetSue/downloads/complete/TV/Arrow S04E03 720p HDTV X264-DIMENSION'.
2015-10-22 12:41:45 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2015-10-22 12:41:45 - autoprocess.sonarr - INFO - Sonarr response: started.

Again sorry.

**Comment by mdhiggins** [comment]
I don't think the problem is with SAB at this point, seems like the conversion and notification to Sonarr is all working fine. If the file is then renamed and moved to its final Sonarr-set destination then we also know the notification portion is working. The question is whether or not the Sonarr post script (postSonarr.py) is being properly executed, which is where the tagging takes place, is actually being executed. I suspect in your case its not but its likely because it isn't probably set up. Can you post a screenshot of your relevant sonarr 'connection' setting so I can take a look. And maybe look through the Sonarr log files, not the SAB log files, to see if there's anything that looks like an explanation as to why its not executing.

**Comment by PetSue** [comment]
Here's a screen of the Post Conversion script in sonar - 

![screen shot 2015-10-22 at 10 21 31 pm](https://cloud.githubusercontent.com/assets/6519959/10663980/552e875c-790b-11e5-84dd-cda94436d11f.png)

The path to python is - /Library/Frameworks/Python.framework/Versions/2.7/python 
The path to Argument is - /Applications/sickbeard_mp4_automator-master/postSonarr.py

Hope that helps.

**Comment by mdhiggins** [comment]
Try just setting the path to the postSonarr.py as the Path and leave the arguments blank and see if that works.

**Comment by PetSue** [comment]
I think we have a winner :)  Had to go to work but will test again tonight and let you know, fingers crossed ;)

**Comment by mdhiggins** [comment]
Keep me posted!

**Comment by PetSue** [comment]
Well mate that has seemed to have fixed it, looking good now ands working fine. Wonder why the different settings worked?

Also 1 other issue sorry - Renaming - had a file yesterday that was converted fine, but not Tagged due to the filename name not being known, even though the folder name was right.

Is there any fix for that please?

Thanks again :)

**Comment by mdhiggins** [comment]
Renaming really has nothing to do with my script - it doesn't do any renaming and it doesn't tag using the file name to identify the file (outside of manual.py). Not sure why the one file wasn't tagged. Are other files being tagged appropriately? Was it converted properly? What was the name before/after?

**Comment by PetSue** [comment]
No worries I wasn't sure if renaming was done but just surprised that it didn't tag as the folder name was fine but not the file name.

Others are being tagged fine so far, just the one yesterday that had totally different name.

The name before & after was the same, didn't change and wasn't tagged - did you want the file or show name?

**Comment by mdhiggins** [comment]
The file and show name would be good, I just want to make sure its not something specific to that episode that errored out the tagging system. But yeah the folder name/file name actually have nothing to do with the tagging. The script communicates with Sonarr which passes all the needed information (TVDB ID, Season, Episode number) all to the script which it uses to pull the metadata, it all comes directly from Sonarr which definitely knows the correct information since it triggered the download and did the renaming.

**Comment by PetSue** [comment]
Yea thought as much but was just curious thank you.

Here is the file in question - The.Originals.S03E03.720p.HDTV.X264-DIMENSION - with the file name being - PiQbp0Gya90qZL.mkv

As I said it converted it no problems but wasn't tagged due to the name.

**Comment by mdhiggins** [comment]
Just curious why was it renamed to that? or did Sonarr simply not recognize the file as a valid piece of media so it didn't move it to the final destination / tag / rename etc

**Comment by PetSue** [comment]
I'm not sure it was renamed as was converted and kept as the same name, hence why it wasn't tagged.

I'm thinking that Sonarr recognised the listed name as that was fine but the actual downloaded file name was totally different as you can see.

**Comment by mdhiggins** [comment]
So again, the script doesn't rename the files at all, I'm thinking this particular download must just have been bad and even though the release name was appropriate, the file itself was oddly named and I'm thinking when sonarr scanned the directory it just ignored it. Because Sonarr ignored it, it was never moved and Sonarr never ran any of its post processing scripts, and therefore it never got tagged.

The conversion still took place because the script that runs after downloading before notifying Sonarr only scans for valid file formats, doesn't care about name, and converts whatever it finds. 

That would be my guess, does that sound like what happened? I think its just a bad download.

**Comment by PetSue** [comment]
Yep sounds about right and all good cause was easy fix anyways, but was just curious is all.

So finally and I say finally you can close this and again I can't thank you enough and so sorry for dragging it out :)

**Comment by mdhiggins** [comment]
No problem, glad we got it all sorted. Enjoy your new automated sonarr setup! I just finished migrating my personal server over to Sonarr (from Sickbeard) as well and its running great. Really liking it.

**Comment by PetSue** [comment]
Sorry know this is now closed but yes agree Sonarr is so much nicer and well built and am running that only now here too :)

Thanks again mate :)
