### ISSUE TITLE
No JSON Object could be decoded

### ISSUE THREAD

**Issue by HazCod** [mdhiggins/sickbeard_mp4_automator#344]
When I post-processed in Sabnzbdplus;

```
2015-10-16 12:41:24 - SABPostProcess - INFO - SAB post processing started.
2015-10-16 12:41:24 - readSettings - ERROR - Subliminal is not installed, automatically downloading of subs has been disabled.
Traceback (most recent call last):
  File "/home/media/scripts/sickbeard_mp4_automator/readSettings.py", line 235, in __init__
    import subliminal
ImportError: No module named subliminal
2015-10-16 12:41:24 - SABPostProcess - INFO - Performing conversion
2015-10-16 12:41:24 - SABPostProcess - INFO - Passing /home/media/data/complete/movies/Thor.The.Dark.World.2013.BluRay.1080p.DTS.x264-PRoDJi.cp(tt1981115) directory to Couch Potato.
2015-10-16 12:41:24 - autoprocess.autoProcessMovie - INFO - Waiting for 65.0 seconds to allow CPS to process newly extracted files.
2015-10-16 12:42:29 - autoprocess.autoProcessMovie - INFO - Opening URL: http://localhost:5050/couchpotato/api/xxxxxxxxxxxxxxxxxxxx/renamer.scan.
Traceback (most recent call last):
  File "/home/media/scripts/sickbeard_mp4_automator/SABPostProcess.py", line 77, in <module>
    autoProcessMovie.process(path, settings, nzb, sys.argv[7])
  File "/home/media/scripts/sickbeard_mp4_automator/autoprocess/autoProcessMovie.py", line 91, in process
    result = json.load(urlObj)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

and:

```
curl "http://localhost:5050/couchpotato/api/xxxxxxxxx/renamer.scan" -vvv
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5050 (#0)
> GET /couchpotato/api/xxxxxxxxxx/renamer.scan HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:5050
> Accept: */*
> 
< HTTP/1.1 302 Found
< Content-Length: 0
< Vary: Accept-Encoding
* Server TornadoServer/4.1 is not blacklisted
< Server: TornadoServer/4.1
< Location: /login/?next=%2Fcouchpotato%2Fapi%xxxxxxxxx%2Frenamer.scan
< Date: Fri, 16 Oct 2015 10:55:38 GMT
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host localhost left intact

```

and:

```
0-16 12:57:55 ERROR [chpotato.core.plugins.log] API log: {'file': u'http://HOST/static/scripts/combined.base.min.js?1444980315', 'message': u"chrome 46: \nUncaught TypeError: Cannot read property 'checked' of undefined", 'line': u'1729', 'page': u'http://HOST/settings/renamer/', '_request': <couchpotato.api.ApiHandler object at 0x7fc3a0936990>}

```

**Comment by HazCod** [comment]
Might just be a bad API key, will test and close if necessary.
