### ISSUE TITLE
Installing Python Libraries

### ISSUE THREAD

**Issue by graeme5150** [mdhiggins/sickbeard_mp4_automator#353]
When installing the python libraries I get an error when installing guest

sh-3.2# pip install guessit
Collecting guessit
Collecting stevedore>=0.14 (from guessit)
  Using cached stevedore-1.9.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from guessit)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): babelfish>=0.5.4 in /Library/Python/2.7/site-packages (from guessit)
Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Python/2.7/site-packages (from guessit)
Requirement already satisfied (use --upgrade to upgrade): pbr>=1.6 in /Library/Python/2.7/site-packages (from stevedore>=0.14->guessit)
Requirement already satisfied (use --upgrade to upgrade): argparse in /Library/Python/2.7/site-packages (from stevedore>=0.14->guessit)
Collecting six>=1.9.0 (from stevedore>=0.14->guessit)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, stevedore, python-dateutil, guessit
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-UggxQZ-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
sh-3.2#

**Comment by mdhiggins** [comment]
Maybe you need to give it admin privileges to install?

Try running with sudo

**Comment by graeme5150** [comment]
Hi, resolved this
see - https://github.com/pypa/pip/issues/3165

**Comment by mdhiggins** [comment]
Thanks for the info
