### ISSUE TITLE
Couchpotato: imdbid = sys.argv[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by M4X-StL** [mdhiggins/sickbeard_mp4_automator#359]
Having trouble w/the automation using the script on my Synology NAS.  It was working fine previously - but I updated to your most recent release and now I can't seem to get it working with Couchpotato (Sickrage works fine!).  

My log from Couchpotato below:

11-04 00:18:02 INFO
[ PostProcess] MP4 Automator - Post processing script initialized
11-04 00:18:02 INFO
[ PostProcess] Executing post processing on file /volume1/DiskStation/Movies/Movie.mkv
11-04 00:18:03 INFO
[ PostProcess] 2015-11-04 00:18:03 - CouchPotatoPostConversion - INFO - MP4 Automator - Post processing script initialized 2015-11-04 00:18:03 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
11-04 00:18:03 INFO
[ PostProcess] Traceback (most recent call last): File "/usr/local/couchpotatoserver/scripts/sickbeard_mp4_automator/postCouchPotato.py", line 21, in <module> imdbid = sys.argv[1] IndexError: list index out of range
11-04 00:18:03 INFO
[ PostProcess] Return code: 1

Is there something wrong with postCouchPotato.py?

**Comment by mdhiggins** [comment]
Seems like the command line parameters aren't being received by postCouchPotato.py for some reason. I don't have a synology to test on but I know on windows sometimes there's issues with python and command line parameters not being recognized by Python, but I'll to do some investigating to see if that's a problem on synology

**Comment by mdhiggins** [comment]
Also what movie are you trying to process there? Looks like the file is named "Movie.mkv". I'm just wondering if that's modified or you were processing some unidentified movie in CouchPotato.

**Comment by M4X-StL** [comment]
Thanks for looking into it - I modified the filename.  :)

**Comment by mdhiggins** [comment]
Shouldn't make a difference honestly I was just curious. If you run a python script with command line variables does that normally work? Like if you run manual.py with command line parameters does it acknowledge those?

**Comment by M4X-StL** [comment]
Admittably, I haven't attempted to run the process manually.  However, I was forcing post-processing in CP - but I believe that also shouldn't matter.  I will report back this afternoon/evening on any further progress, as I'm unable to further troubleshoot right now.

**Comment by mdhiggins** [comment]
What do you mean forcing post-processing in CP?

**Comment by M4X-StL** [comment]
Restarting CP to allow for the post-processing/execution of your script.

**Comment by mdhiggins** [comment]
Wasn't aware that would trigger post-processing. As far as I know the only trigger should be when a renamer.scan is run but I guess it may depend on how CP is setup, if you're using the blackhole method maybe? I only ask cause I'm wondering if that maybe has something to do with why its not working.

**Comment by M4X-StL** [comment]
Appreciate the back-and-forth - so I triggered a download via NZBGet and push to CP earlier this AM - but didn't get a chance to see if it completed the process before work.  I'll certainly report back w/my findings late this afternoon/evening.  And yes, if you've already downloaded via CP, you can throw the file back into its original downloaded directory and restart/reload CP and it will trigger any post-processing scripts are setup in the custom_scripts folder.

**Comment by M4X-StL** [comment]
Investigated the logs again - same issue.  Do you think my Python build is potentially corrupt (grasping at straws here...)?  Permissions are set to 0777 for both the root folder (and sub-folders) of the main script location - in addition to the PostProcess folder in custom_scripts.

**Comment by mdhiggins** [comment]
I don't think its a permissions issue since both scripts appear to be executing themselves as they should. For whatever reason, the command line parameters that should be getting passed from the main.py file to the postCouchPotato.py file aren't being seen. That being said I'm not sure why that would be. 

A couple things you could try:
- see if command line parameters work with manual.py and let me know
- in `main.py` try setting `shell=True` on line 41 (and make sure you shutdown CP, delete any .pyc files, and relaunch CP after you've made the changes) and try again

**Comment by M4X-StL** [comment]
mdhiggins - appreciate your continued engagement on this issue.  I will attempt to run manual.py this evening in addition to your recommended changes to main.py (although I think I tried that as well while burning the midnight oil last night).  Talk soon.

**Comment by mdhiggins** [comment]
You could also try removing the `env={}` from line 41 as well and see if that makes any difference

**Comment by M4X-StL** [comment]
Sooo... progress, but now encountering a new issue mdhiggins.  :(

11-04 19:03:54 INFO
[ PostProcess] Executing post processing on file /volume1/DiskStation/Movies/Insurgent.2015.1080p.BluRay.x264/pMHMRx8ALFURMyAeFYsgg.mkv
11-04 19:03:55 INFO
[ PostProcess]
11-04 19:03:55 INFO
[ PostProcess] Traceback (most recent call last): File "/usr/local/couchpotatoserver/scripts/sickbeard_mp4_automator/postCouchPotato.py", line 6, in <module> from readSettings import ReadSettings File "/volume1/@appstore/couchpotatoserver/scripts/sickbeard_mp4_automator/readSettings.py", line 11, in <module> from babelfish import Language ImportError: No module named babelfish
11-04 19:03:55 INFO
[ PostProcess] Return code: 1

I changed made the recommended changes to line 41 - shell=True & removed env={}.  Additionally, I installed babelfish last night to get the script working again w/Sickrage, by evidence below:

Server> pip install babelfish
Requirement already satisfied (use --upgrade to upgrade): babelfish in /lib/python2.7/site-packages
Cleaning up...
Server> pip install babelfish --upgrade
Requirement already up-to-date: babelfish in /lib/python2.7/site-packages
Cleaning up...
Server>

I'm up for ideas at this point!  Be back in approximately an hour.  :+1:

**Comment by mdhiggins** [comment]
Alright so that new error is coming from deleting the `env={}` part of the script. I would put that back and try it with just Shell=True and see where that gets you.

**Comment by M4X-StL** [comment]
Back to where we were...

11-04 19:45:57 INFO
[ PostProcess] Executing post processing on file /volume1/DiskStation/Movies/Movie.mkv
11-04 19:45:57 INFO
[ PostProcess] 2015-11-04 19:45:57 - CouchPotatoPostConversion - INFO - MP4 Automator - Post processing script initialized 2015-11-04 19:45:57 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
11-04 19:45:57 INFO
[ PostProcess] Traceback (most recent call last): File "/usr/local/couchpotatoserver/scripts/sickbeard_mp4_automator/postCouchPotato.py", line 21, in <module> imdbid = sys.argv[1] IndexError: list index out of range
11-04 19:45:57 INFO
[ PostProcess] Return code: 1

I need about another 20 mins then I can try the manual.py method.

**Comment by M4X-StL** [comment]
Manual.py worked fine - still getting the same error.  :-1:

**Comment by mdhiggins** [comment]
Did you specifically try to pass it command line variables? I suspect it will launch but I’m just wondering if it will obey command line parameters.
