### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by jowandijkhuis** [mdhiggins/sickbeard_mp4_automator#368]
Setting up the automator script for use with Sickrage and using manual.py to test the config.
For some reason the script stops executing after having found the title. See code below:
```
python /volume1/shared/scripts/sickbeard_mp4_automator/manual.py -i 'After.Earth.2013.720p.BluRay.x264-SPARKS.mkv'
Manual processor started.
32bit Python.
Matched movie title as: After Earth 2013-05-30
Proceed using guessed identification from filename?
# [y/n]: y
Processing After Earth
Traceback (most recent call last):
  File "/volume1/shared/scripts/sickbeard_mp4_automator/manual.py", line 355, in <module>
    main()
  File "/volume1/shared/scripts/sickbeard_mp4_automator/manual.py", line 346, in main
    processFile(path, tagdata)
  File "/volume1/shared/scripts/sickbeard_mp4_automator/manual.py", line 204, in processFile
    output = converter.process(inputfile, True)
  File "/volume1/shared/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 139, in process
    options = self.generateOptions(inputfile, original=original)
  File "/volume1/shared/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 247, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "/volume1/shared/scripts/sickbeard_mp4_automator/converter/__init__.py", line 254, in probe
    return self.ffmpeg.probe(fname, posters_as_video)
  File "/volume1/shared/scripts/sickbeard_mp4_automator/converter/ffmpeg.py", line 416, in probe
    '-show_format', '-show_streams', fname])
  File "/volume1/shared/scripts/sickbeard_mp4_automator/converter/ffmpeg.py", line 383, in _spawn
    close_fds=(os.name != 'nt'), startupinfo=startupinfo)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```
The autoProcess.ini looks like this:
```
[SickBeard]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Sonarr]
host = localhost
port = 8989
web_root =
ssl = 0
apikey =

[MP4]
ffmpeg = /volume1/shared/scripts/sickbeard_mp4_automator/ff/ffmpeg
ffprobe = /volume1/shared/scripts/sickbeard_mp4_automator/ff/ffprobe
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
ios-audio = True
ios-first-track-only = False
max-audio-channels =
audio-codec = aac
audio-language =
audio-default-language =
audio-channel-bitrate = 0
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =

[CouchPotato]
host = localhost
port = 5050
username =
password =
web_root =
ssl = 0
apikey =
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
convert =
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username =
password =

[Deluge]
host = localhost
username =
convert = True
password =
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard

[Sickrage]
host = localhost
port = 8083
username =
password =
web_root =
ssl = 0
api_key = 

[Plex]
host = localhost
port = 32400
refresh = True
token =

```
Any tips on how to fix this error?

**Comment by mdhiggins** [comment]
This can be seen when your path to ffmpeg or ffprobe isn't correct or the files you're pointing to aren't valid binaries. I would ensure that they are working executables. Make sure they have execution permissions as well. You can also try grabbing some precompliled ffmpeg binaries and swapping those in and see if the problem persists.

**Comment by jowandijkhuis** [comment]
Already checked permissions a few hours ago. ffmpeg and ffprobe seem to execute. See pictures below.
```
drwxrwxrwx    3 admin    users         4096 Nov 11 00:50 .
drwxrwxrwx   11 admin    users         4096 Nov 11 00:50 ..
drwxrwxrwx    2 admin    users         4096 Nov 11 00:50 @eaDir
-rwxrwxrwx    1 admin    users     31936100 Oct 14 05:45 ffmpeg
-rwxrwxrwx    1 admin    users     31878484 Oct 14 05:45 ffprobe
```

ffprobe executable test
![image](https://cloud.githubusercontent.com/assets/593324/11082908/9c855054-8829-11e5-8b85-acea034b3438.png)

ffmpeg executable test
![image](https://cloud.githubusercontent.com/assets/593324/11082934/f48e521e-8829-11e5-8fca-991f371776e3.png)

**Comment by jowandijkhuis** [comment]
wait a sec. The precompiled ffmpeg binaries are not running on my OSX box but on Synology.....maybe I should look for other binaries

**Comment by jowandijkhuis** [comment]
Found out that my Synology Diskstation already has a ffmpeg executable installed in the Video Station package. 
```
DiskStation> find / -type d -name ffmpeg
/volume1/@appstore/MediaServer/lib/ffmpeg
/volume1/@appstore/VideoStation/lib/ffmpeg
/volume1/@appstore/AudioStation/lib/ffmpeg
```
So I updated the autoProcess.ini path to reflect this new location:
```
ffmpeg = /volume1/@appstore/VideoStation/lib/ffmpeg
```
What I didn't found was an ffprobe executable for the Synology (ARM, Linux). So the OSError is still there.

**Comment by mdhiggins** [comment]
https://github.com/CutePoisonX/ffmpegInstaller

Take a look here maybe

**Comment by mdhiggins** [comment]
FFMPEG build issue
