### ISSUE TITLE
Error while opening encoder for output stream (and succeeding post-process!)

### ISSUE THREAD

**Issue by HazCod** [mdhiggins/sickbeard_mp4_automator#370]
Script pp_sickrage:
```
#!/bin/bash

python /home/media/applications/automator/manual.py -i "$1" -tv "$3" -e "$5" -s "$4" -a --moveto /home/media/data/uploadme/series/
```

Log:
```
2015-11-16 15:35:02 INFO     Thread-56 :: Executing command [u'/home/*****/scripts/pp_sickrage.sh', u'/home/*****/data/transcodeme/series/Mr. Robot/Season 01/Mr. Robot - S01E08 - eps1.7_wh1ter0se.m4v.mkv', u'/home/*****/data/complete/series/Mr. Robot S01 Season 1 Complete 720p HDTV x265 AAC E-Subs [GWC]/Mr. Robot S01E08 HDTV 720p x265 AAC E-Subs [GWC].mkv', '289590', '1', '8', '2015-08-12']

2015-11-16 15:35:14 DEBUG    Thread-56 :: Script result: Manual processor started.
64bit Python.
Overriden move-to to /home/*****/data/uploadme/series/
Processing TV episode
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p.
Video level 93.0.
Reading audio streams.
Audio detected for stream #1: aac [eng].
Creating audio stream 0 from source stream 1.
Reading subtitle streams.
Subtitle detected for stream #2: srt [eng].
Ripping eng subtitle from source stream 2 into external file.
/home/*****/data/transcodeme/series/Mr. Robot/Season 01/Mr. Robot - S01E08 - eps1.7_wh1ter0se.m4v.eng.srt created.
Attempting to download subtitles.
{
    "subtitle": {}, 
    "audio": {
        "0": {
            "channels": 2, 
            "map": 1, 
            "codec": "copy", 
            "bitrate": 256, 
            "language": "eng"
        }
    }, 
    "video": {
        "map": 0, 
        "codec": "h264", 
        "bitrate": 396.076, 
        "level": 7.1
    }, 
    "format": "mp4"
}
Starting conversion.
Traceback (most recent call last):
  File "/home/*****/applications/automator/manual.py", line 355, in <module>
    main()
  File "/home/*****/applications/automator/manual.py", line 346, in main
    processFile(path, tagdata)
  File "/home/*****/applications/automator/manual.py", line 204, in processFile
    output = converter.process(inputfile, True)
  File "/home/*****/applications/automator/mkvtomp4.py", line 151, in process
    outputfile, inputfile = self.convert(inputfile, options, reportProgress)
  File "/home/*****/applications/automator/mkvtomp4.py", line 569, in convert
    for timecode in conv:
  File "/home/*****/applications/automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/home/*****/applications/automator/converter/ffmpeg.py", line 548, in convert
    line, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <FFMpegConvertError error="Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height", pid=23444, cmd="/usr/bin/ffmpeg -fix_sub_duration -i /home/*****/data/transcodeme/series/Mr. Robot/Season 01/Mr. Robot - S01E08 - eps1.7_wh1ter0se.m4v.mkv -vcodec libx264 -map 0:0 -vb 396k -level 7.1 -c:a:0 copy -map 0:1 -metadata:s:a:0 language=eng -f mp4 -threads auto -y /home/*****/data/transcodeme/series/Mr. Robot/Season 01/Mr. Robot - S01E08 - eps1.7_wh1ter0se.m4v.mp4">

2015-11-16 15:35:14 INFO     Thread-56 :: Processing succeeded for /home/*****/data/complete/series/Mr. Robot S01 Season 1 Complete 720p HDTV x265 AAC E-Subs [GWC]/Mr. Robot S01E08 HDTV 720p x265 AAC E-Subs [GWC].mkv
```

**Comment by mdhiggins** [comment]
Try running the command generated by the script in FFMPEG and post the full output FFMPEG gives you so we can see what specifically is causing it to error out. I suspect its an issue with the bitrate or level of the video stream going from HEVC to h264

**Comment by mdhiggins** [comment]
Are you setting the level to 7.1? Cause that's not a valid h264 level. I think FFMPEG only supports up to 4.2

**Comment by HazCod** [comment]
AH, yes I do. Will change it back and report

**Comment by mdhiggins** [comment]
Just pushed a commit that will prevent setting levels that are out of range (3.0-4.2) when encoding to h264. Looks like you probably had your max level set too high, and because the HEVC/H265 level was 9.3 (it uses a different level system) it was trying to scale back to what you had set as your max, `7,1`.

New commit will prevent this for future users.

Also if you wanted to preserve the h265 here instead of reencoding it to h264, just add `hevc` to your `video-codec` list, just as an aside.

**Comment by HazCod** [comment]
Thanks. In the end, the underlying issue is related to https://github.com/mdhiggins/sickbeard_mp4_automator/issues/369.
Does the script return a non-zero exit code when problems arise? Because sickrage mentioned a 'post-process success'.
