### ISSUE TITLE
issue tagging from tmdb

### ISSUE THREAD

**Issue by grahamr** [mdhiggins/sickbeard_mp4_automator#406]
i ran a pull to see what was new, then ran all dependencies again to make sure everything was installed, since then i am getting errors when running the script - I am using manual.py to run against a folder on a scheduled task - this is the log from today when i just ran it on its own. Unsure what is broken - seems like its having issues connecting out, but i can manually hit TMDB/IMDB etc - 

also - in the command prompt i saw this even above picking the "identifer" and it was not able to automatically identify a (very simply) named movie
    SSLError: (IOError(2, 'No such file or directory'),)

```
2016-01-18 13:25:58 - MANUAL - INFO - Manual processor started.
2016-01-18 13:26:57 - MANUAL - ERROR - Failed to connect to tMDB, trying again in 20 seconds.
Traceback (most recent call last):
  File "F:\Install\sickbeard_mp4_automator\tmdb_mp4.py", line 41, in __init__
    self.movie = tmdb.Movie(imdbid)
  File "F:\Install\sickbeard_mp4_automator\tmdb_api\tmdb.py", line 122, in __init__
    self.update_configuration()
  File "F:\Install\sickbeard_mp4_automator\tmdb_api\tmdb.py", line 65, in update_configuration
    c = self.getJSON(config['urls']['config'])
  File "F:\Install\sickbeard_mp4_automator\tmdb_api\tmdb.py", line 53, in getJSON
    page = requests.get(url, params={'language': language}).content
  File "F:\Install\sickbeard_mp4_automator\tmdb_api\requests\api.py", line 55, in get
  File "F:\Install\sickbeard_mp4_automator\tmdb_api\requests\api.py", line 44, in request
  File "F:\Install\sickbeard_mp4_automator\tmdb_api\requests\sessions.py", line 354, in request
  File "F:\Install\sickbeard_mp4_automator\tmdb_api\requests\sessions.py", line 460, in send
  File "F:\Install\sickbeard_mp4_automator\tmdb_api\requests\adapters.py", line 250, in send
SSLError: (IOError(2, 'No such file or directory'),)

```

**Comment by grahamr** [comment]
Ran a test with the same batch file against a folder with 4 movies and 1 tv show - all 4 movies had the same "no such file or directory" and would not auto-detect type/name etc and tag - the tv show on the other hand detected, pulled metadata and converted with no errors, except Cover Art was not downloaded.

**Comment by grahamr** [comment]
```
Processing file f:\Download\TV\Movie\Movie.mkv
(IOError(2, 'No such file or directory'),)
Unable to determine identity based on filename, must enter manually
Select media type:
1. Movie (via IMDB ID)
2. Movie (via TMDB ID)
3. TV
4. Convert without tagging
5. Skip file
#: 5
Processing file f:\Download\TV\tv show]\tv show.m4v
Matched TV episode as Tv Show (TVDB ID:XXXXX) S0XEXX
Proceed using guessed identification from filename?
# [y/n]: y
Processing TV Show Season 0X Episode XX - Tracks
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Reading audio streams.
Audio detected for stream #1: dca [und].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Reading subtitle streams.
Attempting to download subtitles.
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 256,
            "language": "eng"
        },
        "1": {
            "channels": 6,
            "map": 1,
            "codec": "aac",
            "bitrate": 1536,
            "language": "eng"
        }
    },
    "video": {
        "map": 0,
        "codec": "copy",
        "bitrate": null,
        "level": null
    },
    "format": "mp4"
}
Starting conversion.
f:\Download\TV\tv show]\tv show.m4v created.
Tagging file: f:\Download\TV\tv show]\tv show.m4v
Trying to write tags.
Tags written successfully.
Relocating MOOV atom to start of file.
f:\Download\TV\tv show]\tv show.m4v moved to F:\Download\2_Pro.
F:\Install\sickbeard_mp4_automator>
```

**Comment by grahamr** [comment]
Further testing - I've isolated it to something in the pull.... i made a copy of the folder prior to syncing, and that folder will run with no issues. Doing a comparison on the two folders now to see what changed.

**Comment by mdhiggins** [comment]
One thing that comes to mind if this occurred after an update is to make sure you don't have any old empty directories remaining that are causing problems. Doing a fresh pull in a clean directory and restoring only your autoProcess.ini would be a good thing to try

**Comment by grahamr** [comment]
I did a fresh pull, clean folder, copied my auto process and it seems to be working - i reprocessed a few files and had no errors - will wait for a new source to really test, but i think this is safe to close.
