### ISSUE TITLE
Error when setting h265 as the video-codec

### ISSUE THREAD

**Issue by cpressland** [mdhiggins/sickbeard_mp4_automator#410]
I'm trying to call manual.py to transcode to h265 + aac. My command looks like this:

```
./manual.py -i example.mkv -tv 268592 -s 1 -e 1
```

And my autoProcess.ini looks like this:
```
[MP4]
ffmpeg = ffmpeg
ffprobe = ffprobe
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h265
video-bitrate =
video-max-width =
h264-max-level =
ios-audio = False
ios-first-track-only = False
max-audio-channels = 2
audio-codec = aac
audio-language =
audio-default-language =
audio-channel-bitrate =
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
```

And the output looks like this:
```
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Processing The 100 Season 01 Episode 01 - Pilot
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Reading audio streams.
Audio detected for stream #1: dca [eng].
Creating audio stream 0 from source stream 1.
Reading subtitle streams.
No valid subtitle language specified, cannot download subtitles.
{
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "bitrate": 512,
            "language": "eng"
        }
    },
    "video": {
        "map": 0,
        "codec": "h265",
        "bitrate": 5731.0821,
        "level": null
    },
    "format": "mp4"
}
Starting conversion.
Traceback (most recent call last):
  File "./manual.py", line 356, in <module>
    main()
  File "./manual.py", line 347, in main
    processFile(path, tagdata)
  File "./manual.py", line 204, in processFile
    output = converter.process(inputfile, True)
  File "/root/sickbeard_mp4_automator/mkvtomp4.py", line 151, in process
    outputfile, inputfile = self.convert(inputfile, options, reportProgress)
  File "/root/sickbeard_mp4_automator/mkvtomp4.py", line 583, in convert
    for timecode in conv:
  File "/root/sickbeard_mp4_automator/converter/__init__.py", line 241, in convert
    optlist = self.parse_options(options, twopass)
  File "/root/sickbeard_mp4_automator/converter/__init__.py", line 151, in parse_options
    video_options = self.video_codecs[c]().parse_options(x)
  File "/root/sickbeard_mp4_automator/converter/avcodecs.py", line 709, in parse_options
    return super(H264Codec, self).parse_options(opt, stream)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

ffmpeg seems to have 265 support installed correctly:

```
ffmpeg version 2.6.5 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-9)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
```

I'm running this on CentOS 7.2, any ideas where I should be looking? Note that if I change the video-codec to h264 the process works perfectly.

**Comment by mdhiggins** [comment]
Just pushed an update that might fix this bug. Let me know.

**Comment by cpressland** [comment]
Worked a charm. Thanks!
