### ISSUE TITLE
getting a extraction error with subtitles

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#414]
for the last 2 days I get this error with any file that has a subtitle track, the process will continue just fine after but just wondering why this has started popping up.

2016-01-23 20:05:01 - MANUAL - INFO - Reading video stream.
2016-01-23 20:05:01 - MANUAL - INFO - Video codec detected: h264.
2016-01-23 20:05:01 - MANUAL - INFO - Pix Fmt: yuv420p.
2016-01-23 20:05:01 - MANUAL - INFO - Reading audio streams.
2016-01-23 20:05:01 - MANUAL - INFO - Audio detected for stream #1: ac3 [eng].
2016-01-23 20:05:01 - MANUAL - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2016-01-23 20:05:01 - MANUAL - INFO - Creating audio stream 1 from source stream 1.
2016-01-23 20:05:01 - MANUAL - INFO - Reading subtitle streams.
2016-01-23 20:05:01 - MANUAL - INFO - Subtitle detected for stream #2: srt [eng].
2016-01-23 20:05:01 - MANUAL - INFO - Ripping eng subtitle from source stream 2 into external file.
2016-01-23 20:05:03 - MANUAL - ERROR - Unabled to create external subtitle file for stream 2.
Traceback (most recent call last):
  File "C:\Converter\mkvtomp4.py", line 439, in generateOptions
    for timecode in conv:
  File "C:\Converter\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\Converter\converter\ffmpeg.py", line 553, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=21968, cmd="C:\ffmpeg\bin\ffmpeg.exe -i d:\downloads\to convert\Chicago.Fire.S04E11.The.Path.of.Destruction.1080p.WEB-DL.DD5.1.H.264-NTb.mkv -an -sub_charenc UTF-8 -c:s:0 srt -map 0:2 -metadata:s:s:0 language=eng -f srt -y d:\downloads\to convert\Chicago.Fire.S04E11.The.Path.of.Destruction.1080p.WEB-DL.DD5.1.H.264-NTb.eng.srt">
2016-01-23 20:05:03 - MANUAL - INFO - {
    "subtitle": {}, 
    "audio": {
        "0": {
            "channels": 2, 
            "map": 1, 
            "codec": "aac", 
            "bitrate": 256, 
            "language": "eng"
        }, 
        "1": {
            "channels": 6, 
            "map": 1, 
            "codec": "copy", 
            "bitrate": 768, 
            "language": "eng"
        }
    }, 
    "video": {
        "map": 0, 
        "codec": "h264", 
        "bitrate": 2000, 
        "level": 4.1
    }, 
    "format": "mp4"
}

**Comment by mdhiggins** [comment]
Try updating to the latest version. Think this issue might be fixed in a recent commit depending on the last time you've updated.

**Comment by morpheus2n2** [comment]
already had latest version but I deleted the entire folder and re-downloaded and it seems to have fixed it so mush have been something was left over.
