### ISSUE TITLE
Error with script in Sonarr

### ISSUE THREAD

**Issue by scarin66** [mdhiggins/sickbeard_mp4_automator#424]
Very much a noob, but thought I followed the install instructions.   Get the following error not sure what i did wrong.  Any help appreciated. Thanks

Unable to send OnDownload notification to: postSonarr: Access is denied

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 167
   at NzbDrone.Common.Processes.ProcessProvider.StartAndCapture(String path, String args, StringDictionary environmentVariables) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 199
   at NzbDrone.Core.Notifications.CustomScript.CustomScriptService.ExecuteScript(StringDictionary environmentVariables, CustomScriptSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\CustomScript\CustomScriptService.cs:line 88
   at NzbDrone.Core.Notifications.CustomScript.CustomScriptService.OnDownload(Series series, EpisodeFile episodeFile, String sourcePath, CustomScriptSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\CustomScript\CustomScriptService.cs:line 58
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnDownload(DownloadMessage message) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 27
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeDownloadedEvent message) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\NotificationService.cs:line 132

**Comment by mdhiggins** [comment]
Looks more like a Sonarr error than something with my script specifically. Check your permissions on the custom scripts and then I would post this over on the Sonarr forums and see what they think

**Comment by scarin66** [comment]
Thanks Michael.It appears to test fine in sonarr. Now I am getting a script
error in SABnzbd

'python' is not recognized as an internal or external command,
operable program or batch file.

Any help would be appreciated. Thanks.

Larry

**Comment by mdhiggins** [comment]
You need to setup python as an environment variable. Based on the Win32exception error you posted earlier I'm gonna assume you're on windows. Here is a helpful article

https://docs.python.org/2/using/windows.html#excursus-setting-environment-variables

**Comment by scarin66** [comment]
I think I fixed the python error.  Now I got this one.  Sorry to be a pest.

 Traceback (most recent call last):
  File "C:\Automater\SABPostProcess.py", line 5, in <module>
    from autoprocess import autoProcessTV, autoProcessMovie,
autoProcessTVSR, sonarr
  File "C:\Automater\autoprocess\autoProcessMovie.py", line 11, in <module>
    import requests
ImportError: No module named requests

**Comment by mdhiggins** [comment]
Looks like you need to install requests 

See the installation requirements for all the python packages you'll need to install in the read me.
