### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by enz1ey** [mdhiggins/sickbeard_mp4_automator#451]
After conversion and invoking CouchPotato renamer.scan, script outputs the following in SABnzbd:

Traceback (most recent call last):
  File "/home/plex/sickbeard_mp4_automator/SABPostProcess.py", line 74, in <module>
    autoProcessMovie.process(path, settings, nzb, sys.argv[7])
  File "/home/plex/sickbeard_mp4_automator/autoprocess/autoProcessMovie.py", line 93, in process
    rstate = r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by enz1ey** [comment]
Possibly fixed, I am using Ubuntu and didn't realize the instructions for configuring CouchPotato via the guide here on GitHub specified double backslashes for Windows OS using backslashes in paths. Changed path in main.py to have single forward slashes. Will confirm correction on next completed download.

**Comment by mdhiggins** [comment]
Check your couch potato settings in autoProcess.ini. This error usually pops up when they're wrong and it's failing to talk to CP
