### ISSUE TITLE
Error on conversion start

### ISSUE THREAD

**Issue by diremonk** [mdhiggins/sickbeard_mp4_automator#458]
I'm not sure where I went wrong on the install but when a file is downloaded in SAB and the script fire off I get this error.

```
2016-03-31 14:07:19 - SABPostProcess - INFO - SAB post processing started.
2016-03-31 14:07:19 - SABPostProcess - INFO - Performing conversion
2016-03-31 14:07:19 - SABPostProcess - INFO - Processing file \\Mediashare\Downloads\TV\xxxxxxxx.mkv.
2016-03-31 14:07:19 - SABPostProcess - ERROR - Error converting file \\Mediashare\Downloads\TV\xxxxxxxx.mkv.
Traceback (most recent call last):
  File "C:\Downloaders\mp4_automator-master\SABPostProcess.py", line 57, in <module>
    output = converter.process(inputfile)
  File "C:\Downloaders\mp4_automator-master\mkvtomp4.py", line 150, in process
    options = self.generateOptions(inputfile, original=original)
  File "C:\Downloaders\mp4_automator-master\mkvtomp4.py", line 259, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "C:\Downloaders\mp4_automator-master\converter\__init__.py", line 254, in probe
    return self.ffmpeg.probe(fname, posters_as_video)
  File "C:\Downloaders\mp4_automator-master\converter\ffmpeg.py", line 415, in probe
    '-show_format', '-show_streams', fname])
  File "C:\Downloaders\mp4_automator-master\converter\ffmpeg.py", line 379, in _spawn
    startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'
```

The only ideas I have are that maybe I should be using the 32 bit version of Python, the path naming scheme is causing an issue or I just fat fingered something to do with ffmpeg.

It also errors out when I try to run the manal.py script giving:
`An unexpected error occured, processing of the file has failed 'module' object has not attibute 'start_useshowwindow`

**Comment by mdhiggins** [comment]
Just pushed an update to fix this. Its old code from an attempt to hide the FFMPEG window that never worked anyway.

**Comment by diremonk** [comment]
Thanks, that fixed things. Now I get to start converting the library
