### ISSUE TITLE
MacOSX Error Help

### ISSUE THREAD

**Issue by AaronM74** [mdhiggins/sickbeard_mp4_automator#463]
Hi there

I have placed the SCRIPTS into a location called:

/Users/USERNAME/Scripts

Have successfully called it from SABNZB.  But returns with the following error.

### 2016-04-12 18:39:31 - SABPostProcess - INFO - SAB post processing started.
2016-04-12 18:39:31 - readSettings - ERROR - Please install QTFastStart via PIP, relocate_moov will be disabled without this module.
2016-04-12 18:39:31 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-04-12 18:39:31 - SABPostProcess - INFO - Performing conversion
2016-04-12 18:39:31 - SABPostProcess - INFO - Processing file /Users/USERNAME/Downloads/complete/SHOW/SHOW.mkv.
2016-04-12 18:39:31 - SABPostProcess - ERROR - Error converting file /Users/USERNAME/Downloads/complete/SHOW/SHOW.mkv.
Traceback (most recent call last):
  File "/Users/USERNAME/Scripts/SABPostProcess.py", line 57, in <module>
    output = converter.process(inputfile)
  File "/Users/USERNAME/Scripts/mkvtomp4.py", line 150, in process
    options = self.generateOptions(inputfile, original=original)
  File "/Users/USERNAME/Scripts/mkvtomp4.py", line 259, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "/Users/USERNAME/Scripts/converter/__init__.py", line 27, in __init__
    ffprobe_path=ffprobe_path)
  File "/Users/USERNAME/Scripts/converter/ffmpeg.py", line 361, in __init__
    raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path)
FFMpegError: ffmpeg binary not found: ffmpeg
2016-04-12 18:39:31 - SABPostProcess - INFO - Passing /Users/USERNAME/Downloads/complete/SHOW directory to Sonarr.
2016-04-12 18:39:31 - autoprocess.sonarr - INFO - Sonarr notifier started.
2016-04-12 18:39:31 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/Users/USERNAME/Downloads/complete/SHOW'.
2016-04-12 18:39:31 - autoprocess.sonarr - INFO - Sonarr response: queued.

           

Help much appreciated.

**Comment by mdhiggins** [comment]
Your path to the FFMPEG or ffprobe executables in autoProcess.ini are incorrect. Verify these values and try again.

**Comment by AaronM74** [comment]
Thank you.  Something so stupid.  

I had thought that with FFMPEG and FFPROBE being in the system path that it should be fine.

Thanks again!
