### ISSUE TITLE
Error in FFMPEG

### ISSUE THREAD

**Issue by ferlicjl** [mdhiggins/sickbeard_mp4_automator#473]
Here's the log file:

2016-05-10 19:54:12 - uTorrentPostProcess - INFO - uTorrent post processing started.
2016-05-10 19:54:12 - uTorrentPostProcess - INFO - Reading in the arguments
2016-05-10 19:54:12 - uTorrentPostProcess - INFO - Reading in the settings
2016-05-10 19:54:12 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Got to here - trying something
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - INFORMATION: 
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Path: C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD].
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Label: sonarr.
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Categories: ['couchpotato', 'sickbeard', 'sonarr', 'sickrage', 'bypass'].
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Torrent hash: 61E0815B89259562160D3C82D92D857085BB60B2.
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Torrent name: Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD].
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Made it here too
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - This too
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Here
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - WebUI is true.
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Starting conversion
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Performing conversion
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Processing multiple files.
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Ignoring file C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Downloaded From PublicHD.SE.txt.
2016-05-10 19:54:13 - uTorrentPostProcess - INFO - Processing file C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN.mkv.
2016-05-10 19:54:13 - mkvtomp4 - INFO - Reading video stream.
2016-05-10 19:54:13 - mkvtomp4 - INFO - Video codec detected: h264.
2016-05-10 19:54:13 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2016-05-10 19:54:13 - mkvtomp4 - INFO - Reading audio streams.
2016-05-10 19:54:13 - mkvtomp4 - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2016-05-10 19:54:13 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [eng].
2016-05-10 19:54:13 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2016-05-10 19:54:14 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2016-05-10 19:54:14 - mkvtomp4 - INFO - Reading subtitle streams.
2016-05-10 19:54:14 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2016-05-10 19:54:14 - mkvtomp4 - INFO - Starting conversion.
2016-05-10 19:54:14 - mkvtomp4 - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\sickbeard_mp4_automator-master\mkvtomp4.py", line 617, in convert
    for timecode in conv:
  File "C:\sickbeard_mp4_automator-master\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\sickbeard_mp4_automator-master\converter\ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=3712, cmd="C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -i C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -f mp4 -threads auto -y C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN.mp4">
2016-05-10 19:54:14 - uTorrentPostProcess - ERROR - Error converting file C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN.mkv.
Traceback (most recent call last):
  File "C:\sickbeard_mp4_automator-master\uTorrentPostProcess.py", line 143, in <module>
    ignore.append(output['output'])
TypeError: 'bool' object has no attribute '__getitem__'
2016-05-10 19:54:14 - uTorrentPostProcess - INFO - Passing C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD] directory to Sonarr.
2016-05-10 19:54:14 - autoprocess.sonarr - INFO - Sonarr notifier started.
2016-05-10 19:54:14 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]'.
2016-05-10 19:54:15 - autoprocess.sonarr - INFO - Sonarr response: started.
2016-05-10 19:54:15 - uTorrentPostProcess - INFO - Successfully removed tempoary directory C:\Torrents\Incomplete\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD]\Game.of.Thrones.S03E09.REPACK.The.Rains.of.Castamere.1080p.WEB-DL.DD5.1.H.264-YFN [PublicHD].
2016-05-10 19:54:15 - uTorrentPostProcess - INFO - Done

I was running earlier without problems and now am getting this error.  My autoconfig.ini looks like this:

`[SickBeard]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Sonarr]
host = localhost
port = 8989
web_root =
ssl = 0
apikey = edc311db315c4c4a8d2c4998a1c3d282

[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
max-audio-channels =
audio-codec = ac3
audio-language =
audio-default-language =
audio-channel-bitrate =
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =

[CouchPotato]
host = localhost
port = 5050
username =
password =
web_root =
ssl = 0
apikey =
delay = 65
method = renamer
delete_failed = 0

[uTorrent]
convert = True
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:54299/gui/
username = admin
password = password

[Deluge]
host = localhost
username =
convert = True
password =
sonarr-label = sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard

[Sickrage]
host = localhost
port = 8081
username =
password =
web_root =
ssl = 0
api_key =

[Plex]
host = localhost
port = 32400
refresh = True
token = 
`

I saw earlier that some people had problems with the subtitle encoding, but mine is blank.  Any thoughts?

**Comment by ferlicjl** [comment]
Am I getting problems because the file might have a subtitle?  And then I haven't selected an encoding?

**Comment by mdhiggins** [comment]
Your settings look fine. Are you getting this with every file or just this one particular one?
