### ISSUE TITLE
Error notifying sickbeard

### ISSUE THREAD

**Issue by nogardvfx** [mdhiggins/sickbeard_mp4_automator#480]
Over the last week I have getting an SSL error message in SabNZBD.  I finally manually processed a video through sickbeard and received this error message below.  The funny thing is it has been working great for well over a year.  I am assuming I did some system update that caused this?  I am using Ubuntu Server 14..

2016-05-16 21:15:29 - tvdb_mp4 - INFO - Trying to write tags.
2016-05-16 21:15:30 - tvdb_mp4 - INFO - Tags written successfully.
2016-05-16 21:15:30 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
2016-05-16 21:15:38 - SickbeardPostConversion - ERROR - Couldn't refresh Sickbeard, check your autoProcess.ini settings.
Traceback (most recent call last):
File "/usr/serverApps/sickbeard_mp4_automator-master/postConversion.py", line 62, in
refresh = json.load(urllib.urlopen(settings.getRefreshURL(tvdb_id)))
File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
return opener.open(url)
File "/usr/lib/python2.7/urllib.py", line 213, in open
return getattr(self, name)(url)
File "/usr/lib/python2.7/urllib.py", line 443, in open_https
h.endheaders(data)
File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
self._send_output(message_body)
File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
self.send(msg)
File "/usr/lib/python2.7/httplib.py", line 859, in send
self.connect()
File "/usr/lib/python2.7/httplib.py", line 1278, in connect
server_hostname=server_hostname)
File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
_context=self)
File "/usr/lib/python2.7/ssl.py", line 579, in __init__
self.do_handshake()
File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

Cheers

**Comment by mdhiggins** [comment]
Looks like you're having issues with SSL under python.
You could either disable SSL for Sickbeard, verify your autoProcess.ini settings are correct, or look further into the complex web of problems that are SSL certificates under python

http://stackoverflow.com/questions/27804710/python-urllib2-ssl-error/27826829#27826829 is a decent starting place.

**Comment by mdhiggins** [comment]
Also make sure you have the requests security package installed (see readme)

**Comment by mdhiggins** [comment]
Likely improper installation or missing requests security package, reopen if persistent
