### ISSUE TITLE
Script refuses to convert video file under Raspbian (Debian 8 Jessie)

### ISSUE THREAD

**Issue by martylavender** [mdhiggins/sickbeard_mp4_automator#484]
Ive tried downloading a couple video files to make sure it wasnt the video file.

Im getting this in NZBGet

Sat May 21 2016 20:48:20	NZBGetPostProcess: File processing failed.
Sat May 21 2016 20:48:20	NZBGetPostProcess: Reading video stream.

```
2016-05-21 22:40:16 - NZBGetPostProcess - ERROR - File processing failed.
Traceback (most recent call last):
  File "/home/pi/downloads/scripts/NZBGetPostProcess.py", line 173, in <module>
    output = converter.process(inputfile)
  File "/home/pi/sickbeard_mp4_automator/mkvtomp4.py", line 150, in process
    options = self.generateOptions(inputfile, original=original)
  File "/home/pi/sickbeard_mp4_automator/mkvtomp4.py", line 259, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "/home/pi/sickbeard_mp4_automator/converter/__init__.py", line 27, in __init__
    ffprobe_path=ffprobe_path)
  File "/home/pi/sickbeard_mp4_automator/converter/ffmpeg.py", line 361, in __init__
    raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path)
FFMpegError: ffmpeg binary not found: /usr/bin/ffmpeg
```

I have my autoProcess.ini setup like this though

```
[MP4]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = auto
output_directory =
copy_to =
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level =
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
max-audio-channels =
audio-codec = ac3
audio-language =
audio-default-language =
audio-channel-bitrate =
subtitle-codec = mov_text
subtitle-language =
subtitle-default-language =
```

Its obvious from the error but why is it pulling the wrong path?

Ran this:

```
whereis ffmpeg
ffmpeg: /usr/local/bin/ffmpeg
```

When I run ffmpeg -version I get:

```
ffmpeg -version
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.9.2 (Raspbian 4.9.2-10)
configuration: --enable-gpl --enable-postproc --enable-swscale --enable-avfilter --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libx264 --enable-libspeex --enable-shared --enable-pthreads --enable-libopenjpeg --enable-libfaac --enable-nonfree
libavutil      54. 27.100 / 54.  3.  0
libavcodec     56. 41.100 / 56.  1.  0
libavformat    56. 36.100 / 56.  1.  0
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 16.101 /  5.  0.  0
libswscale      3.  1.101 /  3.  0.  0
libswresample   1.  2.100 /  1.  2.100
libpostproc    53.  3.100 / 53.  3.100
```

**Comment by mdhiggins** [comment]
That's really strange I have no idea why it would pull the wrong path. It should be coming directly from the autoProcess.ini file.

Situations like these are tough I would just delete and reinstall the script directory and reset autoProcess.ini and see if it persists. That's very strange

**Comment by mdhiggins** [comment]
Closing due to inactivity
