### ISSUE TITLE
 ReadSettings instance has no attribute 'threads' in NZBGetPostProcess

### ISSUE THREAD

**Issue by astrodad** [mdhiggins/sickbeard_mp4_automator#492]
Getting the following errors in NZBGetPostProcess after doing a pull today to get the latest. I checked and my autoProcess.in has auto for threads in the MP4 section. Also, I removed all pyc files to make sure it wasn't using old stuff.

NZBGetPostProcess: AttributeError: ReadSettings instance has no attribute 'threads'
INFO	Sat Jun 04 2016 17:07:06	NZBGetPostProcess: self.threads = settings.threads
INFO	Sat Jun 04 2016 17:07:06	NZBGetPostProcess: File "/Users/javier/sab_scripts/nzb2media/mkvtomp4.py", line 101, in importSettings
INFO	Sat Jun 04 2016 17:07:06	NZBGetPostProcess: self.importSettings(settings)
INFO	Sat Jun 04 2016 17:07:06	NZBGetPostProcess: File "/Users/javier/sab_scripts/nzb2media/mkvtomp4.py", line 94, in __init__
INFO	Sat Jun 04 2016 17:07:06	NZBGetPostProcess: converter = MkvtoMp4(settings, logger=log)
INFO	Sat Jun 04 2016 17:07:06	NZBGetPostProcess: File "/Users/javier/sab_scripts/nzb2media/NZBGetPostProcess.py", line 164, in <module>
INFO	Sat Jun 04 2016 17:07:06	NZBGetPostProcess: Traceback (most recent call last):
INFO	Sat Jun 04 2016 17:07:03	NZBGetPostProcess: Script triggered from NZBGet (11.0 or later).

**Comment by astrodad** [comment]
I'll add that I don't get this problem if I run manual.py, only if I run NZBGetPostProcess from within Nzbget.

**Comment by astrodad** [comment]
I used a new scripts folder and started from scratch, with a new autoProcess.ini (same contents as before) and it seems to work. I have a new problem, but I'll close this one and search for an answer for the new one.
