### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mattcosa** [mdhiggins/sickbeard_mp4_automator#506]
Recently did a Synology DSM update (minor) to  6.0.1-7393.

When running ./manual.py, I get the following OS error and I'm not sure how to start diagnosing this.

Traceback (most recent call last):
  File "/usr/local/sickbeard_mp4_automator/manual.py", line 356, in <module>
    main()
  File "/usr/local/sickbeard_mp4_automator/manual.py", line 347, in main
    processFile(path, tagdata)
  File "/usr/local/sickbeard_mp4_automator/manual.py", line 204, in processFile
    output = converter.process(inputfile, True)
  File "/usr/local/sickbeard_mp4_automator/mkvtomp4.py", line 150, in process
    options = self.generateOptions(inputfile, original=original)
  File "/usr/local/sickbeard_mp4_automator/mkvtomp4.py", line 259, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "/usr/local/sickbeard_mp4_automator/converter/**init**.py", line 254, in probe
    return self.ffmpeg.probe(fname, posters_as_video)
  File "/usr/local/sickbeard_mp4_automator/converter/ffmpeg.py", line 410, in probe
    '-show_format', '-show_streams', fname])
  File "/usr/local/sickbeard_mp4_automator/converter/ffmpeg.py", line 377, in _spawn
    close_fds=(os.name != 'nt'), startupinfo=None)
  File "/volume1/@appstore/python/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/volume1/@appstore/python/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**./subprocess.py exists and can be run manually with the following error;**

Child traceback:
Traceback (most recent call last):
  File "/volume1/@appstore/python/lib/python2.7/subprocess.py", line 1290, in _execute_child
    os.execvp(executable, args)
  File "/usr/lib/python2.7/os.py", line 346, in execvp
    _execvpe(file, args)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
OSError: [Errno 2] No such file or directory

**os.py can be run without any output to the console.**

**Comment by mdhiggins** [comment]
Looks like your path to your FFPROBE executable isn't correct. Fix that in autoprocess.ini (and check FFMPEG executable path as well since that may be messed up too)
