### ISSUE TITLE
Writing Tags for larger videos

### ISSUE THREAD

**Issue by alexrfan03** [mdhiggins/sickbeard_mp4_automator#52]
I'm getting the following error when I try to tag a larger file:

C:\Users\Owner\Downloads\Pacific.Rim.2013.720p.WEB-DL.H264-PublicHD\Pacific.rim.
2013.720p.web-dl.h264-publichd-1.m4v detected - already correct format, skipping
 reprocessing
Tagging file :C:\Users\Owner\Downloads\Pacific.Rim.2013.720p.WEB-DL.H264-PublicH
D\Pacific.rim.2013.720p.web-dl.h264-publichd-1.m4v
Trying to write tags
Traceback (most recent call last):
  File "C:\scripts\manual.py", line 127, in <module>
    main()
  File "C:\scripts\manual.py", line 121, in main
    tagmp4.writeTags(convert.output)
  File "C:\scripts\tmdb_mp4.py", line 87, in writeTags
    video.save()
  File "C:\scripts\mutagen__init__.py", line 134, in save
    return self.tags.save(filename, **kwargs)
  File "C:\scripts\mutagen\mp4.py", line 299, in save
    self.__save_existing(fileobj, atoms, path, data)
  File "C:\scripts\mutagen\mp4.py", line 352, in __save_existing
    insert_bytes(fileobj, delta, offset)
  File "C:\scripts\mutagen_util.py", line 226, in insert_bytes
    map = mmap.mmap(fobj.fileno(), filesize + size)
OverflowError: cannot fit 'long' into an index-sized integer

**Comment by mdhiggins** [comment]
As of commit 8375e799c53cfa9a0d87d62cccf747072875ee97 a workaround for this issue has been found and tagging should work on 32 bit systems regardless of file size
