### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by thecorax** [mdhiggins/sickbeard_mp4_automator#525]
running couchpotato as root, there shouldnt be any issues. dont know how to fix it. (debian)

already tried chown -R 777 for /var/opt/nzbget/ (i git cloned in there) and /media/secd/db/

> 08-07 14:43:39 INFO [ PostProcess] 2016-08-07 14:43:39 - CouchPotatoPostConversion - INFO - MP4 Automator - Post processing script initialized
> 2016-08-07 14:43:39 - readSettings - INFO - 
> 2016-08-07 14:43:39 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
> 2016-08-07 14:43:39 - CouchPotatoPostConversion - INFO - Processing file: /media/secd/db/Filme/Batman v Superman Dawn of Justice (2016)/Batman v Superman Dawn of Justice.mkv
> 2016-08-07 14:43:39 - CouchPotatoPostConversion - INFO - File is valid
> 2016-08-07 14:43:39 - CouchPotatoPostConversion - ERROR - File processing failed: /media/secd/db/Filme/Batman v Superman Dawn of Justice (2016)/Batman v Superman Dawn of Justice.mkv
> Traceback (most recent call last):
> File "/var/opt/nzbget/scripts/sickbeard_mp4_automator/postCouchPotato.py", line 33, in 
> output = converter.process(inputfile, original=original)
> File "/var/opt/nzbget/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 150, in process
> options = self.generateOptions(inputfile, original=original)
> File "/var/opt/nzbget/scripts/sickbeard_mp4_automator/mkvtomp4.py", line 259, in generateOptions
> info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
> File "/var/opt/nzbget/scripts/sickbeard_mp4_automator/converter/init.py", line 254, in probe
> return self.ffmpeg.probe(fname, posters_as_video)
> File "/var/opt/nzbget/scripts/sickbeard_mp4_automator/converter/ffmpeg.py", line 410, in probe
> '-show_format', '-show_streams', fname])
> File "/var/opt/nzbget/scripts/sickbeard_mp4_automator/converter/ffmpeg.py", line 377, in spawn
> close_fds=(os.name != 'nt'), startupinfo=None)
> File "/usr/lib/python2.7/subprocess.py", line 710, in __init_
> errread, errwrite)
> File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
> raise child_exception
> OSError: [Errno 13] Permission denied

**Comment by thecorax** [comment]
mostly this: 
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/177
