### ISSUE TITLE
mkvtomp4 - ERROR - Error converting file, FFMPEG error.

### ISSUE THREAD

**Issue by gstq54** [mdhiggins/sickbeard_mp4_automator#550]
Just started using an older pc as a media server, using Plex. Machine is too slow to transcode mkv, so thought I would use you  automator and save as mp4. However I'm getting errors from sabnzbd, as follows:

Queue
1
1.39 | 1.39 | 1.87 | V=1951M R=116M
809 MB left
1.0 TB Free Space (Temp Folder)
1.0 TB Free Space

DCI.Banks.S05E01.What.Will.Survive.01.1080p.WEB-DL

80%
3012 MB / 3730 MB
    3:43    

The Beatles - Abbey Road - Vinyl Rip

0%
0 MB / 97 MB
    4:13    

ERROR 31/08/2016 18:03 Cannot change permissions of /home/kodi/Downloads/incomplete
INFO Cache articles in memory to reduce disk access. In bytes, optionally follow with K,M,G. For example: "256M" or "512M"  
History

Titanic.1997.1080p.BluRay.DTS-HD.MA.5.1.x264-FuzerHD.cp(tt0120338)
    ValueError: No JSON object could be decoded  
    01/09/2016 16:06    

The.Great.British.Bake.Off.S07E02.720p.HDTV.x264-DEADPOOL
    Completed  
    31/08/2016 17:49    

Steve.Jobs.2015.1080p.BluRay.DTS-HD.MA.5.1.x264-FuzerHD.cp(tt2080374)
    ValueError: No JSON object could be decoded  
    31/08/2016 17:48    

Great.British.Menu.S10E45.Finals.Week.Banquet.720p.HDTV.x264-C4TV
    Completed  
    31/08/2016 16:39    

Great.British.Menu.S10E33.London.South.East.Main.720p.HDTV.x264-C4TV-Obfuscated
    Completed  
    31/08/2016 16:33    

Great.British.Menu.S10E32.London.South.East.Fish.720p.HDTV.x264-C4TV
    Completed  
    31/08/2016 16:30    

Great.British.Menu.S10E31.London.South.East.Starter.720p.HDTV.x264-C4TV-Obfuscated
    Completed  
    31/08/2016 16:28    

Great.British.Menu.S10E30.North.West.Judges.720p.HDTV.x264-TASTETV
    Completed  
    31/08/2016 16:25    

Great.British.Menu.S10E29.North.West.Dessert.720p.HDTV.x264-C4TV
    Completed  
    31/08/2016 16:23    

Great.British.Menu.S10E28.North.West.Main.720p.HDTV.x264-TASTETV-Obfuscated
    Completed  
    31/08/2016 16:21    

```
1 2 3 4 5 6 
```

18.0 GB Today 18.0 GB This month 115.0 GB Total
Titanic.1997.1080p.BluRay.DTS-HD.MA.5.1.x264-FuzerHD.cp(tt0120338)

2016-09-01 16:16:14 - SABPostProcess - INFO - SAB post processing started.
2016-09-01 16:16:14 - readSettings - INFO - /usr/bin/python
2016-09-01 16:16:14 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-09-01 16:16:14 - SABPostProcess - INFO - Performing conversion
2016-09-01 16:16:14 - SABPostProcess - INFO - Processing file /home/kodi/Movies/Titanic.1997.1080p.BluRay.DTS-HD.MA.5.1.x264-FuzerHD.cp(tt0120338)/Titanic.1997.1080p.BluRay.DTS-HD.MA.5.1.x264-FuzerHD.mkv.
2016-09-01 16:16:15 - mkvtomp4 - INFO - Reading video stream.
2016-09-01 16:16:15 - mkvtomp4 - INFO - Video codec detected: h264.
2016-09-01 16:16:15 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2016-09-01 16:16:15 - mkvtomp4 - INFO - Reading audio streams.
2016-09-01 16:16:15 - mkvtomp4 - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2016-09-01 16:16:15 - mkvtomp4 - INFO - Reading subtitle streams.
2016-09-01 16:16:16 - mkvtomp4 - INFO - Starting conversion.
2016-09-01 16:28:36 - mkvtomp4 - INFO - /home/kodi/Movies/Titanic.1997.1080p.BluRay.DTS-HD.MA.5.1.x264-FuzerHD.cp(tt0120338)/Titanic.1997.1080p.BluRay.DTS-HD.MA.5.1.x264-FuzerHD.mp4 created.
2016-09-01 16:28:38 - SABPostProcess - INFO - Passing /home/kodi/Movies/Titanic.1997.1080p.BluRay.DTS-HD.MA.5.1.x264-FuzerHD.cp(tt0120338) directory to Couch Potato.
2016-09-01 16:28:38 - autoprocess.autoProcessMovie - INFO - Waiting for 65.0 seconds to allow CPS to process newly extracted files.
2016-09-01 16:29:44 - autoprocess.autoProcessMovie - INFO - Opening URL: http://localhost:5050/api//renamer.scan.
Traceback (most recent call last):
  File "/downloads/sickbeard_mp4_automator/SABPostProcess.py", line 74, in <module>
    autoProcessMovie.process(path, settings, nzb, sys.argv[7])
  File "/downloads/sickbeard_mp4_automator/autoprocess/autoProcessMovie.py", line 93, in process
    rstate = r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Hopefully you will be able to help me with this. I fad a stroke 7 years ago and my brain is not quite as sharp as it used to be.
Cheers, Richard Wilkinson

**Comment by mdhiggins** [comment]
JSON errors when autoProcess movie is failing are due to your CouchPotato settings being incorrect or CouchPotato not running.

Verify your couchpotato settings in autoProcess.ini including address/port/api key/username etc

**Comment by gstq54** [comment]
Thanks for you reply. I have made the changes as above and no longer get the JSON error, however still getting many errors as shown in the info.log
I have probably not configured correctly, but perhaps you would take a look and let me know? 
Thanks, Richard
[info.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/460069/info.txt)

**Comment by mdhiggins** [comment]
Just pushed an update that will have the script spit out a lot more debugging information when FFMPEG errors are encountered. Update and rerun and post the output please.

**Comment by gstq54** [comment]
thanks for you message, I have updated the script and posted the output, 
[info.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/517032/info.txt)

here

**Comment by mdhiggins** [comment]
Looks like you're using an old version of FFMPEG that doesn't support the disposition option. Update to a newer build
