### ISSUE TITLE
Couch Potato integreation problems

### ISSUE THREAD

**Issue by TheBigZig** [mdhiggins/sickbeard_mp4_automator#552]
I've followed the instructions for Couch Potato integration, but I get the following errors when I try to load the script:
09-03 11:25:37ERROR[  couchpotato.core.loader] Can't import PostProcess: Traceback (most recent call last):
  File "C:\Users\Bill\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\loader.py", line 58, in run
  File "C:\Users\Bill\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\loader.py", line 164, in loadModule
  File "C:\Users\Bill\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\importhelper\__init__.py", line 37, in import_module
  File "C:\Users\Bill\AppData\Roaming\CouchPotato\custom_plugins\PostProcess\__init__.py", line 1, in <module>
  File "C:\Users\Bill\AppData\Roaming\CouchPotato\custom_plugins\PostProcess\main.py", line 11
    path = C:\sickbeard_mp4_automator\
            ^
SyntaxError: invalid syntax
Any suggestions?
Thanks
Bill

**Comment by mdhiggins** [comment]
Looks like you didn't use double backslashes

**Comment by mdhiggins** [comment]
Or quotes

**Comment by TheBigZig** [comment]
So I need quotes AND double blackslashes?
I tried with not quotes, and got the following:
09-05 15:44:11ERROR[tato.core.plugins.renamer] Missing `cd` or `cd_nr` in the renamer. This will cause multi-file releases of being renamed to the same file. Please add it in the renamer settings. Force adding it for now.

**Comment by mdhiggins** [comment]
You need both, You're editing a python file meaning you need to use python compatible syntax. Strings must be in a quotes and special characters need to be escaped. So you need double backslashes and quotes.

**Comment by TheBigZig** [comment]
Ok, the script looks to be loading, but it doesn't appear to be doing anything.  
CP moves the file, but all that is in the folder is a .mkv file.  Do I just need to wait a while?

**Comment by TheBigZig** [comment]
Yep, I was just moving too fast!  Works like a champ!
Your responsiveness is IMPRESSIVE!!! I Really appreciate the tool you wrote, but more than that, the way you support it.
Thanks
Bill

**Comment by noremacyug** [comment]
^^^^ agreed.

**Comment by mdhiggins** [comment]
Just glad you're enjoying it!
