### ISSUE TITLE
Sonarr and Sabnzbd

### ISSUE THREAD

**Issue by xman4ever** [mdhiggins/sickbeard_mp4_automator#561]
From what I understood is we only have to configure one : either the down loader or the manager.

So I followed the steps and configured Sonarr with the post process script AND Completed Download Handling  set to off.  
Issue:  Sabnzbd downloaded with no issues but Sonarr had no idea the file was downloaded so couldn't process the conversion.

So I went back and enabled Completed Download handling.  Obviously Sonarr  can see the file being downloaded but still wouldn't convert the mkv to mp4.  So I went looking into sonarr log file and found the error:

Message
**"Unable to send OnDownload notification to: PostSonarr: The specified executable is not a valid application for this OS platform."**

Exception

System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 167
   at NzbDrone.Common.Processes.ProcessProvider.StartAndCapture(String path, String args, StringDictionary environmentVariables) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 199
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.ExecuteScript(StringDictionary environmentVariables) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 125
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnDownload(DownloadMessage message) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 84
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeDownloadedEvent message) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Notifications\NotificationService.cs:line 132

So the error may explain why Sonarr couldn't see the file initially when "completed download handling" was disabled BUT wrong OS platform means something is REALLY wrong soemwhere.

My questions are:  
Do I need to configure BOTH downloader (Sabnzbd) and manager (Sonarr) ?
Where did I go wrong?

ps.  Installing python 2.7 with all the includes went very smoothly (using powershell 3)

I downloaded the 64-bit static ffmpeg build

**Comment by mdhiggins** [comment]
https://forums.sonarr.tv/t/custom-scripts-error-on-win-7/6843/11

**Comment by mdhiggins** [comment]
You ever get this sorted?

**Comment by xman4ever** [comment]
No not yet
