### ISSUE TITLE
error from IMDB

### ISSUE THREAD

**Issue by raymatos** [mdhiggins/sickbeard_mp4_automator#572]
### Logs:

```
10-09 01:38:25 INFO [              PostProcess] 2016-10-09 01:36:50 - CouchPotatoPostConversion - INFO - MP4 Automator - Post processing script initialized
2016-10-09 01:36:50 - readSettings - INFO - /usr/local/bin/python2.7
2016-10-09 01:36:50 - CouchPotatoPostConversion - INFO - Processing file: /mnt/media/Movies/Couples Retreat (2009)/Couples Retreat-trailer.mov
2016-10-09 01:36:50 - CouchPotatoPostConversion - INFO - File is valid
2016-10-09 01:36:50 - mkvtomp4 - INFO - Reading video stream.
2016-10-09 01:36:50 - mkvtomp4 - INFO - Video codec detected: h264.
2016-10-09 01:36:50 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2016-10-09 01:36:50 - mkvtomp4 - INFO - Reading audio streams.
2016-10-09 01:36:50 - mkvtomp4 - INFO - Audio detected for stream #1: aac [eng].
2016-10-09 01:36:50 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2016-10-09 01:36:50 - mkvtomp4 - INFO - Audio track is number 0 setting disposition to default
2016-10-09 01:36:50 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2016-10-09 01:36:50 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to none
2016-10-09 01:36:50 - mkvtomp4 - INFO - Reading subtitle streams.
2016-10-09 01:36:50 - mkvtomp4 - INFO - Starting conversion.
2016-10-09 01:36:54 - mkvtomp4 - INFO - /mnt/media/Movies/Couples Retreat (2009)/Couples Retreat-trailer.mp4 created.
2016-10-09 01:36:55 - CouchPotatoPostConversion - INFO - Tagging file with IMDB ID tt1078940
2016-10-09 01:37:05 - tmdb_mp4 - ERROR - Failed to connect to tMDB, trying again in 20 seconds.
Traceback (most recent call last):
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_mp4.py", line 41, in __init__
    self.movie = tmdb.Movie(imdbid)
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 122, in __init__
    self.update_configuration()
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 65, in update_configuration
    c = self.getJSON(config['urls']['config'])
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 53, in getJSON
    page = requests.get(url, params={'language': language}).content
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/api.py", line 55, in get
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/api.py", line 44, in request
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/sessions.py", line 354, in request
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/sessions.py", line 460, in send
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/adapters.py", line 250, in send
SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
2016-10-09 01:37:35 - tmdb_mp4 - ERROR - Failed to connect to tMDB, trying again in 20 seconds.
Traceback (most recent call last):
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_mp4.py", line 41, in __init__
    self.movie = tmdb.Movie(imdbid)
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 122, in __init__
    self.update_configuration()
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 65, in update_configuration
    c = self.getJSON(config['urls']['config'])
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 53, in getJSON
    page = requests.get(url, params={'language': language}).content
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/api.py", line 55, in get
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/api.py", line 44, in request
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/sessions.py", line 354, in request
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/sessions.py", line 460, in send
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/adapters.py", line 250, in send
SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
2016-10-09 01:38:05 - tmdb_mp4 - ERROR - Failed to connect to tMDB, trying again in 20 seconds.
Traceback (most recent call last):
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_mp4.py", line 41, in __init__
    self.movie = tmdb.Movie(imdbid)
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 122, in __init__
    self.update_configuration()
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 65, in update_configuration
    c = self.getJSON(config['urls']['config'])
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 53, in getJSON
    page = requests.get(url, params={'language': language}).content
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/api.py", line 55, in get
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/api.py", line 44, in request
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/sessions.py", line 354, in request
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/sessions.py", line 460, in send
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_api/requests/adapters.py", line 250, in send
SSLError: [Errno 185090050] _ssl.c:344: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
2016-10-09 01:38:25 - tmdb_mp4 - INFO - Tagging file: /mnt/media/Movies/Couples Retreat (2009)/Couples Retreat-trailer.mp4.
2016-10-09 01:38:25 - CouchPotatoPostConversion - ERROR - File processing failed: /mnt/media/Movies/Couples Retreat (2009)/Couples Retreat-trailer.mov
Traceback (most recent call last):
  File "/usr/local/share/sickbeard_mp4_automator/postCouchPotato.py", line 41, in <module>
    tagmp4.writeTags(output['output'], settings.artwork)
  File "/usr/local/share/sickbeard_mp4_automator/tmdb_mp4.py", line 73, in writeTags
    video["\xa9nam"] = self.title  # Movie title
AttributeError: tmdb_mp4 instance has no attribute 'title'

```

**Comment by mdhiggins** [comment]
Getting this error for every movie?
