### ISSUE TITLE
Plex Tells me there is a problem playing the converted file but works perfectly on mobile minus no audio

### ISSUE THREAD

**Issue by rosscco** [mdhiggins/sickbeard_mp4_automator#582]
Hi, SABnzbd returns this:

2016-10-25 02:32:48 - SABPostProcess - INFO - SAB post processing started.
2016-10-25 02:32:48 - readSettings - INFO - /usr/bin/python
2016-10-25 02:32:48 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-10-25 02:32:48 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring.
2016-10-25 02:32:48 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'.
2016-10-25 02:32:48 - SABPostProcess - INFO - Performing conversion
2016-10-25 02:32:48 - SABPostProcess - INFO - Processing file /home/rosscco/Downloads/complete/Bones.S02E01.DVDRip.XviD-TOPAZ.8/tpz-bones201.avi.
2016-10-25 02:32:49 - mkvtomp4 - INFO - Reading video stream.
2016-10-25 02:32:49 - mkvtomp4 - INFO - Video codec detected: mpeg4.
2016-10-25 02:32:49 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2016-10-25 02:32:49 - mkvtomp4 - INFO - Reading audio streams.
2016-10-25 02:32:49 - mkvtomp4 - INFO - Audio detected for stream #1: mp3 [und].
2016-10-25 02:32:49 - mkvtomp4 - INFO - Creating audio stream 0 from source stream 1.
2016-10-25 02:32:49 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to default
2016-10-25 02:32:49 - mkvtomp4 - INFO - Reading subtitle streams.
2016-10-25 02:32:49 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2016-10-25 02:32:49 - mkvtomp4 - INFO - Starting conversion.
2016-10-25 02:44:27 - mkvtomp4 - INFO - /home/rosscco/Downloads/complete/Bones.S02E01.DVDRip.XviD-TOPAZ.8/tpz-bones201.mp4 created.
2016-10-25 02:44:27 - SABPostProcess - INFO - Processing file /home/rosscco/Downloads/complete/Bones.S02E01.DVDRip.XviD-TOPAZ.8/tpz-bones201-sample.avi.
2016-10-25 02:44:27 - mkvtomp4 - INFO - Reading video stream.
2016-10-25 02:44:27 - mkvtomp4 - INFO - Video codec detected: mpeg4.
2016-10-25 02:44:27 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2016-10-25 02:44:27 - mkvtomp4 - INFO - Reading audio streams.
2016-10-25 02:44:27 - mkvtomp4 - INFO - Audio detected for stream #1: mp3 [und].
2016-10-25 02:44:27 - mkvtomp4 - INFO - Creating audio stream 0 from source stream 1.
2016-10-25 02:44:27 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to default
2016-10-25 02:44:27 - mkvtomp4 - INFO - Reading subtitle streams.
2016-10-25 02:44:27 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2016-10-25 02:44:27 - mkvtomp4 - INFO - Starting conversion.
2016-10-25 02:44:44 - mkvtomp4 - INFO - /home/rosscco/Downloads/complete/Bones.S02E01.DVDRip.XviD-TOPAZ.8/tpz-bones201-sample.mp4 created.
2016-10-25 02:44:44 - SABPostProcess - INFO - Passing /home/rosscco/Downloads/complete/Bones.S02E01.DVDRip.XviD-TOPAZ.8 directory to Sonarr.
2016-10-25 02:44:44 - autoprocess.sonarr - INFO - Sonarr notifier started.
2016-10-25 02:44:44 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/home/rosscco/Downloads/complete/Bones.S02E01.DVDRip.XviD-TOPAZ.8'.
2016-10-25 02:44:44 - autoprocess.sonarr - INFO - Sonarr response: queued.

The file has then been converted, When I try to play it via plex it just tells me that theres a problem playing it..... When I play it on my phone it plays perfectly (I get no audio on my phone) so a fix for this would also be appreciated. Any ideas?

**Comment by rosscco** [comment]
UPDATE:

Fixed the above.... Now I'm getting


Traceback (most recent call last):
  File "/home/rosscco/scripts/SABPostProcess.py", line 11, in <module>
    fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(os.path.dirname(sys.argv[0]), 'info.log').replace("\\", "/")})
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'

**Comment by rosscco** [comment]
Update:


2016-10-24 21:17:49 - SABPostProcess - INFO - SAB post processing started.
2016-10-24 21:17:49 - readSettings - INFO - /usr/bin/python
2016-10-24 21:17:49 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-10-24 21:17:49 - SABPostProcess - INFO - Performing conversion
2016-10-24 21:17:49 - SABPostProcess - INFO - Processing file /home/rosscco/Downloads/complete/Arrow.S01E23.720p.BluRay.nSD.x264-NhaNc3-Chamele0n.11/e91aba8db91f4a0dbbd027f2499ccf33.mkv.
2016-10-24 21:17:49 - mkvtomp4 - INFO - Reading video stream.
2016-10-24 21:17:49 - SABPostProcess - ERROR - Error converting file /home/rosscco/Downloads/complete/Arrow.S01E23.720p.BluRay.nSD.x264-NhaNc3-Chamele0n.11/e91aba8db91f4a0dbbd027f2499ccf33.mkv.
Traceback (most recent call last):
  File "/home/rosscco/scripts/SABPostProcess.py", line 57, in <module>
    output = converter.process(inputfile)
  File "/home/rosscco/scripts/mkvtomp4.py", line 156, in process
    options = self.generateOptions(inputfile, original=original)
  File "/home/rosscco/scripts/mkvtomp4.py", line 269, in generateOptions
    self.log.info("Video codec detected: %s." % info.video.codec)
AttributeError: 'NoneType' object has no attribute 'video'
2016-10-24 21:17:49 - SABPostProcess - INFO - Passing /home/rosscco/Downloads/complete/Arrow.S01E23.720p.BluRay.nSD.x264-NhaNc3-Chamele0n.11 directory to Sonarr.
2016-10-24 21:17:49 - autoprocess.sonarr - INFO - Sonarr notifier started.
2016-10-24 21:17:49 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory '/home/rosscco/Downloads/complete/Arrow.S01E23.720p.BluRay.nSD.x264-NhaNc3-Chamele0n.11'.
2016-10-24 21:17:50 - autoprocess.sonarr - INFO - Sonarr response: queued.




The error being this part:

2016-10-24 21:17:49 - SABPostProcess - INFO - Processing file /home/rosscco/Downloads/complete/Arrow.S01E23.720p.BluRay.nSD.x264-NhaNc3-Chamele0n.11/e91aba8db91f4a0dbbd027f2499ccf33.mkv.
2016-10-24 21:17:49 - mkvtomp4 - INFO - Reading video stream.
2016-10-24 21:17:49 - SABPostProcess - ERROR - Error converting file /home/rosscco/Downloads/complete/Arrow.S01E23.720p.BluRay.nSD.x264-NhaNc3-Chamele0n.11/e91aba8db91f4a0dbbd027f2499ccf33.mkv.
Traceback (most recent call last):
  File "/home/rosscco/scripts/SABPostProcess.py", line 57, in <module>
    output = converter.process(inputfile)
  File "/home/rosscco/scripts/mkvtomp4.py", line 156, in process
    options = self.generateOptions(inputfile, original=original)
  File "/home/rosscco/scripts/mkvtomp4.py", line 269, in generateOptions
    self.log.info("Video codec detected: %s." % info.video.codec)
AttributeError: 'NoneType' object has no attribute 'video'

**Comment by mdhiggins** [comment]
Can you post your autoProcess.ini settings as well as ffprobe outputs for the final file that's giving you playback issues

Also need more information about plex failing
 Its it trying to transcode? Is it using directplay/directstream? what player is it failing on?
