### ISSUE TITLE
CouchPotato Complaining, but not sure why?

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#589]
11-02 21:37:14 ERROR [              PostProcess] Failed to execute post processing on file /var/hda/files/drives/8TB/Plex/Movies/Bad Moms (2016)/Bad Moms (2016) 720p.mp4
11-02 21:37:14 ERROR [              PostProcess] Traceback (most recent call last):
  File "/var/hda/web-apps/couchpotato/data/custom_plugins/PostProcess/main.py", line 40, in callscript process = subprocess.Popen([exec_me, imdbid, inputfile, original], shell=False, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env={})
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

Any ideas to what this referencing to? I set my permissions for it to be able to write to the folder just as I did for Sonarr...

**Comment by mdhiggins** [comment]
Did you edit your main.py file to reflect the appropriate script path as directed in the readme?

Looks like that path isn't set or is set incorrectly

**Comment by justinglock40** [comment]
Yea I noticed the instructions last night said to point to where it resides. Not and actual script. Thanks again. All is good now.
