### ISSUE TITLE
Remuxing or Converting

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#595]
So I've been downloading files in h265/10-bit, but when they come out of the script the are h264/8-bit. Is the scripit supposed to be converting or just remuxing from mkv to mp4? 

For Xbox One S to direct play 4K it has to be H265 8-bit/10Bit. Otherwise it transcodes. Any ideas or thoughts on this?

**Comment by mdhiggins** [comment]
Sounds like you haven't listed h265 as a codec you want to remux. Add it to your video-codec list in your settings ini

**Comment by justinglock40** [comment]
I did add it as a codec in autoProcess.ini. However when the script runs this is what is returned seems there's an issue at line 57?:

2016-11-14 08:17:00 - readSettings - INFO - /usr/bin/python 
2016-11-14 08:17:00 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel. 
2016-11-14 08:17:01 - readSettings - WARNING - Invalid interal subtitle codec srt, defaulting to 'mov_text'. 
2016-11-14 08:17:01 - SABPostProcess - INFO - Performing conversion 

2016-11-14 08:17:01 - SABPostProcess - INFO - Processing file /var/hda/files/drives/3TB/newsgroups/complete/Watchmen.(2009).2160p.4K.UltraHD.BluRay.(x265.HEVC.10bit).2CH.AC3/Watchmen (2009) 2160p 4K UltraHD BluRay (x265 HEVC 10bit) 2CH AC3.mkv. 2016-11-14 08:17:01 - mkvtomp4 - INFO - Reading video stream. 

2016-11-14 08:17:01 - SABPostProcess - ERROR - Error converting file /var/hda/files/drives/3TB/newsgroups/complete/Watchmen.(2009).2160p.4K.UltraHD.BluRay.(x265.HEVC.10bit).2CH.AC3/Watchmen (2009) 2160p 4K UltraHD BluRay (x265 HEVC 10bit) 2CH AC3.mkv. 

Traceback (most recent call last): 

 File "/home/jwashington/SABPostProcess.py", line 57, in <module> output = converter.process(inputfile) 
 File "/home/jwashington/mkvtomp4.py", line 156, in process options = self.generateOptions(inputfile, original=original) File "/home/jwashington/mkvtomp4.py", line 269, in generateOptions self.log.info("Video codec detected: %s." % info.video.codec) AttributeError: 'NoneType' object has no attribute 'video' 

2016-11-14 08:17:01 - SABPostProcess 
- INFO - Passing /var/hda/files/drives/3TB/newsgroups/complete/Watchmen.(2009).2160p.4K.UltraHD.BluRay.(x265.HEVC.10bit).2CH.AC3 directory to Couch Potato. 
2016-11-14 08:17:01 - autoprocess.autoProcessMovie - INFO - Waiting for 65.0 seconds to allow CPS to process newly extracted files.
 2016-11-14 08:18:06 - autoprocess.autoProcessMovie - INFO - Opening URL: http://localhost:5050/api/77d9d9d707424bc6b89092ce482bd4a6/renamer.scan. 
2016-11-14 08:19:45 - autoprocess.autoProcessMovie- INFO - CouchPotatoServer returned {u'success': True}.

**Comment by justinglock40** [comment]
So I looked in mkvtomp4.py and there's no reference to h265 despite adding the codec via autoProcess.ini. Do you think thats why my files maybe failing when its 265?

**Comment by mdhiggins** [comment]
Post your autoProcess.ini file so I can take a look

Also in addition to having h265 on your codec list, add x265 and hevc as well just to make sure you capture all the variants of h265

**Comment by justinglock40** [comment]
Thanks I got it last night. I finally figured it out.
