### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by xpack90** [mdhiggins/sickbeard_mp4_automator#601]
I just ran git pull to pull the latest changes and now I am getting the error 

`TypeError: a bytes-like object is required, not 'str'`

This is the full error 
`2016-11-23 11:54:20 - SABPostProcess - INFO - SAB post processing started.
2016-11-23 11:54:20 - readSettings - INFO - C:\Python3\python.exe
Traceback (most recent call last):
  File "C:\Automator\SABPostProcess.py", line 29, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")
  File "C:\Automator\readSettings.py", line 187, in __init__
    self.writeConfig(config, configFile)
  File "C:\Automator\readSettings.py", line 598, in writeConfig
    config.write(fp)
  File "C:\Python3\lib\configparser.py", line 916, in write
    self._sections[section].items(), d)
  File "C:\Python3\lib\configparser.py", line 920, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'`

**Comment by xpack90** [comment]
Running git pull wiped autoProcess.ini so had to recreate it.
