### ISSUE TITLE
AttributeError: ReadSettings instance has no attribute 'log'

### ISSUE THREAD

**Issue by mikey67156** [mdhiggins/sickbeard_mp4_automator#613]
Here's the error that Sabnzbd is outputting.  I'm getting the same log error when I try to run manual.py.    

`2016-12-11 11:08:27 - SABPostProcess - INFO - SAB post processing started.
2016-12-11 11:08:27 - readSettings - INFO - C:\Python27\python.exe
2016-12-11 11:08:27 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
Traceback (most recent call last):
  File "C:\sickbeard_mp4_automator-master\SABPostProcess.py", line 29, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini")
  File "C:\sickbeard_mp4_automator-master\readSettings.py", line 450, in __init__
    self.log.error("Invalid download-artwork value, defaulting to 'poster'.")
AttributeError: ReadSettings instance has no attribute 'log'`

**Comment by mdhiggins** [comment]
Looks like whatever option you have set for download-artwork in your autoProcess.ini is invalid. I would double check those settings.

**Comment by mdhiggins** [comment]
Also looks like there was a small bug in the generation of the error message when that problem occurs. That has been fixed but you'll still need to fix your config file.

**Comment by mikey67156** [comment]
Changed setting to 256, and it works like a champ.  Thank you very much.
