### ISSUE TITLE
Sonarr not sending TVID

### ISSUE THREAD

**Issue by alokshah14** [mdhiggins/sickbeard_mp4_automator#614]
I can get a TV show to convert and get the file moved but during conversion it won't download any metadata. The file is sent from Sonarr so not sure why it wouldn't. When I run the manual.py with the same file it find the TVID and downloads the metadata.

**Comment by mdhiggins** [comment]
Is your Sonarr post processing script set up and being executed? or is the conversion and post downloading script only doing its thing (SAB/NZBGet/Torrent)?
You won't get tagging without the postSonarr.py script configured

**Comment by alokshah14** [comment]
I have the script configured in Sonarr it seems like it is not running after the conversion. I looked at the logs and it gives me a "__Main__module" error for python.exe. 
<img width="994" alt="image" src="https://cloud.githubusercontent.com/assets/6709445/21108783/fd30c152-c05b-11e6-97bc-a7a9e1089781.png">

I have Sonarr postSonarr configure like this:
<img width="1131" alt="image" src="https://cloud.githubusercontent.com/assets/6709445/21108955/a70cc892-c05c-11e6-8b56-e0fc8c5853c9.png">

And this is what my SABNZBD shows: 
<img width="1413" alt="image" src="https://cloud.githubusercontent.com/assets/6709445/21109028/e2cc88e0-c05c-11e6-9723-7c003c38877d.png">

Looking at the INFO file and response it is stuck on queuing at Sonarr:
<img width="1156" alt="image" src="https://cloud.githubusercontent.com/assets/6709445/21109065/0550622e-c05d-11e6-8056-6da171cca969.png">

I love that it is converting everything but would be great if I could get the metadata as well. 

Thank you.

**Comment by mdhiggins** [comment]
Everything you're telling me is how the script is supposed to behave. No tagging should be fine until the file is sent back to Sonarr and Sonarr completes its tasks. It's the final step that Sonarr will execute assuming you have properly configured Sonarr to run postSonarr.py on completion. Have you set this script up?

**Comment by mdhiggins** [comment]
What's the full path in the arguments text box in your Sonarr settings there. I can't see the end of it.

**Comment by alokshah14** [comment]
I have the script set up under connect according to the instructions: Here is the full path

"C:\Users\LivingRoom\Downloads\sickbeard_mp4_automator-master\sickbeard_mp4_automator-master\postSonarr.py" without the quotes.

**Comment by mdhiggins** [comment]
That error looks like it's trying to execute the directory rather than the postSonarr script itself. I dunno why it would be doing that but maybe delete and replace that line in your settings. Alternatively you could try wrapping it in quotes and see if that helps.

**Comment by alokshah14** [comment]
I tried with the quotes and the script says successful when I test it in Sonarr but I still get "Sonar response: Queued" under SABNZBD and no indication of script running in Sonarr logs.

**Comment by mdhiggins** [comment]
Look in the info.log file for messages from postSonarr and see if anything is there

**Comment by alokshah14** [comment]
Info log shows that Sonarr script starts but then there are some errors once it starts. Here is the what is shows in the info.log for the last show I downloaded:

2016-12-14 08:35:30 - MANUAL - INFO - Starting conversion.
2016-12-14 08:39:01 - MANUAL - INFO - Manual processor started.
2016-12-14 08:39:01 - MANUAL - INFO - C:\Python27\python.exe
2016-12-14 08:39:01 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-12-14 08:39:03 - MANUAL - INFO - Reading video stream.
2016-12-14 08:42:31 - SABPostProcess - INFO - SAB post processing started.
2016-12-14 08:42:31 - readSettings - INFO - C:\Python27\python.exe
2016-12-14 08:42:31 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-12-14 08:42:33 - SABPostProcess - INFO - Performing conversion
2016-12-14 08:42:33 - SABPostProcess - INFO - Processing file D:\TV Shows\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD\street.outlaws.s06e07.stuck.in.a.moment.internal.720p.hdtv.x264-dhd-sample.mkv.
2016-12-14 08:42:34 - mkvtomp4 - INFO - Reading video stream.
2016-12-14 08:42:34 - mkvtomp4 - INFO - Video codec detected: h264.
2016-12-14 08:42:34 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2016-12-14 08:42:34 - mkvtomp4 - INFO - Reading audio streams.
2016-12-14 08:42:34 - mkvtomp4 - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2016-12-14 08:42:34 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [und].
2016-12-14 08:42:34 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2016-12-14 08:42:34 - mkvtomp4 - INFO - Audio track is number 0 setting disposition to default
2016-12-14 08:42:34 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2016-12-14 08:42:34 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to none
2016-12-14 08:42:34 - mkvtomp4 - INFO - Reading subtitle streams.
2016-12-14 08:42:34 - mkvtomp4 - INFO - Subtitle detected for stream #2: subrip [eng].
2016-12-14 08:42:34 - mkvtomp4 - INFO - Attempting to download subtitles.
2016-12-14 08:42:34 - subliminal.video - INFO - Scanning video 'street.outlaws.s06e07.stuck.in.a.moment.internal.720p.hdtv.x264-dhd-sample.mkv' in 'D:\\TV Shows\\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD'
2016-12-14 08:42:34 - enzyme.mkv - INFO - Reading Segment element
2016-12-14 08:42:34 - enzyme.parsers.ebml.core - INFO - MasterElement EBML ignored
2016-12-14 08:42:34 - enzyme.parsers.ebml.core - INFO - Maximum level 0 reached for children of MasterElement Segment
2016-12-14 08:42:34 - enzyme.mkv - INFO - Reading SeekHead element
2016-12-14 08:42:34 - enzyme.mkv - INFO - Processing element Info from SeekHead at position 4151
2016-12-14 08:42:34 - enzyme.mkv - INFO - Processing element Tracks from SeekHead at position 4274
2016-12-14 08:42:34 - enzyme.mkv - INFO - Processing element Tags from SeekHead at position 23000841
2016-12-14 08:42:34 - subliminal.api - INFO - Downloading best subtitles for <Episode [u'Street Outlaws', 6x7]>
2016-12-14 08:42:34 - subliminal.api - INFO - Skipping provider 'addic7ed': no language to search for
2016-12-14 08:42:34 - subliminal.api - INFO - Skipping provider 'podnapisi': no language to search for
2016-12-14 08:42:34 - subliminal.api - INFO - Skipping provider 'thesubdb': no language to search for
2016-12-14 08:42:34 - subliminal.api - INFO - Skipping provider 'opensubtitles': no language to search for
2016-12-14 08:42:34 - subliminal.api - INFO - Downloaded 0 subtitle(s)
2016-12-14 08:42:34 - mkvtomp4 - INFO - Starting conversion.
2016-12-14 08:42:39 - mkvtomp4 - INFO - D:\TV Shows\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD\street.outlaws.s06e07.stuck.in.a.moment.internal.720p.hdtv.x264-dhd-sample.m4v created.
2016-12-14 08:42:39 - SABPostProcess - INFO - Processing file D:\TV Shows\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD.mkv.
2016-12-14 08:42:39 - mkvtomp4 - INFO - Reading video stream.
2016-12-14 08:42:39 - mkvtomp4 - INFO - Video codec detected: h264.
2016-12-14 08:42:39 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2016-12-14 08:42:39 - mkvtomp4 - INFO - Reading audio streams.
2016-12-14 08:42:39 - mkvtomp4 - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2016-12-14 08:42:39 - mkvtomp4 - INFO - Audio detected for stream #1: ac3 [und].
2016-12-14 08:42:39 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2016-12-14 08:42:39 - mkvtomp4 - INFO - Audio track is number 0 setting disposition to default
2016-12-14 08:42:39 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2016-12-14 08:42:39 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to none
2016-12-14 08:42:39 - mkvtomp4 - INFO - Reading subtitle streams.
2016-12-14 08:42:39 - mkvtomp4 - INFO - Subtitle detected for stream #2: subrip [eng].
2016-12-14 08:42:39 - mkvtomp4 - INFO - Attempting to download subtitles.
2016-12-14 08:42:39 - subliminal.video - INFO - Scanning video 'Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD.mkv' in 'D:\\TV Shows\\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD'
2016-12-14 08:42:39 - enzyme.mkv - INFO - Reading Segment element
2016-12-14 08:42:39 - enzyme.parsers.ebml.core - INFO - MasterElement EBML ignored
2016-12-14 08:42:39 - enzyme.parsers.ebml.core - INFO - Maximum level 0 reached for children of MasterElement Segment
2016-12-14 08:42:39 - enzyme.mkv - INFO - Reading SeekHead element
2016-12-14 08:42:39 - enzyme.mkv - INFO - Processing element Info from SeekHead at position 4151
2016-12-14 08:42:39 - enzyme.mkv - INFO - Processing element Tracks from SeekHead at position 4274
2016-12-14 08:42:39 - enzyme.mkv - INFO - Processing element Tags from SeekHead at position 986262937
2016-12-14 08:42:39 - enzyme.mkv - INFO - Processing element Chapters from SeekHead at position 5635
2016-12-14 08:42:39 - subliminal.api - INFO - Downloading best subtitles for <Episode [u'Street Outlaws', 6x7]>
2016-12-14 08:42:39 - subliminal.api - INFO - Skipping provider 'addic7ed': no language to search for
2016-12-14 08:42:39 - subliminal.api - INFO - Skipping provider 'podnapisi': no language to search for
2016-12-14 08:42:39 - subliminal.api - INFO - Skipping provider 'thesubdb': no language to search for
2016-12-14 08:42:39 - subliminal.api - INFO - Skipping provider 'opensubtitles': no language to search for
2016-12-14 08:42:39 - subliminal.api - INFO - Downloaded 0 subtitle(s)
2016-12-14 08:42:39 - mkvtomp4 - INFO - Starting conversion.
2016-12-14 08:45:26 - mkvtomp4 - INFO - D:\TV Shows\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD.m4v created.
2016-12-14 08:45:26 - SABPostProcess - INFO - Passing D:\TV Shows\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD directory to Sonarr.
2016-12-14 08:45:26 - autoprocess.sonarr - INFO - Sonarr notifier started.
2016-12-14 08:45:26 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\TV Shows\Street.Outlaws.S06E07.Stuck.In.A.Moment.iNTERNAL.720p.HDTV.x264-DHD'.
2016-12-14 08:45:26 - autoprocess.sonarr - INFO - Sonarr response: queued.
2016-12-14 08:45:29 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2016-12-14 08:45:29 - readSettings - INFO - C:\Python27\python.exe
2016-12-14 08:45:29 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-12-14 08:45:32 - SonarrPostConversion - INFO - Processing D:\TV Shows\Street Outlaws\Season 8\Street Outlaws - S08E06 - Stuck In A Moment HDTV-720p.m4v.
2016-12-14 08:45:32 - SonarrPostConversion - INFO - Tagging D:\TV Shows\Street Outlaws\Season 8\Street Outlaws - S08E06 - Stuck In A Moment HDTV-720p.m4v with ID 270202 season 8 episode 6.
2016-12-14 08:45:35 - tvdb_mp4 - INFO - Tagging file: D:\TV Shows\Street Outlaws\Season 8\Street Outlaws - S08E06 - Stuck In A Moment HDTV-720p.m4v.
2016-12-14 08:45:35 - tvdb_mp4 - INFO - Trying to write tags.
2016-12-14 08:45:35 - tvdb_mp4 - INFO - Tags written successfully.
2016-12-14 08:45:35 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
2016-12-14 08:45:35 - qtfaststart - INFO - Patching stco with 74694 entries
2016-12-14 08:45:35 - qtfaststart - INFO - Patching stco with 103554 entries
2016-12-14 08:45:35 - qtfaststart - INFO - Patching stco with 77881 entries
2016-12-14 08:45:35 - qtfaststart - INFO - Patching stco with 1 entries
2016-12-14 08:45:35 - qtfaststart - INFO - Writing output...
2016-12-14 08:46:02 - SonarrPostConversion - ERROR - Unable to refresh plex, check your settings.
Traceback (most recent call last):
  File "C:\Users\LivingRoom\Downloads\sickbeard_mp4_automator-master\sickbeard_mp4_automator-master\autoprocess\plex.py", line 38, in refreshPlex
    xml_sections = minidom.parse(urlopen(base_url))
  File "C:\Python27\Lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\Lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\Lib\urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "C:\Python27\Lib\urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "C:\Python27\Lib\urllib.py", line 691, in http_error_401
    errcode, errmsg, headers)
  File "C:\Python27\Lib\urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x0000000003A993C8>)

**Comment by mdhiggins** [comment]
Looks like everything with the tagging is working like it's supposed to. That final error you're setting is from trying to refresh Plex unsuccessfully. I would check your Plex settings in autoProcess.ini cause that's why it's failing there. But it looks like tagging should be working.

**Comment by alokshah14** [comment]
I fixed the Plex config and everything seems to be working great. Thank you for your help.
