### ISSUE TITLE
Permission Issue with NZBget PostProcess

### ISSUE THREAD

**Issue by nomadore** [mdhiggins/sickbeard_mp4_automator#633]
Hi there, I was using this script for over a year with no issues with nzbget. Today, I had to reinstall nzbget and sonarr and can't seem to get past this postprocessing error.  I am able to run manual.py fine but always get this error in NZBget.  I've tripled check that i'm running guessit 1.0.2. 

`2017-01-07 08:51:41 - NZBGetPostProcess - INFO - Script triggered from NZBGet (11.0 or later).
2017-01-07 08:51:41 - readSettings - INFO - /usr/bin/python
2017-01-07 08:51:41 - NZBGetPostProcess - ERROR - File processing failed.
Traceback (most recent call last):
  File "/mnt/user/appdata/nzbget/ppscripts/NZBGetPostProcess.py", line 190, in <module>
    output = converter.process(inputfile)
  File "/mnt/user/appdata/mp4automator/mkvtomp4.py", line 159, in process
    options = self.generateOptions(inputfile, original=original)
  File "/mnt/user/appdata/mp4automator/mkvtomp4.py", line 268, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "/mnt/user/appdata/mp4automator/converter/__init__.py", line 254, in probe
    return self.ffmpeg.probe(fname, posters_as_video)
  File "/mnt/user/appdata/mp4automator/converter/ffmpeg.py", line 410, in probe
    '-show_format', '-show_streams', fname])
  File "/mnt/user/appdata/mp4automator/converter/ffmpeg.py", line 377, in _spawn
    close_fds=(os.name != 'nt'), startupinfo=None)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
2017-01-07 08:51:41 - autoprocess.sonarr - INFO - [INFO] Sonarr notifier started.
2017-01-07 08:51:41 - autoprocess.sonarr - INFO - [INFO] Requesting Sonarr to scan directory '/mnt/user/downloads/usenet/complete/tv/Chopped.S32E01.HDTV.x264-CRiMSON'.
2017-01-07 08:51:41 - autoprocess.sonarr - INFO - [INFO] Sonarr response: queued.
`

**Comment by nomadore** [comment]
Looks like i had to run a chmod on the mp4automator directory.  Everything's working now.
