### ISSUE TITLE
Latest version of stevedore not working with guessit 1.0.3

### ISSUE THREAD

**Issue by ridizy** [mdhiggins/sickbeard_mp4_automator#643]
I have had this script working now for a long time (thank you!).  But I recently updated/rebuilt my environment and found that I was getting the following error when running manual.py with Python 2.7.13:

`Traceback (most recent call last):
  File "/usr/local/bin/guessit", line 7, in <module>
    from guessit.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/usr/local/lib/python2.7/site-packages/stevedore/extension.py", line 252, in map
    raise NoMatches('No %s extensions found' % self.namespace)
stevedore.exception.NoMatches: No guessit.transformer extensions found`

I started looking at the guessit library but couldn't figure out what the issue was.  I then went to another machine, setup a new Python environment from scratch, and ran into the same issue.  On a lark, I tried installing an older version of stevedore and it worked.

So in my environment, it seems that stevedore 1.20.0 does not work with guessit 1.0.3.  To get it to work, I ran

`pip uninstall stevedore`
`pip install stevedore==1.19.1`

I don't know if this is an issue with the latest stevedore release (lucky me) or if it will be an ongoing version incompatibility which should be added to the readme.

**Comment by zerosquared** [comment]
Ran into same issue.  Thanks for the quickfix.

**Comment by zerosquared** [comment]
Ran into the same issue.  thanks for researching and posting this quick fix.
