### ISSUE TITLE
Error converting movies?

### ISSUE THREAD

**Issue by ratt2581** [mdhiggins/sickbeard_mp4_automator#650]
Seem to get the same error consistently when converting movies. Was able to convert TV shows without issue?

```
Processing file /mnt/RattNas/Movies/Midnight Special (2016)/Midnight Special.mkv
'season'
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Video level 4.1.
Reading audio streams.
Audio detected for stream #1: ac3 [und].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Audio track is number 0 setting disposition to default
Creating audio stream 1 from source stream 1.
Audio Track is number 1 setting disposition to none
Reading subtitle streams.
{
    "preopts": [
        "-fix_sub_duration"
    ],
    "subtitle": {},
    "format": "mp4",
    "postopts": [
        "-threads",
        "auto"
    ],
    "video": {
        "map": 0,
        "codec": "h264",
        "bitrate": 4410.36075,
        "level": 4.0
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "aac",
            "disposition": "default",
            "bitrate": 256,
            "filter": null
        },
        "1": {
            "map": 1,
            "language": "eng",
            "channels": 6,
            "codec": "copy",
            "disposition": "none",
            "bitrate": 1536,
            "filter": null
        }
    }
}
Starting conversion.
[          ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/home/pi/sickbeard_mp4_automator/mkvtomp4.py", line 647, in convert
    for timecode in conv:
  File "/home/pi/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/home/pi/sickbeard_mp4_automator/converter/ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code -4", pid=18584, cmd="/home/pi/ffmpeg/ffmpeg -fix_sub_duration -i /mnt/RattNas/Movies/Midnight Special (2016)/Midnight Special.mkv -vcodec libx264 -map 0:0 -vb 4410k -level 4.0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -f mp4 -threads auto -y /mnt/RattNas/Movies/Midnight Special (2016)/Midnight Special.mp4">
/home/pi/ffmpeg/ffmpeg -fix_sub_duration -i /mnt/RattNas/Movies/Midnight Special (2016)/Midnight Special.mkv -vcodec libx264 -map 0:0 -vb 4410k -level 4.0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -f mp4 -threads auto -y /mnt/RattNas/Movies/Midnight Special (2016)/Midnight Special.mp4
ffmpeg version N-83023-gfd01040 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 71.100 / 57. 71.100
  libavformat    57. 62.100 / 57. 62.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, matroska,webm, from '/mnt/RattNas/Movies/Midnight Special (2016)/Midnight Special.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-06-07T21:17:10.000000Z
  Duration: 01:51:57.34, start: 0.000000, bitrate: 5090 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x536 [SAR 1:1 DAR 160:67], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 4642143
      BPS-eng         : 4642143
      DURATION        : 01:51:55.250000000
      DURATION-eng    : 01:51:55.250000000
      NUMBER_OF_FRAMES: 161005
      NUMBER_OF_FRAMES-eng: 161005
      NUMBER_OF_BYTES : 3896644573
      NUMBER_OF_BYTES-eng: 3896644573
      _STATISTICS_WRITING_APP: mkvmerge v8.9.0 ('Father Daughter') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.9.0 ('Father Daughter') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-06-07 21:17:10
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-06-07 21:17:10
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      BPS             : 448000
      BPS-eng         : 448000
      DURATION        : 01:51:57.344000000
      DURATION-eng    : 01:51:57.344000000
      NUMBER_OF_FRAMES: 209917
      NUMBER_OF_FRAMES-eng: 209917
      NUMBER_OF_BYTES : 376171264
      NUMBER_OF_BYTES-eng: 376171264
      _STATISTICS_WRITING_APP: mkvmerge v8.9.0 ('Father Daughter') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.9.0 ('Father Daughter') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-06-07 21:17:10
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-06-07 21:17:10
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
**[AVFilterGraph @ 0x1f1eb90] [Eval @ 0xbee05a2c] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0x1f1eb90] Unable to parse option value "auto"**

/mnt/RattNas/Movies/Midnight Special (2016)/Midnight Special.mp4 deleted.
```

**Comment by mdhiggins** [comment]
This is an FFMPEG error, not sure why you're seeing it though.

I would try using a different build of FFMPEG, perhaps a precompiled binary, and see if it makes any difference

**Comment by mdhiggins** [comment]
Can't imagine why TV shows would work though. At this point it hasn't gotten to any stages where the two files would be treated differently. It looks like its failing with regards to encoding your AC3 audio steam

**Comment by ratt2581** [comment]
Yeah it's bizarre but I think you're right. This is happening on my linux box, my windows setup has no issues. I'll have to dig around and see if changing the FFMPEG build and see if that solves the issue.

Thanks for replying (and for all the work you put into this program).
