### ISSUE TITLE
odd behavior from readSettings.py

### ISSUE THREAD

**Issue by g3m1n1-usa** [mdhiggins/sickbeard_mp4_automator#661]
Hello, I was just testing your project and have run into a minor issue which I wanted to share. Sorry for the inbound wall of text. The setup instructions are fantastic, by the way, very well done.

When I run manual.py from the CLI, the autoProcess.ini file is replaced with a new empty file (still named autoProcess.ini). 
The exit text is:
```
Traceback (most recent call last):
  File "C:\...\MediaConverter\sickbeard_mp4_automator-master\manual.py", line 33, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini", logger=log)
  File "C:\...\MediaConverter\sickbeard_mp4_automator-master\readSettings.py", line 199, in __init__
    self.writeConfig(config, configFile)
  File "C:\...\MediaConverter\sickbeard_mp4_automator-master\readSettings.py", line 637, in writeConfig
    config.write(fp)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 916, in write
    self._sections[section].items(), d)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 920, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'
```

If I set autoProcess.ini to be ReadOnly, the script exits with:
```
Traceback (most recent call last):
  File "C:\...\MediaConverter\sickbeard_mp4_automator-master\manual.py", line 33, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini", logger=log)
  File "C:\...\MediaConverter\sickbeard_mp4_automator-master\readSettings.py", line 199, in __init__
    self.writeConfig(config, configFile)
  File "C:\...\MediaConverter\sickbeard_mp4_automator-master\readSettings.py", line 635, in writeConfig
    fp = open(cfgfile, "wb")
PermissionError: [Errno 13] Permission denied: 'C:\\...\\MediaConverter\\sickbeard_mp4_automator-master\\autoProcess.ini'
```

If I comment out lines 198-199 in readSettings.py then I am able to run manual.py without any other problems. I tested auto-converting an mkv file to mp4 and I think it worked quite well.

It seems like the readSettings.py script wants to re-create the autoProcess.ini file only it does so with an empty file. Do you think this is an issue with my  setup, perhaps? 

edit: just realized that it could be that I am running Python 3.6, which you said is basically beta support anyway.

**Comment by mdhiggins** [comment]
Looks like this is an issue with python 3 and the type of write mode being used for the config file.

Just pushed an update that should fix it

**Comment by g3m1n1-usa** [comment]
That was fast, and your fix worked perfectly! I am able to run manual.py normally now. Great work on this whole project.
