### ISSUE TITLE
ERR: Unknown encoder 'libx264'

### ISSUE THREAD

**Issue by Mirabis** [mdhiggins/sickbeard_mp4_automator#679]
```
2017-02-16 18:56:54 - NZBGetPostProcess - INFO - Successfully processed D:\complete\radarr\Arrival.2016.RERiP.1080p.BluRay.x264.DTS-HD.MA7.1-HDC\Arrival.2016.RERiP.1080p.BluRay.x264.DTS-HD.MA7.1-HDC.mkv.
2017-02-16 18:56:54 - autoprocess.radarr - INFO - [INFO] Radarr notifier started.
2017-02-16 18:56:54 - autoprocess.radarr - INFO - [INFO] Requesting Radarr to scan directory 'D:\complete\radarr\Arrival.2016.RERiP.1080p.BluRay.x264.DTS-HD.MA7.1-HDC'.
2017-02-16 18:56:54 - autoprocess.radarr - INFO - [INFO] Radarr response: queued.
2017-02-16 21:54:26 - MANUAL - INFO - Manual processor started.
2017-02-16 21:54:26 - MANUAL - INFO - C:\tools\python2\python.exe
2017-02-16 21:54:26 - MANUAL - INFO - Reading video stream.
2017-02-16 21:54:26 - MANUAL - INFO - Video codec detected: h264.
2017-02-16 21:54:26 - MANUAL - INFO - Pix Fmt: yuv420p.
2017-02-16 21:54:26 - MANUAL - INFO - Reading audio streams.
2017-02-16 21:54:26 - MANUAL - INFO - Audio detected for stream #1: dts [eng].
2017-02-16 21:54:26 - MANUAL - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2017-02-16 21:54:26 - MANUAL - INFO - Audio track is number 0 setting disposition to default
2017-02-16 21:54:26 - MANUAL - INFO - Creating audio stream 1 from source stream 1.
2017-02-16 21:54:26 - MANUAL - INFO - Audio Track is number 1 setting disposition to none
2017-02-16 21:54:26 - MANUAL - INFO - Reading subtitle streams.
2017-02-16 21:54:26 - MANUAL - INFO - Subtitle detected for stream #2: hdmv_pgs_subtitle [eng].
2017-02-16 21:54:26 - MANUAL - INFO - Subtitle detected for stream #3: hdmv_pgs_subtitle [spa].
2017-02-16 21:54:26 - MANUAL - INFO - External nld subtitle file detected.
2017-02-16 21:54:26 - MANUAL - INFO - Creating subtitle stream 0 by importing Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.nl.srt.
2017-02-16 21:54:26 - MANUAL - INFO - {
    "preopts": [
        "-hwaccel", 
        "auto", 
        "-fflags", 
        "+genpts", 
        "-fix_sub_duration"
    ], 
    "subtitle": {
        "0": {
            "path": "C:\\Movies\\Bad Santa 2 (2016)\\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.nl.srt", 
            "map": 0, 
            "codec": "mov_text", 
            "language": "nld", 
            "source": 1
        }
    }, 
    "format": "mp4", 
    "postopts": [
        "-movflags", 
        "+faststart", 
        "-threads", 
        "auto", 
        "-map_metadata", 
        "-1", 
        "-map_chapters", 
        "-1"
    ], 
    "video": {
        "map": 0, 
        "codec": "h264", 
        "bitrate": 10000, 
        "level": 4.1
    }, 
    "audio": {
        "0": {
            "profile": "aac_he", 
            "map": 1, 
            "language": "eng", 
            "cutoff": "18k", 
            "channels": 2, 
            "codec": "libfdk_aac", 
            "disposition": "default", 
            "bitrate": 160, 
            "filter": "volume=8dB"
        }, 
        "1": {
            "map": 1, 
            "language": "eng", 
            "channels": 6, 
            "codec": "ac3", 
            "disposition": "none", 
            "bitrate": 480, 
            "filter": null
        }
    }
}
2017-02-16 21:54:26 - MANUAL - INFO - Starting conversion.
2017-02-16 21:54:26 - MANUAL - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\ProgramData\NZBGet\scripts\sickbeard_mp4_automator\mkvtomp4.py", line 663, in convert
    for timecode in conv:
  File "C:\ProgramData\NZBGet\scripts\sickbeard_mp4_automator\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\ProgramData\NZBGet\scripts\sickbeard_mp4_automator\converter\ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=42576, cmd="C:\tools\media-autobuild_suite\local64\bin-video\ffmpeg.exe -hwaccel auto -fflags +genpts -fix_sub_duration -i C:\Movies\Bad Santa 2 (2016)\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.mkv -i C:\Movies\Bad Santa 2 (2016)\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.nl.srt -vcodec libx264 -map 0:0 -vb 10000k -level 4.1 -c:a:0 libfdk_aac -map 0:1 -disposition:a:0 default -profile:a:0 aac_he -ac:a:0 2 -vbr:a:0 3 -afterburner:a:0 1 -flags:a:0 +qscale -b:a:0 160k -filter:a:0 volume=8dB -metadata:s:a:0 language=eng -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 480k -metadata:s:a:1 language=eng -c:s:0 mov_text -map 1:0 -metadata:s:s:0 language=nld -f mp4 -movflags +faststart -threads auto -map_metadata -1 -map_chapters -1 -y C:\Movies\Bad Santa 2 (2016)\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.mp4">
2017-02-16 21:54:27 - MANUAL - ERROR - C:\tools\media-autobuild_suite\local64\bin-video\ffmpeg.exe -hwaccel auto -fflags +genpts -fix_sub_duration -i C:\Movies\Bad Santa 2 (2016)\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.mkv -i C:\Movies\Bad Santa 2 (2016)\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.nl.srt -vcodec libx264 -map 0:0 -vb 10000k -level 4.1 -c:a:0 libfdk_aac -map 0:1 -disposition:a:0 default -profile:a:0 aac_he -ac:a:0 2 -vbr:a:0 3 -afterburner:a:0 1 -flags:a:0 +qscale -b:a:0 160k -filter:a:0 volume=8dB -metadata:s:a:0 language=eng -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 480k -metadata:s:a:1 language=eng -c:s:0 mov_text -map 1:0 -metadata:s:s:0 language=nld -f mp4 -movflags +faststart -threads auto -map_metadata -1 -map_chapters -1 -y C:\Movies\Bad Santa 2 (2016)\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.mp4
2017-02-16 21:54:27 - MANUAL - ERROR - ffmpeg version N-83533-gada281dbe2 Copyright (c) 2000-2017 the FFmpeg developers

  built with gcc 6.3.0 (Rev1, Built by MSYS2 project)

  configuration:  --enable-avisynth --enable-gcrypt --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-decklink --enable-fontconfig --enable-frei0r --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-opengl --enable-libcdio --enable-libfdk-aac --enable-libkvazaar --enable-librubberband --disable-w32threads --enable-gpl --enable-nonfree --enable-filter=frei0r --disable-debug

  libavutil      55. 47.100 / 55. 47.100

  libavcodec     57. 80.100 / 57. 80.100

  libavformat    57. 66.102 / 57. 66.102

  libavdevice    57.  2.100 / 57.  2.100

  libavfilter     6. 73.100 /  6. 73.100

  libswscale      4.  3.101 /  4.  3.101

  libswresample   2.  4.100 /  2.  4.100

  libpostproc    54.  2.100 / 54.  2.100

[matroska,webm @ 000001c2cdb08fe0] Read error at pos. 26907617887 (0x643d1aa5f)

[matroska,webm @ 000001c2cdb08fe0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle): unspecified size

Consider increasing the value for the 'analyzeduration' and 'probesize' options

Input #0, matroska,webm, from 'C:\Movies\Bad Santa 2 (2016)\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.mkv':

  Metadata:

    title           : Bad Santa 2 Unrated

    encoder         : libebml v1.3.4 + libmatroska v1.4.5

    creation_time   : 2017-02-13T21:03:42.000000Z

  Duration: 01:34:50.07, start: 0.000000, bitrate: 37830 kb/s

    Chapter #0:0: start 0.000000, end 353.228000

    Metadata:

      title           : 00:00:00.000

    Chapter #0:1: start 353.228000, end 660.743000

    Metadata:

      title           : 00:05:53.228

    Chapter #0:2: start 660.743000, end 982.857000

    Metadata:

      title           : 00:11:00.743

    Chapter #0:3: start 982.857000, end 1214.213000

    Metadata:

      title           : 00:16:22.857

    Chapter #0:4: start 1214.213000, end 1534.700000

    Metadata:

      title           : 00:20:14.213

    Chapter #0:5: start 1534.700000, end 1780.445000

    Metadata:

      title           : 00:25:34.700

    Chapter #0:6: start 1780.445000, end 2031.696000

    Metadata:

      title           : 00:29:40.445

    Chapter #0:7: start 2031.696000, end 2217.132000

    Metadata:

      title           : 00:33:51.696

    Chapter #0:8: start 2217.132000, end 2480.019000

    Metadata:

      title           : 00:36:57.132

    Chapter #0:9: start 2480.019000, end 2689.812000

    Metadata:

      title           : 00:41:20.019

    Chapter #0:10: start 2689.812000, end 3129.334000

    Metadata:

      title           : 00:44:49.812

    Chapter #0:11: start 3129.334000, end 3633.546000

    Metadata:

      title           : 00:52:09.334

    Chapter #0:12: start 3633.546000, end 3954.158000

    Metadata:

      title           : 01:00:33.546

    Chapter #0:13: start 3954.158000, end 4397.977000

    Metadata:

      title           : 01:05:54.158

    Chapter #0:14: start 4397.977000, end 4668.497000

    Metadata:

      title           : 01:13:17.977

    Chapter #0:15: start 4668.497000, end 4918.205000

    Metadata:

      title           : 01:17:48.497

    Chapter #0:16: start 4918.205000, end 5143.221000

    Metadata:

      title           : 01:21:58.205

    Chapter #0:17: start 5143.221000, end 5690.070000

    Metadata:

      title           : 01:25:43.221

    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)

    Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit) (default)

    Metadata:

      title           : DTS-HD MA 5.1

    Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle, 1920x1080 (default)

    Metadata:

      title           : English (SDH)

    Stream #0:3(spa): Subtitle: hdmv_pgs_subtitle

    Metadata:

      title           : Spanish (Latin American)

Input #1, srt, from 'C:\Movies\Bad Santa 2 (2016)\Bad.Santa.2 (2016) Bluray-1080p x264.DTS-HD.MA.[EN+ES]-FraMeSToR.nl.srt':

  Duration: N/A, bitrate: N/A

    Stream #1:0: Subtitle: subrip

Unknown encoder 'libx264'

```

Hi,

I'm having some issues converting movies lately. The script works fine for my tv shows, but there seem to be some incompatibilities with movies.

**Comment by Mirabis** [comment]
Looks like it errors out trying to convert hdmv_pgs_subtitle subs to srt.

Can we blacklist those?

**Comment by mdhiggins** [comment]
Its not encoding your hdmv_pgs subtitle track

Your error is `Unknown encoder 'libx264'` which is related to your video codec and is an FFMPEG problem

See here:
https://stackoverflow.com/questions/9764740/unknown-encoder-libx264

**Comment by Mirabis** [comment]
Yes you were right, something wasn't compiled correctly. Re-compiled ffmpeg and is fixed now.
