### ISSUE TITLE
postCouchPotato.py Not working

### ISSUE THREAD

**Issue by herbi3** [mdhiggins/sickbeard_mp4_automator#692]
SickBeard works fine, just CouchPotato gives this issue

Traceback (most recent call last): File "/Volumes/Macintosh HD/usr/local/sickbeard_mp4_automator/postCouchPotato.py", line 6, in <module> from readSettings import ReadSettings File "/usr/local/sickbeard_mp4_automator/readSettings.py", line 11, in <module> from babelfish import Language ImportError: No module named babelfish

Babelfish is certainly installed.

Then trying to avoid babelfish I get afterwards

Traceback (most recent call last): File "/usr/local/sickbeard_mp4_automator/postCouchPotato.py", line 8, in <module> from tmdb_mp4 import tmdb_mp4 File "/usr/local/sickbeard_mp4_automator/tmdb_mp4.py", line 14, in <module> from tmdb_api import tmdb File "/usr/local/sickbeard_mp4_automator/tmdb_api/tmdb.py", line 18, in <module> import requests ImportError: No module named requests

And again, requests is certainly installed.

**Comment by herbi3** [comment]
Never mind, 

changed line 1 from
#!/usr/bin/env python

to

#!/usr/bin/env python2.7

fixed.

**Comment by mdhiggins** [comment]
Wrong python env
