### ISSUE TITLE
Failing to call Radarr after post process

### ISSUE THREAD

**Issue by bfir3** [mdhiggins/sickbeard_mp4_automator#699]
So I just installed Radarr over the weekend, and was able to use it to download and import one movie successfully. However since then I've been getting the following error in NZBGet:

```
INFO	Mon Mar 13 2017 11:39:09	NZBGetPostProcess: KeyError: 'state'
INFO	Mon Mar 13 2017 11:39:09	NZBGetPostProcess: log.info("%sRadarr response: %s." % (infoprefix, rstate['state']))
INFO	Mon Mar 13 2017 11:39:09	NZBGetPostProcess: File "C:/Program Files (x86)/MP4 Automator/autoprocess\radarr.py", line 64, in processMovie
INFO	Mon Mar 13 2017 11:39:09	NZBGetPostProcess: Traceback (most recent call last):
INFO	Mon Mar 13 2017 11:39:09	NZBGetPostProcess: 2017-03-13 11:39:09 - autoprocess.radarr - ERROR - [ERROR] Update to Radarr failed, check if Radarr is running, autoProcess.ini settings and make sure your Radarr settings are correct (apikey?), or check install of python modules requests.
INFO	Mon Mar 13 2017 11:39:09	NZBGetPostProcess: 2017-03-13 11:39:09 - autoprocess.radarr - INFO - [INFO] Requesting Radarr to scan directory 'S:\Unsorted\Movies'.
INFO	Mon Mar 13 2017 11:39:09	NZBGetPostProcess: 2017-03-13 11:39:09 - autoprocess.radarr - INFO - [INFO] Radarr notifier started.
```

I'm not entirely sure what I changed since the first movie that downloaded worked, but I've had this error on every subsequent download, so I obviously changed something. Any ideas? My autoprocess.ini has all my Radarr settings including the correct API key, it looks like this:

[Radarr]
host = localhost
port = 7878
web_root = movies
ssl = False
apikey = myapikey

The only thing I can think of is that I maybe added the webroot to Radarr only after the first movie downloaded. However I'm not entirely sure if that's true because I don't actually remember modifying the autoprocess.ini beyond the first modification. Let me know what you think!

EDIT: If it helps, this is the error I get on Radarr:

```
Message
Request Failed: Sequence contains no matching element

Exception
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Commands.CommandModule.StartCommand(CommandResource commandResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Commands\CommandModule.cs:line 43
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by mdhiggins** [comment]
Radarr changed their API. There was an update pushed this morning that should fix the issue.

**Comment by bfir3** [comment]
Wonderful, thanks for the info!
