### ISSUE TITLE
converted file ends up in automator folder

### ISSUE THREAD

**Issue by smithdo** [mdhiggins/sickbeard_mp4_automator#739]
The mp4 file and all associated files (.srt) are in the mp4_automator folder, not the destination folder which should also be the source folder.

**Comment by mdhiggins** [comment]
Post your logs and post your settings

**Comment by smithdo** [comment]
Autoprocess.ini
[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
max-audio-channels = 
audio-codec = ac3
audio-language = 
audio-default-language = 
audio-channel-bitrate = 256
audio-filter = 
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts = 

info.log
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Reading video stream.
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Video codec detected: h264.
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Pix Fmt: yuv420p.
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Reading audio streams.
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Audio detected for stream #1: ac3 [eng].
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Audio track is number 0 setting disposition to default
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Creating audio stream 1 from source stream 1.
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Audio Track is number 1 setting disposition to none
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Reading subtitle streams.
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Subtitle detected for stream #2: subrip [eng].
2017-05-30 12:40:39 - NZBGetPostProcess - INFO - Ripping eng subtitle from source stream 2 into external file.
2017-05-30 12:40:41 - NZBGetPostProcess - INFO - /downloads/mp4_automator/house.of.cards.2013.s05e08.720p.webrip.x264-morose.eng.srt created.
2017-05-30 12:40:41 - NZBGetPostProcess - INFO - Starting conversion.
2017-05-30 12:48:01 - NZBGetPostProcess - INFO - /downloads/mp4_automator/house.of.cards.2013.s05e08.720p.webrip.x264-morose.mp4 created.
2017-05-30 12:48:02 - NZBGetPostProcess - INFO - Successfully processed /downloads/NZBGet/completed/sonarr/House.of.Cards.2013.S05E08.720p.WEBRip.x264-MOROSE/house.of.cards.2013.s05e08.720p.webrip.x264-morose.mkv.
2017-05-30 12:48:02 - autoprocess.sonarr - INFO - [INFO] Sonarr notifier started.
2017-05-30 12:48:02 - autoprocess.sonarr - INFO - [INFO] Requesting Sonarr to scan directory '/downloads/mp4_automator/'.
2017-05-30 12:48:02 - autoprocess.sonarr - INFO - [INFO] Sonarr response: started.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Script triggered from NZBGet (11.0 or later).
2017-05-30 12:56:11 - readSettings - INFO - /usr/bin/python
2017-05-30 12:56:11 - readSettings - ERROR - Subliminal is not installed, automatically downloading of subs has been disabled.
Traceback (most recent call last):
  File "/downloads/mp4_automator/readSettings.py", line 294, in __init__
    import subliminal
  File "/usr/lib/python2.7/site-packages/subliminal/__init__.py", line 10, in <module>
    from .api import (ProviderPool, check_video, provider_manager, download_best_subtitles, download_subtitles,
  File "/usr/lib/python2.7/site-packages/subliminal/api.py", line 13, in <module>
    from .subtitle import compute_score, get_subtitle_path
  File "/usr/lib/python2.7/site-packages/subliminal/subtitle.py", line 7, in <module>
    from guessit.matchtree import MatchTree
  File "/usr/lib/python2.7/site-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/usr/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/usr/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/usr/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/usr/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 252, in map
    raise NoMatches('No %s extensions found' % self.namespace)
NoMatches: No guessit.transformer extensions found
2017-05-30 12:56:11 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring.
2017-05-30 12:56:11 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Reading video stream.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Video codec detected: h264.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Pix Fmt: yuv420p.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Reading audio streams.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Audio detected for stream #1: ac3 [eng].
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Audio track is number 0 setting disposition to default
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Creating audio stream 1 from source stream 1.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Audio Track is number 1 setting disposition to none
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Reading subtitle streams.
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Subtitle detected for stream #2: subrip [eng].
2017-05-30 12:56:11 - NZBGetPostProcess - INFO - Ripping eng subtitle from source stream 2 into external file.
2017-05-30 12:56:13 - NZBGetPostProcess - INFO - /downloads/mp4_automator/house.of.cards.2013.s05e09.720p.webrip.x264-morose.eng.srt created.
2017-05-30 12:56:13 - NZBGetPostProcess - INFO - Starting conversion.
2017-05-30 13:04:54 - NZBGetPostProcess - INFO - /downloads/mp4_automator/house.of.cards.2013.s05e09.720p.webrip.x264-morose.mp4 created.
2017-05-30 13:04:54 - NZBGetPostProcess - INFO - Successfully processed /downloads/NZBGet/completed/sonarr/House.of.Cards.2013.S05E09.720p.WEBRip.x264-MOROSE/house.of.cards.2013.s05e09.720p.webrip.x264-morose.mkv.
2017-05-30 13:04:54 - autoprocess.sonarr - INFO - [INFO] Sonarr notifier started.
2017-05-30 13:04:54 - autoprocess.sonarr - INFO - [INFO] Requesting Sonarr to scan directory '/downloads/mp4_automator/'.
2017-05-30 13:04:55 - autoprocess.sonarr - INFO - [INFO] Sonarr response: queued.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Script triggered from NZBGet (11.0 or later).
2017-05-30 13:10:16 - readSettings - INFO - /usr/bin/python
2017-05-30 13:10:16 - readSettings - ERROR - Subliminal is not installed, automatically downloading of subs has been disabled.
Traceback (most recent call last):
  File "/downloads/mp4_automator/readSettings.py", line 294, in __init__
    import subliminal
  File "/usr/lib/python2.7/site-packages/subliminal/__init__.py", line 10, in <module>
    from .api import (ProviderPool, check_video, provider_manager, download_best_subtitles, download_subtitles,
  File "/usr/lib/python2.7/site-packages/subliminal/api.py", line 13, in <module>
    from .subtitle import compute_score, get_subtitle_path
  File "/usr/lib/python2.7/site-packages/subliminal/subtitle.py", line 7, in <module>
    from guessit.matchtree import MatchTree
  File "/usr/lib/python2.7/site-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/usr/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/usr/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/usr/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/usr/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 252, in map
    raise NoMatches('No %s extensions found' % self.namespace)
NoMatches: No guessit.transformer extensions found
2017-05-30 13:10:16 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring.
2017-05-30 13:10:16 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Reading video stream.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Video codec detected: h264.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Pix Fmt: yuv420p.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Reading audio streams.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Audio detected for stream #1: ac3 [eng].
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Audio track is number 0 setting disposition to default
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Creating audio stream 1 from source stream 1.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Audio Track is number 1 setting disposition to none
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Reading subtitle streams.
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Subtitle detected for stream #2: subrip [eng].
2017-05-30 13:10:16 - NZBGetPostProcess - INFO - Ripping eng subtitle from source stream 2 into external file.
2017-05-30 13:10:17 - NZBGetPostProcess - INFO - /downloads/mp4_automator/house.of.cards.2013.s05e10.720p.webrip.x264-morose.eng.srt created.
2017-05-30 13:10:17 - NZBGetPostProcess - INFO - Starting conversion.
2017-05-30 13:18:45 - NZBGetPostProcess - INFO - /downloads/mp4_automator/house.of.cards.2013.s05e10.720p.webrip.x264-morose.mp4 created.
2017-05-30 13:18:45 - NZBGetPostProcess - INFO - Successfully processed /downloads/NZBGet/completed/sonarr/House.of.Cards.2013.S05E10.720p.WEBRip.x264-MOROSE/house.of.cards.2013.s05e10.720p.webrip.x264-morose.mkv.
2017-05-30 13:18:45 - autoprocess.sonarr - INFO - [INFO] Sonarr notifier started.
2017-05-30 13:18:45 - autoprocess.sonarr - INFO - [INFO] Requesting Sonarr to scan directory '/downloads/mp4_automator/'.
2017-05-30 13:18:45 - autoprocess.sonarr - INFO - [INFO] Sonarr response: queued.

**Comment by smithdo** [comment]
So what is the cause or do you need additional information?

**Comment by mdhiggins** [comment]
Do you accidentally have the output_dir set in your NZBGetPostProcess settings set to the script directory?

![image](https://user-images.githubusercontent.com/3608298/27298558-2e8a14f8-54f7-11e7-8dc4-8fc30243fd8a.png)
