### ISSUE TITLE
unable to download subtitles

### ISSUE THREAD

**Issue by jkoopmann** [mdhiggins/sickbeard_mp4_automator#783]
Hi,

I am suddenly getting this with automated postprocessing from Sabnzbd:

2017-08-27 15:32:55 - mkvtomp4 - INFO - Unable to download subtitles.
Traceback (most recent call last):
File "/usr/local/sickbeard_mp4_automator/mkvtomp4.py", line 539, in generateOptions
video = subliminal.scan_video(os.path.abspath(inputfile), subtitles=True, embedded_subtitles=True)
File "/usr/local/lib/python2.7/site-packages/subliminal/video.py", line 301, in scan_video
video = Video.fromguess(path, guess_file_info(path))
File "/usr/local/lib/python2.7/site-packages/subliminal/video.py", line 104, in fromguess
return Episode.fromguess(name, guess)
File "/usr/local/lib/python2.7/site-packages/subliminal/video.py", line 174, in fromguess
raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

Any idea?

**Comment by jkoopmann** [comment]
This is still an open issue. What can I do to assist?

**Comment by mdhiggins** [comment]
Should be fixed now with overhaul to latest versions of subliminal and guessit
