### ISSUE TITLE
Filename Causing Error/Crash

### ISSUE THREAD

**Issue by grokdesigns** [mdhiggins/sickbeard_mp4_automator#801]
I have a filename with an em dash (–) in it and it is causing this issue when attempting to convert:
```
manual.py -i "filename.mkv" -a
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
Invalid interal subtitle codec srt, defaulting to 'mov_text'.
32bit Python.
Traceback (most recent call last):
  File "C:\Apps\MP4Automator\manual.py", line 358, in <module>
    main()
  File "C:\Apps\MP4Automator\manual.py", line 348, in main
    tagdata = getinfo(path, silent=silent, tvdbid=tvdbid)
  File "C:\Apps\MP4Automator\manual.py", line 85, in getinfo
    tagdata = guessInfo(fileName, tvdbid)
  File "C:\Apps\MP4Automator\manual.py", line 123, in guessInfo
    guess = guessit.guess_file_info(fileName)
  File "C:\Python27\lib\site-packages\guessit\__init__.py", line 295, in guess_file_info
    filename = u(filename)
  File "C:\Python27\lib\site-packages\guessit\__init__.py", line 63, in u
    return x.decode('utf-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 25: invalid start byte
```

**Comment by Smalfinn** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/745

**Comment by Collisionc** [comment]
Yeah, python3 would definitely fix this.
