### ISSUE TITLE
New installation - FFMPEG Error

### ISSUE THREAD

**Issue by StevenChorkley** [mdhiggins/sickbeard_mp4_automator#818]
HI, 

I'm getting this error and I really don't understand what is causing it. Any ideas? 

```
 Starting conversion.
[          ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/opt/mp4-automator/mkvtomp4.py", line 715, in convert
    for timecode in conv:
  File "/opt/mp4-automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/opt/mp4-automator/converter/ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=12057, cmd="/usr/bin/ffmpeg -fix_sub_duration -vcodec h264_qsv -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mkv -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.en.srt -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -c:s:1 mov_text -map 1:0 -metadata:s:s:1 language=eng -f mp4 -threads auto -y /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mp4">
/usr/bin/ffmpeg -fix_sub_duration -vcodec h264_qsv -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mkv -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.en.srt -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -c:s:1 mov_text -map 1:0 -metadata:s:s:1 language=eng -f mp4 -threads auto -y /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mp4
ffmpeg version N-89088-gce001bb Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 20160609
  configuration: --prefix=/home/steven/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/steven/ffmpeg_build/include --extra-ldflags=-L/home/steven/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/steven/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  3.102 / 58.  3.102
  libavformat    58.  2.100 / 58.  2.100
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.101 /  7.  0.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Unknown decoder 'h264_qsv'
```

**Comment by StevenChorkley** [comment]
I can't find out how to disable h264_qsv

**Comment by StevenChorkley** [comment]
After removing it's entry in mkvtomp4.py, I got this error

`

> Starting conversion.
> [          ] 0%Error converting file, FFMPEG error.
> Traceback (most recent call last):
>   File "/opt/mp4-converter/mkvtomp4.py", line 715, in convert
>     for timecode in conv:
>   File "/opt/mp4-converter/converter/__init__.py", line 243, in convert
>     timeout=timeout, preopts=preopts, postopts=postopts):
>   File "/opt/mp4-converter/converter/ffmpeg.py", line 548, in convert
>     total_output, pid=p.pid)
> FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=14523, cmd="/usr/bin/ffmpeg -fix_sub_duration   -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mkv -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.en.srt -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -c:s:1 mov_text -map 1:0 -metadata:s:s:1 language=eng -f mp4 -threads auto -y /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mp4">
> /usr/bin/ffmpeg -fix_sub_duration   -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mkv -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.en.srt -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -c:s:1 mov_text -map 1:0 -metadata:s:s:1 language=eng -f mp4 -threads auto -y /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mp4
> ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
>   configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
>   libavutil      54. 31.100 / 54. 31.100
>   libavcodec     56. 60.100 / 56. 60.100
>   libavformat    56. 40.101 / 56. 40.101
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 40.101 /  5. 40.101
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  2.101 /  1.  2.101
>   libpostproc    53.  3.100 / 53.  3.100
> Input #0, matroska,webm, from '/mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mkv':
>   Metadata:
>     encoder         : libebml v1.3.4 + libmatroska v1.4.5
>     creation_time   : 2017-10-23 01:30:21
>   Duration: 00:44:10.15, start: 0.000000, bitrate: 6236 kb/s
>     Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
>     Metadata:
>       BPS             : 5850881
>       BPS-eng         : 5850881
>       DURATION        : 00:44:10.148000000
>       DURATION-eng    : 00:44:10.148000000
>       NUMBER_OF_FRAMES: 63540
>       NUMBER_OF_FRAMES-eng: 63540
>       NUMBER_OF_BYTES : 1938212718
>       NUMBER_OF_BYTES-eng: 1938212718
>       _STATISTICS_WRITING_APP: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_APP-eng: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_DATE_UTC: 2017-10-23 01:30:21
>       _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-23 01:30:21
>       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>     Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
>     Metadata:
>       BPS             : 384000
>       BPS-eng         : 384000
>       DURATION        : 00:44:10.144000000
>       DURATION-eng    : 00:44:10.144000000
>       NUMBER_OF_FRAMES: 82817
>       NUMBER_OF_FRAMES-eng: 82817
>       NUMBER_OF_BYTES : 127206912
>       NUMBER_OF_BYTES-eng: 127206912
>       _STATISTICS_WRITING_APP: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_APP-eng: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_DATE_UTC: 2017-10-23 01:30:21
>       _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-23 01:30:21
>       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>     Stream #0:2(eng): Subtitle: subrip
>     Metadata:
>       BPS             : 127
>       BPS-eng         : 127
>       DURATION        : 00:43:31.340000000
>       DURATION-eng    : 00:43:31.340000000
>       NUMBER_OF_FRAMES: 975
>       NUMBER_OF_FRAMES-eng: 975
>       NUMBER_OF_BYTES : 41761
>       NUMBER_OF_BYTES-eng: 41761
>       _STATISTICS_WRITING_APP: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_APP-eng: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_DATE_UTC: 2017-10-23 01:30:21
>       _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-23 01:30:21
>       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
> Input #1, srt, from '/mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.en.srt':
>   Duration: N/A, bitrate: N/A
>     Stream #1:0: Subtitle: subrip
> Option fix_sub_duration (fix subtitles duration) cannot be applied to output url  -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
> Error parsing options for output file .
> Error opening output files: Invalid argument

`

Then after disabling subtitles:

`

> Starting conversion.
> [          ] 0%Error converting file, FFMPEG error.
> Traceback (most recent call last):
>   File "/opt/mp4-converter/mkvtomp4.py", line 715, in convert
>     for timecode in conv:
>   File "/opt/mp4-converter/converter/__init__.py", line 243, in convert
>     timeout=timeout, preopts=preopts, postopts=postopts):
>   File "/opt/mp4-converter/converter/ffmpeg.py", line 548, in convert
>     total_output, pid=p.pid)
> FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=14642, cmd="/usr/bin/ffmpeg   -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -f mp4 -threads auto -y /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mp4">
> /usr/bin/ffmpeg   -i /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 copy -map 0:1 -metadata:s:a:1 language=eng -disposition:a:1 none -f mp4 -threads auto -y /mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mp4
> ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
>   configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
>   libavutil      54. 31.100 / 54. 31.100
>   libavcodec     56. 60.100 / 56. 60.100
>   libavformat    56. 40.101 / 56. 40.101
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 40.101 /  5. 40.101
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  2.101 /  1.  2.101
>   libpostproc    53.  3.100 / 53.  3.100
> Input #0, matroska,webm, from '/mnt/media/TV Series/Heartland (2007) (CA)/Season 11/heartland.ca.s11e05.1080p.webrip.x264-aaf.mkv':
>   Metadata:
>     encoder         : libebml v1.3.4 + libmatroska v1.4.5
>     creation_time   : 2017-10-23 01:30:21
>   Duration: 00:44:10.15, start: 0.000000, bitrate: 6236 kb/s
>     Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
>     Metadata:
>       BPS             : 5850881
>       BPS-eng         : 5850881
>       DURATION        : 00:44:10.148000000
>       DURATION-eng    : 00:44:10.148000000
>       NUMBER_OF_FRAMES: 63540
>       NUMBER_OF_FRAMES-eng: 63540
>       NUMBER_OF_BYTES : 1938212718
>       NUMBER_OF_BYTES-eng: 1938212718
>       _STATISTICS_WRITING_APP: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_APP-eng: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_DATE_UTC: 2017-10-23 01:30:21
>       _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-23 01:30:21
>       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>     Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
>     Metadata:
>       BPS             : 384000
>       BPS-eng         : 384000
>       DURATION        : 00:44:10.144000000
>       DURATION-eng    : 00:44:10.144000000
>       NUMBER_OF_FRAMES: 82817
>       NUMBER_OF_FRAMES-eng: 82817
>       NUMBER_OF_BYTES : 127206912
>       NUMBER_OF_BYTES-eng: 127206912
>       _STATISTICS_WRITING_APP: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_APP-eng: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_DATE_UTC: 2017-10-23 01:30:21
>       _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-23 01:30:21
>       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>     Stream #0:2(eng): Subtitle: subrip
>     Metadata:
>       BPS             : 127
>       BPS-eng         : 127
>       DURATION        : 00:43:31.340000000
>       DURATION-eng    : 00:43:31.340000000
>       NUMBER_OF_FRAMES: 975
>       NUMBER_OF_FRAMES-eng: 975
>       NUMBER_OF_BYTES : 41761
>       NUMBER_OF_BYTES-eng: 41761
>       _STATISTICS_WRITING_APP: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_APP-eng: mkvmerge v14.0.0 ('Flow') 64bit
>       _STATISTICS_WRITING_DATE_UTC: 2017-10-23 01:30:21
>       _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-23 01:30:21
>       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
>       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
> [NULL @ 0x1a38740] Unable to find a suitable output format for ''
> : Invalid argument

`

I'm completely out of ideas, mdhiggins do you have any idea? 

My OS is Ubuntu 16.04 if that helps :)

**Comment by StevenChorkley** [comment]
Thank you very much. 

All the best to you both.
