### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'video'

### ISSUE THREAD

**Issue by smattord** [mdhiggins/sickbeard_mp4_automator#829]
I'm running Ubuntu 17.10 with Plex. I'm trying to use a call to your automator as a postprocessor from Plex. This error is displayed in my syslog when Plex performs the script call. However, I'm able to execute the same script call from my terminal as my user (as opposed to the plex user). 

Here's the complete syslog output:
```
Dec  8 18:55:58 cloudview-nuc sh[14204]: Manual processor started.
Dec  8 18:55:58 cloudview-nuc sh[14204]: /usr/bin/python
Dec  8 18:55:58 cloudview-nuc sh[14204]: Audio bitrate was invalid, defaulting to 256 per channel.
Dec  8 18:55:58 cloudview-nuc sh[14204]: 64bit Python.
Dec  8 18:55:58 cloudview-nuc sh[14204]: No module named expat; use SimpleXMLTreeBuilder instead
Dec  8 18:55:58 cloudview-nuc sh[14204]: Reading video stream.
Dec  8 18:55:58 cloudview-nuc sh[14204]: Traceback (most recent call last):
Dec  8 18:55:58 cloudview-nuc sh[14204]:   File "/usr/local/bin/sickbeard-mp4-automator/manual.py", line 358, in <module>
Dec  8 18:55:58 cloudview-nuc sh[14204]:     main()
Dec  8 18:55:58 cloudview-nuc sh[14204]:   File "/usr/local/bin/sickbeard-mp4-automator/manual.py", line 349, in main
Dec  8 18:55:58 cloudview-nuc sh[14204]:     processFile(path, tagdata)
Dec  8 18:55:58 cloudview-nuc sh[14204]:   File "/usr/local/bin/sickbeard-mp4-automator/manual.py", line 207, in processFile
Dec  8 18:55:58 cloudview-nuc sh[14204]:     output = converter.process(inputfile, True)
Dec  8 18:55:58 cloudview-nuc sh[14204]:   File "/usr/local/bin/sickbeard-mp4-automator/mkvtomp4.py", line 183, in process
Dec  8 18:55:58 cloudview-nuc sh[14204]:     options = self.generateOptions(inputfile, original=original)
Dec  8 18:55:58 cloudview-nuc sh[14204]:   File "/usr/local/bin/sickbeard-mp4-automator/mkvtomp4.py", line 296, in generateOptions
Dec  8 18:55:58 cloudview-nuc sh[14204]:     self.log.info("Video codec detected: %s." % info.video.codec)
Dec  8 18:55:58 cloudview-nuc sh[14204]: AttributeError: 'NoneType' object has no attribute 'video'
```

Can you provide any insight on how to resolve this?

**Comment by mdhiggins** [comment]
Usually this comes from a bad video file or inability to read the video stream
Also I have never testing running this as a postprocessor from Plex, only a preprocessor before sending to plex

**Comment by Collisionc** [comment]
I've found that increasing probesize/analyzeduration in ffprobe fixes this sometimes. 

go to converter/ffmpeg.py  - https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/converter/ffmpeg.py#L409  

change lines 409/410 to say this: 

        p = self._spawn([self.ffprobe_path, '-analyzeduration', '300000000', '-probesize', '1999999999',
                         '-show_format', '-show_streams', fname])

This will tell ffprobe that it may use up to 5 minutes of time or 2 GB of ram to analyze a file. If it still fails after that, then it's likely a corrupt video.

**Comment by trymbill** [comment]
I've been seeing pretty much every mkv I send through SABPostProcess.py result in this error. I tried sending the same mkv through ffmpeg directly (via `ffmpeg -i test.mkv -codec copy test.mp4`) and that worked without any issues.

I tried @Collisionc's idea but that didn't seem to help. I also tried running the file through manual.py but that resulted in the same error.

Here's the result of `ffmpeg -i test.mkv -codec copy test.mp4`:

```
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, matroska,webm, from 'test.mkv':
  Metadata:
    ENCODER         : The Black Sparrow
  Duration: 00:58:02.96, start: 0.000000, bitrate: 2456 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Stream #0:1: Audio: ac3, 48000 Hz, stereo, fltp, 384 kb/s (default)
    Stream #0:2(eng): Subtitle: ass
[mp4 @ 0x7fd8ae198800] track 1: codec frame size is not set
Output #0, mp4, to 'test.mp4':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 16k tbn, 1k tbc (default)
    Stream #0:1: Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, stereo, fltp, 384 kb/s (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 9231 fps=0.0 q=-1.0 size=  113664kB time=00:06:09.12 bitrate=2522.6kbits/s speed= 7frame=17654 fps=17650 q=-1.0 size=  220160kB time=00:11:46.04 bitrate=2554.5kbits/s speed=frame=26712 fps=17803 q=-1.0 size=  329728kB time=00:17:48.36 bitrate=2528.3kbits/s speed=frame=35868 fps=17908 q=-1.0 size=  436224kB time=00:23:54.60 bitrate=2491.0kbits/s speed=frame=43691 fps=17423 q=-1.0 size=  532224kB time=00:29:07.52 bitrate=2495.0kbits/s speed=frame=52440 fps=17433 q=-1.0 size=  629760kB time=00:34:57.48 bitrate=2459.6kbits/s speed=frame=60550 fps=17238 q=-1.0 size=  728832kB time=00:40:21.88 bitrate=2465.3kbits/s speed=frame=68712 fps=17106 q=-1.0 size=  826624kB time=00:45:48.36 bitrate=2463.9kbits/s speed=frame=79034 fps=17474 q=-1.0 size=  949504kB time=00:52:41.24 bitrate=2460.5kbits/s speed=frame=87074 fps=17297 q=-1.0 Lsize= 1045261kB time=00:58:02.91 bitrate=2458.5kbits/s speed= 692x
video:879804kB audio:163263kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.210342%
```

I can upload the file somewhere if you need the file for testing, just let me know. Any help would be greatly appreciated.

**Comment by trymbill** [comment]
Well, never mind ... I just realized that my autoProcess.ini had ffmpeg and ffprobe pointing straight to the homebrew cellar bin instead of `/usr/local/bin`, so SABPostProcess.py was using a really old version of ffprobe. Changed that and everything works as expected again.

**Comment by haboutnnah** [comment]
Same thing is happening to me.
