### ISSUE TITLE
Getting "Unknown decoder 'hevc_qsv'"

### ISSUE THREAD

**Issue by evanwins** [mdhiggins/sickbeard_mp4_automator#834]
I updated my version of sickbeard_mp4_automator and then manually updated my version of ffmpeg from 3.2.3 to 3.4.1 (using home-brew with `brew update && brew upgrade ffmpeg`).

The update did include this message:

```
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig
```
But everything seemed to install fine.

So, in the new version of the Automator I set `use-hevc-qsv-decoder` to True. According to Intel's spec's my mid 2011 Mac Mini has QSV support, even though it's not "6th generation Skylake or newer," see https://ark.intel.com/products/53449/Intel-Core-i5-2415M-Processor-3M-Cache-up-to-2_90-GHz.

I then test by running the script manually on a folder and I get the Unknown decoder 'hevc_qsv' error. The entire message is: 

```
Starting conversion.
[          ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/sickbeard_mp4_automator/mkvtomp4.py", line 715, in convert
    for timecode in conv:
  File "/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/sickbeard_mp4_automator/converter/ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=79318, cmd="/usr/local/Cellar/ffmpeg/3.4.1/bin/ffmpeg -fix_sub_duration -vcodec hevc_qsv -i /Volumes/The Giga CinePlex/Now Playing/Whiplash.2014.1080p.BluRay.x265.INTERNAL-FLAME/flame-whiplash.2014.1080p.bluray.x265.internal.mkv -i /Volumes/The Giga CinePlex/Now Playing/Whiplash.2014.1080p.BluRay.x265.INTERNAL-FLAME/flame-whiplash.2014.1080p.bluray.x265.internal.en.srt -vcodec libx264 -map 0:0 -vb 2937k -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -c:s:1 mov_text -map 1:0 -metadata:s:s:1 language=eng -f mp4 -threads auto -y /Volumes/The Giga CinePlex/Now Playing/Whiplash.2014.1080p.BluRay.x265.INTERNAL-FLAME/flame-whiplash.2014.1080p.bluray.x265.internal.mp4">
/usr/local/Cellar/ffmpeg/3.4.1/bin/ffmpeg -fix_sub_duration -vcodec hevc_qsv -i /Volumes/The Giga CinePlex/Now Playing/Whiplash.2014.1080p.BluRay.x265.INTERNAL-FLAME/flame-whiplash.2014.1080p.bluray.x265.internal.mkv -i /Volumes/The Giga CinePlex/Now Playing/Whiplash.2014.1080p.BluRay.x265.INTERNAL-FLAME/flame-whiplash.2014.1080p.bluray.x265.internal.en.srt -vcodec libx264 -map 0:0 -vb 2937k -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -c:s:1 mov_text -map 1:0 -metadata:s:s:1 language=eng -f mp4 -threads auto -y /Volumes/The Giga CinePlex/Now Playing/Whiplash.2014.1080p.BluRay.x265.INTERNAL-FLAME/flame-whiplash.2014.1080p.bluray.x265.internal.mp4
ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-ffplay --enable-frei0r --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librtmp --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.0/include/openjpeg-2.3 --enable-nonfree
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Unknown decoder 'hevc_qsv'
```

I go to the older version of the Automator, the one without the `use-hevc-qsv-decoder` option, which has been working flawlessly previous to the update, and changed the path to ffmpeg and ffprobe to the newer 3.4.1 version and I get the same error, Unknown decoder 'hevc_qsv'.

This leads me to believe it's something with the new version of ffmpeg but really, what do I know? (not a ton is the answer to that).

Let me know if you see anything I'm missing ir anything extra I need to do. I was trying to update the Automator so I could do HEVC, h265 and x265 conversion but I'm not sure that's even possible.  Regardless, the new version of ffmpeg should work, shouldn't it?

If you need any more info I'd be happy to provide it.

**Comment by Collisionc** [comment]
Your processor does not support decoding hevc, so it will always throw the 'unknown decoder' error. See here: https://trac.ffmpeg.org/wiki/Hardware/QuickSync

**Comment by PaidToTrade** [comment]
I have a 7700k and I'm getting the same error.

**Comment by Collisionc** [comment]
Just tried the script with a pc from work as my 6900k doesn't have a gpu on it, and it works fine with hevc_qsv. 

Are you on windows or another operating system?

**Comment by shpankey** [comment]
If you're on linux, I think you may need...

Intel Media Server Studio – Community Edition

...but I'm not positive about that.

**Comment by mdhiggins** [comment]
This should be solved now
