### ISSUE TITLE
Crypto Error on Synology

### ISSUE THREAD

**Issue by Neotizz** [mdhiggins/sickbeard_mp4_automator#847]
Hi, 

Ive installed all the PIP Packages on synology DSM, and am now trying to run manual.py for testing. Im getting this output.. Ive looked everywhere but can't find any solutions. Someone with the same problem?

/volume1/PlexMedia/mp4auto$ python manual.py -i /volume1/TEST/South.Park.S08E07.Goobacks.1080p.WEB-DL.AVC-jhonny2.mkv

Traceback (most recent call last):
  File "manual.py", line 13, in <module>
    from tmdb_mp4 import tmdb_mp4
  File "/volume1/PlexMedia/mp4auto/tmdb_mp4.py", line 14, in <module>
    from tmdb_api import tmdb
  File "/volume1/PlexMedia/mp4auto/tmdb_api/tmdb.py", line 18, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 13, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "/usr/lib/python2.7/site-packages/asn1crypto/keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "/usr/lib/python2.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "/usr/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "/usr/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library crypto

**Comment by mdhiggins** [comment]
Issue is specifically related to synology missing a compiler

See here:
https://github.com/pypa/pip/issues/3588
