### ISSUE TITLE
preopts or postopts -profile:v high

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#859]
Can someone please help me setup -profile:v high, I have some video files with high 10 profiles which plex cannot handle on android.

**Comment by Smalfinn** [comment]
log from when I tried a manual converstion with "postopts = -profile:v high;" in autoProcess.ini

2018-02-12 12:15:21 - MANUAL - INFO - Manual processor started.
2018-02-12 12:15:21 - MANUAL - INFO - C:\Program Files (x86)\Python36\python.exe
2018-02-12 12:15:21 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2018-02-12 12:15:22 - RadarrPostConversion - INFO - queued
2018-02-12 12:15:23 - MANUAL - INFO - Reading video stream.
2018-02-12 12:15:23 - MANUAL - INFO - Video codec detected: h264.
2018-02-12 12:15:23 - MANUAL - INFO - Pix Fmt: yuv420p.
2018-02-12 12:15:23 - MANUAL - INFO - Reading audio streams.
2018-02-12 12:15:23 - MANUAL - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2018-02-12 12:15:23 - MANUAL - INFO - Audio detected for stream #1: eac3 [eng].
2018-02-12 12:15:23 - MANUAL - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2018-02-12 12:15:23 - MANUAL - INFO - Audio track is number 0 setting disposition to default
2018-02-12 12:15:23 - MANUAL - INFO - Creating audio stream 1 from source stream 1.
2018-02-12 12:15:23 - MANUAL - INFO - Audio Track is number 1 setting disposition to none
2018-02-12 12:15:23 - MANUAL - INFO - Reading subtitle streams.
2018-02-12 12:15:23 - MANUAL - INFO - Subtitle detected for stream #2: subrip [eng].
2018-02-12 12:15:23 - MANUAL - INFO - Ripping eng subtitle from source stream 2 into external file.
2018-02-12 12:15:25 - MANUAL - INFO - C:\FREEFLIX\manual\American Horror Story - S07E01 - Bluray-1080p.eng.srt created.
2018-02-12 12:15:25 - MANUAL - INFO - {
    "format": "mp4",
    "video": {
        "codec": "copy",
        "map": 0,
        "level": 4.1,
        "crf": 18
    },
    "audio": {
        "0": {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "language": "eng",
            "disposition": "default"
        },
        "1": {
            "map": 1,
            "codec": "ac3",
            "channels": 6,
            "bitrate": 1536,
            "filter": null,
            "language": "eng",
            "disposition": "none"
        }
    },
    "subtitle": {},
    "preopts": [],
    "postopts": [
        "-threads",
        "auto",
        "-profile:v high;"
    ]
}
2018-02-12 12:15:25 - MANUAL - INFO - Starting conversion.
2018-02-12 12:15:25 - MANUAL - ERROR - Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "C:\FREEFLIX\sickbeard_mp4_automator\mkvtomp4.py", line 715, in convert
    for timecode in conv:
  File "C:\FREEFLIX\sickbeard_mp4_automator\converter\__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "C:\FREEFLIX\sickbeard_mp4_automator\converter\ffmpeg.py", line 548, in convert
    total_output, pid=p.pid)
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
2018-02-12 12:15:25 - MANUAL - ERROR - C:\FREEFLIX\ffmpeg\bin\ffmpeg.exe -i C:\FREEFLIX\manual\American Horror Story - S07E01 - Bluray-1080p.mkv -vcodec copy -map 0:0 -c:a:0 aac -map 0:1 -disposition:a:0 default -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -disposition:a:1 none -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -f mp4 -threads auto -profile:v high; -y C:\FREEFLIX\manual\American Horror Story - S07E01 - Bluray-1080p.mp4
2018-02-12 12:15:25 - MANUAL - ERROR - ffmpeg version N-89956-gcaa4bd7a9f Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      56.  7.100 / 56.  7.100
  libavcodec     58.  9.100 / 58.  9.100
  libavformat    58.  7.100 / 58.  7.100
  libavdevice    58.  0.101 / 58.  0.101
  libavfilter     7. 11.101 /  7. 11.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
Input #0, matroska,webm, from 'C:\FREEFLIX\manual\American Horror Story - S07E01 - Bluray-1080p.mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2017-09-06T12:00:35.000000Z
  Duration: 00:50:22.85, start: 0.000000, bitrate: 9303 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 8661159
      BPS-eng         : 8661159
      DURATION        : 00:50:22.853000000
      DURATION-eng    : 00:50:22.853000000
      NUMBER_OF_FRAMES: 72476
      NUMBER_OF_FRAMES-eng: 72476
      NUMBER_OF_BYTES : 3272676362
      NUMBER_OF_BYTES-eng: 3272676362
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-09-06 12:00:35
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-09-06 12:00:35
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
    Metadata:
      BPS             : 640000
      BPS-eng         : 640000
      DURATION        : 00:50:22.816000000
      DURATION-eng    : 00:50:22.816000000
      NUMBER_OF_FRAMES: 94463
      NUMBER_OF_FRAMES-eng: 94463
      NUMBER_OF_BYTES : 241825280
      NUMBER_OF_BYTES-eng: 241825280
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-09-06 12:00:35
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-09-06 12:00:35
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: subrip
    Metadata:
      BPS             : 64
      BPS-eng         : 64
      DURATION        : 00:50:19.316000000
      DURATION-eng    : 00:50:19.316000000
      NUMBER_OF_FRAMES: 900
      NUMBER_OF_FRAMES-eng: 900
      NUMBER_OF_BYTES : 24330
      NUMBER_OF_BYTES-eng: 24330
      _STATISTICS_WRITING_APP: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.8.0 ('Wind at my back') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-09-06 12:00:35
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-09-06 12:00:35
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[NULL @ 00000180a45a00c0] [Eval @ 00000042179fe4b0] Undefined constant or missing '(' in 'y'
[NULL @ 00000180a45a00c0] Unable to parse option value "-y"
[NULL @ 00000180a45a00c0] Error setting option profile to value -y.
Error setting up codec context options.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
  Stream #0:1 -> #0:2 (eac3 (native) -> ac3 (native))
    Last message repeated 1 times
2018-02-12 12:15:25 - MANUAL - ERROR - C:\FREEFLIX\manual\American Horror Story - S07E01 - Bluray-1080p.mp4 deleted.

**Comment by mdhiggins** [comment]
Post your autoProcess.ini
It sounds like you didn't follow the instructions and use comma separated values
`postopts = -profile:v,high`

**Comment by Smalfinn** [comment]
[Sonarr]
host = localhost
port = 8989
web_root =
ssl = False
apikey = c2cdd1360be24fa78b61511876c0b8b5

[Radarr]
host = localhost
port = 7878
web_root =
ssl = False
apikey = 2faa544c38714d63bfdf835f5306c9f6

[MP4]
ffmpeg = C:\FREEFLIX\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\FREEFLIX\ffmpeg\bin\ffprobe.exe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 20000
video-crf = 18
video-max-width = 1920
h264-max-level = 4.1
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = ac3
audio-language =
audio-default-language = eng
audio-channel-bitrate =
audio-filter =
audio-copy-original = False
subtitle-codec = srt
subtitle-language =
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Thumbnail
download-subs = False
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts = -profile:v,high
preopts =

[Deluge]
host = localhost
username = sampleuser
convert = True
password = samplepass
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
port = 58846
output_directory =
remove = true

[SABNZBD]
convert = True
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output_directory =

[Plex]
host = 192.168.1.100
port = 32400
refresh = True
token = GjztoCKMoHeFsSMdMQKy

**Comment by mdhiggins** [comment]
Is that what you had originally or did you update it to reflect the suggestion I just made? Cause you edited your old post to remove the semicolon and now I'm confused

> "postopts = -profile:v high;" 
`...-metadata:s:a:1 language=eng -f mp4 -threads auto **-profile:v high;** -y C:\FREEFLIX\manual\American Horror Story - S07E01 - Bluray-1080p.mp4...`

And it looks like the semicolon was present there previously too in the log

**Comment by Smalfinn** [comment]
Okay sorry for the confusion, I've re-ran the script now:
autoProcess.ini : https://pastebin.com/raw/Lttis3Bt
log : https://pastebin.com/raw/LLvYe1T9

**Comment by mdhiggins** [comment]
https://lists.ffmpeg.org/pipermail/ffmpeg-user/2012-January/004428.html

You can try `-vprofile,high`
However upon closer inspection it looks like the video stream is set to 'copy' which means its not gonna convert or use your profile settings anyway since the video stream meets your predefined parameters and its just going to remux. The use of copy may also be why the profile:v option isn't working since technically you can't apply a profile to copy but I'm not 100% sure

**Comment by Smalfinn** [comment]
-vprofile,high seems to be working so far.

Let me try and convert a file I know to have its vprofile as high10 and see if it converts it down to high

**Comment by mdhiggins** [comment]
It won’t if you’re using copy, its just ignoring it, it needs to be a video stream that gets converted

**Comment by Smalfinn** [comment]
Can I force conversion?

**Comment by mdhiggins** [comment]
Not globally, which you wouldn't want to do anyway
The script aims to minimize doing conversions when not appropriate so it will only trigger if your video exceeds certain maximum parameters such as bitrate, resolution, wrong pix_fmt or obviously the wrong codec entirely

**Comment by Smalfinn** [comment]
Can I request the vprofile to be 1 of those parameters?

**Comment by mdhiggins** [comment]
Not really, what will need to happen is I'll need to add an option specifically for profiles then have the script run a check against whether the video is already in the correct profile, then if its not to force a conversion to the profile of your choosing

I'll add this, shouldn't take long

I'll treat it like codecs or pix_fmt where you add a whitelist comma separated to your autoProcess.ini of acceptable profiles, then if its not on that list it will convert to your first profile listed

Example:
video-profile: high, high10

If you load a video with that's high10, no conversion
If you load a video that's high444, it will convert and use high as profile (since high is first on list)

**Comment by mdhiggins** [comment]
8802e4932f8804a4fc5a52f94fe250dd20a66e85

Give that a shot, update from github and either run manual.py and close it to add the video-profile option or manually add it to your config

**Comment by Smalfinn** [comment]
manual crashed 
log: https://pastebin.com/raw/3MnJZnqX
autoprocess.ini: https://pastebin.com/raw/q8uLp09Q

**Comment by mdhiggins** [comment]
`x264 [error]: high profile doesn't support a bit depth of 10`

https://video.stackexchange.com/questions/15946/how-to-encode-video-to-profile-high-using-ffmpeg

**Comment by mdhiggins** [comment]
Its either an issue with FFMPEG build or you can try and set your pix_fmt to something not 10 bit like `yuv420p`

Also pushed a small update that causes pix_fmt and profiles to always be paired if you specify settings for both and one gets applied

fd0e2e6de9e0ab9c96d119dcd0aacfcff1651802

**Comment by Smalfinn** [comment]
Will yuv420p be best for direct play on plex?

**Comment by mdhiggins** [comment]
Yeah should be fine

**Comment by Smalfinn** [comment]
`2018-02-12 14:49:56 - MANUAL - INFO - Manual processor started.
2018-02-12 14:49:56 - MANUAL - INFO - C:\Program Files (x86)\Python36\python.exe
2018-02-12 14:49:56 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2018-02-12 14:49:59 - MANUAL - INFO - Reading video stream.
2018-02-12 14:49:59 - MANUAL - INFO - Video codec detected: h264.
2018-02-12 14:49:59 - MANUAL - INFO - Pix Fmt: yuv420p10le.
2018-02-12 14:49:59 - MANUAL - INFO - Profile: High 10.
2018-02-12 14:49:59 - MANUAL - INFO - Reading audio streams.
2018-02-12 14:49:59 - MANUAL - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2018-02-12 14:49:59 - MANUAL - INFO - Audio detected for stream #1: flac [eng].
2018-02-12 14:49:59 - MANUAL - INFO - Creating audio stream 0 from source stream 1.
2018-02-12 14:49:59 - MANUAL - INFO - Audio Track is number 1 setting disposition to default
2018-02-12 14:49:59 - MANUAL - INFO - Audio detected for stream #2: flac [jpn].
2018-02-12 14:49:59 - MANUAL - INFO - Creating audio stream 1 from source stream 2.
2018-02-12 14:49:59 - MANUAL - INFO - Audio Track is number 2 setting disposition to none
2018-02-12 14:49:59 - MANUAL - INFO - Reading subtitle streams.
2018-02-12 14:49:59 - MANUAL - INFO - Subtitle detected for stream #3: ass [eng].
2018-02-12 14:49:59 - MANUAL - INFO - Ripping eng subtitle from source stream 3 into external file.
2018-02-12 14:49:59 - MANUAL - INFO - C:\FREEFLIX\manual\FateStay Night Unlimited Blade Works - 0x02 (27) - Sunny Day.eng.srt created.
2018-02-12 14:49:59 - MANUAL - INFO - {
    "format": "mp4",
    "video": {
        "codec": "h264",
        "map": 0,
        "level": 4.1,
        "profile": "high",
        "pix_fmt": "yuv420p",
        "crf": 18
    },
    "audio": {
        "0": {
            "map": 1,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "language": "eng",
            "disposition": "default"
        },
        "1": {
            "map": 2,
            "codec": "aac",
            "channels": 2,
            "bitrate": 256,
            "filter": null,
            "language": "jpn",
            "disposition": "none"
        }
    },
    "subtitle": {},
    "preopts": [],
    "postopts": [
        "-threads",
        "auto"
    ]
}
2018-02-12 14:49:59 - MANUAL - INFO - Starting conversion.
2018-02-12 14:54:44 - MANUAL - INFO - C:\FREEFLIX\manual\FateStay Night Unlimited Blade Works - 0x02 (27) - Sunny Day.mp4 created.
2018-02-12 14:54:44 - MANUAL - INFO - Tagging file: C:\FREEFLIX\manual\FateStay Night Unlimited Blade Works - 0x02 (27) - Sunny Day.mp4.
2018-02-12 14:54:44 - MANUAL - INFO - Trying to write tags.
2018-02-12 14:54:44 - MANUAL - INFO - Tags written successfully.
2018-02-12 14:54:44 - MANUAL - INFO - Relocating MOOV atom to start of file.`

Worked perfectly, a lot slower than before but I assume that's due to it converting not copying.

**Comment by Mirabis** [comment]
@Smalfinn I would advise you to regenerate a Plex Token, now that you published the one above ;)

**Comment by Smalfinn** [comment]
Really? I will now

**Comment by shpankey** [comment]
From https://trac.ffmpeg.org/wiki/Encode/H.264

"Note that usage of -profile:v is incompatible with lossless encoding"

...may have been that issue.
