### ISSUE TITLE
Automator stuck after attempting to find subtitles

### ISSUE THREAD

**Issue by AHaymond** [mdhiggins/sickbeard_mp4_automator#864]
I have been using mp4_automator manual.py for about year and a half now and it has been working great. However all of a sudden it has randomly started hanging right after it outputs a notice about subtitles.

Specifically it hangs right after this line:

[readSettings.py#L441](https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/readSettings.py#L441).

I can interrupt the conversion and it will continue on to the next one, sometimes it seems I can come back and it will work on the same file again. I am not sure what is going on but I would really appreciate some help.

FWIW:

- ffmpeg version 3.3.4
- ffprobe version 3.3.4
- Linux 4.12.12-1-ARCH x86_64
- Python 2.7.13

**Comment by AHaymond** [comment]
When I interrupt the locked up process the following stack trace is provided.

```
Traceback (most recent call last):
  File "/opt/mp4_automator/manual.py", line 358, in <module>
    main()
  File "/opt/mp4_automator/manual.py", line 349, in main
    processFile(path, tagdata)
  File "/opt/mp4_automator/manual.py", line 198, in processFile
    tagmp4 = Tvdb_mp4(tvdbid, season, episode, language=settings.taglanguage, logger=log)
  File "/opt/mp4_automator/tvdb_mp4.py", line 40, in __init__
    self.showdata = self.tvdb_show[self.show]
  File "/opt/mp4_automator/tvdb_api/tvdb_api.py", line 948, in __getitem__
    self._getShowData(key, self.config['language'])
  File "/opt/mp4_automator/tvdb_api/tvdb_api.py", line 884, in _getShowData
    epsEt = self._getetsrc( url, language=language)
  File "/opt/mp4_automator/tvdb_api/tvdb_api.py", line 621, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "/opt/mp4_automator/tvdb_api/tvdb_api.py", line 616, in _loadUrl
    return resp.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 633, in _read_chunked
    value.append(self._safe_read(amt))
  File "/usr/lib/python2.7/httplib.py", line 688, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
```
