### ISSUE TITLE
Undefined constant or missing '('

### ISSUE THREAD

**Issue by Dulanic** [mdhiggins/sickbeard_mp4_automator#884]
So this is kind of odd to me. I can manually run the command it is trying to run and it also gets an error. It is not access related as I have access to both paths. I can't seem to find whats causing the failure.

```
sudo python manual.py -i /mnt/4K
[sudo] password for dulanic:
Sorry, try again.
[sudo] password for dulanic:
Manual processor started.
/usr/bin/python
64bit Python.
Processing file /mnt/4K/Ghostbusters (2016)/Ghostbusters (2016) Bluray-2160p.mkv
Matched movie title as: Ghostbusters 2016-07-14
Proceed using guessed identification from filename?
# [y/n]: y
Processing Ghostbusters
Reading video stream.
Video codec detected: hevc.
Pix Fmt: yuv420p10le.
Profile: Main 10.
Reading audio streams.
Audio detected for stream #1: dca [eng].
Creating audio stream 0 from source stream 1.
Audio Track is number 1 setting disposition to default
Audio detected for stream #2: dca [eng].
Creating audio stream 1 from source stream 2.
Audio Track is number 2 setting disposition to none
Audio detected for stream #3: ac3 [fre].
Reading subtitle streams.
Subtitle detected for stream #4: srt [fre].
{
    "preopts": [],
    "subtitle": {},
    "format": "mp4",
    "postopts": [
        "-threads",
        "auto"
    ],
    "video": {
        "profile": null,
        "map": 0,
        "level": 4.0,
        "width": 1920,
        "codec": "h264",
        "crf": 23,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 5,
            "codec": "ac3",
            "disposition": "default",
            "bitrate": 1280,
            "filter": null
        },
        "1": {
            "map": 2,
            "language": "eng",
            "channels": 5,
            "codec": "ac3",
            "disposition": "none",
            "bitrate": 1280,
            "filter": null
        }
    }
}
Starting conversion.
[          ] 0%Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/home/dulanic/sickbeard_mp4_automator/mkvtomp4.py", line 732, in convert
    for timecode in conv:
  File "/home/dulanic/sickbeard_mp4_automator/converter/__init__.py", line 243, in convert
    timeout=timeout, preopts=preopts, postopts=postopts):
  File "/home/dulanic/sickbeard_mp4_automator/converter/ffmpeg.py", line 551, in convert
    total_output, pid=p.pid)
FFMpegConvertError: <FFMpegConvertError error="Exited with code 1", pid=29748, cmd="/usr/bin/ffmpeg -i /mnt/4K/Ghostbusters (2016)/Ghostbusters (2016) Bluray-2160p.mkv -vcodec libx264 -map 0:0 -crf 23 -level 4.0 -vf scale=1920:trunc(ow/a/2)*2 -c:a:0 ac3 -map 0:1 -disposition:a:0 default -ac:a:0 5 -b:a:0 1280k -metadata:s:a:0 language=eng -c:a:1 ac3 -map 0:2 -disposition:a:1 none -ac:a:1 5 -b:a:1 1280k -metadata:s:a:1 language=eng -f mp4 -threads auto -y /local-media/Media/Movies/Convert/Ghostbusters (2016) Bluray-2160p.mp4">
/usr/bin/ffmpeg -i /mnt/4K/Ghostbusters (2016)/Ghostbusters (2016) Bluray-2160p.mkv -vcodec libx264 -map 0:0 -crf 23 -level 4.0 -vf scale=1920:trunc(ow/a/2)*2 -c:a:0 ac3 -map 0:1 -disposition:a:0 default -ac:a:0 5 -b:a:0 1280k -metadata:s:a:0 language=eng -c:a:1 ac3 -map 0:2 -disposition:a:1 none -ac:a:1 5 -b:a:1 1280k -metadata:s:a:1 language=eng -f mp4 -threads auto -y /local-media/Media/Movies/Convert/Ghostbusters (2016) Bluray-2160p.mp4
ffmpeg version 3.3-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-8) 20170304
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-5 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, matroska,webm, from '/mnt/4K/Ghostbusters (2016)/Ghostbusters (2016) Bluray-2160p.mkv':
  Metadata:
    encoder         : libebml v1.3.1 + libmatroska v1.4.2
    creation_time   : 2017-12-05T21:23:19.000000Z
  Duration: 02:05:59.73, start: 0.083000, bitrate: 44257 kb/s
    Stream #0:0(fre): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS             : 40094480
      BPS-eng         : 40094480
      DURATION        : 02:05:59.588000000
      DURATION-eng    : 02:05:59.588000000
      NUMBER_OF_FRAMES: 181249
      NUMBER_OF_FRAMES-eng: 181249
      NUMBER_OF_BYTES : 37887218967
      NUMBER_OF_BYTES-eng: 37887218967
      _STATISTICS_WRITING_APP: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-05 21:23:19
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-05 21:23:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s16p (default)
    Metadata:
      BPS             : 2266213
      BPS-eng         : 2266213
      DURATION        : 02:05:59.637000000
      DURATION-eng    : 02:05:59.637000000
      NUMBER_OF_FRAMES: 708716
      NUMBER_OF_FRAMES-eng: 708716
      NUMBER_OF_BYTES : 2141468800
      NUMBER_OF_BYTES-eng: 2141468800
      _STATISTICS_WRITING_APP: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-05 21:23:19
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-05 21:23:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s
    Metadata:
      BPS             : 1508999
      BPS-eng         : 1508999
      DURATION        : 02:05:59.638000000
      DURATION-eng    : 02:05:59.638000000
      NUMBER_OF_FRAMES: 708716
      NUMBER_OF_FRAMES-eng: 708716
      NUMBER_OF_BYTES : 1425936592
      NUMBER_OF_BYTES-eng: 1425936592
      _STATISTICS_WRITING_APP: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-05 21:23:19
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-05 21:23:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(fre): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s
    Metadata:
      title           : French AC3 384kbps
      BPS             : 384000
      BPS-eng         : 384000
      DURATION        : 02:05:59.616000000
      DURATION-eng    : 02:05:59.616000000
      NUMBER_OF_FRAMES: 236238
      NUMBER_OF_FRAMES-eng: 236238
      NUMBER_OF_BYTES : 362861568
      NUMBER_OF_BYTES-eng: 362861568
      _STATISTICS_WRITING_APP: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-05 21:23:19
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-05 21:23:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(fre): Subtitle: subrip
    Metadata:
      title           : Forced
      BPS             : 0
      BPS-eng         : 0
      DURATION        : 02:00:41.400000000
      DURATION-eng    : 02:00:41.400000000
      NUMBER_OF_FRAMES: 24
      NUMBER_OF_FRAMES-eng: 24
      NUMBER_OF_BYTES : 825
      NUMBER_OF_BYTES-eng: 825
      _STATISTICS_WRITING_APP: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.2.0 ('World of Adventure') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-12-05 21:23:19
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-12-05 21:23:19
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (dts (dca) -> ac3 (native))
  Stream #0:2 -> #0:2 (dts (dca) -> ac3 (native))
Press [q] to stop, [?] for help
[AVFilterGraph @ 0x59f9400] [Eval @ 0x7ffe0f718820] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0x59f9400] Unable to parse option value "auto"
[AVFilterGraph @ 0x59d4220] [Eval @ 0x7ffe0f718820] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0x59d4220] Unable to parse option value "auto"
[AVFilterGraph @ 0x5bf92c0] [Eval @ 0x7ffe0f718750] Undefined constant or missing '(' in 'auto'
[AVFilterGraph @ 0x5bf92c0] Unable to parse option value "auto"
[libx264 @ 0x5957200] using SAR=1/1
[libx264 @ 0x5957200] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0x5957200] profile High, level 4.0
[libx264 @ 0x5957200] 264 - core 148 r333 90a61ec - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[mp4 @ 0x59a3920] muxer does not support non seekable output
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --
Conversion failed!


```

**Comment by Dulanic** [comment]
I reran the same command today and it it worked. Waiting for next to finish successfully and will close this if it does. Not sure why it would run one day but not another when there was 0 difference between the file on the 2 days.
