### ISSUE TITLE
guest and stevedore errors?

### ISSUE THREAD

**Issue by evanwins** [mdhiggins/sickbeard_mp4_automator#885]
Not sure what happened but was having no problems running manual-py and now I'm getting this:
`Traceback (most recent call last):
  File "manual.py", line 5, in <module>
    import guessit
  File "/usr/local/lib/python2.7/site-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/usr/local/lib/python2.7/site-packages/stevedore/extension.py", line 261, in map
    raise NoMatches('No %s extensions found' % self.namespace)
stevedore.exception.NoMatches: No guessit.transformer extensions found`

The only thing I did recently to the machine (a Mac on High Sierra) was install NZBHydra and I think something (sorry, not very proficient in most of this but can usually figure things out) happened with Python, like I had to install a new version maybe?

Right now

`which -a python python2 python2.7 python3 python3.6`

returns

`/usr/local/bin/python
/usr/bin/python
/usr/local/bin/python2
/usr/local/bin/python2.7
/usr/bin/python2.7
/usr/local/bin/python3
/usr/local/bin/python3.6`

and `python`

returns `Python 2.7.14 (default, Mar 22 2018, 15:04:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin`

Any help is greatly appreciated.

**Comment by mdhiggins** [comment]
Probably wrong version of guessit installed, see readme

**Comment by philhudson91** [comment]
FYI fix is:

```
pip uninstall stevedore
pip install stevedore==1.19.1
```
