### ISSUE TITLE
Error moving file to output dir (mkvtomp4 & shutil)

### ISSUE THREAD

**Issue by tscibilia** [mdhiggins/sickbeard_mp4_automator#898]
I recently posted issue #887 and now I'm now trying to avoid it by combining all applications into one VM instead of separately (as the benefit of getting this to work outweighs the benefits of containerizing).

However I'm getting some permission errors when triggering `delugePostProcess.py` via deluge which I thought was related to #850 (because I'm running each app as a separate user) so I tried to run it via `manual.py` and received this error...

```
Processing file /mnt/download/completed/Movies/Mission Impossible (1996) [1080p] [YTS.AG]/Mission.Impossible.1996.1080p.BluRay.x264-[YTS.AG].mp4
Matched movie title as: Mission: Impossible 1996-05-22
Processing Mission: Impossible
Error moving file to output directory.
Traceback (most recent call last):
  File "/opt/SB_MP4_Auto/mkvtomp4.py", line 213, in process
    shutil.copy(inputfile, outputfile)
  File "/usr/lib/python2.7/shutil.py", line 120, in copy
    copymode(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 91, in copymode
    os.chmod(dst, mode)
OSError: [Errno 1] Operation not permitted: '/mnt/download/transcoding/Mission.Impossible.1996.1080p.BluRay.x264-[YTS.AG].mp4'
```

My hope was to take moives from /completed ... process them in /transcoding ... move them into a /postProcess folder for final use. As I alluded earlier, I'm running these apps with 4 separate users deluge, sonarr, radarr, ffmpeg and each of them are members of the ffmpeg group so they can rwx your script.

**Comment by tscibilia** [comment]
ok scratch that issue...
I was confused why it worked on my old VM and not this one. turns out there were three changes I made:
1. I built ffmpeg from source
2. I was using python 2.7 instead of 3.5.2
3. I forgot quotes around the input directory in the manual.py command

I'm very sure it all had to do with the last item but I didn't realize it until I had reinstalled ffmpeg and upgraded python. I might go back to ffmpeg from source later, but i'm more concerned about getting this process to work for me before I start tinkering.
