### ISSUE TITLE
Automator only starts conversion if the torrent is paused. (Deluge)

### ISSUE THREAD

**Issue by tj1816** [mdhiggins/sickbeard_mp4_automator#917]
Recently I've been having an issue with the automator not working correctly.  After the torrent is finished downloading, the cmd window will open.  If the torrent is seeding, the cmd window will close after about 5 seconds; if the torrent has finished seeding or I manually pause it as soon as it finishes downloading, the cmd window will open and the conversion will start.  I assume it's acting this way because when seeding, the file is still being used by Deluge.  I'm using Windows 10, Python 2.7.10, Deluge 1.3.15 and the most recent version of the automator (dated July 17, 2018).

**Comment by mdhiggins** [comment]
Hm I am not experiencing this issue; the system for torrents only reads the files and does not modify any of the original files (and creates its own directory) so that shouldn't matter

See if there's anything in the log files that can provide further information and post it here

**Comment by tj1816** [comment]
readSettings - INFO - C:\Python27\python.exe
readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring.
readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'.

And then nothing....

If the torrent was paused:

delugePostProcess - INFO - Successfully connected to Deluge
etc...

Maybe it's just a coincidence that it works when it's paused.  I've been having a lot of issues with Sonarr/Radarr losing connection with Deluge periodically throughout the day, so maybe it's just an issue with Deluge.  The Sonarr logs show: 

"Unable to retrieve queue and history items from Deluge: Unable to connect to Deluge, please check your settings

NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 95
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 121
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 224
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 250
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String method, Object[] arguments) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 196
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetTorrentsByLabel(String label, DelugeSettings settings) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 80
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems() in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 96
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 89"

**Comment by mdhiggins** [comment]
Seems like this is a deluge problem more than anything
Maybe try rolling back to a prior version and see if the problem persists or try a reinstall

**Comment by tj1816** [comment]
I'll give it a shot, thanks for the help.  Btw, when I'm trying to troubleshoot, what's the difference between index.log and info.log?

**Comment by mdhiggins** [comment]
info.log is just the old name, recent update changed it

**Comment by tj1816** [comment]
Got it, thanks!

**Comment by Rediculocity** [comment]
@tj1816 Thanks for the quick reply, I tried that as well. No luck. Then I did a 3rd total reinstall of everything script, python, and all pips, everything and started from scratch and it appears to be working. Not sure what didn't get installed correctly but at least its working now.
