### ISSUE TITLE
Enabling ios audio removes the original AC3 stereo track

### ISSUE THREAD

**Issue by Maximus97** [mdhiggins/sickbeard_mp4_automator#931]
Hi. 
These are my settings.
```[MP4]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = False
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 4.1
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = True
ios-audio-filter = 
ios-move-last = True
max-audio-channels = 
audio-codec = ac3
audio-language = 
audio-default-language = 
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = srt
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = False
tag-language = 
download-artwork = False
download-subs = False
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = True
pix-fmt = 
aac_adtstoasc = False
preopts = 
postopts = -movflags, faststart
```
_____________________________________________________________________________________________________
I set up ios `ios-audio = True` because I wanted mp4automator to create an additional 2 channel AAC track and keep the original one at AC3. I thought this was the meaning of the ios-audio option? To create a secondary ios compatible track? But when I do this, mp4automator removes the AC3 track from the original file. So I tested a manual conversion with both ios audio disabled and enabled.

Output console when running manual.py, first with `ios-audio = False` and then `ios-audio = True`
_____________________________________________________________________________________________________
```➜  ~ docker exec -it -u hotio radarr /bin/bash
hotio@1671b29dcdb4:/$ /scripts/sickbeard_mp4_automator/manual.py -i /mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.N                             ORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Half.Men.S01E10.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL.mkv
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
Unable to set tag language, defaulting to English.
Traceback (most recent call last):
  File "/scripts/sickbeard_mp4_automator/readSettings.py", line 271, in __init__
    self.abitrate = int(self.abitrate)
ValueError: invalid literal for int() with base 10: ''
64bit Python.
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Profile: High.
Reading audio streams.
No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
Audio detected for stream #1: ac3 [eng].
Creating audio stream 0 from source stream 1.
Audio Track is number 1 setting disposition to default
Reading subtitle streams.
Subtitle detected for stream #2: subrip [dan].
Ripping dan subtitle from source stream 2 into external file.
/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Half.Men.S01E10.NORDiC.720p.WE                  B-DL.DD2.0.H.264-DBRETAiL.dan.srt created.
Subtitle detected for stream #3: subrip [nor].
Ripping nor subtitle from source stream 3 into external file.
/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Half.Men.S01E10.NORDiC.720p.WE                  B-DL.DD2.0.H.264-DBRETAiL.nor.srt created.
Subtitle detected for stream #4: subrip [swe].
Ripping swe subtitle from source stream 4 into external file.
/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Half.Men.S01E10.NORDiC.720p.WE                  B-DL.DD2.0.H.264-DBRETAiL.swe.srt created.
No valid subtitle language specified, cannot download subtitles.
{
    "preopts": [],
    "subtitle": {},
    "format": "mp4",
    "postopts": [
        "-threads",
        "0",
        "-movflags",
        " faststart"
    ],
    "video": {
        "profile": null,
        "map": 0,
        "level": 4.1,
        "codec": "copy",
        "bitrate": 3889.16225,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "copy",
            "disposition": "default",
            "bitrate": 512,
            "filter": null
        }
    }
}
Starting conversion.
[######### ] 99%/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Half.Men.S01E1                  0.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL.mp4 created.
Relocating MOOV atom to start of file.
2018-09-18 16:11:40 - post_processor - INFO - Running script '/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py'.
2018-09-18 16:11:41 - post_processor - INFO - Running script '/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py.save'.
2018-09-18 16:11:41 - post_processor - INFO - Running script '/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py.save.1'.
hotio@1671b29dcdb4:/$ /scripts/sickbeard_mp4_automator/manual.py -i /mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.                                             a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Half.Men.S01E10.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL.mkv
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
Unable to set tag language, defaulting to English.
Traceback (most recent call last):
  File "/scripts/sickbeard_mp4_automator/readSettings.py", line 271, in __init__
    self.abitrate = int(self.abitrate)
ValueError: invalid literal for int() with base 10: ''
64bit Python.
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Profile: High.
Reading audio streams.
No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
Audio detected for stream #1: ac3 [eng].
Creating audio stream 0 from source stream 1.
Audio Track is number 1 setting disposition to default
Reading subtitle streams.
Subtitle detected for stream #2: subrip [dan].
Ripping dan subtitle from source stream 2 into external file.
/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Hal                                             f.Men.S01E10.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL.dan.2.srt created.
Subtitle detected for stream #3: subrip [nor].
Ripping nor subtitle from source stream 3 into external file.
/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Hal                                             f.Men.S01E10.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL.nor.2.srt created.
Subtitle detected for stream #4: subrip [swe].
Ripping swe subtitle from source stream 4 into external file.
/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL/Two.and.a.Hal                                             f.Men.S01E10.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL.swe.2.srt created.
No valid subtitle language specified, cannot download subtitles.
{
    "preopts": [],
    "subtitle": {},
    "format": "mp4",
    "postopts": [
        "-threads",
        "0",
        "-movflags",
        " faststart"
    ],
    "video": {
        "profile": null,
        "map": 0,
        "level": 4.1,
        "codec": "copy",
        "bitrate": 3889.16225,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "aac",
            "disposition": "default",
            "bitrate": 256,
            "filter": null
        }
    }
}
Starting conversion.
[######### ] 98%/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETA                                             iL/Two.and.a.Half.Men.S01E10.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL.mp4 created.
Relocating MOOV atom to start of file.
2018-09-18 16:17:44 - qtfaststart - ERROR - This file appears to already be setup for streaming!
QT FastStart did not run - perhaps moov atom was at the start already.
2018-09-18 16:17:44 - post_processor - INFO - Running script '/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py'.
2018-09-18 16:17:44 - post_processor - INFO - Running script '/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py.save'.
2018-09-18 16:17:44 - post_processor - INFO - Running script '/scripts/sickbeard_mp4_automator/post_process/sickbeard_plex_autoscan.py.save.1'.
hotio@1671b29dcdb4:/$
```

Is `ios-audio=True` supposed to overwrite existing stereo tracks?

**Comment by Maximus97** [comment]
ffprobe of the original file
```ffprobe version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, matroska,webm, from 'Two.and.a.Half.Men.S01E10.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL.mkv':
  Metadata:
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2017-11-03T12:49:21.000000Z
  Duration: 00:21:07.07, start: 0.000000, bitrate: 4285 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Metadata:
      BPS             : 4091654
      BPS-eng         : 4091654
      DURATION        : 00:21:07.059000000
      DURATION-eng    : 00:21:07.059000000
      NUMBER_OF_FRAMES: 30379
      NUMBER_OF_FRAMES-eng: 30379
      NUMBER_OF_BYTES : 648045927
      NUMBER_OF_BYTES-eng: 648045927
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-11-03 12:49:21
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-11-03 12:49:21
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      BPS             : 192000
      BPS-eng         : 192000
      DURATION        : 00:21:07.072000000
      DURATION-eng    : 00:21:07.072000000
      NUMBER_OF_FRAMES: 39596
      NUMBER_OF_FRAMES-eng: 39596
      NUMBER_OF_BYTES : 30409728
      NUMBER_OF_BYTES-eng: 30409728
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-11-03 12:49:21
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-11-03 12:49:21
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(dan): Subtitle: subrip (default)
    Metadata:
      title           : Dansk
      BPS             : 64
      BPS-eng         : 64
      DURATION        : 00:20:57.758000000
      DURATION-eng    : 00:20:57.758000000
      NUMBER_OF_FRAMES: 232
      NUMBER_OF_FRAMES-eng: 232
      NUMBER_OF_BYTES : 10113
      NUMBER_OF_BYTES-eng: 10113
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-11-03 12:49:21
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-11-03 12:49:21
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(nor): Subtitle: subrip
    Metadata:
      title           : Norsk
      BPS             : 65
      BPS-eng         : 65
      DURATION        : 00:20:58.092000000
      DURATION-eng    : 00:20:58.092000000
      NUMBER_OF_FRAMES: 232
      NUMBER_OF_FRAMES-eng: 232
      NUMBER_OF_BYTES : 10369
      NUMBER_OF_BYTES-eng: 10369
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-11-03 12:49:21
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-11-03 12:49:21
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(swe): Subtitle: subrip
    Metadata:
      title           : Svenska
      BPS             : 66
      BPS-eng         : 66
      DURATION        : 00:20:57.758000000
      DURATION-eng    : 00:20:57.758000000
      NUMBER_OF_FRAMES: 232
      NUMBER_OF_FRAMES-eng: 232
      NUMBER_OF_BYTES : 10453
      NUMBER_OF_BYTES-eng: 10453
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-11-03 12:49:21
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-11-03 12:49:21
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
hotio@1671b29dcdb4:/mnt/local/downloads/torrents/rutorrent/completed/Two.and.a.Half.Men.S01-S12.NORDiC.720p.WEB-DL.H.264-DBRETAiL/Two.and.a.Half.Men.S01.NORDiC.720p.WEB-DL.DD2.0.H.264-DBRETAiL$
```

**Comment by Maximus97** [comment]
I know that setting `audio-copy-original` to `True` would solve the problem in this case, but that would make files with DTS sound have 3 output tracks (AC3, DTS and AAC stereo) which is something I would like to avoid

**Comment by mdhiggins** [comment]
This only happens when its a stereo audio track so you don't end up multiple stereo audio tracks of comparable quality, it is the intended behavior

Taken from mkvtomp4.py:
`# If the iOS audio option is enabled and the source audio channel is only stereo, the additional iOS channel will be skipped and a single AAC 2.0 channel will be made regardless of codec preference to avoid multiple stereo channels`

If you want to keep your AC3 stereo tracks you can add that to the codec list of ios-audio but then it won't make new AAC tracks

`ios-audio = aac, ac3`
