### ISSUE TITLE
TypeError: cannot deepcopy this pattern object

### ISSUE THREAD

**Issue by everettsouthwick** [mdhiggins/sickbeard_mp4_automator#949]
When using `manual.py` it appears that there's an issue deepcopying the pattern object. I've tried iterating over an entire directory full of mkvs, as well as directly specifying a single input file and they all receive the same error. 

```

root@efe0b3155e10:/sickbeard_mp4_automator# python manual.py -i /unionfs/movies/The\ Hunt\ for\ Red\ October\ \(1990\)/The\ Hunt\ for\ Red\ October\ \(1990\).mkv -a
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Traceback (most recent call last):
  File "manual.py", line 370, in <module>
    main()
  File "manual.py", line 342, in main
    elif (os.path.isfile(path) and MkvtoMp4(settings, logger=log).validSource(path)):
  File "/sickbeard_mp4_automator/mkvtomp4.py", line 121, in __init__
    self.importSettings(settings)
  File "/sickbeard_mp4_automator/mkvtomp4.py", line 126, in importSettings
    settings = deepcopy(settings)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 298, in _deepcopy_inst
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 298, in _deepcopy_inst
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object

```

**Comment by mdhiggins** [comment]
This change was reverted yesterday and replaced with a different solution, please update and the error should go away

**Comment by everettsouthwick** [comment]
Thank you, that worked!
