### ISSUE TITLE
Support for Medusa

### ISSUE THREAD

**Issue by Sithlord82** [mdhiggins/sickbeard_mp4_automator#950]
Any chance of getting support added for Medusa? Its built on Sickbeard but has a lot more features and is actively updated. Works a lot better!

https://github.com/pymedusa/Medusa

**Comment by Sithlord82** [comment]
Thats what I hoped but with Sickbeard settings it doenst hit the logs and with Sickrage settings it gets this 
2018-11-07 21:41:39 INFO     TORNADO :: [0c0a735] User logged into the Medusa web interface

in Medusa and this is the last info after the file converts in automator

2018-11-07 21:41:38 - SABPostProcess - INFO - Passing \\192.168.0.4\Download\Complete\TV\****** directory to Sickrage.
2018-11-07 21:41:38 - autoprocess.autoProcessTVSR - INFO - Opening URL: http://192.168.0.102:9001/home/postprocess/processEpisode.
2018-11-07 21:41:39 - autoprocess.autoProcessTVSR - INFO - </html>

Im using postconversion.py in Medusa and SABpostprocess in SAB. Any suggestions?

**Comment by mdhiggins** [comment]
Is that not working?

It seems like the issue is the file isn't being passed back to Medusa after being downloaded if that's the last you see in the logs.

Does medusa have some sort of download monitoring or does it have a script you would normally run from SAB to pass the file back to have it rename / move the file?

**Comment by Sithlord82** [comment]
Medusa has the same settings as Sickrage/beard. SAB is set with sabpostprocess.py and a category of tv
Medusa has this in postprocessing settings

C:\\MediaServer\\Python27\\python.exe C:\\MediaServer\\sickbeard_mp4_automator\postConversion.py

Wiki here for details of how it works on there system. Seems the same as SR/SB

https://github.com/pymedusa/Medusa/wiki/Post-Processing

I can upload any logs if itll help. Appreciate your time. 

The logs updated with a time out after 25 minutes

018-11-07 21:41:38 - autoprocess.autoProcessTVSR - INFO - Opening URL: http://192.168.0.102:9001/home/postprocess/processEpisode.
2018-11-07 21:41:39 - autoprocess.autoProcessTVSR - INFO - </html>
2018-11-07 22:06:47 - autoprocess.autoProcessTV - ERROR - Unable to open URL
Traceback (most recent call last):
  File "C:\MediaServer\sickbeard_mp4_automator\autoprocess\autoProcessTV.py", line 100, in processEpisode
    urlObj = myOpener.openit(url)
  File "C:\MediaServer\sickbeard_mp4_automator\autoprocess\autoProcessTV.py", line 47, in openit
    return FancyURLopener.open(self, url)
  File "C:\MediaServer\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\MediaServer\Python27\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "C:\MediaServer\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\MediaServer\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\MediaServer\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\MediaServer\Python27\lib\httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "C:\MediaServer\Python27\lib\ssl.py", line 363, in wrap_socket
    _context=self)
  File "C:\MediaServer\Python27\lib\ssl.py", line 611, in __init__
    self.do_handshake()
  File "C:\MediaServer\Python27\lib\ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:661)

**Comment by mdhiggins** [comment]
Looks like its failing due to SSL issues, do you have things set up to use SSL when you shouldn't or vice versa?

**Comment by Sithlord82** [comment]
Hmm. I'll double check. I thought SSL was off on all of them. Will let you know

**Comment by Sithlord82** [comment]
No ssl enabled anywhere in the settings for the script, Medusa or sab

**Comment by mdhiggins** [comment]
Do you have the requests security package installed?

pip install -U requests[security]

**Comment by Sithlord82** [comment]
Yep that's installed. Just updated it by 0.00.1
