### ISSUE TITLE
manual.py and TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by ravensorb** [mdhiggins/sickbeard_mp4_automator#966]
It looks like there is an issue where some video files have a bitrate of "N/A" which causes the script to fail -- shouldn't this be treated as a need to re-encode the video file instead (convert-mp4 is set to true in the ini file)?

Here is the full call stack

```
Manual processor started.
/usr/local/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python.
Matched TV episode as XXXXXXXX
Processing XXXXXXXX
Reading video stream.
Video codec detected: mpeg4.
Traceback (most recent call last):
  File "/mnt/Scripts/sickbeard_mp4_automator/manual.py", line 370, in <module>
    main()
  File "/mnt/Scripts/sickbeard_mp4_automator/manual.py", line 361, in main
    processFile(path, tagdata)
  File "/mnt/Scripts/sickbeard_mp4_automator/manual.py", line 219, in processFile
    output = converter.process(inputfile, True)
  File "/mnt/Scripts/sickbeard_mp4_automator/mkvtomp4.py", line 189, in process
    options = self.generateOptions(inputfile, original=original)
  File "/mnt/Scripts/sickbeard_mp4_automator/mkvtomp4.py", line 311, in generateOptions
    vbr = info.format.bitrate / 1000
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

Here is the output of an example from ffprobe

```
[STREAM]
index=0
codec_name=mpeg4
codec_long_name=MPEG-4 part 2
profile=Advanced Simple Profile
codec_type=video
codec_time_base=1001/24000
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=640
height=368
coded_width=640
coded_height=368
has_b_frames=1
sample_aspect_ratio=1:1
display_aspect_ratio=40:23
pix_fmt=yuv420p
level=5
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=unknown
timecode=N/A
refs=1
quarter_sample=false
divx_packed=false
id=N/A
r_frame_rate=21845/911
avg_frame_rate=24000/1001
time_base=1/1200000
start_pts=1155157
start_time=0.962631
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
[/STREAM]
[FORMAT]
filename=/mnt/Media/video.avi
nb_streams=1
nb_programs=0
format_name=m4v
format_long_name=raw MPEG-4 video
start_time=0.962631
duration=N/A
size=366987264
bit_rate=N/A
probe_score=5
[/FORMAT]
```

**Comment by mdhiggins** [comment]
This should be fixed
