### ISSUE TITLE
lugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?

### ISSUE THREAD

**Issue by dexinthecity** [mdhiggins/sickbeard_mp4_automator#975]
Finally got the script to run after downloading torrent by moving my MP4_Automator folder to desktop. But it was opening cmd prompt and closing right away. Nothing would get converted and it doesn't get handed back to Radarr.

C:\Users\DEXTVHD\Desktop\mp4_automator>python "C:\Users\DEXTVHD\Desktop\mp4_automator\delugePostProcess.py"
2019-01-23 10:06:49 - delugePostProcess - INFO - Deluge post processing started.
2019-01-23 10:06:49 - readSettings - INFO - C:\Python27\python.exe
2019-01-23 10:06:49 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2019-01-23 10:06:49 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring.
2019-01-23 10:06:49 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'.
2019-01-23 10:06:49 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?

Running manual.py works just fine, I can drag and file converts.

**Comment by dexinthecity** [comment]
> Did you try pointing to the bat file instead of the py file on windows? And do you have python in your ENV variables with appropriate setup for command line variables to be passed? These are the most common issues with python on windows when trying to execute scripts with command line arguments; its usually a problem with your python installation https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows https://eli.thegreenplace.net/2010/12/14/problem-passing-arguments-to-python-scripts-on-windows From: dexinthecity Sent: Wednesday, January 23, 2019 1:20 PM To: mdhiggins/sickbeard_mp4_automator Cc: Subscribed Subject: [mdhiggins/sickbeard_mp4_automator] lugePostProcess - ERROR - Notenough command line parameters present, are you launching this from deluge?(#975) Finally got the script to run after downloading torrent by moving my MP4_Automator folder to desktop. But it was opening cmd prompt and closing right away. Nothing would get converted and it doesn't get handed back to Radarr. C:\Users\DEXTVHD\Desktop\mp4_automator>python "C:\Users\DEXTVHD\Desktop\mp4_automator\delugePostProcess.py" 2019-01-23 10:06:49 - delugePostProcess - INFO - Deluge post processing started. 2019-01-23 10:06:49 - readSettings - INFO - C:\Python27\python.exe 2019-01-23 10:06:49 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel. 2019-01-23 10:06:49 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring. 2019-01-23 10:06:49 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'. 2019-01-23 10:06:49 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge? Running manual.py works just fine, I can drag and file converts. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

yes I actually executed the .bat here's the full command:

> C:\Users\DEXTVHD\Desktop\mp4_automator>cmd /k delugePostProcess.bat

C:\Users\DEXTVHD\Desktop\mp4_automator>python "C:\Users\DEXTVHD\Desktop\mp4_automator\delugePostProcess.py"
2019-01-23 10:06:49 - delugePostProcess - INFO - Deluge post processing started.
2019-01-23 10:06:49 - readSettings - INFO - C:\Python27\python.exe
2019-01-23 10:06:49 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2019-01-23 10:06:49 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring.
2019-01-23 10:06:49 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'.
2019-01-23 10:06:49 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge?

> 

I also have C:\Python27\Scripts and C:\Python27\ in my ENV

when I try using utorrent instead of deluge for postprocessing it works just fine. SABnzbd and Utorrent are able to run their respected scripts after the download is completed, converts to mp4 then hands it back to Radarr/Sonarr.

**Comment by mdhiggins** [comment]
Are you running it from deluge though like the error is suggesting? Deluge passes all the command line arguments which is looks like you’re missing because you’re just running the bat without any arguments which will naturally error out because the bat and subsequent python script has no information

**Comment by dexinthecity** [comment]
> Are you running it from deluge though like the error is suggesting? Deluge passes all the command line arguments which is looks like you’re missing because you’re just running the bat without any arguments which will naturally error out because the bat and subsequent python script has no information From: dexinthecity Sent: Wednesday, January 23, 2019 1:49 PM To: mdhiggins/sickbeard_mp4_automator Cc: Michael Higgins; Comment Subject: Re: [mdhiggins/sickbeard_mp4_automator] lugePostProcess - ERROR - Notenough command line parameters present, are you launching this from deluge?(#975) Did you try pointing to the bat file instead of the py file on windows? And do you have python in your ENV variables with appropriate setup for command line variables to be passed? These are the most common issues with python on windows when trying to execute scripts with command line arguments; its usually a problem with your python installation https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows https://eli.thegreenplace.net/2010/12/14/problem-passing-arguments-to-python-scripts-on-windows From: dexinthecity Sent: Wednesday, January 23, 2019 1:20 PM To: mdhiggins/sickbeard_mp4_automator Cc: Subscribed Subject: [mdhiggins/sickbeard_mp4_automator] lugePostProcess - ERROR - Notenough command line parameters present, are you launching this from deluge?(#975) Finally got the script to run after downloading torrent by moving my MP4_Automator folder to desktop. But it was opening cmd prompt and closing right away. Nothing would get converted and it doesn't get handed back to Radarr. C:\Users\DEXTVHD\Desktop\mp4_automator>python "C:\Users\DEXTVHD\Desktop\mp4_automator\delugePostProcess.py" 2019-01-23 10:06:49 - delugePostProcess - INFO - Deluge post processing started. 2019-01-23 10:06:49 - readSettings - INFO - C:\Python27\python.exe 2019-01-23 10:06:49 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel. 2019-01-23 10:06:49 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring. 2019-01-23 10:06:49 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'. 2019-01-23 10:06:49 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge? Running manual.py works just fine, I can drag and file converts. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. yes I actually executed the .bat here's the full command: C:\Users\DEXTVHD\Desktop\mp4_automator>cmd /k delugePostProcess.bat C:\Users\DEXTVHD\Desktop\mp4_automator>python "C:\Users\DEXTVHD\Desktop\mp4_automator\delugePostProcess.py" 2019-01-23 10:06:49 - delugePostProcess - INFO - Deluge post processing started. 2019-01-23 10:06:49 - readSettings - INFO - C:\Python27\python.exe 2019-01-23 10:06:49 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel. 2019-01-23 10:06:49 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring. 2019-01-23 10:06:49 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'. 2019-01-23 10:06:49 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge? I also have C:\Python27\Scripts and C:\Python27\ in my ENV when I try using utorrent instead of deluge for postprocessing it works just fine. SABnzbd and Utorrent are able to run their respected scripts after the download is completed, converts to mp4 then hands it back to Radarr/Sonarr. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

When deluge itself runs the bat all I get is a quick CMD window and then it goes away but nothing happens.

**Comment by morpheus2n2** [comment]
> > Are you running it from deluge though like the error is suggesting? Deluge passes all the command line arguments which is looks like you’re missing because you’re just running the bat without any arguments which will naturally error out because the bat and subsequent python script has no information From: dexinthecity Sent: Wednesday, January 23, 2019 1:49 PM To: mdhiggins/sickbeard_mp4_automator Cc: Michael Higgins; Comment Subject: Re: [mdhiggins/sickbeard_mp4_automator] lugePostProcess - ERROR - Notenough command line parameters present, are you launching this from deluge?(#975) Did you try pointing to the bat file instead of the py file on windows? And do you have python in your ENV variables with appropriate setup for command line variables to be passed? These are the most common issues with python on windows when trying to execute scripts with command line arguments; its usually a problem with your python installation https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows https://eli.thegreenplace.net/2010/12/14/problem-passing-arguments-to-python-scripts-on-windows From: dexinthecity Sent: Wednesday, January 23, 2019 1:20 PM To: mdhiggins/sickbeard_mp4_automator Cc: Subscribed Subject: [mdhiggins/sickbeard_mp4_automator] lugePostProcess - ERROR - Notenough command line parameters present, are you launching this from deluge?(#975) Finally got the script to run after downloading torrent by moving my MP4_Automator folder to desktop. But it was opening cmd prompt and closing right away. Nothing would get converted and it doesn't get handed back to Radarr. C:\Users\DEXTVHD\Desktop\mp4_automator>python "C:\Users\DEXTVHD\Desktop\mp4_automator\delugePostProcess.py" 2019-01-23 10:06:49 - delugePostProcess - INFO - Deluge post processing started. 2019-01-23 10:06:49 - readSettings - INFO - C:\Python27\python.exe 2019-01-23 10:06:49 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel. 2019-01-23 10:06:49 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring. 2019-01-23 10:06:49 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'. 2019-01-23 10:06:49 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge? Running manual.py works just fine, I can drag and file converts. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. yes I actually executed the .bat here's the full command: C:\Users\DEXTVHD\Desktop\mp4_automator>cmd /k delugePostProcess.bat C:\Users\DEXTVHD\Desktop\mp4_automator>python "C:\Users\DEXTVHD\Desktop\mp4_automator\delugePostProcess.py" 2019-01-23 10:06:49 - delugePostProcess - INFO - Deluge post processing started. 2019-01-23 10:06:49 - readSettings - INFO - C:\Python27\python.exe 2019-01-23 10:06:49 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel. 2019-01-23 10:06:49 - readSettings - WARNING - Invalid external subtitle codec mov_text, ignoring. 2019-01-23 10:06:49 - readSettings - WARNING - No valid subtitle formats found, defaulting to 'srt'. 2019-01-23 10:06:49 - delugePostProcess - ERROR - Not enough command line parameters present, are you launching this from deluge? I also have C:\Python27\Scripts and C:\Python27\ in my ENV when I try using utorrent instead of deluge for postprocessing it works just fine. SABnzbd and Utorrent are able to run their respected scripts after the download is completed, converts to mp4 then hands it back to Radarr/Sonarr. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> When deluge itself runs the bat all I get is a quick CMD window and then it goes away but nothing happens.

That means its actually executing, if its disappearing really quick it normally means the ffmpeg can't access the file so it just errors out., delete your info file (Log) and download something again to have it trigger then look at whats is logged in the info file.

Going by the reddit posts and here, you have definitely missed a step or setting.

**Comment by dexinthecity** [comment]
I added debug in logging

2019-01-24 18:10:55 - readSettings - INFO - C:\Python27\python.exe
2019-01-24 18:10:55 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2019-01-24 18:10:55 - delugePostProcess - DEBUG - Path: D:\Torrents.
2019-01-24 18:10:55 - delugePostProcess - DEBUG - Torrent: Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv.
2019-01-24 18:10:55 - delugePostProcess - DEBUG - Hash: 031a83640d9374169332ddf2eb66d2b423db395f.

not sure what im reading lol

**Comment by dexinthecity** [comment]
Okay so I got passed the above issue, now here we are: 

2019-01-24 19:41:16 - delugePostProcess - INFO - Deluge post processing started.
2019-01-24 19:41:16 - readSettings - INFO - C:\Python27\python.exe
2019-01-24 19:41:16 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2019-01-24 19:41:16 - delugePostProcess - DEBUG - Path: D:\Torrents.
2019-01-24 19:41:16 - delugePostProcess - DEBUG - Torrent: Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv.
2019-01-24 19:41:16 - delugePostProcess - DEBUG - Hash: 031a83640d9374169332ddf2eb66d2b423db395f.
2019-01-24 19:41:16 - delugePostProcess - INFO - Successfully connected to Deluge
2019-01-24 19:41:16 - delugePostProcess - DEBUG - List of files in torrent:
2019-01-24 19:41:16 - delugePostProcess - DEBUG - Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv
2019-01-24 19:41:16 - mkvtomp4 - DEBUG - Settings imported.
2019-01-24 19:41:16 - mkvtomp4 - DEBUG - Settings imported.
2019-01-24 19:41:16 - mkvtomp4 - DEBUG - D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv is valid.
2019-01-24 19:41:16 - delugePostProcess - INFO - Converting file D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv at location D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv-convert.
2019-01-24 19:41:16 - mkvtomp4 - DEBUG - Process started.
2019-01-24 19:41:16 - mkvtomp4 - DEBUG - D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv is valid.
2019-01-24 19:41:16 - mkvtomp4 - DEBUG - D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv needs processing.
2019-01-24 19:41:16 - delugePostProcess - ERROR - Error converting file D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv.
Traceback (most recent call last):
  File "C:\mp4_automator\delugePostProcess.py", line 93, in <module>
    output = converter.process(inputfile)
  File "C:\mp4_automator\mkvtomp4.py", line 189, in process
    options = self.generateOptions(inputfile, original=original)
  File "C:\mp4_automator\mkvtomp4.py", line 302, in generateOptions
    info = Converter(self.FFMPEG_PATH, self.FFPROBE_PATH).probe(inputfile)
  File "C:\mp4_automator\converter\__init__.py", line 27, in __init__
    ffprobe_path=ffprobe_path)
  File "C:\mp4_automator\converter\ffmpeg.py", line 364, in __init__
    raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path)
FFMpegError: ffmpeg binary not found: ‪C:\ffmpeg\bin\ffmpeg.exe
2019-01-24 19:41:16 - delugePostProcess - INFO - Passing D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv-convert directory to Sonarr.
2019-01-24 19:41:16 - autoprocess.sonarr - INFO - Sonarr notifier started.
2019-01-24 19:41:16 - autoprocess.sonarr - DEBUG - Sonarr host: localhost.
2019-01-24 19:41:16 - autoprocess.sonarr - DEBUG - Sonarr port: 8989.
2019-01-24 19:41:16 - autoprocess.sonarr - DEBUG - Sonarr webroot: .
2019-01-24 19:41:16 - autoprocess.sonarr - DEBUG - Sonarr apikey: REMOVED.
2019-01-24 19:41:16 - autoprocess.sonarr - DEBUG - Sonarr protocol: http://.
2019-01-24 19:41:16 - autoprocess.sonarr - DEBUG - URL 'http://localhost:8989/api/command' with payload '{'path': 'D:\\Torrents\\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv-convert', 'name': 'downloadedepisodesscan'}.'
2019-01-24 19:41:16 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv-convert'.
2019-01-24 19:41:16 - autoprocess.sonarr - INFO - Sonarr response: queued.
2019-01-24 19:41:16 - delugePostProcess - DEBUG - Successfully removed tempoary directory D:\Torrents\Greys.Anatomy.S15E09.HDTV.x264-KILLERS.mkv-convert.

**Comment by dexinthecity** [comment]
I think i've fixed it my ffmpeg.exe path was C:\ffmpeg\bin\ffmpeg.exe but I changed it to lowercase c and that did it omfg..................

**Comment by mdhiggins** [comment]
Huh that's very strange and windows usually isn't case sensitive but glad that fixed it. Guess we can close this now
