### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by mstrelan** [mdhiggins/sickbeard_mp4_automator#977]
It's been a while since I did a ```git pull``` on this project, so I did one yesterday and now my downloads from SABnzbd are not making their way to Sonarr. I'm getting the following in the logs, wondering if I need to update some config or install some other dependencies?

```
2019-01-24 08:53:50 - autoprocess.sonarr - INFO - Sonarr notifier started.
2019-01-24 08:53:50 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'REDACTED'.
2019-01-24 08:53:50 - autoprocess.sonarr - ERROR - Update to Sonarr failed, check if Sonarr is running, autoProcess.ini settings and make sure your Sonarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "/home/michael/sickbeard_mp4_automator/autoprocess/sonarr.py", line 63, in processEpisode
r = requests.post(url, json=payload, headers=headers)
File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
return request('post', url, data=data, **kwargs)
File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

Any help would be appreciated.

**Comment by mdhiggins** [comment]
Looks like its failing to communicate with Sonarr and not getting any JSON data back, you check your Sonarr settings in autoProcess.ini?

**Comment by mstrelan** [comment]
Yeah, hasn't changed. Confirmed apikey is correct too. Is there any more logging I can enable?

```
[Sonarr]
host = localhost
port = 8989
web_root =
ssl = False
apikey = 993621edac554dfb95b86d83e9d444f6
```

**Comment by mstrelan** [comment]
I reverted [this commit](https://github.com/mdhiggins/sickbeard_mp4_automator/commit/8324e99f6f8a6a8d9b44813818621568ef8595e6#diff-22d4b720cf7827e29d9d52cf1f04c39b) and it's working now. Maybe due to my version of python-requests? I'm on 2.2.1 and latest is 2.21.0.

**Comment by mdhiggins** [comment]
I do believe this change was made in response to some changes with requests so it might be a version thing
