### ISSUE TITLE
Plex Notification not working

### ISSUE THREAD

**Issue by seed1234** [mdhiggins/sickbeard_mp4_automator#982]
It does convert mkv to mp4 but it does not refresh plex media server

My log shows the following:

2019-02-03 12:05:55 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
2019-02-03 12:05:55 - readSettings - INFO - /usr/local/bin/python
2019-02-03 12:05:55 - SonarrPostConversion - INFO - Processing /mnt/media/tv/series/The Good Doctor/Season 02/The Good Doctor - S02E11 - Quarantine Part Two.mkv.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Reading video stream.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Video codec detected: h264.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Profile: High.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Reading audio streams.
2019-02-03 12:05:55 - mkvtomp4 - INFO - No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Audio detected for stream #1: eac3 [eng].
2019-02-03 12:05:55 - mkvtomp4 - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2019-02-03 12:05:55 - mkvtomp4 - INFO - Audio track is number 0 setting disposition to default
2019-02-03 12:05:55 - mkvtomp4 - INFO - Creating audio stream 1 from source stream 1.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Audio Track is number 1 setting disposition to none
2019-02-03 12:05:55 - mkvtomp4 - INFO - Reading subtitle streams.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Subtitle detected for stream #2: subrip [eng].
2019-02-03 12:05:55 - mkvtomp4 - INFO - Creating subtitle stream 0 from source stream 2.
2019-02-03 12:05:55 - mkvtomp4 - ERROR - No valid subtitle language specified, cannot download subtitles.
2019-02-03 12:05:55 - mkvtomp4 - INFO - Starting conversion.
2019-02-03 12:07:06 - mkvtomp4 - INFO - /mnt/media/tv/series/The Good Doctor/Season 02/The Good Doctor - S02E11 - Quarantine Part Two.mp4 created.
2019-02-03 12:07:06 - SonarrPostConversion - INFO - Tagging /mnt/media/tv/series/The Good Doctor/Season 02/The Good Doctor - S02E11 - Quarantine Part Two.mkv with ID 328634 season 2 episode 11.
2019-02-03 12:07:10 - tvdb_mp4 - INFO - Tagging file: /mnt/media/tv/series/The Good Doctor/Season 02/The Good Doctor - S02E11 - Quarantine Part Two.mp4.
2019-02-03 12:07:11 - tvdb_mp4 - INFO - Trying to write tags.
2019-02-03 12:07:11 - tvdb_mp4 - INFO - Tags written successfully.
2019-02-03 12:07:11 - mkvtomp4 - INFO - Relocating MOOV atom to start of file.
2019-02-03 12:07:11 - qtfaststart - INFO - Removing free atom at 32 (8 bytes)
2019-02-03 12:07:11 - qtfaststart - INFO - Patching stco with 61870 entries
2019-02-03 12:07:11 - qtfaststart - INFO - Patching stco with 101065 entries
2019-02-03 12:07:11 - qtfaststart - INFO - Patching stco with 80642 entries
2019-02-03 12:07:11 - qtfaststart - INFO - Patching stco with 825 entries
2019-02-03 12:07:11 - qtfaststart - INFO - Writing output...
2019-02-03 12:07:35 - SonarrPostConversion - ERROR - Sonarr monitor status update failed.
Traceback (most recent call last):
  File "/usr/local/sickbeard_mp4_automator/postSonarr.py", line 102, in <module>
    log.info("Sonarr response: ID %d %s." % (rstate['id'], rstate['state']))
TypeError: list indices must be integers, not str
2019-02-03 12:07:35 - SonarrPostConversion - ERROR - Unable to refresh plex, check your settings.
Traceback (most recent call last):
  File "/usr/local/sickbeard_mp4_automator/autoprocess/plex.py", line 38, in refreshPlex
    xml_sections = minidom.parse(urlopen(base_url))
  File "/usr/local/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/local/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python2.7/urllib.py", line 357, in open_http
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)

**Comment by kushfest** [comment]
I've had the same issue arise in the last couple days. Been wracking my brain to figure it out, but then I saw this post and realized it may not just be me configuring things wrong. 

From my logs...seems to match yours exactly

2019-02-07 10:54:21 - SonarrPostConversion - ERROR - Unable to refresh plex, check your settings.
Traceback (most recent call last):
  File "/mp4_automator/autoprocess/plex.py", line 38, in refreshPlex
    xml_sections = minidom.parse(urlopen(base_url))
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 357, in open_http
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)

**Comment by seed1234** [comment]
Its a real problem, I can see the episode in plex showing up but it cannot be played unless i manually refresh the library to update it to mp4.

I have tried changing the token and re checked the Ip with no outcome

**Comment by kushfest** [comment]
@seed1234 Is your Plex Server set to require secure connections? I changed that back to preferred instead of required and things seem to be working again. I can't say 100% that was the fix, but definitely makes sense what what I was seeing and is worth checking out.

**Comment by seed1234** [comment]
@kushfest  The changes you have mentioned worked, the **Preferred Setting** in Plex Media Server is required for the script to be able to communicate to the server

**Comment by mdhiggins** [comment]
So this isn't a great fix because you're reducing the security of your server by allowing insecure connections to do the API requests. Definitely sub optimal.

Did some attempts to look in to this and think I have a solution

Updated the plex.py file in autoProcess to include an https request (relaxed to some degree without hostname check cause its happening locally) but doesn't require you to allow non SSL connections.

What you have to do instead is tell plex to allow connections from your local network without authentication which seems to let this work. (My local network uses 10.0.1.***)

![image](https://user-images.githubusercontent.com/3608298/52716936-e61b4b80-2f6d-11e9-8537-83ab9321948b.png)

And here is the updated script that will try an https request if the http request fails

```
#!/usr/bin/env python
try:
    from urllib.request import urlopen
except ImportError:
    from urllib import urlopen
import logging
from xml.dom import minidom


def refreshPlex(settings, source_type, logger=None):
    if logger:
        log = logger
    else:
        log = logging.getLogger(__name__)

    host = settings.Plex['host']
    port = settings.Plex['port']
    token = settings.Plex['token']

    log.debug("Host: %s." % host)
    log.debug("Port: %s." % port)
    log.debug("Token: %s." % token)

    approved_sources = ['movie', 'show']
    if settings.Plex['refresh'] and source_type in approved_sources:
        base_url = 'http://%s:%s/library/sections' % (host, port)
        refresh_url = '%s/%%s/refresh' % base_url

        if token:
            refresh_url = refresh_url + "?X-Plex-Token=" + token
            base_url = base_url + "?X-Plex-Token=" + token
            log.debug("Plex home token detected.")

        log.debug("Refresh URL: %s." % refresh_url)
        log.debug("Base URL: %s." % base_url)

        try:
            refresh(base_url, refresh_url, source_type)
        except IOError:
            try:
                import ssl
                ctx = ssl.create_default_context()
                ctx.check_hostname = False
                ctx.verify_mode = ssl.CERT_NONE
                refresh_url = refresh_url.replace("http://", "https://")
                base_url = base_url.replace("http://", "https://")
                refresh(base_url, refresh_url, source_type, ctx=ctx)
            except:
                log.error(refresh_url)
                log.error(base_url)
                log.error("Unable to refresh plex https, check your settings.")
        except Exception:
            log.exception("Unable to refresh plex, check your settings.")

def refresh(base_url, refresh_url, source_type, ctx=None):
    xml_sections = minidom.parse(urlopen(base_url, context=ctx))
    sections = xml_sections.getElementsByTagName('Directory')
    for s in sections:
        if s.getAttribute('type') == source_type:
            url = refresh_url % s.getAttribute('key')
            urlopen(url, context=ctx)
```

Try testing this and see if it works

**Comment by mdhiggins** [comment]
Seems to be working on my end, pushed an update to the master branch and updated the readme, let me know

**Comment by kushfest** [comment]
I'm so glad you jumped in on this. I wasn't thrilled to drop the secure connection requirement, but it was the only work-around within my skill-set hah.

I just pulled the updates and configured Plex to require secure connections + added my local network to the list of IPs that do not require auth. My test was successful!

Thank you!

**Comment by seed1234** [comment]
I just updated it to the new master. Changed the Plex . It works . Good Stuff

@mdhiggins Thank you

**Comment by mdhiggins** [comment]
Glad its working, thanks for following up 👍

**Comment by johnwchambers** [comment]
Can this issue be reopened? Below is an excerpt from my server where it's failing to fresh my plex library.

> 2019-04-25 19:45:45 - RadarrPostConversion - INFO - Requesting updated information from Radarr for movie ID 1837.
2019-04-25 19:45:45 - RadarrPostConversion - INFO - MEDIAINFORMATION
2019-04-25 19:45:49 - RadarrPostConversion - INFO - Radarr monitoring information updated for movie District 9.
2019-04-25 19:45:49 - RadarrPostConversion - ERROR - Unable to refresh plex, check your settings.
Traceback (most recent call last):
  File "/opt/mp4automator/autoprocess/plex.py", line 38, in refreshPlex
    refresh(base_url, refresh_url, source_type)
  File "/opt/mp4automator/autoprocess/plex.py", line 56, in refresh
    xml_sections = minidom.parse(urlopen(base_url, context=ctx))
TypeError: urlopen() got an unexpected keyword argument 'context'

My autoProcess.ini file includes the server's IP address as well as the correct token. My setup is a little more involved across three separate servers but works great minus this small part of the puzzle. In the meantime, I've just added a plex media server connect option in radarr/sonarr as a stop-gap to get the library to update after media is converted.

If there is anything else that you need at all just let me know.

Thank you!
